### ISSUE TITLE
Sandbox playground is broken

### ISSUE THREAD

**Issue by arobert93** [mdx-js/mdx#1007]
### Expected behaviour

It should be rendering the JSX output.

### Actual behaviour

It displays an error.

```jsx
/* @jsx mdx */
const makeShortcode = name => function MDXDefaultShortcode(props) {
  console.warn("Component " + name + " was not imported, exported, or provided by MDXProvider as global scope")
  return <div {...props}/>
};
const Button = makeShortcode("Button");
const layoutProps = {
```

We are getting the same error when running on different machines. On my personal one it works as expected.

**Comment by aaronware** [comment]
@arobert93 was this something simple that was overlooked? I am having the same issue

**Comment by arobert93** [comment]
> @arobert93 was this something simple that was overlooked? I am having the same issue

It was a problem on my side. I forgot to generate .babelrc file in the root folder.
