### ISSUE TITLE
Victory svg charts components not rendering or rendering badly

### ISSUE THREAD

**Issue by remorses** [mdx-js/mdx#1016]
### Component not rendering (recharts)

I tried importing and using the `rechart` line chart component inside mdx but it display nothing
I think the problem is that the elements are created dynamically and the `mdx.createElement` pragma doesn't work
I also tried with victory charts, which output the elements in the first render (not dynamic), these at least show something on the screen but the styles and certain svg elements are messed up, maybe because of the mdx elements overrides, i added the victory example in the same sandbox

**This is what is rendered with code sandbox**
![Schermata 2020-04-15 alle 17 20 01](https://user-images.githubusercontent.com/31321188/79354938-58eed080-7f3d-11ea-8c95-e10c692d5959.png)

**This is what it should render (same component in a normal jsx page)**
![Schermata 2020-04-15 alle 17 20 25](https://user-images.githubusercontent.com/31321188/79354987-67d58300-7f3d-11ea-8027-171e6b930444.png)

Here is how victory chart renders
![Schermata 2020-04-15 alle 17 28 45](https://user-images.githubusercontent.com/31321188/79355897-9142de80-7f3e-11ea-8f65-b3e56e054d56.png)

Here is how should render
![Schermata 2020-04-15 alle 17 29 45](https://user-images.githubusercontent.com/31321188/79356002-b46d8e00-7f3e-11ea-8987-3ddfd7305bf4.png)

### Steps to reproduce

Here is the code sandbox using nextjs 
https://codesandbox.io/s/friendly-dream-p6q4q

**Comment by remorses** [comment]
probably solving #821 will solve the styling problems

**Comment by wooorm** [comment]
Hi @remorses, thanks for your patience!

#821 is solved on the next branch, which will become v2. Could you check if your assumption is correct, and that solves it?

Otherwise, I’d have a hunch that it relates to SVG handling in MDX, which is also better in v2.

For me to dig in more, I’d appreciate a smaller example: just the bare minimum. No Next, to other libraries, as small as it can be!

**Comment by wooorm** [comment]
As #821 probably solves this, I’ll close this issue. If that’s not the case, please provide more info and I’ll reopen.
