### ISSUE TITLE
Compiler API: createCompiler is not a function

### ISSUE THREAD

**Issue by nwalters512** [mdx-js/mdx#1025]
### Subject of the issue

Per https://mdxjs.com/advanced/api#compiler, I should be able to access the compiler like this: 

```js
const { createCompiler } = require('@mdx-js/mdx')
```

However, when I try to do that, I get the following error:

```
TypeError: createCompiler is not a function
```

When I look at `node_modules/@mdx-js/mdx/index.js`, I see that `createMdxAstCompiler` is the only compiler creation function exported.

### Your environment

*   **OS**: macOS 10.14.6
*   **Packages**: `@mdx-js/mdx` ^1.5.8
*   **Env**: node 10.18.1, npm 6.13.4

### Steps to reproduce

Run the example on https://mdxjs.com/advanced/api#compiler with the latest version of all dependencies.

### Expected behaviour

`{ title: "Hello, MDX" }` should be logged to the console.

### Actual behaviour

The program crashes with the following error:

```
TypeError: createCompiler is not a function
```

**Comment by johno** [comment]
Thanks for opening an issue @nwalters512! Can you bump MDX to 1.5.9 (just cut a new release) and see if that fixes your issue?

**Comment by nwalters512** [comment]
That did the trick! Thanks much @johno 🙏
