### ISSUE TITLE
Support Class and decorator

### ISSUE THREAD

**Issue by YuunYang** [mdx-js/mdx#1028]
### Subject of the feature

Support writing decorator and class in MDX file

### Problem

Now, if I want to write class or decorator in mdx file, it will report an error. maybe we need add a feature to enable those grammar 

Like if I write a class in mdx file it will throw an error from '@mdx-js/loader/index.js': 
`Support for the experimental syntax 'classProperties' isn't currently enabled`,

It is actually not a bug in mdx, but a problem caused by lack of babel-loader plugin, I have tried to add those plugins in `mdx/mdx-hast-to-jsx.js`, solved those errors but caused another error -.-
![image](https://user-images.githubusercontent.com/15278220/80101005-5cb8cd80-85a3-11ea-8368-d4f70ac9f200.png)

### Expected behavior

Now, the mdx seems not support class declaration and other experimental syntax, So I want mdx to support more experimental

### Alternatives

No alternatives

**Comment by wooorm** [comment]
Could you fill out expected behavior and alternatives? Could you provide example code of what you’d like to be supported?

**Comment by YuunYang** [comment]
@wooorm Thanks for attention, I just updated the text

**Comment by wooorm** [comment]
Thanks. Is this issue about:
1. Allowing fancy new features in MDX, by letting you define your own Babel plugins?
2. These two features specifically?

**Comment by YuunYang** [comment]
Yes, because some experimental feature is used in many times, and it is much better if we can add custom babel or other configs

**Comment by wooorm** [comment]
Alright, so I’m assuming you want a solution to 1) instead of 2).

There are some caveats with solving this because some parts of the babel config are required for MDXjs to work, so we can’t give users *all* control.

**Comment by wooorm** [comment]
Hi @YuunYang, thanks for your patience!

The MDX loader is used alongside babel: https://github.com/mdx-js/mdx/tree/master/packages/loader. Have you tried configuring that?

To dig into this some more, I’d appreciate if you could update your issue with a minimal reproduction: something that a maintainer or contributor can run to reproduce your problem. Thanks!
