### ISSUE TITLE
RFC: Support variable declaration (const/let/var)

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#1046]
Currently, users leverage `export` syntax in order to instantiate local variables for usage in an MDX file. We could introduce `const`/`let`/`var` to better define an MDX document's API by allowing users to not need to overload exports for local variables.

Nothing else would really differ from the `export` syntax except that we'd read `const`/`let`/`var` directly.

## const

```jsx
const MyComponent = () => <div style={{ padding: 20, backgroundColor: 'tomato' }} />
```

## let

```jsx
let MyComponent = () => <div style={{ padding: 20, backgroundColor: 'tomato' }} />
```

## var

```jsx
var MyComponent = () => <div style={{ padding: 20, backgroundColor: 'tomato' }} />
```

**Comment by wooorm** [comment]
I think there are two alternatives (using a different style to show that they’d allow more too):

- **b)** executable code
  ````markdown
  # heading

  ```js run
  function MyComponent() {
    return <div style={{ padding: 20, backgroundColor: 'tomato' }} />
  }
  ```

  paragraph
  ````
- **c)** expressions
  ````markdown
  # heading

  {
    function MyComponent() {
      return <div style={{ padding: 20, backgroundColor: 'tomato' }} />
    }
  }

  paragraph
  ````

**Comment by aleclarson** [comment]
This feature would be much appreciated, as `export const` breaks Fast Refresh when its value is not a component.

**Comment by ng-hai** [comment]
I'm not sure my issue related to this. I'm using MDX/React with Parcel bundler, somehow it does not interpolate React expression

```mdx
export const name = "world";

# Hello {name.toUpperCase()}

{1+1}

<p>{1 + 1}</p>
```

And how it renders
```
Hello {name.toUpperCase()}
{1+1}
2
```

**Comment by wooorm** [comment]
@ng-hai that is unrelated to this proposal. You show MDX 2 features and Parcel does not support MDX 2 apparently.

**Comment by wooorm** [comment]
Closing as there is little traction on this.
The main problem I see is that we need to make exceptions for more and more words. And what about `function MyComponent`, for example?
There is a good alternative possible, as outlined above: `~~~js eval`. That can be supported in a plugin. The pseudocode for that is in [in this comment](https://github.com/mdx-js/mdx/issues/701#issuecomment-947030041).
