### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by vixalien** [mdx-js/mdx#1069]
### YAML Support

I was digging through [mdast](https://github.com/syntax-tree/mdast#yaml) and saw one component: YAML, which can be very important.

### Problem

Missing YAML markup to create front-matter.

### Expected behavior

We should be able to write code like:

```yaml
---
foo: bar
---
```

which can be passed as YAML as the following data

```js
{type: 'yaml', value: 'foo: bar'}
```

### Alternatives

The current alternatives are using `export const meta = {...}` which disturbs some use of pure-md and involve the use of JS which is very depressing in case of very many markdown files.

### End notes

We can try to implement this, if there is no problem.

**Comment by wooorm** [comment]
I believe you can add support for frontmatter in MDX by [using](https://mdxjs.com/advanced/plugins) the [remark-frontmatter](https://github.com/remarkjs/remark-frontmatter) plugin!

**Comment by johno** [comment]
Yeah, this is something you should be able to achieve in user land with a plugin as @wooorm brings up. We also have a guide using a custom loader to add frontmatter support: https://mdxjs.com/guides/custom-loader

Other frameworks that use MDX often have frontmatter support built in, too, like [`gatsby-plugin-mdx`](https://www.gatsbyjs.org/docs/mdx/).

As such, I'm going to close this for now, but please reach out to use if this doesn't suffice.
