### ISSUE TITLE
[Feature Request] Detect imports in mdx-loader

### ISSUE THREAD

**Issue by Ayc0** [mdx-js/mdx#1070]
### Subject of the feature

Add an `importStatements` exported constant to mdx files parsed by mdx-loader

### Problem

I'm using MDX for a custom website that documents React components (like StoryBook or StyleGuidist) and I have editable code snippets (just like this one: https://mdxjs.com/playground) but the difference is that I have a lot of components and variables that can be in the MDX scope and I cannot load all of them in it.

What I need is to have the list of every import statements done in the MDX file so that I can use those to populate a global scope.

I already done it here: https://github.com/bloczjs/mdx/tree/master/packages/mdx-loader and I wanted to know if you were interested in having this in the main mdx-loader code (it can be useful to other people I think)

### Expected behavior

if the MDX file is the following:

```jsx
import { Button } from '@mylib/button';

export const label = 'I am a label';

- I am a l list

<Button>{label}</Button>
```

the current output is a JS file with:

```js
import React from 'react';
// other imports to make it work

import { Button } from '@mylib/button';

export const label = 'I am a label';

export default function() {
  return (
    <>
      <ul><li>I am a list</li></ul>
      <Button>{label}</Button>
    </>
  );
}
```

I propose to add a new constant in the file (the named could be configured if we want to make it robust for everyone) `importStatements` that would act like this:

```js
import React from 'react';
// other imports to make it work

import { Button } from '@mylib/button';

export const label = 'I am a label';

export const importStatements = [
    {
        module: '@mylib/button',
        imports: [
            {
                imported: 'Button', // original exported name, used for cross files reconciliation
                local: 'Button',    // imported name, used for internal population of the scope for `@mdx/runtime`
                value: Button,      // imported value, injected from the import itself
            },
        ],
    },
];

export default function() {
  return (
    <>
      <ul><li>I am a list</li></ul>
      <Button>{label}</Button>
    </>
  );
}
```

### Alternatives

As I said, I already wrote the lib here: https://github.com/bloczjs/mdx/tree/master/packages/mdx-loader
But it will get out of date quickly (it is already and I only wrote the 1st version of this lib a few months ago).

Also the lib isn't meant to be configurable for now (we cannot change the variable name or deactivate this feature).

**Comment by wooorm** [comment]
Your alternatives point to a fork, not really a list of alternatives to your proposal 😅

One thing off the top of my head: imports/exports are available in mdast and hast, so remark and rehype plugin can access them.

Another: well, Babel doesn’t add such a thing to your javascript either, why would we do it? You can parse the result of MDX with Babel to get what you want?

**Comment by Ayc0** [comment]
A bit of followup on this: I wrote a remark plugin https://www.npmjs.com/package/@blocz/mdx-plugin-detect-imports to be used with `@mdx-js/loader`
