### ISSUE TITLE
Add TypeScript types to the `next` branch

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#1078]
@ChristianMurphy do you think we can grab the code changes from #811 and apply to the `next` branch? That's the new working branch for v2 since `v2` got so stale 😬😞. I just tried to cherry pick this commit but there have been some monorepo changes so wasn't sure how the `dtslint` side of things would work.

Would love to get this in there and make sure that you get the code credit!

**Comment by ChristianMurphy** [comment]
Thanks for the ping @johno!
I'll take a look at migrating those over to the `next` branch.
