### ISSUE TITLE
Variables cannot be checked in mdx

### ISSUE THREAD

**Issue by kuworking** [mdx-js/mdx#1089]
Provided that in a document I define a variable then I can use it as expected

```js
export const special = 'because x'

This is a post that is special {special}
```

But if I want to check if `special` is defined, I can't

```js
// export const special = 'because x'

<p>{special && `This is a post that is special ${special}`]</p>
```

At least it's giving me a `ReferenceError, special is not defined`

My use case is that I'm using a common `mdx` file for all posts, and I'd like to show a specific variable only if it is defined on the post

Is there any way to workaround this? Apart from defining the variable in all posts

**Comment by kuworking** [comment]
I've found that I can workaround this with

```js
<Comp
  special={typeof special !== 'undefined' ? special: null}
/>
```

That would suffice, leave it open in case I'm missing something here

**Comment by wooorm** [comment]
That error is te same if you do it outside of mdx, directly in a normal JavaScript file too, no?

**Comment by kuworking** [comment]
Damn, you're right, I guess I'm never working with uninitialized variables 😓
Sorry for the disturbance
