### ISSUE TITLE
MDX does not work with mismatched version of mds-utils

### ISSUE THREAD

**Issue by peter-mouland** [mdx-js/mdx#1090]
### Subject of the issue

When consuming MDX dependencies, we sometimes get errors when MDX updates related packages.

We have pinned our versions, but it seems MDX does not.

https://github.com/mdx-js/mdx/blob/master/packages/mdx/package.json#L40

Since version 1.6.1 of mdx react or run-time does not actually work with mismatched versions of utils, would you consider pinning your internal deps?

### Your environment

*   **OS**: MacOX
*   **Packages**: "@mdx-js/react" + "@mdx-js/run-time"
*   **Env**:  yarn: 1.21.1.    node: v12.14.1

### Steps to reproduce

pin your version of react or run-time to `1.6.1`. running yarn install will install `1.6.4` of utils.  This means the rendering no longer works as expected

we caught this error as we test for our class names to be applied to the md component:

```sh
dxInput › raw markdown › renders table correctly as markdown
    expect(received).toContain(expected) // indexOf
    Expected substring: "<table class=\"table--1clGC\">"
    Received string:    "<div class=\"mdxPlacement\" data-id=\"mdx-output\"><div class=\"component--3kq6z isPaddingMedium--3DaAA\" data-qa=\"card\"><div class=\"preview\"><table><thead><tr><th>c1</th><th>c2</th></tr></thead><tbody><tr><td>r1</td><td>r1</td></tr><tr><td>r2</td><td>r2</td></tr></tbody></table></div></div></div>"
```

our table component (the `Table` applies it's own classes and this is what breaks)
```
import React from 'react';
import { Table } from '@clearscore/rainbow.table';

import Spacing from '../spacing';

const BlockWrapper = () => ({ children }) => (
    <Spacing type={Spacing.types.TABLE}>
        <Table>{children}</Table>
    </Spacing>
);

export default BlockWrapper;
```

### Expected behaviour

for a pinned version of mdx react/run-time to work after a release of utils goes out.

### Actual behaviour

tests fails and rendering breaks when a new version of utils is released.

**Comment by johno** [comment]
Hmm, yeah I'm not sure I see a reason why we don't pin our internal deps. Do you see a reason not to @mdx-js/maintainers?

**Comment by ChristopherBiscardi** [comment]
makes sense to me for runtime (which is really react-runtime right now)

**Comment by johno** [comment]
https://github.com/mdx-js/mdx/pull/1157#issuecomment-661050766
