### ISSUE TITLE
Inconsistent behavior with MDX components in markdown paragraphs

### ISSUE THREAD

**Issue by mattly** [mdx-js/mdx#1093]
### Subject of the issue

I'm seeing inconsistent behavior when placing an MDX component into a markdown paragraph.

If the paragraph *starts with* an MDX component, any markdown _after_ the component fails to render.

If the paragraph starts with some text and later contains an MDX component, markdown after the component will render.

### Your environment

*   **OS**: macOS Mojave
*   **Packages**:     `"@mdx-js/mdx": "^1.6.5", "@mdx-js/react": "^1.6.5",`
*   **Env**: I reproduced this in the playground in Safari

### Steps to reproduce

Go to the [playground](https://mdxjs.com/playground), paste this in:

``` mdx
# Hello, world!

<Button>Here is a button</Button> Does it render _markdown_ on the same line as a component?
```

And see how `_markdown_` is not rendered

Now paste 

``` mdx
# Hello, world!

Some text. <Button>Here is a button</Button> Does it render _markdown_ on the same line as a component?
```

and see how the markdown does render

### Expected behaviour

I would expect consistent behavior, but would prefer the markdown to render in both scenarios

### Actual behaviour

The behaviors are different. Again, I would prefer the behavior where the markdown renders if the paragraph starts with an MDX component

**Comment by wooorm** [comment]
This will become more clear in MDX@2!

**Comment by mattly** [comment]
cool, I'm... looking forward to it.

**Comment by wooorm** [comment]
Forgot to mention it here, but there is a `next` branch and some open issues for MDX@2, which works well, although some more stuff will have to land on it first before we release it

**Comment by wooorm** [comment]
Hi all! I’m going to close this as it landed on the `main`, the (now default) branch we’re using to gear up to the MDX@2 release.

The reason is so that it’s more clear which issues still need to be solved already and don’t require further work.

Expect another `next` release soonish, which might include it, or maybe it’s already released as a beta!

For more info, see <https://github.com/mdx-js/mdx/issues/1041>.
