### ISSUE TITLE
Is it possible to load mdx from memory instead of file system?

### ISSUE THREAD

**Issue by Vadorequest** [mdx-js/mdx#1097]
### Goal

> The end-goal would be to define customer-specific pages and complex layouts, all stored on the DB, and allow a much higher level of customisation, from a customer perspective. (based on existing set of React components they could use and that'd be at their disposal)

I'd love the ability to load content stored in a DB, with some records containing markdown, and I would like to know if that's possible to load such content as MDX.

Basically, it's what's possible already, except it doesn't load the content from the filesystem.

This would allow advanced use case of content customisation, with the awesome ability to use complex JSX components at runtime.

**An example:**

DB record `product.description`, as long text (or similar):
```
# Product title

Some description

<Subscribe />
```

`Subscribe` is a JSX component that could be made available through the `MDXProvider` (or another way?).

> This would grant an ability that's not achievable even by using supposedly more powerful HTML.

**Use case:**
- Customer who wants to have access to powerful components/integrations while still writing "just" markdown

### Problem

A file-based approach is too limiting for such things, it's not as flexible.

**Comment by vladshcherbin** [comment]
Wondering same thing, if it's possible to store mdx files in database (as markdown or json) and then edit on client in some kind of wysiwyg or block editor.

**Comment by Vadorequest** [comment]
I've achieved it, but I'm not using MDX, just Markdown.

Demo example:
https://v2-mst-aptd-at-lcz-sty.vercel.app/fr/terms

PR: https://github.com/UnlyEd/next-right-now/pull/113

**Comment by mariusGundersen** [comment]
I've gotten it to work in a Gulpfile, but note that any imports need to be loaded somehow. I made it work by hacking the file loading in node, and it can be made to load from a different source than the filesystem. But I would be very careful with it for a cms, it could probably easily be made to run arbitrary code. You can read about my Gulpfile solution on my website https://mariusgundersen.net/mdx/

**Comment by millette** [comment]
Do you mean with [@mdx/runtime](https://github.com/mdx-js/mdx/tree/master/packages/runtime)? See #764

**Comment by johno** [comment]
As @millette suggested, this is something you can achieve with `@mdx-js/runtime`. Let us know if there's something missing with that library for what you're trying to achieve. Thanks for opening the issue!

Docs: https://mdxjs.com/advanced/runtime

**Comment by Vadorequest** [comment]
@johno I tried with MDX but really didn't go far. I just didn't get it.

Using https://github.com/probablyup/markdown-to-jsx, I got it working super fast, and eventually left behind MDX in favor of https://github.com/probablyup/markdown-to-jsx.

So, if your goal is to increase the adoption of that particular feature, I suggest you make it easier to get started with, use examples and such. 😃

**Comment by acaua** [comment]
@Vadorequest I think this is what you are looking for:

https://github.com/hashicorp/next-mdx-remote
