### ISSUE TITLE
BLM home page makes the documentation text white and unreadable

### ISSUE THREAD

**Issue by Kampfkarren** [mdx-js/mdx#1108]
The documentation looks like this after accessing the BLM home page:

![image](https://user-images.githubusercontent.com/3190756/84317795-426e8b00-ab22-11ea-9984-f95400137bb0.png)

To reproduce:

1. Go to the [getting started page](https://mdxjs.com/getting-started) directly. Notice how the text is readable.
2. Click the logo in the top left to access the BLM home page.
3. Click "the docs pages are still available".

**Comment by wooorm** [comment]
I think this can be closed, as there is now a banner! Thanks though, sorry we missed it!
