### ISSUE TITLE
How to /Can I export function to MDXProvider?

### ISSUE THREAD

**Issue by gaplo917** [mdx-js/mdx#1120]
I cannot find from the documentation. 

I want to create and export some global utility function to MDX Context. Like the following codes:

```jsx
function plusOne(a) {
  return a + 1
}

<MDXProvider functions={{ plusOne }}>
    <MDXRenderer>{some.body}</MDXRenderer>
</MDXProvider>
```

`some.mdx`
```md
# H1

Some content

<Comp value={plusOne(10)} />
```

**Comment by vitordino** [comment]
not only functions, constants in general would be great to pass them..

currently i’m using (inside the mdx) a function-as-a-child component that provides some simple values

**Comment by wooorm** [comment]
Why would that be a good idea? React also doesn’t let you access some global state in all your files 🤷‍♂️

**Comment by ChristianMurphy** [comment]
@vitordino It is possible to create a wrapping https://reactjs.org/docs/context.html that can be used inside custom components, contexts can share functions and values.

I agree with @wooorm that exposing functions on a global scope (rather than a Context scope) may not be a good idea.

**Comment by gaplo917** [comment]
@wooorm I want to build single data-source-less MDX component that allows user to specify their data source in `.mdx`. 

`SomeList.tsx`
```
interface SomeListProps {
  source: Promise<T[]>
}
export const SomeList: React.FC<SomeListProps> = ({ source }) => {
  return source.map((it,index) => <ListItem key={index} item={it} />)
}
```

`mdx-functions.ts`
```
export function fetchDataFromFacebook(pageUrl: string) : Promise<FBPost[]> {
  // some fetch logic and mapping
  return axios(..).then(..)
}
export function fetchDataFromTwitter(twAccountId: string) : Promise<FBPost[]> {
  // some fetch logic and mapping
  return axios(..).then(..)
}
```

Export in the MDX Scope.
```
<MDXProvider functions={{ fetchDataFromFacebook }} components={{ SomeList }} >
    <MDXRenderer>{some.body}</MDXRenderer>
</MDXProvider>
```

Then, in `some.mdx`
```
# Facebook
Here is some latest post from GraphQL community, check it out!
<SomeList source={fetchDataFromFacebook('https://www.facebook.com/groups/graphql.community')} />

# Twitter
Here is some latest twitter from GraphQL community, check it out!
<SomeList source={fetchDataFromTwitter('https://twitter.com/GraphQL')} />
```

Function Components are functions, the examples I wrote also is a function. There is no global state involved in my use case. Also, I believe `MDXProvider` is also using React Context underlying. 


### Without this feature
The MDX we could write has limitations to build "re-useable" components, although they share the same UI.

i.e. `some.mdx`
```
# Facebook
Here is some latest post from GraphQL community, check it out!
<FacebookPostList url={'https://www.facebook.com/groups/graphql.community'} />

# Twitter
Here is some latest twitter from GraphQL community, check it out!
<TwitterPostList url={fetchDataFromTwitter('https://twitter.com/GraphQL')} />
```

**Comment by ChristianMurphy** [comment]
Two answers to your question:
1. Can you do it? Yes (it already can be done)
2. Should you do this? Probably not, MDX is a content format

# Can you do it? Yes

in mdx-loader https://codesandbox.io/s/funny-grass-ce9cb?file=/src/hello.mdx
in runtime https://codesandbox.io/s/gifted-frost-frpdv

# Should you do this?

Probably not.
MDX is a content format, much like JSX.
It's bad form to put a lot of business logic directly in JSX, JSX is for presentation of HTML.
likewise it's bad form to stuff a bunch of functions into MDX.

**Comment by gaplo917** [comment]
@ChristianMurphy 
Let's say there are two groups of people.
- MDX Developer (Design the MDX features)
- MDX Writer (The consumer)

Faithfully, the current MDX gives the existing markdown writer to have an opportunity to write something encapsulate, expressive, and declarative.

I do think the reason of "why you have a chance to register a component in <MDXProvider> instead of `import` every time" is that. 

> You actually don't want the MDX Writer to know "the context, where to import". 

The MDX writer just needs to read the documentation to see which component they could use rather than import it every time in each .mdx file.

This exactly applies to the same case in "functions". The MDX Writer just need to read the documentation provided by MDX Developer to use the functions + components to create what they want. 

To determine this feature is bad or good, it depends on the quality of design on MDX Components/Functions. Instead, the above use case is a declaration to define where are the data source(getter), not business logic. This unleashes the opportunity for the MDX Developers to design declarative components that are in a simple and reusable manner rather than creating infinite components because of lacking this feature.

And yes, I could work around like this, and write a switch internally.
```
<SomeList type={'facebook'} pageId={'graphql'} />
<SomeList type={'twitter'} accountId={'graphql'} />
```

Data and UI should always be decoupled. I couldn't find an elegant way that allows MDX writer to compose a "Generic UI" + "Generic Data Source" without this feature.

[The use case](https://github.com/mdx-js/mdx/issues/1120#issuecomment-727117272) is a declaration to declare the remote data source from a MDX writer perspective. Nothing involves business logic in my point of view.

**Comment by ChristianMurphy** [comment]
> Faithfully, the current MDX gives the existing markdown writer to have an opportunity to write something encapsulate, expressive, and declarative.
> I do think the reason of "why you have a chance to register a component in instead of import every time" is that

@gaplo917 please read the example before commenting.
Functions can be passed in, using props https://codesandbox.io/s/funny-grass-ce9cb?file=/src/hello.mdx

**Comment by ChristianMurphy** [comment]
> Data and UI should always be decoupled

I agree, again please read my comments

> MDX (like Markdown, JSX, and HTML) is a presentation format.
> It's designed to render values passed to it.
> JavaScript is designed to handle logic.
>
> Mixing the logic into the presentation breaks separation of concerns.
> As well as taking away access to life cycle control (everything is inside the render function)

passing a function in is doable.
And if that's what you need for your use case go for it.
But there are trade offs, both from a practical standpoint (not life cycle access means data will be fetched on every render), and ideological (breaking separation of concerns)

**Comment by gaplo917** [comment]
> > Faithfully, the current MDX gives the existing markdown writer to have an opportunity to write something encapsulate, expressive, and declarative.
> > I do think the reason of "why you have a chance to register a component in instead of import every time" is that
> 
> @gaplo917 please read the example before commenting.
> Functions can be passed in, without importing, using props https://codesandbox.io/s/funny-grass-ce9cb?file=/src/hello.mdx

Ops, the previous version example you wrote don't use a `props` but `import`.

That's probably a new way for my MDX components design, Thanks!
