### ISSUE TITLE
acorn__WEBPACK_IMPORTED_MODULE_1__.Parser.extend is not a function

### ISSUE THREAD

**Issue by deligent-ant** [mdx-js/mdx#1121]
when use in ssr (react nextjs),it will show the error below

```js
acorn__WEBPACK_IMPORTED_MODULE_1__.Parser.extend is not a function
```
how can i do

**Comment by johno** [comment]
Thanks for opening up an issue! Unfortunately, there's not a lot of information so it will be tricky for us to help you.

Are you using the `@next/mdx` plugin? Can you provide a minimal reproduction we can use to debug?

**Comment by johno** [comment]
Going to go ahead and close this since there's nothing actionable on our end. If you create a minimal reproduction with a bug we'd love to see it, so feel free to open up a new issue if you do. Thanks!
