### ISSUE TITLE
It's pointless to use buble in @mdx-js/runtime when @mdx-js/mdx depends on babel

### ISSUE THREAD

**Issue by wereHamster** [mdx-js/mdx#1124]
### Subject of the feature

When you use @mdx-js/runtime you are including two completely separate ES parsers, buble AND babel. Also, the buble-jsx-only dependency is tiny compared to all the babel dependencies.

https://bundlephobia.com/result?p=@mdx-js/runtime@1.6.6

### Problem

It unnecessarily increases the bundle size.

### Expected behavior

Not to include duplicate, redundant code.

**Comment by johno** [comment]
Thanks for opening up the issue! This is something that will be addressed in v2 because we will be looking to drop babel entirely.

Feel free to follow along here #1152
