### ISSUE TITLE
Title set briefly using next/head before reverting 

### ISSUE THREAD

**Issue by sarimabbas** [mdx-js/mdx#1133]
### Subject of the issue

I'm using `<Head>` from "next/head" to set page titles. It works well on my normal`.tsx` pages. But in `.mdx` pages, the title is only set for a split second when loading the page before it reverts to "localhost". Which is why I'm posting here on the MDX repo. 

![ScreenFlow](https://user-images.githubusercontent.com/3000809/86639941-cc860400-bfa7-11ea-8c06-e80633a98a55.gif)

Here is some code:

```js
// sample-post.mdx

import Head from "next/head";

<Head>
  <title>Sarim - My page title</title>
</Head>

# My page title
```

The title shows up in the source code, just not in the browser tab. 

Strangely, when I remove the `<Head>` import, the title persists, but then I get a warning that <Head> is not registered with MDXProvider. 

### Your environment

*   **OS**: macOS 10.15.5 Catalina 
*   **Packages**: "@mdx-js/loader": "^1.6.6", "@next/mdx": "^9.4.4", "next": "9.4.4",
*   **Env**: Node 14.4.0, Google Chrome (latest)

### Steps to reproduce

1. Create an `.mdx` file in `pages`
2. Import `next/head` and use it to set a title 
3. Observe that the title is set only momentarily before blanking

**Comment by wooorm** [comment]
Thanks for all the details! I'm doubting that this is a problem with MDX, rather, maybe you'll have more luck in the Next direction?

**Comment by samrobbins85** [comment]
You might have better luck with the [next-mdx-enhanced](https://github.com/hashicorp/next-mdx-enhanced) plugin. You can set the title in the frontmatter (which is a nicer user interface anyway) and specify it to be taken in as the title in a layout you create. I've got a website set up with this technique and I don't get the issue you are facing.

**Comment by sarimabbas** [comment]
I'll give that a try, thank you!
