### ISSUE TITLE
Running yarn bootstrap returns not found

### ISSUE THREAD

**Issue by samrobbins85** [mdx-js/mdx#1137]
### Subject of the issue

Running yarn bootstrap returns a command not found error, this is due to there not being a bootstrap command in the package.json here https://github.com/mdx-js/mdx/blob/next/package.json

### Your environment

*   **OS**: OpenSUSE Tumbleweed 2020-07-08
*   **Env**: Node 14.4.0, Yarn 1.22.4, npm 6.14.5

### Steps to reproduce

Run yarn followed by yarn bootstrap, as instructed in https://mdxjs.com/contributing

### Expected behaviour

Some command should run

### Actual behaviour

An error is returned that the command boostrap is not found

**Comment by wooorm** [comment]
@JounQin I believe you changed the scripts. Do you have any insight here / What are the suggestions on how to run tests or docs site?

**Comment by JounQin** [comment]
@wooorm Oh sorry I believe `yarn bootstrap` need to be removed in favor of yarn workspaces feature.

**Comment by wooorm** [comment]
Could you PR a fix? Or do you have a short list of commands to run, that I can then PR?
