### ISSUE TITLE
Parcel implementation not working

### ISSUE THREAD

**Issue by dioptre** [mdx-js/mdx#1142]
### Subject of the issue

Parcel demo not working (https://mdxjs.com/getting-started/parcel)
### Your environment
Mac
### Steps to reproduce
Install parcel and mdx.

Create an index.mdx file with ```# test this```

run ```parcel index.mdx```

### Expected behaviour
Should render
### Actual behaviour
Doesn't render

(I'm new to both parcel and mdx)

**Comment by hamlim** [comment]
Hmm, it has been a while since I've used parcel with MDX (mostly using webpack these days). I can try and take a look at it today though!

**Comment by hamlim** [comment]
Alright so I think the plugin only works when your parcel entry point is a different file, e.g. `parcel index.html` and from within that `index.html` file you import the MDX file and render it.

I setup an example here following those docs: https://github.com/hamlim/parcel-mdx-demo

Seems like there might be an opportunity here to improve that documentation to call this out possibly?
