### ISSUE TITLE
Only run test-types once, perhaps as part of its own GitHub Action

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#1172]
`yarn test-types` appears to be a bit flaky when run in CI (likely as a result of our large test matrix) and causes builds to fail. Perhaps it makes sense to run it in its own action ~~and maybe mark as optional~~?

cc/ @ChristianMurphy @JounQin

**Comment by ChristianMurphy** [comment]
I'd prefer to keep it enabled if possible, type tests are very helpful for verifying the correctness typings.
Having it in a separate job would be okay if desired.
I'm more interesting in finding/fixing what is causing the flakiness.

**Comment by johno** [comment]
Cool, that works for me! Maybe to start we can make it a single action running on ubuntu + node v14 if we can't get to the bottom of the flakiness?

AFAICT it seems to request dependencies and install stuff on the fly which might not be resilient enough to GitHub Action network flapping 🤔

**Comment by ChristianMurphy** [comment]
#1178 has one possible way of addressing this, based of the dtslint readme:

> Package lock files such as yarn.lock and package-lock.json may cause this issue because of our github dependency on "definitelytyped-header-parser": "github:Microsoft/definitelytyped-header-parser#production", which contains the list of typescript versions to install. To fix this, try deleting your lock file and re-installing.

https://github.com/microsoft/dtslint#faq

if the issue persists it may be related to https://github.com/microsoft/dtslint/issues/267

**Comment by johno** [comment]
Gonna push the test out to its own (required) action for now to wait to check stability and then try to figure out what's going wrong with the windows tests.

Thanks for the quick response and PR @ChristianMurphy 🙏
