### ISSUE TITLE
bug(remark-mdx): remark-stringify should be a dependency

### ISSUE THREAD

**Issue by redallen** [mdx-js/mdx#1189]
Package: "remark-mdx": "2.0.0-next.4"

## Steps to reproduce
`npm init` -> `npm i remark-mdx@2.0.0-next.4`

`require('remark-mdx')` throws:
```
Error: Cannot find module 'remark-stringify/lib/util/enclose-uri':
Require stack:
- remark-mdx/lib/serialize/link.js
- remark-mdx/lib/serialize/index.js
- remark-mdx/index.js
```

`remark-stringify` is currently listed as a `devDependency`.

**Comment by wooorm** [comment]
Nice catch! Related to https://github.com/mdx-js/mdx/pull/1171

**Comment by johno** [comment]
Released in the latest version of `next`. Thanks for reporting and opening a PR for the fix!
