### ISSUE TITLE
Emphasis inside math block are being parsed

### ISSUE THREAD

**Issue by skyme5** [mdx-js/mdx#1198]
### Subject of the issue

For below input

```md
Display mode:

$$
I = 1_{1} + 2_{2} + 3_{3}
$$

Inline-mode:
$I = 1_{1} + 2_{2} + 3_{3}$
```

![2020-07-30T21-31-20_MDX](https://user-images.githubusercontent.com/15525399/88946503-f67fcd00-d2ac-11ea-8b70-4299fc98db15.png)

As you can see the Emphasis are being parsed.

### Expected behaviour

Content inside math block (emphasis (`_`)) should not be parsed.

### Actual behaviour

Content inside math block is parsed

**Comment by wooorm** [comment]
You can use `remark-math` in `remarkPlugins`!
