### ISSUE TITLE
Wrapping JSX around a multiline nested list breaks the parser

### ISSUE THREAD

**Issue by patrickarlt** [mdx-js/mdx#1202]
### Subject of the issue

Sorry for the terrible issue title.

I've run into an odd edge case when trying to use JSX with multiple paragraphs inside a nested list that breaks the parser. [AST explorer link for broken version](https://astexplorer.net/#/gist/ca5b9c951ef515aba8d0c6a01eb8b09b/d2c3aada3f5a1785400ceda8c927a0bbc558adab).

```
1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
et dolore magna aliqua.

   <Box>

   - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
   - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

   </Box>
```

This ends up with `unknown: Expected corresponding JSX closing tag for <li>`

Indenting the list after the line break fixes this. [AST explorer link for fixed version](https://astexplorer.net/#/gist/ca5b9c951ef515aba8d0c6a01eb8b09b/c007f5fbc50bafbcdbb187883ad384a12737cdb1)

```
1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
   et dolore magna aliqua.

   <Box>

   - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
   - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

   </Box>
```

However I'm filing this as a bug because every other Markdown processor I've previously used (remark, markdown-it, GitHub) all seem to parse the first case just fine. [AST explorer link for remark](https://astexplorer.net/#/gist/13c89c1de718347174c2c140abd02f7c/c27feda3dfff4e850016b9ccf1a8229ae3170275). The remark tree looks a _little_  odd here but it does serialize to the correct HTML.

```
1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
et dolore magna aliqua.

   <div class="box">

   - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
   - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

   </div>
```

### Your environment

*   **OS**: AST Explorer
*   **Packages**: 1.5.8 via [AST Explorer](https://github.com/fkling/astexplorer/blob/fbcdbcea86f32680983d1798f91314adb2a479a6/website/package.json#L50)
*   **Env**: All browsers/environments

### Steps to reproduce

[AST explorer link for broken version](https://astexplorer.net/#/gist/ca5b9c951ef515aba8d0c6a01eb8b09b/d2c3aada3f5a1785400ceda8c927a0bbc558adab).

```
1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
et dolore magna aliqua.

   <Box>

   - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
   - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

   </Box>
```

This ends up with `unknown: Expected corresponding JSX closing tag for <li>`

### Expected behavior

What should happen?

MDX should parse this as.

* `OL`
   * `LI`
      * `P`
      * `<Box>`
        * `UL`
            * `LI`
               * `P`
            * `LI` 
               * `P`

Given that this is pretty standard Markdown behavior I think this should work for compatibility reasons.

What happens instead?

Parser error.

**Comment by patrickarlt** [comment]
I'm unsure if MDX v2 will handle this correctly if it does then great!

I'm also happy to write a failing test case for this (v1 or v2). Let me know.

**Comment by patrickarlt** [comment]
Looks like v2 fixes this:

```js
var mdx = require("@mdx-js/mdx");

const content = `
import { Box } from "rebass";

1. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
et dolore magna aliqua.

      <Box>

   - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
   - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

      </Box>
`;

const transpile = async () => {
  const jsx = await mdx(content);
  return jsx;
};

transpile().then(console.log);
```

Produces:

```
/* @jsx mdx */
import { Box } from "rebass";

const makeShortcode = name => function MDXDefaultShortcode(props) {
  console.warn("Component " + name + " was not imported, exported, or provided by MDXProvider as global scope")
  return <div {...props}/>
};

const layoutProps = {};
const MDXLayout = "wrapper"
export default function MDXContent({
  components,
  ...props
}) {
  return <MDXLayout {...layoutProps} {...props} components={components} mdxType="MDXLayout">
    <ol>

      <li {...{
        "parentName": "ol"
      }}>

        <p {...{
          "parentName": "li"
        }}>{`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
et dolore magna aliqua.`}</p>


        <Box mdxType="Box">
          <ul>

            <li {...{
              "parentName": "ul"
            }}>{`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`}</li>


            <li {...{
              "parentName": "ul"
            }}>{`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`}</li>

          </ul>
        </Box>

      </li>

    </ol>
  </MDXLayout>;
}

;
MDXContent.isMDXComponent = true;
```

**Comment by johno** [comment]
Thanks for opening up such a thorough issue!

Yeah, this is something that will be resolved in v2, and is something we likely won't be able to support in v1 because it'd be too complex a fix.

You _should_ be able to upgrade to v2 (`next`) for your project since it's pretty stable now and will likely be released in the next month or so. We don't anticipate any additional breaking changes (if it works on your site now, it should continue to work), and will be actively fixing bugs in the v2 branch that are brought up by folks willing to take the canary release for a spin : )

**Comment by patrickarlt** [comment]
Thank @johno since there is workaround I don't really think this needs fixing in v1. I'm trying a v2 update now and and hitting

```
 ERROR #98124  WEBPACK

Generating SSR bundle failed

Can't resolve 'gatsby-plugin-mdx/loaders/mdx-components' in '/Users/patr7104/Projects/gatsby-theme-arcgis-for-developers/demo'

If you're trying to use a package make sure that 'gatsby-plugin-mdx/loaders/mdx-components' is installed. If you're trying to use a local file make sure that the path is correct.

File: ../gatsby-theme-afd/node_modules/gatsby-plugin-mdx/wrap-root-element.js
```

This is trying to run an example site using a theme in the same yarn workspace it is based on https://github.com/gatsbyjs/gatsby-starter-theme-workspace I'm fairly certain the error is mine somewhere though we have a lot of custom code and I can't get it to work in a minimal scenario based on that theme starter.

I'm going to keep trying on a minimal reproduction of this issue and if I can nail down and reproduction I'll open up a new issue. In the meantime I've made a post on Spectrum https://spectrum.chat/mdx/general/problems-updating-to-mdx-v2~126eddd4-942f-4e8b-9064-de45e8b4a4d9 if you have any debugging tips I would appreciate it.

I think this can be closed since it is resolved in 2.0 and there is a reasonable workaround in 1.0.

**Comment by patrickarlt** [comment]
Ended up figuring this out https://spectrum.chat/mdx/general/problems-updating-to-mdx-v2~126eddd4-942f-4e8b-9064-de45e8b4a4d9. It was an issue with the way we were using Yarn workspaces.

**Comment by wooorm** [comment]
Let us know how v2 testing goes!
