### ISSUE TITLE
How to work with remark-highlight.js?

### ISSUE THREAD

**Issue by egoist** [mdx-js/mdx#122]
Trying to use `remark-highlight.js`:

```js
{
	mdPlugins: [
		require('remark-highlight.js')
	]
}
```

But what I got is:

<img width="911" alt="2018-05-02 1 51 49" src="https://user-images.githubusercontent.com/8784712/39485663-119f35c2-4dac-11e8-9357-52caf9eb22ee.png">

**Comment by timneutkens** [comment]
@johno this is actually a bug in mdx's wrapping of code tags.

**Comment by trevordmiller** [comment]
@timneutkens Would you mind updating this issue once https://github.com/mdx-js/mdx/pull/132 is released? Thank you.

**Comment by chen3452** [comment]
@trevordmiller thank you guys! it works

**Comment by wooorm** [comment]
Hey folks! tip: use `hastPlugins` with [rehype-highlight](https://github.com/rehypejs/rehype-highlight) (lowlight) or [@mapbox/rehype-prism](https://github.com/mapbox/rehype-prism) (refractor) instead!

There are some slight differences and I’d suggest using the rehype versions above remark versions!
