### ISSUE TITLE
Global MDX components do not work when MDX is used via a Gatsby theme with NPM.

### ISSUE THREAD

**Issue by patrickarlt** [mdx-js/mdx#1223]
I was unsure if this was a Gatsby or MDX issue so this is cross posted with Gatsby https://github.com/gatsbyjs/gatsby/issues/26541.

### Subject of the issue

I'm running into an issue where we add components to MDX global scope but those components don't render in the page if the theme is installed via NPM, the compnents work fine if the theme is installed via Yarn.

We publish a theme (`gatsby-theme-minimal`) to a tag on Github via `gitpkg`. This theme configures MDX via `gatsby-plugin-mdx`, configures pages and provides a component for rendering MDX files.

Several additional components are added to the `<MDXProvider>` in the theme:

```jsx
<MDXProvider components={{ Box, Test }}>
  <MDXRenderer>{mdx.body}</MDXRenderer>
</MDXProvider>
```

However when we install with `npm` in the `reproduction` folder we see this on the `/test/` page:

![2020-08-18_12-43-25](https://user-images.githubusercontent.com/378557/90558506-0888b900-e151-11ea-9ef1-6885bc044cbb.png)

We also see the following message in the console:

```
Component Box was not imported, exported, or provided by MDXProvider as global scope commons.js line 5071 > Function:14:13
Component Test was not imported, exported, or provided by MDXProvider as global scope commons.js line 5071 > Function:14:13
Component Box was not imported, exported, or provided by MDXProvider as global scope
```

Installing with `yarn` in the reproduction folder produces this on the `/test/` page:

![2020-08-18_13-04-18](https://user-images.githubusercontent.com/378557/90560069-661e0500-e153-11ea-9bfa-281e40320d88.png)

### Your environment

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 80.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.23.12 => 2.24.47
    gatsby-source-filesystem: ^2.1.41 => 2.3.24
    gatsby-theme-minimal: https://github.com/patrickarlt/gatsby-mdx-theme-reproduction-issue.git#gatsby-theme-minimal-v1.0.0-gitpkg => 1.0.0
  npmGlobalPackages:
    gatsby-cli: 2.12.29
```

### Steps to reproduce

I have created a minimal reproduction at https://github.com/patrickarlt/gatsby-mdx-theme-reproduction-issue

1. Clone the repo
2. `cd reproduction`
3. `npm install`
4. `gatsby develop`
5. Note the styling on `/test/`
6. Kill the server
7. `gatsby clean`
8. Delete `package-lock.json` and `node_modules`
9. `yarn install`
10. `gatsby develop`
11. Note the styling on `/test/`

### Expected/Actual behaviour

The MDX page should render the same regardless on installation via Yarn/NPM.

![2020-08-18_13-04-18](https://user-images.githubusercontent.com/378557/90561774-0ffe9100-e156-11ea-8859-cbddeba39a9e.png)

**Comment by wooorm** [comment]
The code you have here, in the original issue, seems rather Gatsby specific. If there is an MDX-related problem, I’d appreciate a smaller reproduction: something that only uses MDX. Thanks!
