### ISSUE TITLE
img Markdown tag dynamic src

### ISSUE THREAD

**Issue by garyposter** [mdx-js/mdx#1249]
### Subject of the feature

Using `next-images`, I tried doing this...

```
![Flowchart of delegation]({require("./delegating.png")})
```

and this.

```
import delegating from "./delegating.png";
![Flowchart of delegation]({delegating})
```

They didn't work. For instance, the second results in `<img src="%7Bdelegating%7D" alt="Flowchart of delegation"/>`

It would be cool if they worked!

Of course, I can do `<img src={delegating} alt="Flowchart of delegation" />` but I wanted to support the markdown spelling.

### Problem

Support the markdown spelling of images, while also importing the image in next to trigger including it in the build.

### Expected behavior

I want src to actually be the result of the expression.

### Alternatives

I also tried a component that could parse something like this:

```
![Flowchart of delegation](./delegating.png)
```

However, making that work with next-image requires the component to do a dynamic require, which probably is a bad idea? It also requires that the component receive the mdx file path in order to calculate relative paths, but I could do that with a tree walker if I needed to.

**Comment by wooorm** [comment]
For Next related questions, it might be better to ask Next folks.

For MDX, the recommended route is to either do [tree traversal with a plugin](https://mdxjs.com/advanced/plugins), or do JSX: `<img src={delegating} alt="Flowchart of delegation" />`

**Comment by dpyzo0o** [comment]
@garyposter Hi, have you managed to get it working?
