### ISSUE TITLE
Inline HTML breaks markdown formatting

### ISSUE THREAD

**Issue by TomBrien** [mdx-js/mdx#1251]
### Subject of the issue

Using inline HTML (i.e. `<img ... />`) causes further markdown formatted script to fail. I saw this with Docusaurus 2.0.0-alpha62+ and they directed me to raise it here (ref: facebook/docusaurus#3403).

### Your environment

*   **OS**:  Win10 and ubunutu 20.04
*   **Packages**:  Docusaurus 2.0.0-alpha62+ which I believe is calling [`"@mdx-js/mdx": "^1.5.8"`](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-mdx-loader/package.json#L18)
*   **Env**:  Chrome 85.0.4183.83, yarn 1.22.4, node.js 12.16.1

### Steps to reproduce
- Create a simple page containing, for example:
```js
<img src='https://companion.home-assistant.io/assets/apple.svg' />Hello, world. `code`.
```
- Build page

You can also see it here on <https://mdxjs.com/playground/>

For a fuller version see <https://github.com/home-assistant/companion.home-assistant/tree/fix-dark-logos> and the associated draft PR home-assistant/companion.home-assistant#323 and [Netlify preview](https://deploy-preview-323--home-assistant-companion-docs.netlify.app/docs/core/sensors#activity-sensor)

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behaviour
Expect the image to render inline and "code" to be formatted as inline code. The code can be rendered by including to line breaks between the HTML and the rest but this of course breaks the inline image. This gives:

![image](https://user-images.githubusercontent.com/12411302/92218402-f917a880-ee90-11ea-8a69-b1dd709616e2.png)

### Actual behaviour

Inline code not rendered. 

![image](https://user-images.githubusercontent.com/12411302/92218344-deddca80-ee90-11ea-88e1-483e7c09e0a5.png)

Further, a line like:
```js
<img src='https://companion.home-assistant.io/assets/apple.svg' />Hello, world. `<code>`.
```

Causes a compile error (taken from playground site)

```
SyntaxError: unknown: Unterminated JSX contents (10:16)
   8 | <img src='https://companion.home-assistant.io/assets/apple.svg' />
   9 | <p>{`Hello, world. `}<inlineCode parentName="p">{`code`}</inlineCode>{`.`}</p>
> 10 |     </MDXLayout>
     |                 ^
  11 |   )
  12 | };
  13 | MDXContent.isMDXComponent = true
```

**Comment by wooorm** [comment]
This is solved in MDX@2.

For a solution, why not use a markdown image? (`[important: add alt text here](path.svg)`)

**Comment by TomBrien** [comment]
That's good to know. Yeah sorry that wasn't clear in the MWE. I need to add a `class` attribute on some images to allow CSS to invert them when switching between dark and light mode

**Comment by wooorm** [comment]
Hi all! I’m going to close this as it landed on the `main`, the (now default) branch we’re using to gear up to the MDX@2 release.

The reason is so that it’s more clear which issues still need to be solved already and don’t require further work.

Expect another `next` release soonish, which might include it, or maybe it’s already released as a beta!

For more info, see <https://github.com/mdx-js/mdx/issues/1041>.
