### ISSUE TITLE
Build Modernization

### ISSUE THREAD

**Issue by ChristopherBiscardi** [mdx-js/mdx#1271]
https://github.com/mdx-js/mdx/pull/1269 introduces microbundle to handle the preact package builds and enables node v14 native esm usage for mdx (that is, importing mdx from .mjs files). The usage should expand and result in the removal of `@pkgr/rollup`.

This issue should be closed after the work in #1269 is expanded to the other packages.

**Comment by wooorm** [comment]
@ChristopherBiscardi Is this, to bring ESM to all packages, something you can work on, or should others work on it?

**Comment by ChristianMurphy** [comment]
Cross pollinating, micromark recently went through a similar ESM modularization.
https://github.com/micromark/micromark/pull/27, https://github.com/micromark/micromark/pull/28, https://github.com/micromark/micromark/pull/35, https://github.com/micromark/micromark/pull/36.
The transition worked well for node projects, but runtime/browser usage (particularly builds with webpack 4) was negatively impacted https://github.com/remarkjs/react-markdown/issues/518

I'm all for a modular build, there may be some additional documentation on supported build systems, and/or testing common build platforms which may be needed to roll this out smoothly.

**Comment by ChristopherBiscardi** [comment]
To clarify the core purpose of this issue: we are currently on an unsupported one-off build toolchain that isn't used anywhere else afaict, was last released months ago, and has only 257 weekly downloads: https://www.npmjs.com/package/@pkgr/rollup. It is a project risk issue to depend on a niche build pipeline that we don't control and isn't maintained. The work was started to get rid of that toolchain and put us onto something more mainstream that is actively maintained (microbundle in this case) that is still based on rollup.

Your concerns about the handling of esm conversion in micromark are heard, but not required for this conversion as the source code is not changing and all existing exports are being maintained as-is. I'll repeat that we are not changing the underlying build system like micromark did (from browserify to rollup). MDX is already built using rollup.

**Comment by wooorm** [comment]
I replaced pkgr with microbundle for vue and react already: https://github.com/mdx-js/mdx/commit/e7e9d464c7d1eec83bc7b86689ba9428a0e023bd. It’s no longer used.

> MDX is already built using rollup.

Not all of it is: `mdx-js/mdx`, `mdx-js/loader` , and `mdx-js/vue-loader` use CJS. I was wondering if  this issue was also about changing them to MJS?

(aside: `mdx-js/runtime` uses MJS but doesn’t have microbundle set up yet so that’s a todo, it seems it was done by pkgr before and I missed it)

**Comment by ChristopherBiscardi** [comment]
> I replaced pkgr with microbundle for vue and react already: e7e9d46. It’s no longer used.

great! seems like this would've been a useful issue to mention in that PR.

> MDX is already built using rollup.
>> Not all of it is: mdx-js/mdx, mdx-js/loader , and mdx-js/vue-loader use CJS. 

you are correct in stating that the packages that don't get built, are also not built with rollup. I will be more clear about that next time.

> I was wondering if this issue was also about changing them to MJS?

This issue is about removing pkgr. If pkgr is gone, we can close this issue.

**Comment by wooorm** [comment]
Perfect, and yes you’re right!

Then this was closed by GH-1338.
