### ISSUE TITLE
Question: why is `mdx` shown in example as a production dependency?

### ISSUE THREAD

**Issue by trevordmiller** [mdx-js/mdx#128]
The docs currently show:

```
npm install --save @mdx-js/mdx
npm install --save-dev @mdx-js/loader
```

Shouldn't the `@mdx-js/mdx` also be a `--save-dev` since it is all compiled? Or does MDX have a production runtime that is required? If so, how much weight does it add to your app? And then shouldn't the `@mdx-js/mdx` dependency be a peer dependency of `@mdx-js/loader`?

p.s. Thanks for the fantastic library!

**Comment by timneutkens** [comment]
You’re right that it should be a devDep, please send a pull request 🙏🏻

**Comment by timneutkens** [comment]
Basically mdx is transpiled to a js/jsx file, which is then parsed by babel.
