### ISSUE TITLE
[v2] Lines beginning with `~` inside a JSX block fail to parse

### ISSUE THREAD

**Issue by jerelmiller** [mdx-js/mdx#1290]
While using MDX v2.0.0-next.8, it appears that lines beginning with `~` fail to parse when the text is nested inside a JSX block. An error is thrown when the parser tries to parse it:

```
Unexpected end of file in code, expected a corresponding fence for `~`
```

### Steps to reproduce

You can reproduce this while using the [playground](https://mdx-git-next.mdx.vercel.app/playground/) and copying this sample code:

```js
<div>
  ~/.newrelic
</div>
```

Notice that be removing the `<div>` , it is able to parse correctly. I am using the following minimal unified setup to reproduce this:

```js
const mdx = require('remark-mdx');
const parse = require('remark-parse');
const unified = require('unified');

const tree = unified().use(parse).use(mdx).parse(`
<div>
  ~/.newrelic
</div>
`);
```

Removing the `remark-mdx` plugin parses the tree without error, albeit with `html` nodes instead of the additional parsed nodes provided by `remark-mdx`. 

### Expected behaviour

I would expect this to only try and the parse the text as a code block inside JSX nodes when there are 3 or more `~` 
characters.

**Comment by wooorm** [comment]
Yeah it’s a bit ugly. You can use the character reference version for now though: `&#x7e;` or `&#126;`. Maybe an escape works too? `\~`. And lastly, using a brace expression always forces plain text instead of markdown: `{'~/.newrelic'}` (`as *emphasis* works here {'but not *here*'}`)

**Comment by jerelmiller** [comment]
Excellent! That is great information. I can certainly use that as a workaround in the near term.

Is this something, long term, that would be considered as a bug fix in the parser since fenced code blocks require 3 tildes?

**Comment by wooorm** [comment]
It is a bug indeed. As remark is moving to micromark, a rewrite of the parser is again needed anyway. I’m hoping it can wait a bit for that

**Comment by jerelmiller** [comment]
Oh totally! I'd be happy to use the workaround until this has been updated. I'll keep tabs on the rewrite of the parser. Thanks for the update!

**Comment by wooorm** [comment]
Closing as this was reported a bit earlier here: #1238. We can discuss there.
