### ISSUE TITLE
Abbreviations <abbr>

### ISSUE THREAD

**Issue by murillo94** [mdx-js/mdx#1326]
# Subject of the feature

Support html tag `abbr` in md rendered templates. Anyone trying do this? Or any plans to add `abbr` in `MDXProviderComponents`?

### Expected behavior

As `abbr` are supported in markdown template, it's useful the lib support something like [this one](https://github.com/Python-Markdown/markdown/blob/master/docs/extensions/abbreviations.md#:~:text=The%20Abbreviations%20extension%20adds%20the,in%20the%20standard%20Markdown%20library.)

**Comment by ChristianMurphy** [comment]
@murillo94 this already is supported, try entering
```mdx
<abbr title="American Psychological Association">APA</abbr>
```
into the playground https://mdxjs.com/playground
it renders the abbr tag as expected.

If you have futher questions please use https://github.com/mdx-js/mdx/discussions rather than the issue tracker.
