### ISSUE TITLE
Can't get syntax highlighting to work

### ISSUE THREAD

**Issue by trevordmiller** [mdx-js/mdx#134]
I saw that https://github.com/mdx-js/mdx/issues/122 was fixed so I tried to add syntax highlighting.

I ran `npm install remark-highlight.js --save-dev`, then updated my `next.config.js` to include it:

```
const remarkHighlight = require('remark-highlight.js')

module.exports = {
  pageExtensions: ['js', 'md'],
  webpack: (config, { defaultLoaders }) => {
    config.module.rules.push({
      test: /\.md$/,
      use: [
        defaultLoaders.babel,
        {
          loader: '@mdx-js/loader',
          options: {
            mdPlugins: [remarkHighlight],
          },
        },
      ],
    })

    return config
  },
}
```

This is what the output looks like:

![image](https://user-images.githubusercontent.com/5497885/39665268-5463b6b8-504e-11e8-9b42-3afaf87836be.png)

Here are the relevant parts of my package.json:

```
{
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "devDependencies": {
    "@mdx-js/loader": "^0.8.1",
    "@mdx-js/mdx": "^0.8.1",
    "remark-highlight.js": "^5.0.0"
  },
  "dependencies": {
    "next": "^6.0.0",
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
  }
}
```

Is this another bug or am I doing something wrong? It would be very helpful if the docs could include an example as I feel like syntax highlighting is a common use case.

**Comment by timneutkens** [comment]
It wasn't released yet.
