### ISSUE TITLE
Docs: How to use MDX with create-react-app?

### ISSUE THREAD

**Issue by bcherny** [mdx-js/mdx#135]
Is it possible to do without ejecting?

**Comment by timneutkens** [comment]
Check https://github.com/mdx-js/mdx/tree/master/examples/create-react-app

**Comment by bcherny** [comment]
Thanks for the quick response @timneutkens!

For anyone that finds this issue in the future:

1. Init a project with *create-react-app*
2. Install *react-app-rewired* ([docs](https://github.com/timarney/react-app-rewired))
3. Install mdx: `yarn add --dev @mdx-js/loader @mdx-js/mdx`
4. Copy+paste this [config-overrides.js](https://github.com/mdx-js/mdx/blob/master/examples/create-react-app/config-overrides.js) into your project's root

And if you're using TypeScript, also:

5. Install *react-app-rewire-typescript*
6. Add it to your existing config-overrides.js ([docs](https://github.com/lwd-technology/react-app-rewire-typescript))
7. Create an ambient file *mdx.d.ts* and include it in your tsconfig.json:

  ```ts
  // mdx.d.ts
  declare module '*.mdx' {
    let MDXComponent: () => JSX.Element
    export default MDXComponent
  }
  ```

**Comment by tornordqvist** [comment]
@bcherny do you have any updated url to the config-file?
https://github.com/mdx-js/mdx/blob/master/examples/create-react-app/config-overrides.js

**Comment by Joshua-Sherer-Bose** [comment]
@tornordqvist - The config-file is in the repo's history: https://github.com/mdx-js/mdx/blob/8469707ef5f0dcf3c0d56cf2793710916ef92c0c/examples/create-react-app/config-overrides.js

**Comment by mtajammulzia** [comment]
I have been following MDX docs and after configuring everything with react-app-rewired I get this error when I run yarn start (which runs react-app-rewired start). Any ideas how to fix this?


The "getBabelLoader" helper has been deprecated as of v2.0. You can use customize-cra plugins in replacement - https://github.com/arackaf/customize-cra#available-plugins

**Comment by wooorm** [comment]
This is an old issue. There are more recent discussions: https://github.com/mdx-js/mdx/discussions/1870.
