### ISSUE TITLE
Utilize remark-mdx on client side - Module not found: Can't resolve 'fs' in '/sandbox/node_modules/remark-mdx/node_modules/@babel/core/lib/transformation'

### ISSUE THREAD

**Issue by ajonp** [mdx-js/mdx#1353]
### Subject of the issue
Utilize remark-mdx on client side - Module not found: Can't resolve 'fs' in '/sandbox/node_modules/remark-mdx/node_modules/@babel/core/lib/transformation'

Describe your issue here.
Can we remove the reqiurement for `fs`?

### Steps to reproduce

https://codesandbox.io/s/wonderful-matsumoto-6ce6t?file=/pages/index.js:185-190

### Expected behaviour

successful translation.

### Actual behaviour

Error: Module not found: Can't resolve 'fs' in '/sandbox/node_modules/remark-mdx/node_modules/@babel/core/lib/transformation'

**Comment by ChristianMurphy** [comment]
@ajonp remark-mdx is designed to be used in node but can also be used in a browser with an appropriate polyfill.
There are several questions and answers in the next.js forum that show how to do this https://github.com/vercel/next.js/discussions?discussions_q=resolve+fs+is%3Aanswered

**Comment by ajonp** [comment]
@ChristianMurphy the only references within the link above are suggesting that you use Node based imports on the server side. If remark-mdx is allowed in browser there must be another solution that I am missing.

**Comment by ChristianMurphy** [comment]
Again, to be used browser side, `fs` needs to be polyfilled, which needs to be done on the Next.js/WebPack side.
This example https://github.com/vercel/next.js/discussions/17897#discussion-24802 for the discussions linked above, shows how to set an empty polyfill.
