### ISSUE TITLE
Add line numbers in code block

### ISSUE THREAD

**Issue by sgmheyhey** [mdx-js/mdx#1360]
Feature:

I want to add line numbers in code block.

### AS-IS

![image](https://user-images.githubusercontent.com/30946314/101326144-2de03500-38b0-11eb-8a69-e5330d6357a3.png)

### TO-BE

![image](https://user-images.githubusercontent.com/30946314/101327101-8e23a680-38b1-11eb-9d96-8a10d018dfbf.png)

Let you see, there are line numbers like 1, 2, 3.
Is should be in the mdx package like this or not?

![image](https://user-images.githubusercontent.com/30946314/101326796-21a8a780-38b1-11eb-98fb-fe5953da867d.png)

**Comment by wooorm** [comment]
This does not make sense in core, but can be done through plugins, or by using a custom react component to handle code.
An example is [in our docs here](https://mdxjs.com/guides/syntax-highlighting). [`react-syntax-highlighter`](https://github.com/react-syntax-highlighter/react-syntax-highlighter) also supports line numbers

**Comment by sgmheyhey** [comment]
I couldn't find it in docs contents. I will try `react-syntax-highlighter`. Thanks!
