### ISSUE TITLE
Releasing remark-mdx-strip (remark-mdx-remove-jsx and remark-mdx-remove-comment)

### ISSUE THREAD

**Issue by riywo** [mdx-js/mdx#1364]
### Subject of the feature

Why don't you release additional `unified` plugins like below?

- `remark-mdx-strip`
    - Drop-in replacement of `markdown-strip` for MDX. Just utilizing all `remark-mdx-remove-*` plugins along with `markdown-strip`.
- `remark-mdx-remove-jdx` and `remark-mdx-remove-comment`
    - According to [MDX doc](https://mdxjs.com/advanced/ast#mdxast), there are four extra types in MDXAST on top of MDAST. `remark-mdx-remove-import` and `remark-mdx-remove-export` already exist. We should have ones for the remaining as well.

### Problem

When we want to transform MDXAST to plain text like [`strip-markdown`](https://github.com/remarkjs/strip-markdown) does, we can do it by ad-hoc Unified pipeline:

```js
var unified = require("unified")
var strip = require("strip-markdown")
var remove = require("unist-util-remove")
var stripMdx = options => tree => remove(strip(options)(tree), ["jsx", "import", "export", "comment"])
var stringify = require("remark-stringify")

var processor = unified().use(stripMdx).use(stringify)

var mdxast = {...}
console.log(processor.stringify(processor.runSync(mdxast)))
```

However, the official plugin for this use case is much ideal.

Our use case here is to generate a plain text content for JSON-LD like [`articleBody`](https://schema.org/articleBody). Since the GraphQL has `mdxAST` field, it is easy if we have these plugins.

### Expected behavior

All MDX-specific nodes are removed from input tree.

### Alternatives

As I mentioned, we can do it by ad-hoc pipeline.

**Comment by wooorm** [comment]
You’re free to create such project in the ecosystem. There are so many things that we can do, but we can’t maintainer it all.

IMO, a better solution might be to render your pages and then strip HTML from their output though?

**Comment by riywo** [comment]
Got it, thanks. Then, I'll release `remark-mdx-strip`.
