### ISSUE TITLE
"Component X was not imported, exported, or provided by MDXProvider as global scope even though they are, and they render fine

### ISSUE THREAD

**Issue by Southclaws** [mdx-js/mdx#1368]
### Subject of the issue

We have a docs site with some custom template components for things like "this function only works on version X and above", these are used in MDX like:

```md
<VersionWarn version="v1.2.3" />
```

And they render fine on the live site and in dev mode, but at build time the log is spammed with

```
Component VersionWarn was not imported, exported, or provided by MDXProvider as global scope
```

It's especially annoying as we have close to 3000 pages now, so the log is filled with this and we may miss other important log messages during build.

We're using Next.js and next-mdx-remote from Hashicorp. The components are passed in via `renderToString` here: https://github.com/hashicorp/next-mdx-remote/blob/master/render-to-string.js#L51 I've also created my own MDXProvider in _app.tsx and passed in our components there, but the warning still appears.

It's difficult to track exactly where this message is coming from - whether it's caused by MDX or next-mdx-remote.

### Your environment

*   **OS**: Windows, Mac, Linux - occurs on all
*   **Packages**: 
  - "@mdx-js/loader": "^1.6.21",
  - "@next/mdx": "^10.0.3",
  - "next-mdx-remote": "^1.0.0",
*   **Env**: ❯ node -v v12.18.3 ❯ npm -v 6.14.6

### Steps to reproduce

Clone https://github.com/openmultiplayer/web and `npm run build` inside `frontend`

**Comment by wooorm** [comment]
If you’re seeing that those components aren‘t passed correctly. Those backup components are put in the highest scope, and if you pass components correctly they‘re overwritten.

Maybe `next-mdx-remote` is doing something wrong?

I’m sorry but I’m not going to try and build and debug a complete project. A small reproduction would be helpful though.

**Comment by Southclaws** [comment]
Turns out I was using the API incorrectly (not typescript so no errors to tell me!) I converted it to typescript and realised what I was doing wrong! Sorry for useless issue!

**Comment by wooorm** [comment]
No problem, good to hear!
For future reference, as more folks might stumble upon this and find this issue, could you describe in short what you did to solve this?

**Comment by Southclaws** [comment]
Ah yes of course, my bad! The issue was that I was passing `components` to `mdxOptions` instead of just to the object that was the second parameter of `renderToString`: https://github.com/openmultiplayer/web/pull/83/files#diff-442afcaa0f95331ca8e75e4b43d02227f3ac5cc34434abf44d451a20a9a9def9L161-L165

It took copying the code to my own codebase (it's only two files, and quite simple) and adding type annotations to figure that one out!

I may do a PR to the original repo to just rewrite it in TypeScript 😂

**Comment by wooorm** [comment]
Thank you! Glad it’s working!
