### ISSUE TITLE
Nested markdown does not render as markdown

### ISSUE THREAD

**Issue by plummer-flex** [mdx-js/mdx#1374]
### Nested markdown does not render as markdown

The following markdown:

```
- Item one: **test 1**
- Item two: **test 2**
```

renders as follows: 

- Item one: \*\*test 1\*\*
- Item two: \*\*test 2\*\*

This is *not* a place to ask questions.  For that, go to [Discussions](https://github.com/mdx-js/mdx/discussions)

### Your environment

*   **OS**: 
*   **Packages**: 
*   **Env**: 

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behaviour

What should happen?

### Actual behaviour

What happens instead?

**Comment by wooorm** [comment]
You didn't fill out the template. See here for markdown syntax: https://commonmark.org/help/

**Comment by plummer-flex** [comment]
> You didn't fill out the template. See here for markdown syntax: https://commonmark.org/help/

Sorry, meant to delete.
