### ISSUE TITLE
Katex rendering not working with MDX

### ISSUE THREAD

**Issue by sonapraneeth-a** [mdx-js/mdx#1391]
### Subject of the issue

Math blocks not rendering properly when using KaTeX with MDX

### Your environment

*   **OS**: Ubuntu 20.04 (But the issue is not related to OS)
*   **Packages**: 
      - gatsby-plugin-mdx
      - katex
      - gatsby-remark-katex
*   **Env**: 
      - yarn: 1.22.5

```
System:
    OS: Linux 4.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.15.1 - ~/Softwares/node/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - ~/Softwares/node/bin/npm
  npmPackages:
    gatsby: 2.28.1 => 2.28.1
    gatsby-image: 2.7.0 => 2.7.0
    gatsby-plugin-manifest: 2.8.0 => 2.8.0
    gatsby-plugin-mdx: 1.6.0 => 1.6.0
    gatsby-plugin-offline: 3.6.0 => 3.6.0
    gatsby-plugin-react-helmet: 3.6.0 => 3.6.0
    gatsby-plugin-sharp: 2.10.1 => 2.10.1
    gatsby-remark-katex: ^3.6.0 => 3.6.0
    gatsby-source-filesystem: 2.7.0 => 2.7.0
    gatsby-transformer-sharp: 2.8.0 => 2.8.0
  npmGlobalPackages:
    gatsby: 2.28.1
```

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

[Repo link](https://github.com/sonapraneeth-a/using-mdx)

1. Clone the repository
2. `npm install`
3. `npm run develop`
4. Open `http://localhost:8000/info/`
4. Verify the equation rendering

[Website](https://unruffled-kepler-657338.netlify.app/info/)

### Expected behaviour

What should happen?

![image](https://user-images.githubusercontent.com/13482560/101592645-a4964300-3a14-11eb-9c30-06c3a81272c6.png)

![image](https://user-images.githubusercontent.com/13482560/101592669-ae1fab00-3a14-11eb-9aa9-c1686cc34114.png)

### Actual behaviour

What happens instead?

![image](https://user-images.githubusercontent.com/13482560/101592750-cb547980-3a14-11eb-9fa3-f084f9d32db1.png)

![image](https://user-images.githubusercontent.com/13482560/101592770-d0b1c400-3a14-11eb-89b5-daf1ae34e42b.png)

**Comment by wooorm** [comment]
Probably this Gatsby issue: https://github.com/gatsbyjs/gatsby/issues/28031

**Comment by sonapraneeth-a** [comment]
It looks to be a different issue as even the simplest math formulas are not rendering as opposed to complex formulas in the attached issue.

**Comment by wooorm** [comment]
Hmm, might be?
Regardless, `gatsby-plugin-mdx` and `gatsby-remark-katex` are gatsby projects, and to my knowledge often don’t work.
I see you’ve already asked there btw: https://github.com/gatsbyjs/gatsby/issues/28546.

I would personally avoid gatsby-remark-* projects.
You can also use normal remark and rehype plugins: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx#remark-plugins.
[remark-math and rehype-katex](https://github.com/remarkjs/remark-math) should do the trick

**Comment by nikoladev** [comment]
@sonapraneeth-a The solution of using regular remark and rehype plugins that @wooorm proposed should work. [This is how I set it up to work](https://github.com/gatsbyjs/gatsby/issues/20538#issuecomment-721845436).

**Comment by sonapraneeth-a** [comment]
The workaround by @nikoladev  works. Thanks 👍
