### ISSUE TITLE
Syntax highlight doesn't work for scala

### ISSUE THREAD

**Issue by YikSanChan** [mdx-js/mdx#1411]
### Subject of the issue

Syntax highlight doesn't work for scala

### Your environment

Browser. I verify the issue on https://mdxjs.com/playground/

### Steps to reproduce

Put below markdown raw content to https://mdxjs.com/playground/.

```scala
object Hello {
    def main(args: Array[String]) = {
        println("Hello, world")
    }
}
```

(The code comes from https://docs.scala-lang.org/overviews/scala-book/hello-world-1.html)

### Expected behaviour

It should highlight the scala syntax

![image](https://user-images.githubusercontent.com/17229109/102908948-0e5b1780-442d-11eb-81f6-a2a19a837690.png)

### Actual behaviour

It shows no syntax highlight.

![image](https://user-images.githubusercontent.com/17229109/102908891-f71c2a00-442c-11eb-9c84-9c5a533a4a85.png)

**Comment by ChristianMurphy** [comment]
MDX itself doesn't do code syntax highlighting.
It parses the code block
````
```scala
```
````

but it doesn't parse or highlight the code inside the block.
To add syntax higlighting follow the guide in https://mdxjs.com/guides/syntax-highlighting

The playground for example uses https://github.com/FormidableLabs/prism-react-renderer
`scala` is not on the default list of languages that package includes, you can follow their guide to add the languages you want.
