### ISSUE TITLE
Specify plugins options in mdPlugins array?

### ISSUE THREAD

**Issue by madiodio** [mdx-js/mdx#143]
Given a remark plugin, let's say [`remark-emoji`](https://github.com/rhysd/remark-emoji/): how do I specify his options using the `mdPlugins` array.

Sorry if I'm missing something so obvious.

**Comment by johno** [comment]
Looks like we have a docs bug 😸, I've opened up #144 to improve our documentation for applying plugins to your MDX.

Plugins need to be passed to the MDX loader via webpack options. This will usually live in your `webpack.config.js`:

```js
const images = require('remark-images')
const emoji = require('remark-emoji')

module.exports = {
  module: {
    rules: [
      {
        test: /\.mdx?$/,
        use: [
          {
            loader: 'babel-loader'
          },
          {
            loader: '@mdx-js/loader',
            options: {
              mdPlugins: [images, emoji]
            }
          }
        ]
      }
    ]
  }
}
```

If you're using Next.js, you can specify options in your `next.config.js`:

```js
const images = require('remark-images')
const emoji = require('remark-emoji')

module.exports = {
  pageExtensions: ['js', 'jsx', 'md', 'mdx'],
  webpack: (config, { defaultLoaders }) => {
    config.module.rules.push({
      test: /\.mdx?$/,
      use: [
        defaultLoaders.babel,
        {
          loader: '@mdx-js/loader',
          options: {
            mdPlugins: [images, emoji]
          }
        }
      ]
    })

    return config
  }
}
```

Hope this helps! Let us know if you have any other questions.

**Comment by madiodio** [comment]
@johno Thanks for your prompt reaction. I have already chimed in the examples folder to see how one can pass plugins to the webpack loader options 😅 but it's nice that you added that to the docs. But my issue was specifically do you pass options to the `remark-emoji` plugin like it can be done [here](https://github.com/rhysd/remark-emoji/#options).

**Comment by johno** [comment]
My apologies on misunderstanding you. We don't support providing options yet, unfortunately. Though it's definitely something we should add functionality for.

**Comment by madiodio** [comment]
No worries @johno, it's kind of a edge case but in the meantime I've got to shim trough the code and discover that this line [mdx/packages/mdx/index.js#L24](mdx/packages/mdx/index.js#L24) actually allowed me to specify the plugin options like this

```js
...
options: {
  mdPlugins: [images, emoji],
  padSpaceAfter: true // this is a `remark-emoji` option
}
...
```

This works but it would be awesome if there was a more elegant way to achieve that.

**Comment by johno** [comment]
This is now supported in `0.15.0-1` thanks to @revolunet.

Thanks for reporting @madiodio ❤️.
