### ISSUE TITLE
mdx-js/mdx@1171f43 failed to deploy to production

### ISSUE THREAD

**Issue by francisfuzz** [mdx-js/mdx#1431]
### Subject of the issue

👋  Hello, @unifiedjs! Since the repository's default branch is set to `main`, I noticed its HEAD (at this time of writing) points to https://github.com/mdx-js/mdx/commit/1171f431bbf6b1d84556fb19de54626f59deb0d6. Every status check passed _except_ its deployment––reviewing [that deployment's logs on Vercel](https://vercel.com/mdx/mdx/5tzphwewp), here's the tail-end of the stack trace starting from the error:

```shell
01:18:35.043  	error "gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:
01:18:35.043  	Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)/vercel/workpath0/docs/getting-started/create-react-app.mdx: Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)
01:18:35.056  	
01:18:35.056  	  Error: 
01:18:35.056  	
01:18:35.057  	not finished source and transform nodes - 2.836s
01:18:35.958  	error Command failed with exit code 1.
01:18:35.959  	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
01:18:35.979  	error Command failed with exit code 1.
01:18:35.979  	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
01:18:35.988  	Error: Command "yarn run now-build" exited with 1
01:18:39.735  	Done with "package.json"
```

Since that deployment failed, the changes proposed in https://github.com/mdx-js/mdx/pull/1427 aren't reflected in production. I reviewed the [first page of commits on `main`](https://github.com/mdx-js/mdx/commits/main) and it appears as thought the last 19 known deployments failed. 😱 

### Your environment

I don't think the OS, packages, or env are applicable here, since this report involves what's in production. 

### Steps to reproduce

> _Tell us how to reproduce this issue.  Please provide a working and simplified example._

> _🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉_

https://github.com/mdx-js/mdx/pull/1427 updates `ar` to `are` in the [Contributing guide's `Running the tests` section](https://mdxjs.com/contributing#running-the-tests). 

### Expected behaviour

The Contributing guide should reflect the latest changes from `main` (assuming that what's configured to deploy for this repository is that branch, and not some other branch like say, `master`).

... Is what's deployed to production `main`, `master`, or another branch? 🤔 

### Actual behaviour

Although the changes were [merged yesterday](https://github.com/mdx-js/mdx/pull/1427#event-4164026732), what's in production isn't reflected.

**Comment by francisfuzz** [comment]
I'm leaving some additional observations in the case it helps the next person. 📝   :v:

After reviewing the [list of this repo's closed PRs](https://github.com/mdx-js/mdx/pulls?q=is%3Apr+is%3Aclosed):

- https://github.com/mdx-js/mdx/pull/1427 was merged into `mdx-js:master`.
- https://github.com/mdx-js/mdx/pull/1422 was the latest PR [merged almost a week ago](https://github.com/mdx-js/mdx/pull/1422#event-4155600494), but merged into `mdx-js:main`. However, a spot comparison of its [files changed](https://github.com/mdx-js/mdx/pull/1422/files) and [its rendered page in production](https://mdxjs.com/getting-started/create-react-app) don't match.
- The next five merged pull requests were merged into `mdx-js:main`––https://github.com/mdx-js/mdx/pull/1416, https://github.com/mdx-js/mdx/pull/1415, https://github.com/mdx-js/mdx/pull/1414, https://github.com/mdx-js/mdx/pull/1412, https://github.com/mdx-js/mdx/pull/1407.

**Comment by francisfuzz** [comment]
> ... Is what's deployed to production main, master, or another branch? 🤔

Following up on my earlier question, I reviewed [this repository's commits at `master`](https://github.com/mdx-js/mdx/commits/master) and similarly found a trail of failed deployments. Combing through the commits, it _seems_ like the [deployment](https://vercel.com/mdx/mdx/onyt77qd0) for https://github.com/mdx-js/mdx/commit/39252199cbdbd8bd276d1a410d78a333477ebead was the last successful deploy for `master`; the [one file it updated ](https://github.com/mdx-js/mdx/pull/1331/files) lines up with the production version of [Table of Components](https://mdxjs.com/table-of-components).

**Comment by wooorm** [comment]
Hey, thanks for checking in!

Building the website on `main` is currently indeed broken, we’re getting ready for v2 and one of the things is creating a brand new website. The actual code is passing tests though; we’re aware!

I’ll close this because we’re working on it!

**Comment by francisfuzz** [comment]
Ah, that was the context I was missing. Thank you @wooorm!
