### ISSUE TITLE
Transform content example broken with remark 13+

### ISSUE THREAD

**Issue by jvelo** [mdx-js/mdx#1440]
### Subject of the issue

The [transform content](https://mdxjs.com/advanced/transform-content) example in the docs yields the expected output when running against remark 12 or below ; but a different output with remark 13

This is *not* a place to ask questions.  For that, go to [Discussions](https://github.com/mdx-js/mdx/discussions)

### Your environment

*   **OS**: macOS Big sur
*   **Packages**: @mdx-js/mdx 1.6.22, remark 13.0.0
*   **Env**: node 12, yarn 1.22

### Steps to reproduce

See repos at https://github.com/jvelo/mdx-transform-remark13

Running `node index.js` yields:

```
{
  type: 'root',
  children: [
    { type: 'paragraph', children: [Array], position: [Object] },
    { type: 'paragraph', children: [Array], position: [Object] },
    {
      type: 'heading',
      depth: 1,
      children: [Array],
      position: [Object]
    },
    { type: 'paragraph', children: [Array], position: [Object] },
    { type: 'html', value: '<Component />', position: [Object] }
  ],
  position: {
    start: { line: 1, column: 1, offset: 0 },
    end: { line: 12, column: 1, offset: 107 }
  }
}
```

### Expected behaviour

While running it against remark 12.x yields the expected 

```
{
  type: 'root',
  children: [
    {
      type: 'import',
      value: "import Component from 'Component'",
      position: [Position]
    },
    {
      type: 'export',
      value: "export const meta = {\nprop: 'value'\n}",
      position: [Position]
    },
    {
      type: 'heading',
      depth: 1,
      children: [Array],
      position: [Position]
    },
    { type: 'paragraph', children: [Array], position: [Position] },
    { type: 'jsx', value: '<Component />', position: [Position] }
  ],
  position: {
    start: { line: 1, column: 1, offset: 0 },
    end: { line: 12, column: 1, offset: 107 }
  }
}
```

**Comment by jvelo** [comment]
At a lower level looks like the incompatibility lays between `remark-parse` 8.x vs. 9.x

**Comment by cha0s** [comment]
Can confirm that it works with 8.x and not with 9.x

**Comment by ChristianMurphy** [comment]
mdx 2 (in beta) supports remark 13+, you can find out more here: https://github.com/mdx-js/mdx/issues/1041
mdx 1 still needs remark 12.

**Comment by pd4d10** [comment]
Hi, just running into this issue.

The latest version [v2.0.0-next.8](https://github.com/mdx-js/mdx/blob/v2.0.0-next.8/packages/remark-mdx/package.json) seems still use remark-parse@8 (remark@12).

In which branch does remark@13 compatible version land? Thanks!
