### ISSUE TITLE
Custom component props lead to tailing backslash in mdx

### ISSUE THREAD

**Issue by rotpunkt-dev** [mdx-js/mdx#1442]
### Subject of the issue

Custom component props lead to tailing backslash in mdx.

### Your environment

*   **OS**: MacOS Big Sur
*   **Packages**:
 "remark-parse": "9.0.0",
    "remark-stringify": "9.0.1",
    "remark-mdx": "1.6.22",

*   **Env**: Node: 12, Yarn 1.22.4

### Steps to reproduce

```javascript var unified = require('unified')
var parse = require('remark-parse')
var stringify = require('remark-stringify')
var mdx = require('remark-mdx')

const testMd ='# Hello <Image alt={`Some alt text`}/>'

unified()
  .use(parse, {position: false})
  .use(stringify)
  .use(mdx)
  .process(testMd, function (err, file) {
    console.log(String(file))})
```

### Expected behaviour

No tailing backslash before component.

### Actual behaviour

A tailing backslash is added.
```
/* Output:
# Hello \<Image alt={`Some alt text`}/> */
```

**Comment by rotpunkt-dev** [comment]
Seems to happen in the stringlify step. Moved issue to:
https://github.com/remarkjs/remark/issues/620

**Comment by ChristianMurphy** [comment]
@rotpunkt-dev have you tried version 2, as noted in https://github.com/remarkjs/remark/issues/620#issuecomment-770386590 ?

**Comment by rotpunkt-dev** [comment]
Yes, I tried it with version 2.0.0-next.8
Same issue here.

**Comment by wooorm** [comment]
I can reproduce it here: https://codesandbox.io/s/awesome-surf-x7y5t?file=/src/index.md.
The grave accents (ticks) cause the problem on the last beta.
I have confirmed that is is working on the `main` branch though.

**Comment by ChristianMurphy** [comment]
`main` version with fix(es) has been released as https://github.com/mdx-js/mdx/releases/tag/v2.0.0-next.9
