### ISSUE TITLE
frontmatter example is not working

### ISSUE THREAD

**Issue by chenxsan** [mdx-js/mdx#1445]
### Subject of the issue

See example https://mdxjs.com/advanced/api#compiler, it's expected to yield `{ title: "Hello, MDX" }` while I got `undefined`.

### Your environment

*   **OS**: macOS BigSur
*   **Packages**: 
*   **Env**: 

### Steps to reproduce

1. clone `https://github.com/chenxsan/bug-mdxjs-frontmatter`
2. run `yarn`
3. run `node index.js`

### Expected behaviour

Yields `{ title: "Hello, MDX" }`.

### Actual behaviour

Got `undefined`.

**Comment by JounQin** [comment]
Did you try to add a blank line as the document?

**Comment by JounQin** [comment]
@chenxsan use `remark-frontmatter@^2.0.0` for now.

**Comment by JounQin** [comment]
If you want to use `@mdx-js/mdx@^2.0.0-next.9` with `remark-frontmatter@^3.0.0`

```js
const {createCompiler} = require('@mdx-js/mdx')
const detectFrontmatter = require('remark-frontmatter')
const vfile = require('vfile')
const visit = require('unist-util-visit')
const remove = require('unist-util-remove')
const yaml = require('yaml')
const file = vfile(`
---
title: Hello, MDX
---
I &lt; 3 Markdown and JSX {/* < must be escaped */}
`.trimStart())
function extractFrontmatter() {
  return function transformer(tree, file) {
    console.log('tree', tree)
    visit(tree, 'yaml', function visitor(node) {
      file.data.frontmatter = yaml.parse(node.value)
    })
    remove(tree, 'yaml')
  }
}
mdxCompiler = createCompiler({
  remarkPlugins: [detectFrontmatter, extractFrontmatter]
})
mdxCompiler.process(file, function done(err, file) {
  if (err){
    console.error(err)
    return
  }
  console.log(file.data.frontmatter)
  // { title: "Hello, MDX" }
})
```
