### ISSUE TITLE
render html element style error

### ISSUE THREAD

**Issue by nanlei2000** [mdx-js/mdx#1454]
### Subject of the issue

when the markdown have html element with style property, mdx will not parse it to object which will cause react throw error
in runtime.

### Your environment

*   **OS**: mac os 10.15.7
*   **Packages**:  "@mdx-js/runtime": "^1.6.22"
*   **Env**: chrome 

### Steps to reproduce

```
<div style="color: red;">text</div>
```

### Expected behaviour

"text" with red color

### Actual behaviour

cause react throw error in runtime

**Comment by ChristianMurphy** [comment]
Using JSX with React, React syntax for inline styles needs to be used https://reactjs.org/docs/dom-elements.html#style

```jsx
<div style={{color: "red"}}>text</div>
```

this can be tested at: https://mdxjs.com/playground
