### ISSUE TITLE
Changing `img` definition in MDXProvider breaks SSR of other shortcode components

### ISSUE THREAD

**Issue by blvdmitry** [mdx-js/mdx#1459]
### Subject of the issue

In @mdx-js/react, defining a custom component for the `img` markdown element breaks SSR rendering of other components in the document.

```
const components = {
  Video: ElementVideo,
  Image: ElementImage,
  Guideline: ElementGuideline,
  img: ElementImage,
}

const Markdown = (props) => {
  return <MDXProvider components={components}>{ props.children }</MDXProvider>;
};
```

Adding an `img` definition in this example renders other component attributes incorrectly during SSR. 
Their children get correctly rerendered during rehydration, but attributes don't update on the client because of the React rendering performance approach. A more specific example is in the steps to reproduce section.

### Your environment

*   **OS**: MacOS Catalina
*   **Packages**: We use next-mdx-enchanced 5.0.0, but the issue happens on the @mdx-js/react 1.6.21 level
*   **Env**: Node 12.16, Yarn 1.22

### Steps to reproduce

ElementImage.jsx
```
import React from 'react';
import s from './ElementImage.module.css';

const ElementImage = (props) => {
  const { src, alt } = props;
  return <img src={imageUrl} alt={alt} className={s.root} />;
};

export default ElementImage;
```

ElementGuideline.jsx
```
import React from 'react';
import s from './ElementGuideline.module.css';

const ElementGuideline = (props) => {
  const { src, text, type } = props;
  const rootClassName = s.root + (type ? ` ${s[`--type-${type}`]}` : '');

  return (
      <div className={rootClassName}>
        <img alt="" src={imageUrl} className={s.image} />
        <div className={s.bar} />
        <div className={s.text}>
          { type === 'yes' ? 'Yes' : 'No' }
        </div>
      </div>
  );
};

export default ElementGuideline;
```

article.mdx
```
![Image](/img.jpg)

<Guideline src="/img.jpg" type="yes" />
<Guideline src="/img.jpg" type="no" />
```

During SSR both Guidelines render with type `no` for some reason and then their children get updated on the client to the correct type, but classes don't get rerendered. As a result, we get a Guideline rendered with `--type-no` className but with a `Yes` label in it.

### Expected behaviour

Guideline component should render --type-yes className for the first item and --type-no for the second item

### Actual behaviour

--type-no className is applied to both items during SSR. 
It gets fixed after client-side routing to the same page or when `img` definition is removed from MDX provider.

**Comment by jamesmfriedman** [comment]
I'm having this issue as well still, latest on everything. It's exactly as described here. I've attempted every workaround I can find, it just seems like SSR is completely ignoring the MDXProvider

**Comment by ChristianMurphy** [comment]
@jamesmfriedman do everything is the same, but everything is different? 😉 

This issue several years old, and it sounds like you have a very different setup.

Folks are happy to help, please open a new ticket with the details of _your_ setup, and the workarounds that _you_ have tried. So Folks actually have some information to go off of 🙂
