### ISSUE TITLE
mdx renders incorrect class names when used in conjunction with NextJS

### ISSUE THREAD

**Issue by rikvanderkemp** [mdx-js/mdx#146]
So i've tried highlight.js and midas both yield the same result. 

When the code block is rendered it renders the class name incorrectly, in case of using midas:

```html
<element class="language-css,midas"></element>
```

Due to the comma, highlighting won't work properly. Using remark-highlight.js results in a similar issue:

```html
<element class="hljs,language-css"></element>
```
Any help would be appreciated 😀

next.config.js

```es6
const withSass = require('@zeit/next-sass')
const SWPrecacheWebpackPlugin = require('sw-precache-webpack-plugin')
const images = require('remark-images')
const emoji = require('remark-emoji')
const highlight = require('remark-midas')
const html = require('remark-html')

module.exports = withSass({
    pageExtensions: ['js', 'jsx', 'md', 'mdx'],
    webpack: (config, {defaultLoaders}) => {
        config.plugins.push(
            new SWPrecacheWebpackPlugin({
                verbose: true,
                staticFileGlobsIgnorePatterns: [/\.next\//],
                runtimeCaching: [
                    {
                        handler: 'networkFirst',
                        urlPattern: /^https?.*/
                    }
                ]
            })
        )

        config.module.rules.push({
            test: /\.md$/,
            use: [
              defaultLoaders.babel,
              {
                loader: '@mdx-js/loader',
                options: {
                  mdPlugins: [images, emoji, html, highlight]
                }
              }
            ]
        })

        return config
    }
})
```

Packages used:
```
@mdx-js/loader@0.9.0
@mdx-js/mdx@0.9.0
@zeit/next-sass@0.2.0
next@6.0.3
node-sass@4.9.0
react@16.3.2
react-dom@16.3.2
remark@9.0.0
remark-emoji@2.0.1
remark-highlight.js@5.0.0
remark-html@7.0.0
remark-images@0.8.1
remark-midas@5.0.0
sw-precache-webpack-plugin@0.11.5
```

The markdown file is just:

```markdown
~~~css
body {
    color: red;
}
~~~
```

I import this file like:

```es6
import Something from '../md/something.md'
```

And use this in a component like this:

```es6
<Something />
```

**Comment by timneutkens** [comment]
I don't think this is a MDX issue to be honest 🤔 cc @johno

**Comment by tajo** [comment]
Saw the same thing! Strangely enough, it was also happening with `rehype-prism`.

On the side note: What setup do you use for Next + MDX + Highlighting JSX? The best I can currently do is setting up hljs (following https://github.com/mdx-js/mdx/issues/122) but that doesn't like JSX at all.

Prism (using rehype-prism) looks more promising but all generated class names have `,` (commas) instead of spaces, so I can't style it.

No luck with remark-react-codemirror either (runtime error).

**Comment by rikvanderkemp** [comment]
@tajo did you manage to get it working by any chance?

**Comment by tajo** [comment]
Nope, only with hljs. I think I'm just going to implement code highlighting as a React `<Code />` component using Prism and avoid marked plugin completely.

**Comment by jculvey** [comment]
Looks like @devongovett fixed it with this commit: https://github.com/mdx-js/mdx/commit/fd0b3d98e5339ba35f4e53fc29adb31933c9fb27. 

Thanks!

**Comment by timneutkens** [comment]
Yep, closing this.
