### ISSUE TITLE
Less-than signs in inline math mode (Katex) are not understood as math in MDX v2.

### ISSUE THREAD

**Issue by janmaltel** [mdx-js/mdx#1462]
### Subject of the issue

I'm trying to upgrade from MDX v1 to v2. Inline equations such as `$x < 3$` used to be correctly understood as a LaTeX equation in my old setup but stopped working with v2.

I'm using gatsby.js and the MDX / Katex setup described in this issue [comment]( https://github.com/gatsbyjs/gatsby/issues/20538#issuecomment-721845436) (see below for specific package versions).

### Your environment

*   **OS**: macOS 10.14.6
*   **Packages**:  
```
// package.json
    "@mdx-js/mdx": "v2.0.0-next.8",
    "@mdx-js/react": "v2.0.0-next.8",
    "gatsby": "2.25.2",
    "gatsby-plugin-mdx": "1.3.1",
    "remark-html-katex": "3.0.0",
    "remark-math": "3.0.1",
```

And my config file:
```
// gatsby-config.js
    {
      resolve: 'gatsby-plugin-mdx',
      options: {
        defaultLayouts: {
          default: require.resolve(`./src/components/mdxLayout.js`),
        },
        remarkPlugins: [
          require('remark-math'),
          require('remark-html-katex'),
        ],
      },
    },
```

*   **Env**: `node --version` v10.23.3, `npm --version` 6.14.11

### Steps to reproduce (incl. expected and actual behavior)

The mdx file 
```
// works.mdx
greater-than sign inline math $x > 3$ and smaller-than sign in code snippet `x < 3`
```
produces
<img width="594" alt="image" src="https://user-images.githubusercontent.com/3419333/107768823-59abeb00-6d37-11eb-95c2-c728d254483d.png">

but 
```
// doesntwork.mdx
$x<3$
```
throws the following error:
```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed.

Unexpected character `3` (U+0033) before name, expected a character that can start a name, such as a letter, `$`, or `_`/Users/malte/Desktop/janmaltel/src/pages/posts/gridworld.mdx: Unexpected character `3` (U+0033) before name, expected a
character that can start a name, such as a letter, `$`, or `_`
```

### Expected behaviour
Render a LaTeX equation $x<3$.

### Actual behaviour
Webpack error

**Comment by nikoladev** [comment]
Gatsby uses some older plugins in `gatsby-plugin-mdx` so not everything works correctly. I had the same problem with some Katex formulas which I described [here][gatsby-issue]. In there you can also find a link to [a reproduction of the bug][repro], which also contains a workaround for the bug using a custom Katex component ([the component][component] and [the implementation][implementation]).

Hope it helps!

[gatsby-issue]: https://github.com/gatsbyjs/gatsby/issues/28031
[repro]: https://github.com/nikoladev/mdx-katex-bug
[component]: https://github.com/nikoladev/mdx-katex-bug/blob/main/src/components/Katex.jsx
[implementation]: https://github.com/nikoladev/mdx-katex-bug/blob/main/src/pages/index.mdx

**Comment by ChristianMurphy** [comment]
As noted by @nikoladev this appears to be an issue with Gatsby, (see https://github.com/mdx-js/mdx/discussions/1329) which will be resolved by https://github.com/gatsbyjs/gatsby/issues/28031 rather than an issue with MDX itself
