### ISSUE TITLE
Releasing v2.0.0-next.9 from master

### ISSUE THREAD

**Issue by iAdramelk** [mdx-js/mdx#1479]
I'm trying to use `remark-mdx` together with `remark-cli` and `remark-lint` to lint files formatted with mdx v2, but there are a bunch of issues E. g.:

- https://github.com/mdx-js/mdx/issues/1476
- https://github.com/remarkjs/remark-lint/issues/258

I tried to run examples above with the current master branch and it looks like that update to `micromark` solves issues above.

Is it possible to release new `next` version from master? Maybe I can somehow help with it if there is something that needs to be done before it can be released?

**Comment by pd4d10** [comment]
+1, also waiting for the micromark compatible release

We are building a MDX plugin for [ByteMD](https://github.com/bytedance/bytemd), which is a Markdown editor component based on the remark/rehype ecosystem.

**Comment by JounQin** [comment]
You can try `"remark-mdx": "https://gitpkg.now.sh/mdx-js/mdx/packages/remark-mdx?main"` temporarily.

**Comment by ChristianMurphy** [comment]
Another option while the release is stalled is [XDM](https://github.com/wooorm/xdm#readme)

**Comment by johno** [comment]
`v2.0.0-next.9` has been released, please let us know if you encounter any issues!
