### ISSUE TITLE
Relaxed versions

### ISSUE THREAD

**Issue by daveisfera** [mdx-js/mdx#1480]
### Subject of the feature

Use `^` to allow for updating versions

### Problem

Versions are locked down to a specific version and can result in multiple versions being installed.

### Expected behavior

Specific versions are controlled by the user rather than the `package.json` file

### Alternatives

Use `~` to allow at least some flexibility in the versions installed

**Comment by JounQin** [comment]
I'm in favor of it personally, but see

https://github.com/mdx-js/mdx/issues/1267#issuecomment-726879768
https://github.com/mdx-js/mdx/issues/865#issuecomment-661121773

**Comment by ChristianMurphy** [comment]
I agree with @JounQin, I'm in favor of ranges as well, but there is not unanimous desire on core team for them.
Closing this as it has been discussed several times.

An alternative is [XDM](https://github.com/wooorm/xdm) which [does use version ranges](https://github.com/wooorm/xdm/blob/f9c3108bc86590b6f2ee20a5d93bc27107a8455d/package.json#L39-L59)
