### ISSUE TITLE
Style in mdxjs.com seem to break

### ISSUE THREAD

**Issue by katopz** [mdx-js/mdx#1481]
### Subject of the issue
Style in mdxjs.com seem to break, side bar look native, code not highlight

### Your environment

*   **OS**: macOS
*   **Packages**: v1.6.22
*   **Env**: chrome 88

### Steps to reproduce
Go to https://mdxjs.com/

### Expected behaviour
Nice looking web with cool code highlight, etc.

### Actual behaviour
![image](https://user-images.githubusercontent.com/97060/110427149-e39e6800-80d9-11eb-862b-dbbb8f02880d.png)

Something break here?

**Comment by ChristianMurphy** [comment]
The styles loaded.
Enhancements to the site are welcome!
