### ISSUE TITLE
createCompiler export missing in index.d.ts 

### ISSUE THREAD

**Issue by ihupoo** [mdx-js/mdx#1497]
### Subject of the issue

 'createCompiler' is missing in the index.d.ts for '@mdx-js/mdx'.  But the api  actually exists.

###  Your environment
remark-mdx – 2.0.0-next.9.

### Steps to reproduce

use typescript and import createCompiler from  mdx
```
import {createCompiler} from '@mdx-js/mdx'
```

### Expected behaviour

no ts error

### Actual behaviour

 ts error(2305):  Module '"@mdx-js/mdx"' has no exported member 'createCompiler'.

**Comment by wooorm** [comment]
PR welcome!
