### ISSUE TITLE
Render Markdown loaded with Ajax

### ISSUE THREAD

**Issue by stackerine** [mdx-js/mdx#150]
Hello, 
I fetch markdown from another repo with AJAX and I'd like to render it with MDX. No idea how todo that even if it is possible.
Pseudo-code should be something like: 
```js
async render() {
 const markdownAndJsx = await fetch('myRepo/content');
 const content = mdx(markdownAndJsx);
 
 return content;
}
```

Thank for your help

**Comment by timneutkens** [comment]
It's not possible without a parser like babel, see my explanation here: https://github.com/mdx-js/mdx/issues/126#issuecomment-389073920
