### ISSUE TITLE
[v2-next.9] "import" at the start of a paragraph causes micromark parser to fail

### ISSUE THREAD

**Issue by ChristopherBiscardi** [mdx-js/mdx#1502]
### next.9 parser breakage

The word "import" at the beginning of a paragraph line causes `micromark-extension-mdxjs-esm` to fail.

### Your environment

*   **Packages**:
       * @mdx-js/mdx@^2.0.0-next.9

### Steps to reproduce

```js
const mdx = require("@mdx-js/mdx");

main();

async function main() {
  try {
    const t = mdx.createCompiler().parse(string);

    const f = await mdx(`
some paragraph here and then 
import the module, as is typical
in documentation.
`);
    console.log(f);
  } catch (e) {
    console.log(e);
  }
}
```

### Expected behaviour

The micromark extension shouldn't try to parse words that are in predefined markdown blocks, such as paragraphs, where the words can come up easily.

### Actual behaviour

```
[3:12: Could not parse import/exports with acorn: SyntaxError: Unexpected token] {
  reason: 'Could not parse import/exports with acorn: SyntaxError: Unexpected token',
  line: 3,
  column: 12,
  location: {
    start: { line: 3, column: 12, offset: 42 },
    end: { line: null, column: null }
  },
  source: 'micromark-extension-mdxjs-esm',
  ruleId: 'acorn'
}
```

**Comment by wooorm** [comment]
Was fixed in https://github.com/micromark/micromark-extension-mdxjs-esm/releases/tag/0.3.1
