### ISSUE TITLE
Warning when rendering tables

### ISSUE THREAD

**Issue by n-sviridenko** [mdx-js/mdx#151]
When rendering tables, it shows the following warning:
```
Warning: validateDOMNesting(...): <tr> cannot appear as a child of <table>. Add a <tbody> to your code to match the DOM tree generated by the browser.
```

It seems like either mdx or any dependency renders `<table/>`s without `<tbody/>`s inside.

React 16.3.

**Comment by timneutkens** [comment]
Can you provide a reproduction?

**Comment by n-sviridenko** [comment]
@timneutkens  Sorry, was a wrong warning. The real one is because of `\n` inside `thead` caused by https://github.com/mdx-js/mdx/blob/master/packages/mdx/mdx-hast-to-jsx.js#L23-L26:
```
Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <thead>. Make sure you don't have any extra whitespace between tags on each line of your source code.
```

**Comment by n-sviridenko** [comment]
It produces the following code:
```jsx
`}<MDXTag name="thead" components={components} parentName="table">{`
`}<MDXTag name="tr" components={components} parentName="thead">{`
`}<MDXTag name="th" components={components} parentName="tr" props={{"align":null}}>{`Item 1`}</MDXTag>{`
```

**Comment by timneutkens** [comment]
I mean, can you provide the MDX you're writing, since otherwise I can't make a failing test.

**Comment by n-sviridenko** [comment]
Sure,
```md
| Item 1 | Item 2 |
| --- | --- |
| Item 1 | Item 2 |
```

**Comment by n-sviridenko** [comment]
@timneutkens is there any updates regarding this issue?

**Comment by kakuyogy** [comment]
![image](https://user-images.githubusercontent.com/32446924/41506180-77555946-724b-11e8-9fd6-8fc4c4cf5cdc.png)
hi, this warning is boring, although it can work well, can you fixed it  as soon as possible ?

**Comment by n-sviridenko** [comment]
Is there any update?
