### ISSUE TITLE
Document compatible versions of remark-parse for remark-mdx

### ISSUE THREAD

**Issue by loreanvictor** [mdx-js/mdx#1516]
### Subject of the feature

It is not clear in the [documentation](https://github.com/mdx-js/mdx/tree/main/packages/remark-mdx) which versions
of `remark-parse` are compatible with (latest version of) `remark-mdx`.

### Problem

Do this:

```bash
npm i unified remark-parse remark-mdx
```
```js
const unified = require('unified')
const parse = require('remark-pare')
const mdx = require('remark-mdx')

const ast = unified()
  .use(parse)
  .use(mdx)
  .parse('<Component>Hellow</Component>')

console.log(ast)
```

And you will get the wrong AST. The solution? As of now (when latest for `remark-mdx` is `1.6.22`), is to
install `remark-parse@8.0.3` instead.

```bash
npm i unified remark-parse@8.0.3 remark-mdx
```

### Expected behavior

This version compatibility should be documented somewhere (perhaps in the Readme).

### Alternatives

Well I installed `@mdx-js/mdx`, and checked its `package.json` to see why it was working properly, so I guess thats also an alternative solution.

**Comment by JounQin** [comment]
PR welcome

**Comment by loreanvictor** [comment]
> PR welcome

[done](https://github.com/mdx-js/mdx/pull/1517).
