### ISSUE TITLE
Invalid placement of <p> tag in certain cases

### ISSUE THREAD

**Issue by digitalsadhu** [mdx-js/mdx#1529]
### Invalid placement of <p> tag in certain cases

```
<Guideline title="Make alert banners actionable">Whenever possible, 
        add an in-line action button if there's a way for a user to
  quickly address the issue associated with an alert.

Whenever possible, add an in-line action button if there's a way for a user to
quickly address the issue associated with an alert.
Whenever possible, add an in-line action button if there's a way for a user to
quickly address the issue associated with an alert.</Guideline>
```

resulting error

```
Syntax error: Expected corresponding JSX closing tag for <p>
  35 | quickly address the issue associated with an alert.`}</p>
  36 | <p>{`Whenever possible, add an in-line action button if there's a way for a user to
> 37 | quickly address the issue associated with an alert.`}</Guideline></p>
```

### Your environment

*   **OS**: Mac OS
*   **Packages**: @next/mdx, @mdx-js/loader, next, react, MDXLayout component
*   **Env**: node 14, npm

### Steps to reproduce

Hard to say exactly, something to do with whitespace and/or newlines? Here are a series of examples that fail:

```
<div>
  a

  a</div>
```

```
Syntax error: Expected corresponding JSX closing tag for <p>

  26 | <div>
  27 |   a
> 28 | <p>{`  a`}</div></p>
     |           ^
  29 |     </MDXLayout>
  30 |   )
  31 | };
```

Also an error:
(note that there are no spaces in the empty line. If you add at least 1 space to the empty line, it works again.
```
<div>

a</div>
```

```
Syntax error: Expected corresponding JSX closing tag for <p>

  25 | <div>a</div>
  26 | <div>
> 27 | <p>{`a`}</div></p>
     |         ^
  28 |     </MDXLayout>
  29 |   )
  30 | };
```

Compared with the following which works fine:

(there is a single space on the empty line)
```
<div>
 
a</div>
```

**Comment by wooorm** [comment]
This particular error seems to have to do with blank lines *inside* a paragraph. That didn’t work before, and it’s now explicitly documented. Please see [What is MDX?](https://v2.mdxjs.com/docs/what-is-mdx/) on the site for the new RC for more info.
