### ISSUE TITLE
Vulnerability on @mdx-js/loader related with trim

### ISSUE THREAD

**Issue by BiancaArtola** [mdx-js/mdx#1531]
I know that it is not a bug, but I need to report a vulnerability that `@mdx-js/loader` has. I am not using this library directly, but Storybook is using this library so I have the vuln.

![image](https://user-images.githubusercontent.com/21174759/114767355-e70eba00-9d3d-11eb-9cfd-18350faf35d3.png)

The following is the related dependencie tree:
`@mdx-js/loader` -> `@mdx-js/mdx` -> `remark-mdx` -> `remark-parse` -> `trim 0.0.1`

`trim 0.0.1` has a `ReDoS` vulnerability

Please let me know if you need more information about this. 
Can you fix this vuln?

**Comment by ChristianMurphy** [comment]
duplicate of https://github.com/mdx-js/mdx/issues/1458
this is addressed in mdx 2 #1041 (currently in beta)
