### ISSUE TITLE
Upgrade dependency on remark to ^13 for compatibility with plugins

### ISSUE THREAD

**Issue by marcofranssen** [mdx-js/mdx#1536]
### Subject of the feature

Updating the remark version. I require at least remark 13.

### Problem

Some of the `remark` plugins (e.g. `remark-gfm`) require an updated version of `remark`.

```bash
$ yarn install 
[remark-gfm] Warning: please upgrade to remark 13 to use this plugin
```

My dependencies are listed below. The problem started when I switched from `remark-html` to `next-mdx-remote`.

```json
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-brands-svg-icons": "^5.15.3",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@fortawesome/react-fontawesome": "^0.1.14",
    "@tailwindcss/typography": "^0.4.0",
    "classnames": "2.3.1",
    "date-fns": "2.21.1",
    "gray-matter": "4.0.3",
    "js-yaml": "^4.1.0",
    "next": "latest",
    "next-mdx-remote": "^2.1.4",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "remark": "13.0.0",
    "remark-autolink-headings": "^6.0.1",
    "remark-emoji": "^2.2.0",
    "remark-external-links": "^8.0.0",
    "remark-gfm": "^1.0.0",
    "remark-slug": "^6.0.0"
  },
  "devDependencies": {
    "autoprefixer": "^10.2.1",
    "next-remote-watch": "^1.0.0",
    "postcss": "^8.2.13",
    "tailwindcss": "^2.1.2"
  },
```

### Expected behavior

Remark GFM can be used without the warning.

### Alternatives

N.A.

### Additional info

https://github.com/hashicorp/next-mdx-remote/issues/122

**Comment by ChristianMurphy** [comment]
This is part of mdx 2 https://github.com/mdx-js/mdx/issues/1041
You can try out the remark 13 compatible version in the pre-release of version 2

**Comment by marcofranssen** [comment]
@ChristianMurphy what would be the expected timeline for GA of version 2?

**Comment by ChristianMurphy** [comment]
Not exactly sure, the most recent I've heard was https://twitter.com/mdx_js/status/1340680033971687424, but that didn't quite pan out.

**Comment by ChristianMurphy** [comment]
Another option is XDM (https://github.com/wooorm/xdm) which is a lighter implementation of MDX 2, which has remark ^13 on it's stable release.

**Comment by bluprince13** [comment]
@marcofranssen - did you find a solution to this? Also, does `remark-gfm` not work for you at all? It doesn't for me. I'm surprised it says `warning` than `error` if it isn't going to work at all.
