### ISSUE TITLE
Any way to modify the "wrapper" element?

### ISSUE THREAD

**Issue by aputinski** [mdx-js/mdx#154]
From what I can tell, there is no way to modify the wrapper element.

https://github.com/mdx-js/mdx/blob/64ffe2faece9ece7a71e60bc02e915594fd88c7f/packages/mdx/mdx-hast-to-jsx.js#L27

Am I missing something or do you have any thoughts on what an API for this could look like? Happy to contribute if this is something that makes sense to add.

**Comment by timneutkens** [comment]
You can provide any `name` that includes `wrapper` 

https://github.com/mdx-js/mdx#component-customization

```
export default () =>
  <Hello
    components={{
      wrapper: Something
      h1: Heading,
      p: Text,
      code: Code,
      inlineCode: InlineCode
    }}
  />
```

**Comment by timneutkens** [comment]
Feel free to send a pull request improving that part of the docs 🙌

**Comment by aputinski** [comment]
https://github.com/mdx-js/mdx/pull/155
