### ISSUE TITLE
npm init mdx fails

### ISSUE THREAD

**Issue by 1ak31sha** [mdx-js/mdx#1551]
### Subject of the issue
i ran
`npm init mdx`
and i got an error:

```shell
...
 create mode 100644 node_modules/zwitch/package.json
 create mode 100644 node_modules/zwitch/readme.md
 create mode 100644 package-lock.json
 create mode 100644 package.json
 create mode 100644 pages/_app.js
 create mode 100644 pages/index.md
 create mode 100644 readme.md
npm ERR! missing script: test

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lakeishapogrzeba/.npm/_logs/2021-05-11T20_58_27_900Z-debug.log
Error: Command failed: npm test
    at checkExecSyncError (node:child_process:680:11)
    at execSync (node:child_process:717:15)
    at create (/Users/lakeishapogrzeba/.npm/_npx/2a84fa2ef1b7650f/node_modules/initit/index.js:83:3)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 94786,
  stdout: null,
  stderr: null
}
npm ERR! code 1
npm ERR! path /Users/lakeishapogrzeba/playground
npm ERR! command failed
npm ERR! command sh -c create-mdx

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lakeishapogrzeba/.npm/_logs/2021-05-11T20_58_27_953Z-debug.log
```

### Your environment

*   **OS**: macOs catalina
*   **Packages**: mdx?
*   **Env**:
- node: 15.9, 
- npm: 6.14.11
- yarn: 1.22,

### Steps to reproduce

`npm init mdx`

### Expected behaviour

successful setup

### Actual behaviour

error reported: npm ERR! missing script: test

note, i then tried it on 14.16.0 and a similar error was reported:
```shell
> next-mdx@1.0.0 test /Users/lakeishapogrzeba/playground/next-mdx
> echo 'Error: no test specified'

Error: no test specified
```
not sure if this is critical to the thing working. mdx looks amazing though, thanks in advance!

**Comment by wooorm** [comment]
Hmm. I’m not sure this ever worked 🤔 Several examples never had a `test` script (which [`initit`](https://github.com/c8r/initit/blob/912910ce738d67e84d816ece917e13586d68f5f2/index.js#L83), the dependency used by `create-mdx`, uses).
`initit` is also unmaintained and depends on a hardcoded `master` branch, which we’re no longer using.

Maybe `create-mdx` can be deprecated and the same solved with better docs?

**Comment by wooorm** [comment]
The latest RC of MDX 2 (see: https://v2.mdxjs.com) has completely rewritten docs. Including new docs on how to get started, which no longer suggest `create-mdx`.
All the references to it were removed and when version 2 is released, I’ll deprecate it on npm!
