### ISSUE TITLE
Missing typings and typescript files from `@mdx-js/mdx`

### ISSUE THREAD

**Issue by floroz** [mdx-js/mdx#1552]
### Subject of the issue

Missing typescript files and typings from `@mdx-js/mdx`.

I have installed version ` "@mdx-js/mdx": "^1.6.22",` but I cannot see any typings. 

If I look into my `node_modules` folder, this is the output:

<img width="284" alt="Screenshot 2021-05-12 at 15 32 22" src="https://user-images.githubusercontent.com/45793869/117983446-40670a80-b337-11eb-9c67-458e3a6b250f.png">

There is no TypeScript nor `.d.ts` files.

### Steps to reproduce

1. I create an empty folder
2. I run `yarn init -y` 
2. I do a `yarn add -D @mdx-js/mdx`
2. I try import a default export or a named export
3. TSC compiler throws an error: _Could not find declaration files for @mdx-js/mdx, etc..._

<img width="527" alt="Screenshot 2021-05-12 at 15 41 50" src="https://user-images.githubusercontent.com/45793869/117984961-94beba00-b338-11eb-8ca4-60fded82495c.png">

**Comment by floroz** [comment]
I can see the Typings being referenced both in the documentation: https://mdxjs.com/advanced/typescript#typings-for-mdx-imports and in the source code: https://github.com/mdx-js/mdx/tree/main/packages/mdx/types

**Comment by ChristianMurphy** [comment]
The documentation you are looking at is for version 2.
Either run version 2 (see https://github.com/mdx-js/mdx/issues/1041 for more info)
Or follow the guide for version 1 https://github.com/mdx-js/mdx/blob/master/docs/advanced/typescript.mdx

**Comment by floroz** [comment]
Thank you @ChristianMurphy

**Comment by lostfictions** [comment]
hey there, just ran into this as well -- maybe the website should note somewhere that the documentation is for a pre-release version and won't work as described?
