### ISSUE TITLE
markdown links with odd number of preceding pairs of brackets are not rendered correctly

### ISSUE THREAD

**Issue by leonnicolas** [mdx-js/mdx#1559]
Hello all, here is my first issue to this project. I hope I provided all the information that you need :smile:

### Subject of the issue

Markdown links with an odd number of preceding pairs of brackets are not rendered to html correctly.
For example `[][link](#somewhere)` yields `[][link](#somewhere)` instead of [][link](#somewhere).

On the other hand `[][][link](#somewhere)` yields the correct result of [][][link](#somewhere).

### Your environment

*   **OS**: 5.12.3-arch1-1 and the [mdxjs playgound](https://mdxjs.com/playground)
*   **Packages**: I just followed to [getting started guide with react](https://mdxjs.com/getting-started/create-react-app)
*   **Env**: yarn: 1.22.10, node v16.1.0, 

### Steps to reproduce

Write a link with an odd number of preceding pairs of brackets in a .mdx file or in the [playgound](https://mdxjs.com/playground) and look at the resulting html.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

[here](https://github.com/leonnicolas/mdx-md-links-with-brackets) is an example with react, but you can also try it in the  [playgound](https://mdxjs.com/playground).

### Expected behaviour
`[][link](#somewhere)` should yield [][link](#somewhere)

### Actual behaviour

`[][link](#somewhere)` yields `[][link](#somewhere)`

### Additional Information

I thought this was an Issue with [remark](https://github.com/remarkjs/remark). I think you are using it to parse the markdown.
However, I could not reproduce the behavior with their CLI. All links with preceding pairs of brackets were rendered correctly to html.

### Why do I want to put brackets in front of links?

An example is in the prometheus docs: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#alertmanagerlist
The [] preceding a link means that we have an array of this object that is being referred to by the link.

**Comment by leonnicolas** [comment]
Apparently, the issue is fixed in v2. Will there be a v. 1.6.23+ to fix this behavior?

**Comment by ChristianMurphy** [comment]
The move to be fully commonmark compatible is itself a breaking change, which is why the change is considered major, and is a part of version 2+. Breaking changes are generally not applied to existing stable releases (for example v1)
