### ISSUE TITLE
JSX followed by markdown link does not render link as HTML

### ISSUE THREAD

**Issue by Farrser** [mdx-js/mdx#1571]
### JSX followed by markdown link does not render link as HTML

Using a `<jsx>tag</jsx>` followed by a `[link](../path)` does not render the link as HTML and instead outputs the raw markdown. 

### Your environment

*   **OS**: Mac 10.14.6
*   **Packages**: docusaurus 2.0.0-alpha.73

### Steps to reproduce

1. Go to the [mdx playground](https://mdxjs.com/playground/)
2. Try the following line `<Hello/> [link](../path)`
3. The raw link is output `[link](../path)`

Interestingly, putting text before the JSX fixes it e.g. `Text <Hello/> [link](../path)`

### Expected behaviour

The link should be output as an HTML `<a>` tag

### Actual behaviour

The raw markdown is output

Screenshot from playground:
![image](https://user-images.githubusercontent.com/2736036/120536905-8d8d4800-c3dc-11eb-92a8-6f2826879bf0.png)

**Comment by ChristianMurphy** [comment]
In MDX 1 this behavior is intended.
If the line starts with JSX content, it is assumed the whole line is JSX, and no wrapping paragraph is added.
If the line starts with Markdown/plaintext, it is assumed the line is mixed and a wrapping paragraph is added.

This behavior changes in MDX version 2, thanks to https://github.com/mdx-js/mdx/issues/628
And you can try out the new behavior today in the v2 release line https://codesandbox.io/s/affectionate-bohr-90e2p
The will be available in docusaurus when https://github.com/facebook/docusaurus/issues/4029 is addressed.
