### ISSUE TITLE
[v2] plugins not running with invalid HTML/JSX

### ISSUE THREAD

**Issue by Ehesp** [mdx-js/mdx#1577]
I've successfully been using [`next-mdx-remote`](https://github.com/hashicorp/next-mdx-remote) on a project, so upgraded the library locally to v2 to reap the benefits. Everything is going well, however I have ran into an "issue" which I was able to circumvent in v1.

Im dealing with a situation where the MDX content is unknown, so I apply a few plugins to prevent misuse of the content.

For example, parsing the following MDX:

```
<img src="...">

<td>Foo</td>
```

For this to be valid JSX, it should have a closing slash. Running this via `@mdx-js/mdx` throws the following error:

```
Unexpected closing tag `</td>`, expected corresponding closing tag for `<img>`
```

In v1 I was able to write a quick plugin which scanned HTML elements and basically sanitised them:

```js
const content = mdx('...', {
  remarkPlugins: [
    sanitizeHtml
  ]
});
```

This plugin looked something like:

```js
function sanitizeHtml() {
  return tree => {
    visit(tree, 'jsx', visitor);
  };

  function visitor(node) {
    // A `jsx` node might be a HTML element from the Markdown, or a MDX
    // component. We only want to sanitize the HTML ones.
    if (isHtml(node.value)) {
      node.value = sanitizeHtml(node.value, {
        allowedTags: [...sanitizeHtml.defaults.allowedTags, 'img'],
        allowedAttributes: {
          ...sanitizeHtml.defaults.allowedAttributes,
          img: [...sanitizeHtml.defaults.allowedAttributes.img, 'alt', 'width', 'height'],
        },
      });
    }
  }
}

```

A very hacky solution, but it worked for my use-case. However, after upgrading to v2 the plugins are simply not executed and the error is thrown straight away, not allowing me to modify the tree before being sent to the MDX compiler.

Obviously writing correct HTML/JSX would be the first step, but thought I'd highlight an upgrade "issue".

Thanks

**Comment by ChristianMurphy** [comment]
Right, in MDX version 2, MD and JSX are parsed at the same time as part of https://github.com/mdx-js/mdx/issues/628
this is also noted in the MDX 2 release plan https://github.com/mdx-js/mdx/issues/1041

**Comment by Ehesp** [comment]
Thanks - makes sense
