### ISSUE TITLE
MDX import not working in Create React App with Typescript 

### ISSUE THREAD

**Issue by janrembold** [mdx-js/mdx#1591]
### Subject of the issue

I'm trying to use MDX-JS inside a React App that was created with Create React App and TypeScript support.
Following the instructions leads to this error message after starting the app:

```
Cannot find module '!babel-loader!@mdx-js/loader!./Content.mdx' or its corresponding type declarations.  TS2307
```

By the way, following the same instructions inside a non-Typescript CRA the MDX import works fine!

### Environment

*   **OS**: MacOS 10.15.7
*   **Env**: node@14.16.1 - npm@7.11.1 - yarn@1.22.10

### Steps to reproduce

You can find an absolute minimalistic demo here: https://github.com/janrembold/mdx-demo-ts

```
git clone https://github.com/janrembold/mdx-demo-ts.git
cd mdx-demo-ts
yarn && yarn start
```

### Expected behaviour

The app should import the MDX file without any errors.

**Comment by JounQin** [comment]
It's a TypeScript usage problem with webpack loader syntax, nothing related to mdx at all.

**Comment by janrembold** [comment]
@JounQin  I had also suspected this, but unfortunately your answer is not helpful at all. I had not found a solution on the internet and all users of MDX-JS with the same (default boilerplate) setup will have this problem. It would be much more helpful and appreciated to point to a solution here or to extend the documentation.
