### ISSUE TITLE
Create a Language Server for MDX files

### ISSUE THREAD

**Issue by michaeljota** [mdx-js/mdx#1599]
### Subject of the feature

MDX 2.0 is improving its support with TS but in order to get more from it, and be able to have feedback from editors, we need a Language Server that can handle the syntax of an MDX file.

### Problem

Currently, when editing a `.mdx` file, by default VSCode treats it as a plain text file.

![image](https://user-images.githubusercontent.com/10507776/126902360-a865722e-5cb3-450c-abe6-23b01090579b.png).

### Expected behavior

MDX files should support highlighting, autocomplete, type-checking, better formatting, and other things that improve the quality of experience while developing.

### Alternatives

There is an extension [MDX](https://marketplace.visualstudio.com/items?itemName=silvenon.mdx) that `Provides syntax highlighting and bracket matching for MDX (JSX in Markdown) files.` 

So, the above code snippet would look like this:

![image](https://user-images.githubusercontent.com/10507776/126902451-8f2a260f-7212-4e76-b09a-55157386085f.png)

But, this is only for highlighting in MDX files.

### Other considerations

There is currently an issue in the TS repo asking for support of MDX files microsoft/TypeScript#36440, but for the TS LS to support this, TS itself needs work on other open issues. However, in the same ticket, you can see a member suggest an MDX LS deal with this.

`.vue` files used to suffer for this kind of behavior as well. But with the [Vue Language Server](https://github.com/vuejs/vetur/tree/master/server) and the vuejs/vetur plugin (that implements the VLS) you know have a rich experience while editing `.vue` files.

**Comment by ChristianMurphy** [comment]
See https://github.com/mdx-js/vscode-mdx and https://github.com/mdx-js/vscode-mdx/issues/165

**Comment by remcohaszing** [comment]
I actually think it may be worthwhile to create this as a language server. This could then be consumed by various editor integrations, including [vscode-mdx](https://github.com/mdx-js/vscode-mdx), vim, neovim, atom, and more.

This is not the same as the [unified-language-server](https://github.com/unifiedjs/unified-language-server) based projects I’m working on. Those provide editor compatibility with the unified CLIs. The MDX language server could instead focus on code completion, type hints, code navigation, etc.

**Comment by ShivamJoker** [comment]
Any updates on this guys? I am desperately looking for something easy to work with mdx in neovim.

**Comment by wooorm** [comment]
- Not everyone in this conversation is a guy
- This issue is closed, and refers to different places, there will not be updates here
