### ISSUE TITLE
Valid standard markdown syntax variant

### ISSUE THREAD

**Issue by vjpr** [mdx-js/mdx#160]
Because of a lack of editor support at present, it would be great to have a variant that could be parsed by a standard markdown parser.

All code would just have to be wrapped in a code block and we could use a code block prefix to identify that something should be rendered with mdx.

Here is the example from the readme with a suggestion for syntax:

```md

```mdx
import Graph from './components/graph'
```mdx

## Here's a graph

```mdx
<Graph />
```mdx

```

**Comment by johno** [comment]
This is a great idea, thought its something we should handle at the plugin level since it would cause issues with backwards compatibility in the long term.

**Comment by johno** [comment]
Thanks for opening up the issue! Going to close this in favor of https://github.com/mdx-js/specification/issues/17
