### ISSUE TITLE
remarkOptions not working

### ISSUE THREAD

**Issue by tw1t611** [mdx-js/mdx#1608]
### Subject of the issue

[remark-break](https://github.com/remarkjs/remark-breaks) not working, when passed as remarkOptions in next-mdx-remote.

I am using [next-mdx-remote](https://github.com/hashicorp/next-mdx-remote) to parse my markdown from a headless CMS.

I created an  issue there, but the problem seems mdx related.
https://github.com/hashicorp/next-mdx-remote/issues/177

```js 
import breaks from "remark-breaks";

... 

  const mdxSource = await serialize(source, {
    mdxOptions: {
      remarkPlugins: [breaks],
    },
  })
```

### Your environment

*   **OS**:  fedora 33
*   **Packages**: "next-mdx-remote": "^3.0.4"
*   **Env**: npm: 7.17.0, node: v14.15.3, Mozilla Firefox 90.0

### Steps to reproduce

Parse markdown with line breaks.

### Expected behaviour

One line break `<br>` should appear in parsed html.

### Actual behaviour

It doesn't.

**Comment by ChristianMurphy** [comment]
`remark-breaks` works with the version of MDX used in `next-mdx-remote` (1.6.x https://github.com/hashicorp/next-mdx-remote/blob/452755393f2bcadf1807f6398bf1429069acba42/package.json#L10)
Here is a running example showing the versions are compatible https://codesandbox.io/s/distracted-wescoff-3rde8?file=/src/App.js

It may be related to `remark-breaks`v3  being ESM https://github.com/remarkjs/remark-breaks/releases/tag/3.0.0, until recently (https://github.com/vercel/next.js/pull/27069) Next has had issues loading ESM.
If there are ESM related warnings/errors shown in the console consider either:
* Updating to a Next version that includes the ESM fixes
* Or temporarily downgrading `remark-breaks` to version 2, until Next can be updated.

If no ESM related errors are thrown, this may be a bug in how `next-mdx-remote` handles plugins.
