### ISSUE TITLE
2.0.0-next.9: incorrectly parse attribute value with parenthesis in JSX tags

### ISSUE THREAD

**Issue by hanayashiki** [mdx-js/mdx#1617]
### Subject of the issue

Describe your issue here.

This is *not* a place to ask questions.  For that, go to [Discussions](https://github.com/mdx-js/mdx/discussions)

### Your environment

*   **OS**: Mac
*   **Packages**: @mdx-js/mdx
*   **Env**: node

### Steps to reproduce

```
const { createMdxAstCompiler } = require("@mdx-js/mdx");

const compiler = createMdxAstCompiler();

console.log(
  compiler.parse(`
<Layout
  render={(<Content />)}
/>
`),
);

```

https://codesandbox.io/s/proud-rgb-3roji?file=/src/index.ts

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behaviour

Should be valid JSX

### Actual behaviour

returns with `Could not parse expression with acorn: Unexpected content after expression`

After a little digging, I find the problem lies in one of the dependencies: [micromark-extension-mdx-expression](https://github.com/micromark/micromark-extension-mdx-expression/blob/083e0de59ec7f34420471da80aed0bf16e1bf975/lib/factory-expression.js#L105). When the slice of code of the attribute value is passed, acorn returns with a range of `(1, 11)`, ignoring the parenthesis. So MDX considers there are more to parse, returning an incorrect error. One of the solutions might be modifying acorn's config (as I write here: https://github.com/acornjs/acorn/issues/1057).

**Comment by wooorm** [comment]
Thanks, fixed. Smart idea to parse with parens (and then remove them, because they’re non-standard!)
