### ISSUE TITLE
css float property becomes cssFloat

### ISSUE THREAD

**Issue by supersnager** [mdx-js/mdx#1623]
### Subject of the issue

When a style declaration is given as a string in the mdx file, the css **float** property becomes **cssFloat** instead of **float**.

### Your environment

*   **OS**: Linux Mint
*   **Packages**: @mdx-js/mdx: 1.6.22, @mdx-js/react: 1.6.22, gatsby-plugin-mdx: 2.8.0, 
*   **Env**: N/A 

### Steps to reproduce

Use this code in the mdx file:
```jsx
<div style="float:left">Float bug</div>
```
### Expected behaviour

The **float** property should stay as is.

### Actual behaviour

The **float** property becomes **cssFloat** in the output.
```html
<div style="cssfloat:left">Float bug</div>
```

### Additional info

This is happened here: https://github.com/mdx-js/mdx/blob/510bae2580958598ae29047bf755b1a2ea26cf7e/packages/mdx/mdx-hast-to-jsx.js#L42

Because the **camelcase-css** library makes an exception for the **float** property: https://github.com/stevenvachon/camelcase-css/blob/5fe025f5e8fdad5b1a347f2a4b301e1e32cc2723/index.js#L13

**Comment by wooorm** [comment]
Most likely fixed on next!

**Comment by ChristianMurphy** [comment]
@supersnager assuming you are using MDX with React.
MDX handles the inline `style` prop the same way React does https://reactjs.org/docs/dom-elements.html#style

```jsx
// this is an invalid way to define inline style
<div style="float:left">Float bug</div>

// this is how to define style prop
<div style={{float: "left"}}>Float works</div>
```

you can see a runnable example here: https://codesandbox.io/s/style-prop-with-jsx-lw39h?file=/src/App.js

**Comment by ChristianMurphy** [comment]
@geyang see the comment right before you posted https://github.com/mdx-js/mdx/issues/1623#issuecomment-911856459 it explains the issue and the solution.
If you are seeing something similar please open a new issue with a reproducible example of what you are seeing https://github.com/mdx-js/mdx/issues/new/choose, or if you want additional assistance open a discussion https://github.com/mdx-js/mdx/discussions

**Comment by ChristianMurphy** [comment]
Yeah, unfortunately Gatsby has customized mdx so the language behaves different, and maintains their own forks of many remark plugins with mixed success.
There is some ongoing outreach to downstream projects to support MDX 2 https://github.com/mdx-js/mdx/issues/1045
Hopefully along side that, we can help project(s) realign with the mainline mdx language and plugins.
