### ISSUE TITLE
Overflow of text in mdx docs for mobile handsets. 

### ISSUE THREAD

**Issue by hugekontrast** [mdx-js/mdx#1627]
### Subject of the issue

The text on landing page of mdxjs.com is overflowing out of the desired container.

### Your environment

*   **OS**: Android 11
*   **Packages**: 
*   **Env**: Chrome browser 92.0.4515.115

### Steps to reproduce

Take a smartphone, open chrome browser and search for mdxjs.org. At the home page only, pinch in the screen to see the overflow of text.

### Expected behaviour

The text should remain between the constraints of the screen.

### Actual behaviour

The text is rolling out of the container which in turn is broadening the container.
![Screenshot_20210907-101523_Chrome](https://user-images.githubusercontent.com/44055846/132286539-ed4cd89c-b8fd-4c99-89d7-8f2d1d9fe8fd.jpg)

**Comment by wooorm** [comment]
Fixed, thanks!

**Comment by hugekontrast** [comment]
Good job! And the new style looks "sleek".
