### ISSUE TITLE
Markdown in code block comments

### ISSUE THREAD

**Issue by brillout** [mdx-js/mdx#1636]
~~~md

# Example of using markdown to define rich comments

Some code block:

```js
function hello() {
   // Example of a [url](https://example.org/) or even `inline code` defined in a comment
}
```
~~~

That would be so sweet...

While inline codes are a nice to have, URLs in comments are actually quite common.

**Comment by ChristianMurphy** [comment]
Markdown and MDX are aware there is a code block, but they don't parse the language/content inside the block.
This is not something which would be added to core.

That said, what you want could/would be possible with a plugin.
Similar to how syntax highlighting can be added to codeblocks https://mdxjs.com/guides/syntax-highlighting
You could create a plugin/component to parse JavaScript codeblocks, find the comments, and check the comments with a markdown parser to highlight or link the way you want.

You can find an intro to working with syntax trees and plugins at https://unifiedjs.com/learn and if you have questions on creating plugins https://github.com/mdx-js/mdx/discussions there to help.
