### ISSUE TITLE
Footnotes reversed when referenced in a table

### ISSUE THREAD

**Issue by xgfd** [mdx-js/mdx#1638]
### Footnotes displayed in reverse order when referenced in a table

I have the following markdown that has 3 footnotes in a table: 

```markdown
|title|
|---  |
|[^1] |
|[^2] |
|[^3] |

[^1]: footnote 1
[^2]: footnote 2
[^3]: footnote 3
```

The MDX playground renders the footnotes in reverse order (i.e. footnote 3, footnote 2, footnote 1 instead of footnote 1, footnote 2, footnote 3).

<img width="749" alt="Screenshot 2021-09-10 at 21 18 03" src="https://user-images.githubusercontent.com/4529752/132914226-3a298c52-7f44-45fa-a22b-9af2705fa8c7.png">

I also tried referencing footnote outside a table and they are rendered correctly.

<img width="741" alt="Screenshot 2021-09-10 at 21 19 22" src="https://user-images.githubusercontent.com/4529752/132914842-a24a6cf8-9587-4d93-a375-b7b5fa5f2c75.png">

### Your environment

*   **MDX playground**: https://mdxjs.com/playground/

### Steps to reproduce
Past the following markdown into https://mdxjs.com/playground/

```markdown
|title|
|---  |
|[^1] |
|[^2] |
|[^3] |

[^1]: footnote 1
[^2]: footnote 2
[^3]: footnote 3
```

### Expected behaviour

The footnotes should be rendered as 

1. footnote 1
2. footnote 2
3. footnote 3

### Actual behaviour

They rendered as 

1. footnote 3
2. footnote 2
3. footnote 1

**Comment by wooorm** [comment]
Nice catch, thanks for the report! I fixed in in the downstream package

**Comment by xgfd** [comment]
Thank you. That's a really prompt fix!
