### ISSUE TITLE
Feature request: footnotes

### ISSUE THREAD

**Issue by lachlanjc** [mdx-js/mdx#164]

**Comment by timneutkens** [comment]
Please provide a full description when doing a feature request. This makes it easier for us to understand what you mean exactly.

**Comment by lachlanjc** [comment]
Some flavors of Markdown include support for footnotes/endnotes, and as someone using MDX for writing essays for school, it'd be great to have that built-in. See the "Footnotes" section here: https://help.ghost.org/article/4-markdown-guide

**Comment by daneden** [comment]
+1 I'm in the process of moving my blog off of Jekyll and onto Gatsby w/ MDX, and footnotes are a key part of many of my posts.

```markdown
This paragraph has a footnote.[^1]

[^1]: Here's the footnote
```

Should render to something like:

```html
<p>
  This paragraph has a footnote.<sup><a href="#fn1" id="fnref1">1</a></sup>
</p>

<!-- at the bottom of the document -->
<ol>
  <li id="fn1">Here's the footnote. <a href="#fnref1">↩</a></li>
</ol>
```

**Comment by johno** [comment]
Thanks for creating the issue @lachlanjc and providing your thoughts @daneden!

We've added support for footnotes in `0.12.0` via #173. Please let us know if you encounter any issues.

**Comment by lachlanjc** [comment]
Fantastic, thank you @johno!
