### ISSUE TITLE
how should interpolation work?

### ISSUE THREAD

**Issue by iamstarkov** [mdx-js/mdx#165]
in jsx you can do `<div>{expression}</div>`.

it seems to be not working with mdx =(

```md
import { Meta } from '../components';

export const meta = {
  date: 'April 20, 2015',
  title: 'Minimum viable blog',
  description: '…',
  url: '/mvb'
}

<Meta
  title={meta.title}
  description={meta.description}
/>

# {meta.title}

_{meta.date}_

You should have ability to write it, readers — to read it.
Content is a king. Spend time on writing, not on developing.
```

This one gets you `<h1>{meta.title}</h1>` instead of `<h1>Minimum viable blog</h1>`.

What do you think about how it should work?

**Comment by ticky** [comment]
These assignment expressions don't seem to be supported at all outside of JSX element props. I’ve opened an issue about it on the spec: mdx-js/specification#15

**Comment by johno** [comment]
Thanks for opening up this issue! You can see my response here https://github.com/mdx-js/mdx/issues/391#issuecomment-461160735 and follow along with #196 for progress.
