### ISSUE TITLE
`@mdx-js/runtime@next` doesn't work in CRA

### ISSUE THREAD

**Issue by yume-chan** [mdx-js/mdx#1663]
### Subject of the issue

`@mdx-js/runtime@next` doesn't work in CRA

### Your environment

*   **OS**: Windows 10
*   **Packages**: @mdx-js/runtime@2.0.0-next.9
*   **Env**: react-scripts@4.0.3

### Steps to reproduce

[minimal repro](https://github.com/yume-chan/mdx-runtime-next-issue)

1. `npx create-react-app mdx-runtime-test`
2. `cd mdx-runtime-test`
3. `yarn add @mdx-js/runtime@next`
4. Add a component using example code in README
5. `yarn start`

### Expected behaviour

It compiles.

### Actual behaviour

```text
> yarn start
yarn run v1.22.10
$ react-scripts start
i ｢wds｣: Project is running at http://192.168.50.127/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from D:\dev\mdx-runtime-test\public
i ｢wds｣: 404s will fallback to /
Starting the development server...

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Failed to compile.

./node_modules/periscopic/dist/periscopic.mjs
Can't import the named export 'walk' from non EcmaScript module (only default export is available)
```

Maybe related: Rich-Harris/periscopic#10

**Comment by ChristianMurphy** [comment]
@yume-chan could you try reducing your example further?
Trying a minimal example: https://codesandbox.io/s/mdx-2-cra-cmy53, it works fine.

**Comment by yume-chan** [comment]
Caused by CRA itself (facebook/create-react-app#10356)
