### ISSUE TITLE
Table and Strikethrough not parsing correctly

### ISSUE THREAD

**Issue by homumado** [mdx-js/mdx#1713]
### Subject of the issue

Tables and strikethroughs aren't parsing in [MDX Playground](https://mdxjs.com/playground/).  Had similar results in my local copy.

Looking through old Issues they seemed to work at one point?

### Your environment

*   **OS**:  Window 10
*   **Packages**: https://mdxjs.com/playground/
*   **Env**: Chrome

### Steps to reproduce

Go to [MDX Playground](https://mdxjs.com/playground/) and try to type in tables or strikethrough [in Markdown](https://github.com/syntax-tree/mdast).

```
# Hello, world!

<button>Here is a button</button>

| foo | bar |
| :-- | :-: |
| baz | qux |


~~Test~~

| Left | Centre | Right |
|:-----|:------:|------:|
| 1 | 2 | 3 |
```

### Expected behaviour

Should look like

| foo | bar |
| :-- | :-: |
| baz | qux |

~~Test~~

| Left | Centre | Right |
|:-----|:------:|------:|
| 1 | 2 | 3 |

### Actual behaviour

What happens instead?

![image](https://user-images.githubusercontent.com/84349818/136080241-e1f40c45-8de9-4986-9eef-f1641d8a1aac.png)

**Comment by ChristianMurphy** [comment]
MDX builds off CommonMark https://commonmark.org/help/
Tables and Strikethough are part of GitHub Flavored Markdown https://github.github.com/gfm/
These features can be added by including https://github.com/remarkjs/remark-gfm as a plugin

You can find more details in the guides @wooorm is writing https://github.com/mdx-js/mdx/pull/1712
