### ISSUE TITLE
mdx v2: import URL causes fail to compile error 

### ISSUE THREAD

**Issue by homumado** [mdx-js/mdx#1802]
### Subject of the issue

The `import {URL} from 'url'` line in [recma-document plugin](https://github.com/mdx-js/mdx/blob/079c8c7bb953dda5e59cf4c93fb924ad07b15ad1/packages/mdx/lib/plugin/recma-document.js) creates a compile error.

I don't think it's necessary to import the URL class since it's a global object?

### Your environment

*   **OS**: Window 10 64bit
*   **Packages**: v.2.0.0.rc
*   **Env**:  yarn v1.22.15 Next 11.0.1

### Steps to reproduce

`yarn build` a nextjs project.

### Expected behaviour

Project compiles.

### Actual behaviour

Failed to compile due to error.

```
./node_modules/@mdx-js/mdx/lib/plugin/recma-document.js
Attempted import error: 'URL' is not exported from 'url' (imported as 'URL').
```

**Comment by wooorm** [comment]
> I don't think it's necessary to import the URL class since it's a global object?

TypeScript can’t deal with it properly.

> `The import {URL} from 'url' line in recma-document plugin creates a compile error.`

Where? Several people are using xdm and mdxjs/mdx@next without errors. And `URL` should be exported from `'url'`, so this leads me to think its a problem in your bundler?

**Comment by homumado** [comment]
I'm using webpack 5 for production bundling. 

`import {URL} from 'url'` line is the only difference between the recma-document plugins on mdx-js/mdx@next and xdm:

https://github.com/mdx-js/mdx/blob/079c8c7bb953dda5e59cf4c93fb924ad07b15ad1/packages/mdx/lib/plugin/recma-document.js

**Comment by wooorm** [comment]
And how do you configure webpack? For example, I'm currently using all of this swimingly with webpack through next

**Comment by homumado** [comment]
I worked on the problem a bit more overnight and figured out the problem was caused by the version of nextjs I was using. 

The compile error clears when I changed the next package from `"next": "v11.0.1"` to `"next": "latest"`.

**Comment by cesutherland** [comment]
I'm bumping into this too in laravel-mix with the webpack 5.67.0. Afaict it works fine w/o `import {URL} from 'url'` but I'll make sure and submit a patch.

**Comment by cesutherland** [comment]
OK, in my case this is related to some project importing `node-url`, and this issue: https://github.com/defunctzombie/node-url/issues/53 URL not exported.

`URL` should be available as a global and I don't understand the comment about TS in that regard, but this trouble is on my end.
