### ISSUE TITLE
Request to support configurable import interception

### ISSUE THREAD

**Issue by EricMCornelius** [mdx-js/mdx#1826]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Apologies if there is already a way to do this that I'm not finding. I'll describe the desired feature here:

When using the @mdx-js/mdx compile function in client settings it would be useful to be able to define an alternative implementation for the dynamic import calls instead of being reliant on the browser global dynamic import functionality.

E.g. taken from here: https://johno.com/react-hooks-in-mdx/

```
import { useState } from 'react'

# Here's a button, click it!

export const MyDynamicButton = () => {
  const [count, setCount] = useState(0)
  return (
    <button onClick={() => setCount(count + 1)}>Clicked {count} times!</button>
  )
}

Click it! <MyDynamicButton />
```

```
// assume mdx_src is the above
const compiled = await compile(mdx_src, {outputFormat: 'function-body', useDynamicImport: true, providerImportSource: '#'});

// yields the following compiled.value currently
/*@jsxRuntime automatic @jsxImportSource react*/
const {Fragment: _Fragment, jsx: _jsx, jsxs: _jsxs} = arguments[0];
const {useMDXComponents: _provideComponents} = arguments[0];
const {useState} = await import('react');
const MyDynamicButton = () => {
  const _components = Object.assign({
    button: "button"
  }, _provideComponents());
  const [count, setCount] = useState(0);
  return _jsxs(_components.button, {
    onClick: () => setCount(count + 1),
    children: ["Clicked ", count, " times!"]
  });
};
function MDXContent(props = {}) {
  const _components = Object.assign({
    h1: "h1",
    p: "p"
  }, _provideComponents(), props.components), {wrapper: MDXLayout} = _components;
  const _content = _jsxs(_Fragment, {
    children: [_jsx(_components.h1, {
      id: "i6ii3xU8WpZXMMjF8BM6C-1",
      children: "Here's a button, click it!"
    }), "\n", "\n", _jsxs(_components.p, {
      children: ["Click it! ", _jsx(MyDynamicButton, {})]
    })]
  });
  return MDXLayout ? _jsx(MDXLayout, Object.assign({}, props, {
    children: _content
  })) : _content;
}
return {
  MyDynamicButton,
  default: MDXContent
};
```

As far as I can discern, we currently have no configuration options to modify `await import('react');` other than [import maps](https://github.com/WICG/import-maps)

However, if you allow an arbitrary replacement of the dynamic import function to be one that can be injected via configuration to the compiler, then you can generate something akin to:

```
const {useState} = await <custom_dynamic_import_function>('react');
```

Then it will be possible for end-users of the compilation api to intercept dynamic import requests.

```
import * as react from 'react';

const custom_dynamic_import_function = req => {
  // return webpack bundled version here
  if (req === 'react') {
    return react;
  }

  // fallback to standard dynamic import - potentially with more sophisticated logic
  // or even return customized injected dependencies here
  return import(req);
};
```

This is useful if, e.g. we want to mock dependencies inside mdx, inject bundled browser dependencies which might be already loaded, or expose any other arbitrary context to the mdx compiler for use by an end-user.

I'm presently hacking this in by using a regex replacement on the compiled output and using a non-standard run function that passes it in as a bound function argument name in the local scope:

```
import * as react from 'react';

const custom_import = async request => {
  if (request !== 'react') throw new Error(`Unsupported mdx sandbox import`);
  return react;
};

const run = (source, opts) => {
  const AsyncFunction = Object.getPrototypeOf(async () => {}).constructor;
  const replace_imports = source => source.replace(/import[\s]*\(/g, 'dynamic_import(');
  const patched_src = replace_imports(source);
  return new AsyncFunction('__opts__', 'dynamic_import', patched_src)(opts, opts.dynamic_import_fn ?? import);
};

// mdx_str comes from wherever
const compiled = await compile(mdx_str, {outputFormat: 'function-body', useDynamicImport: true, providerImportSource: '#'});

run(compiled.value, {dynamic_import_fn: custom_import});
```

I wonder if a similar argument of utility could be made for also passing in a ctx object during the run of the compiled output which then gets injected into scope. E.g.

```
const run = (source, opts, ctx = {}) => {
  const args = ['__opts__', 'dynamic_import', ...Object.keys(ctx)];
  const values = [opts, opts.dynamic_import_fn, ...Object.values(ctx)];

  return new AsyncFunction(...args, replace_imports(source))(...values);
};
```

### Solution

If there's sufficient interest in the utility, then I imagine an option should be added to the compile/evaluate/run functions to accept a non-standard dynamic import function.

The compiler can then use this in lieu of the default global import when generating function-body output.

### Alternatives

Really just depends on whether this is seen as overly complicated vs. beneficial to the ecosystem. I can certainly keep hacking the behavior in for my use-case, but spent quite a bit of time with the docs trying to find a more kosher alternative.

**Comment by ChristianMurphy** [comment]
This is possible today through [recma plugins](https://mdxjs.com/packages/mdx/#optionsrecmaplugins).
In mdx, like much of [unified](https://unifiedjs.com/), plugins can modify content, recma plugins modify the final JavaScript content though an abstract syntax tree, including having the ability to rewrite imports.

To get started with creating a plugin, https://unifiedjs.com/learn/ provides guides introducing syntax trees and how plugins can modify content.
https://mdxjs.com/playground/ shows how mdx parses content, and what the syntax trees look like at each step, including the esast/remca step.
You could probably use https://github.com/syntax-tree/unist-util-visit-parents and visit `ImportExpression`s replacing them with your desired alternative loader system.
https://github.com/mdx-js/mdx/discussions is open for questions and discussions on creating plugins.
