### ISSUE TITLE
MDXProvider seems not work in nextjs

### ISSUE THREAD

**Issue by ChinW** [mdx-js/mdx#1831]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/react

### Steps to reproduce

https://github.com/ChinW/mdx-js-nextjs-playground

### Expected behavior

MDXProvider should replace h2/h3 components as per configuration

### Actual behavior

MDXProvider doesnt work
but 

`<Component components={components}>` will do the job

### Runtime

Node v16

### Package manager

npm v8

### OS

macOS

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
See the migration guide: https://mdxjs.com/migrating/v2/#mdx-jsloader

**Comment by ChinW** [comment]
this resolved the problem... I spent days to track this in code and read the nextjs/nextra/mdx docs but just missed above migration doc.... many thanks!
