### ISSUE TITLE
Cannot export a layout

### ISSUE THREAD

**Issue by noghte** [mdx-js/mdx#1867]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@next/mdx 12.0.7

### Link to runnable example

https://codesandbox.io/s/nice-jasper-jwfky

### Steps to reproduce

After reading [the documentation](https://mdxjs.com/docs/using-mdx/#layout) to use a layout for MDX files, I created a sample code:

https://codesandbox.io/s/nice-jasper-jwfky

Steps:
1. Install `@next/mdx`, `@mdx-js/loader`, and `@next/bundle-analyzer`
2. Create next.config.js similar to the sandbox
3. Create a directory in `pages` and add a `layout.js` and an `mdx` file
4. Try to import the Layout into the `mdx` with `export from` syntax as mentioned in the documentation

### Expected behavior

The `export from` syntax works similarly to including the Layout contents into the MDX file.

### Actual behavior

Raising an exception:
```
Syntax error: Only one default export allowed per module. (14:0)
```
I have also tried defining the Layout component without `default export`, and the Layout does not apply to the MDX file.

**Comment by wooorm** [comment]
solved in v2!
