### ISSUE TITLE
The default export breaks if multiline

### ISSUE THREAD

**Issue by silvenon** [mdx-js/mdx#188]
The following MDX:

```jsx
export default ({ children }) => (
  <Layout>
    {children}
  </Layout>
)
```

transpiles into broken JSX:

```jsx
export default ({components}) => <MDXTag name="wrapper" Layout={({ children }) => (} components={components}>
  <Layout>
    {children}
  </Layout>
)</MDXTag>
```

because the default export is being added using [line-by-line interpolation](https://github.com/mdx-js/mdx/blob/679e32311fd63e8421ca755f6201ab1cc1f01396/packages/mdx/mdx-hast-to-jsx.js#L33).

**Comment by ChristopherBiscardi** [comment]
afaict, this is only the case for an mdx file without any content. While the first example here produces weird output, the second works just fine ([codesandbox](https://codesandbox.io/s/3y4wymyj75)).

```js
const t = mdx.sync(
  `export default ({ children }) => (
  <Layout>
    {children}
  </Layout>
)`
);
```

```js
const t = mdx.sync(
  `export default ({ children }) => (
  <Layout>
    {children}
  </Layout>
)

some content`
);
```
