### ISSUE TITLE
Expected component `xyz` to be defined: you likely forgot to import, pass, or provide it.

### ISSUE THREAD

**Issue by godmar** [mdx-js/mdx#1882]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"@mdx-js/mdx": "^2.0.0-rc.2"

### Link to runnable example

https://codesandbox.io/s/recursing-cannon-5cy32?file=/pages/index.js

### Steps to reproduce

[Sandbox](https://codesandbox.io/s/recursing-cannon-5cy32?file=/pages/index.js)

I am defining a component `DDemo`
```
const dcomponents = {
  DDemo: props => <h1>This is a demo component passed directly: {props.children}</h1>,
}
```
I pass it to the Content component returned by `evaluateSync`:

```
      <Content components={dcomponents}/>
```

The MDX content is:
```mdx
# Hello, world!

<Demo />

export default ({ children }) => <DDemo>{children}</DDemo>
```

### Expected behavior

It should recognize `DDemo` since I passed it via the `components` property, just like it did in MDX v1.

### Actual behavior

An error appears:
```
Error: Expected component `DDemo` to be defined: you likely forgot to import, pass, or provide it.
It’s referenced in your code at `6:34-6:59`
```

Note: If I move the DDemo component into the MDXProvider, interestingly, it is recognized. ~~However, this work-around doesn't fit my actual application since I need to replace the definition of one component for the dynamically rendered MDX compared to what's in the MDX provider.~~ *Upon reflection*, this work-around does work for me since I can nest MDXProviders and provide the replaced component in a (inner)nested provider.

### Runtime

Node v16

### Package manager

npm v8

### OS

Linux

### Build and bundle tools

Next.js

**Comment by godmar** [comment]
PS: a shorter reproduction without involving `MDXProvider` is in [this sandbox](https://codesandbox.io/s/epic-burnell-15mq0?file=/pages/index.js):

```js
import React from "react";
import * as runtime from "react/jsx-runtime.js";
import * as provider from "@mdx-js/react";
import { evaluateSync } from "@mdx-js/mdx";

const dcomponents = {
  DDemo: (props) => (
    <h1>This is a demo component passed directly: {props.children}</h1>
  )
};

const mdx = `
# Hello, world!

export default ({ children }) => <DDemo>{children}</DDemo>
`;

export default () => {
  const { default: Content } = evaluateSync(mdx, { ...provider, ...runtime });
  return <Content components={dcomponents} />;
};
```

**Comment by wooorm** [comment]
Hey!

It’s not possible to pass components to `MDXContent` and have them suddenly appear as props to other components. In the case of the wrapper, because the wrapper is used around `MDXContent`, in the case of other imported or exported components, because those can be used even if `MDXContent` itself isn’t used.

This is visible when you look at your MDX when it becomes “pseudo JS”:

```js
export function MDXContent(props) {
  return <>
    <h1>Hello, world!</h1>
    <props.components.Demo />
  </>
}

export default ({ children }) => <DDemo>{children}</DDemo>
```

MDXProvider can be used, because context is exactly for that: passing “props” without having to pass props.

This used to work, because passing components as a prop deferred to the context API.

Note that you can pass a layout. You don’t need to define it in a file:

```js
const dcomponents = {
  layout: (props) => (
    <h1>This is a demo component passed directly: {props.children}</h1>
  )
};

const mdx = `
# Hello, world!
`;
```

More information [on layouts/wrapper is here](https://mdxjs.com/docs/using-mdx/#layout)

**Comment by godmar** [comment]
Thanks for the tip to use layout.  I think the actual key that needs to be used is `wrapper` as per the documentation to which you link and my testing.

However, my actual code passes an additional property to the wrapping component, as in:
```mdx
....

export default ({ children }) => 
          <HotUpdateAbleMDX src="pages/index.mdx">{children}</HotUpdateAbleMDX>
```

**Comment by wooorm** [comment]
You‘re right, fixed the typo!
