### ISSUE TITLE
compilers registered in remarkPlugins are always overridden

### ISSUE THREAD

**Issue by aweiu** [mdx-js/mdx#1901]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@next

### Link to runnable example

https://codesandbox.io/s/misty-brook-n6we0?file=/index.js

### Steps to reproduce

Look at the console output

### Expected behavior

![image](https://user-images.githubusercontent.com/15623620/149767250-b42a8198-fd7a-4130-88f1-ec3410148271.png)

the `log 1` is equal to `log 2`

### Actual behavior

the custom unified compiler is overridden.

It may be overridden by a plugin used in the following source code:

https://github.com/mdx-js/mdx/blob/main/packages/mdx/lib/core.js#L112

This makes it impossible for me to use this plugin: https://github.com/remcohaszing/remark-prettier#format 🙏🏻

**Comment by wooorm** [comment]
Yes, it is impossible to change to a different compiler. You don’t need to in MDX.

Use remark with `remark-mdx` instead, and use that plugin.

**Comment by aweiu** [comment]
> 

I understand, but I use @mdxJS/rollup in my project, it can't  use remark with remark-mdx instead.

Maybe I can only call prettier manually in my remark plug-in

**Comment by aweiu** [comment]
> Yes, it is impossible to change to a different compiler. You don’t need to in MDX.
> 
> Use remark with `remark-mdx` instead, and use that plugin.

I understand, but I use @mdxJS/rollup in my project, it can't  use remark with remark-mdx instead.

Maybe I can only call prettier manually in my remark plug-in

**Comment by wooorm** [comment]
You‘re looking at the wrong abstraction level.

MDX is two things:
1. a language
2. a unified pipeline with certain plugins so that it can take the language and compile it to JavaScript

You’re dealing with 1, not with 2. You don’t want to generate JavaScript.

> but I use @mdxJS/rollup in my project, it can't use remark with remark-mdx instead.

The first phrase does not make the second phrase true.
You can use `@mdx-js/rollup` in your project to compile MDX files into JavaScript.
**And you can use remark with remark-mdx and other remark plugins to format MDX**.
You can also use Prettier.

**Comment by wooorm** [comment]
Prettier is also pretty broken about MDX 2. remark is likely a better formatter of MDX 2: https://github.com/mdx-js/mdx/blob/04c7faedf7131495410c55ff8fb37403483d8c08/package.json#L132.

**Comment by aweiu** [comment]
> You‘re looking at the wrong abstraction level.
> 
> MDX is two things:
> 
> 1. a language
> 2. a unified pipeline with certain plugins so that it can take the language and compile it to JavaScript
> 
> You’re dealing with 1, not with 2. You don’t want to generate JavaScript.
> 
> > but I use @mdxJS/rollup in my project, it can't use remark with remark-mdx instead.
> 
> The first phrase does not lead to the second phrase. You can use `@mdx-js/rollup` in your project to compile MDX files into JavaScript. **And you can use remark with remark-mdx and other remark plugins to format MDX**. You can also use Prettier.


Well, I'm coding a document service. I need to display formatted user's mdx in the browser through the service.

And the user's mdx is processed by `@mdxJS/rollup`, so I use `remark-prettier`.

**Comment by wooorm** [comment]
You can’t.
It’s impossible to use `@mdx-js/mdx`, let alone `evaluate` from it, to format MDX.
You can use remark to format things in browsers... 🤷‍♂️

**Comment by aweiu** [comment]
> You can’t. It’s impossible to use `@mdx-js/mdx`, let alone `evaluate` from it, to format MDX. You can use remark to format things in browsers... 🤷‍♂️

Thanks! I understand it. I can use a rollup plugin prettier mdx first, and then use @mdxjs/rollup to compile mdx.
