### ISSUE TITLE
a component must be at least one line away from an import statement before it can be used

### ISSUE THREAD

**Issue by aweiu** [mdx-js/mdx#1903]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@next

### Link to runnable example

https://mdxjs.com/playground/

### Steps to reproduce

> We assume that the `Text` file exists

## ❎

```
import Text from './Text';
<Text />
```
![image](https://user-images.githubusercontent.com/15623620/149939938-9cedde0d-bc5e-42df-ac60-562e7807c1b6.png)

```
import Text from './Text'
<Text />
```
![image](https://user-images.githubusercontent.com/15623620/149940117-0bdb0fc3-ca2a-4249-96d1-e02f5581e9e5.png)

## ✅
```
import Text from './Text'

<Text />
```

```
import Text from './Text';

<Text />
```

### Expected behavior

`<Text />` can be used on the next line of `import`

### Actual behavior

A component must be at least one line away from an import statement before it can be used

**Comment by wooorm** [comment]
Yes, you do need a blank line!
