### ISSUE TITLE
V2 not working with mdx-js/react. The MDXProvider components does not work as a result of this

### ISSUE THREAD

**Issue by Elijah-trillionz** [mdx-js/mdx#1904]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/react; < v1.6.22, @mdx-js/loader; >v2

### Steps to reproduce

Start a project, install these dependencies
`npm install @mdx-js/react@next`
`npm install @mdx-js/loader@next`

Use the `MDXProvider` from `@mdx-js/react` to wrap your components, and apply the `components` props to attempt styling or changing any HTML tag. It won't work.

```js
    <MDXProvider components={{
     p: <p style={{ color: 'red', fontSize: '1.6rem' }} {...props} />
      }}>
      <Component {...pageProps} />
    </MDXProvider>
```

All paragraphs still remain black and 1rem.

**Am using npm v 7.20.3**

### Expected behavior

I expect the paragraph to be styled according to the style for the p tag passed into the `components` props

### Actual behavior

It doesn't change. Nothing works at all

### Runtime

Node v16

### Package manager

Other (please specify in steps to reproduce)

### OS

Windows

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
Update both

**Comment by Elijah-trillionz** [comment]
@wooorm update to what?
I should mention that the MDXProvider works when I install an older version (or should I say current) of both dependencies; leaving me with v1.6.22 for both.
But then I don't have access to the new features in mdx v2. That's the purpose of reporting this issue

**Comment by wooorm** [comment]
Use v2 for both, or use v1 for both.
If you want to migrate from v1 to v2, see [migrating from v1 to v2](https://mdxjs.com/migrating/v2/)

**Comment by Elijah-trillionz** [comment]
Sorry why is this closed.
What you recommended still didn't workz after using be for both

**Comment by wooorm** [comment]
- this is not an issue, the tests and many people using it show that it works
- questions can go in Discussions
- follow the migration guide, you’re likely missing `providerImportSource`

**Comment by Elijah-trillionz** [comment]
I can't use the `providerImportSource` in next.config.js. Or can I?
I don't see a place in next.js where I can apply the config from `webpack.config.js` in the docs. Because in mdx we don't directly use the `@mdx-js/loader` in our config, we just install `@next/mdx` and it sets it up I think.
Or am I missing something

**Comment by wooorm** [comment]
Yes you can.
You can definitely use `@mdx-js/loader` in your config: https://mdxjs.com/docs/getting-started/#nextjs.
`@next/mdx` also includes in their documentation how to pass options to the webpack loader.

**Comment by Elijah-trillionz** [comment]
Thanks for this. I have been able to use webpack config in `next.config.js`

But it seems like am faced with a bigger problem.
I apologize if I am being a pain, but there is an error `Could not parse expression with acorn: Unexpected content after expression` that keeps coming up during build process.

I found [https://mdxjs.com/docs/troubleshooting-mdx/#could-not-parse-expression-with-acorn-unexpected-content-after-expression](https://mdxjs.com/docs/troubleshooting-mdx/#could-not-parse-expression-with-acorn-unexpected-content-after-expression) on the mdx docs, but it doesn't really apply to my mdx file because I don't have any expressions in my file.

I have tried to make my mdx file as plain as possible with just a "# Hello world" message, but I still get the error, any suggestions please?

**Comment by wooorm** [comment]
Pretty sure there’s a `{` somewhere. Post the file. The error. I don’t have 🔮 to look into. See https://mdxjs.com/community/support/#asking-quality-questions for more info.

**Comment by Elijah-trillionz** [comment]
Alright. I have uploaded it on [codesandbox](https://codesandbox.io/s/crimson-dawn-7gesb). Thanks

**Comment by wooorm** [comment]
There is no error in the codesandbox

**Comment by Elijah-trillionz** [comment]
It actually does, when you navigate to the `/about` page. That is where I used mdx, and that's where it throws the error. Thanks

**Comment by Elijah-trillionz** [comment]
It actually does, when you navigate to the `/about` page. That is where I used mdx, and that's where it throws the error. Thanks

**Comment by wooorm** [comment]
Here’s a working example: codesandbox.io/s/github/mdx-js/.github/tree/main/sandbox-templates/mdx-loader-next.
Note especially that one tool is used: the loader. Not next-mdx which *also* adds the loader.
