### ISSUE TITLE
Expose `MDXModule` and other typings

### ISSUE THREAD

**Issue by peterj35-dd** [mdx-js/mdx#1930]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

When trying to implement a hook such as `useMdx`:
```ts
import { evaluate } from "@mdx-js/mdx"
import { useEffect, useState } from "react"
import * as runtime from "react/jsx-runtime"

type UseMdxProps = {
  mdx: string
}

export const useMdx = ({ mdx }: UseMdxProps) => {
  // Should be typed as MDXModule
  const [exports, setExports] = useState<any>(undefined)

  useEffect(() => {
    evaluate(mdx, {
      // Also note that omitting these results in a typescript issue, this is likely a separate bug
      Fragment: undefined,
      jsx: undefined,
      jsxs: undefined,
      ...runtime,
    }).then((exports) => setExports(exports))
  }, [mdx])

  return exports
}
```

The state should be typable as MDXModule but the export is missing from the library. 

### Solution

Expose MDXModule as well as it's `default` property's type, `MDXContent` types, to the library's exported types. 

It will help make usages of hooks such as `useMdx` more maintainable

### Alternatives

N/A

**Comment by ChristianMurphy** [comment]
@peterj35-dd the type is exported from the shared `@types/mdx` package. (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7bc243aeec0035d9f921954ed10fda7c56d6924f/types/mdx/types.d.ts#L52-L65)
That same type is used by `@mdx-js/mdx` itself (https://github.com/mdx-js/mdx/blob/4b514e1a944f04a98591a47ffd05558bbd29c879/packages/mdx/lib/evaluate.js#L5)

To use it in your code:

```typescript
import type {MDXModule} from 'mdx/types'
```

should do the trick.

**Comment by wooorm** [comment]
See the Types section in the documentation: https://mdxjs.com/docs/getting-started/#types.

**Comment by peterj35-dd** [comment]
Ahh I see, there's a separate package; thanks for the reply!
