### ISSUE TITLE
How to get only a portion of the mdx? For example, first several sentences of a mdx blog article

### ISSUE THREAD

**Issue by fzyzcjy** [mdx-js/mdx#1932]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Thanks so much for the lib!

I am making a blog using GatsbyJS + MDX. For the articles list page, I want to show the first several sentences/paragraphs of each article (just as you almost always see in a normal blog). However, I cannot figure out a way to do so in mdx.

For example, I cannot simply truncate the .mdx file (say truncate first 1000 bytes), otherwise we may end up having unclosed tags and so on, making mdx confused.

### Solution

Provide an approach (possibly already existing approach?) to solve it

### Alternatives

see above

**Comment by wooorm** [comment]
a) This is a question for Gatsby, b) I think Gatsby already has stuff for that.
