### ISSUE TITLE
Cannot use mdx with jest

### ISSUE THREAD

**Issue by johackim** [mdx-js/mdx#1933]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.0

### Steps to reproduce

```bash
git clone https://github.com/johackim/test
yarn
npm run test
````

### Expected behavior

Don't return error

### Actual behavior

When my tests use a mdx library, this return me this error : `Cannot find module 'estree-walker' from 'node_modules/estree-util-build-jsx/index.js'`

```
 FAIL  __tests__/index.spec.js
  ● Test suite failed to run
                                 
    Cannot find module 'estree-walker' from 'node_modules/estree-util-build-jsx/index.js'
                                 
    Require stack:                                                
      node_modules/estree-util-build-jsx/index.js
      node_modules/@mdx-js/mdx/lib/plugin/recma-jsx-build.js
      node_modules/@mdx-js/mdx/lib/core.js
      node_modules/@mdx-js/mdx/index.js        
      __tests__/index.spec.js
                                 
      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/estree-util-build-jsx/index.js:1:1)

Test Suites: 1 failed, 1 total                                                                                                       
Tests:       0 total                                              
Snapshots:   0 total
Time:        3.257 s
Ran all test suites
```

This bug appear only when I import a library from mdx, I test many others and there is no problems.

### Runtime

Node v16

### Package manager

npm v8

### OS

Linux

**Comment by ChristianMurphy** [comment]
Jest needs to be configured to support ESM. https://mdxjs.com/migrating/v2/#esm
The [Jest ESM guide](https://jestjs.io/docs/ecmascript-modules) and the [ESM guide by Sindre](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#im-having-problems-with-esm-and-jest) linked in the trouble shooting section explain this more on how to configure and known bugs in Jest.
