### ISSUE TITLE
Pre-parsing plugins

### ISSUE THREAD

**Issue by sswatson** [mdx-js/mdx#1937]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Sometimes you want to insert code *before* the initial remark parsing, for example to save yourself some boilerplate import statements at the beginning of every mdx file. It would be nice to have a plugin option which is similar to how remark and rehype plugins work currently but which inserts earlier in the pipeline.

### Solution

Add an extra plugin option to allow the user to inject plugins before the remark-parse pass.

### Alternatives

I can't think of another solution to this problem, though my knowledge is far from complete. 

It's tempting to say you can and should do these transformations with a remark plugin, but this can be very difficult depending on what you're trying to do (since the `remarkMdx` step happens before the remark plugins are applied and is a fairly complex transformation).

**Comment by wooorm** [comment]
You can add import statements with remark, rehype, and recma plugins already. Some of these add imports: https://mdxjs.com/docs/extending-mdx/#list-of-plugins. I see no reason to do something earlier.

**Comment by sswatson** [comment]
Thanks, the reference is really helpful. I had seen those but hadn't realized that some of them add imports.

For anyone who may stumble upon this thread in the future: what [remark-mdx-images](https://github.com/remcohaszing/remark-mdx-images) does to include imports after the remark-parse pass is to manually construct and insert the `mdxjsEsm` object that remark-parse would create if the import were in the original source ([see here](https://github.com/remcohaszing/remark-mdx-images/blob/80cc59d3b0c60dc2e5d9be9f3f46db51563d968e/src/index.ts#L45)).

That's probably the best approach, particularly since unified doesn't actually allow you to do the thing I was originally asking for here (because the remark-parse plugin is the processor's `Parser` and therefore necessarily happens first).
