### ISSUE TITLE
Consistent crash of playground by replacing JSX variable with a double quote

### ISSUE THREAD

**Issue by ernstki** [mdx-js/mdx#1956]
Hi everyone. Hope you're well.

### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

_This pertains to [the playground](https://mdxjs.com/playground/), so whatever package/version is in use there._

### Link to runnable example

_See [below](#steps-to-reproduce)._

### Steps to reproduce

Probably the rendering engine and the OS don't matter, but I tried both Firefox and Chrome (latest versions) on macOS, on Intel, running Catalina.

1. visit https://mdxjs.com/playground/
2. select `{{padding: '1rem', backgroundColor: 'violet'}}` with the pointing device (or your finger)
3. overwrite the selection by typing `"`

### Expected behavior

I'm probably not going to get the terminology right here, since JSX and all this is new to me, but I am trying this out because I think I might have a use case for it.

The first thing I wondered about with the playground demo is "how is this different from CSS?" so I tried replacing the object within the JSX variable—the `{{stuff in braces}}`—with a quoted attribute, plain CSS. This is when I experienced the crash.

### Actual behavior

The entire page goes white. The following error messages appear in the developer console:

```
Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 8
react-dom.production.min.js:193:243
```
```
Uncaught Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 8
react-dom.production.min.js:50:340
```

### Runtime, Package manager, OS, Build and bundle tools

As noted above, this was Firefox and Chrome on macOS, but I think that probably doesn't matter. The issue pertains to the web site, specifically [the playground](https://mdxjs.com/playground/).

<hr>

Thanks!

**Comment by wooorm** [comment]
Thanks for thoroughly filling out the issue form! I can reproduce it :)
Folks that have react experience, and with handling errors, can likely help here. See our contribution guide on [the site](https://mdxjs.com/community/contribute/) for more on how!

**Comment by ernstki** [comment]
You bet. Thanks for having a look.

**Comment by ernstki** [comment]
Thanks for digging in to this @homumado.

Should

```html
<div style="color:violet">
  Try and change the background color to `tomato`.
</div>
```

still be a `Minified React error #62`, though?

**Comment by wooorm** [comment]
Yes, that MDX should be an error. The error is followed by a link. You can follow that link: https://reactjs.org/docs/error-decoder.html/?invariant=62. It’ll explain that `style` expects an object, not a string.

**Comment by ernstki** [comment]
Ah, I'm like a babe in the woods here. In the MDX woods. Thanks!

Cheers, all.
