### ISSUE TITLE
Unexpected Token `...` in production

### ISSUE THREAD

**Issue by max-pod** [mdx-js/mdx#1966]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/mdx@2.0.0
next-mdx-remote@4.0.0
sentry/nextks@6.12.0
next@11.1.3

### Link to runnable example

https://github.com/vercel/next.js/tree/canary/examples/with-mdx-remote

### Steps to reproduce

My users have the problem, but I don't. I can't replicate it nor debug how it's happening.
Wide spectrum of browsers, multiple users creating client-side errors
- Chrome Mobile 42, 43, 50
- Chrome Dekstop 50, 83, 84, 86, 87 (highest 87)
- Firefox 78

Chrome 87 particularly threw me off, since that's not exactly old: 2020-11-17
https://en.wikipedia.org/wiki/Google_Chrome_version_history

I think it's coming from Next's link preloading, but I can't tell.
Following same code pattern of: https://github.com/vercel/next.js/tree/canary/examples/with-mdx-remote

Using:
1. next-mdx-remote 4.0.0
2. sentry/nextks ^6.12.0
3. next 11.1.3

TSConfig:

`
{
  "compilerOptions": {
    // "incremental": true,
    "target": "es5",
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "lib": ["es2015", "dom"],
    "noEmit": true,
    "jsx": "preserve",
    "noImplicitAny": true,
    "alwaysStrict": true,
    "strictNullChecks": true
  },
  "include": ["src", "pages"],
  "exclude": ["node_modules", "build", "src/**/*.test.ts", "src/**/*.test.tsx"]
}

### Expected behavior

No unexpected token error on object destructing line.

### Actual behavior

Error:
Raw original/unminified:
`SyntaxError: Unexpected token ...
  at ? (../../node_modules/next-mdx-remote/node_modules/@mdx-js/react/lib/index.js:53:43)`

Unminified:
`   * @param {Record<string, unknown> & {components?: Components}} props
   * @returns {JSX.Element}
   */
  function boundMDXComponent(props) {
    const allComponents = useMDXComponents(props.components)
    return React.createElement(Component, {...props, allComponents}) // Error: unexpected token ...
  }
}`

### Runtime

Node v16

### Package manager

yarn v1

### OS

Windows, Linux, macOS

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
Your issue is hard to read. I recommend reading up on markdown, specifically how to use code, and use code for your code.

It also isn’t reproducible: “users have a problem”. I can’t do anything with that. You need to explain what and why and how.

This seems like an error that has to do with your users. The info you provide, Node 16, Next, TypeScript, all support `...`. So the problem is the versions of your users.

**Comment by max-pod** [comment]
@wooorm Fair enough, but this is a platform/plugin-specific issue, that seems to give an error for certain browsers with some unknown configuration, that does cause errors in production. If I could reproduce the error I could probably solve it. As it is, I saw an error from MDX on certain browser versions / and despite emulating that exact browser version, couldn't replicate it.

Hoped to get some ideas from the community, because as it is hard to read, it's even harder to debug. :shrug:

**Comment by wooorm** [comment]
You’re asking about how to turn modern javascript into javascript that runs in several old browsers. You are also using TypeScript and Next.js. I am guessing that you’ll likely have more luck searching for this question regarding those two tools. E.g., your tsconfig contains an exclude of `node_modules`? Maybe that’s a problem? I don’t really know TypeScript though, and I’m assuming that if you ask these questions to Next.js or TS folks, you’ll much quicker get answers.
