### ISSUE TITLE
MDXProvider not support inlineCode

### ISSUE THREAD

**Issue by maqi1520** [mdx-js/mdx#1972]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [x] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.0

### Steps to reproduce

Add a test  `packages/react/test`

```jsx
test('should support `components` with `MDXProvider`', async () => {
  const {default: Content} = await evaluate('# hi \n test`inlineCode`', {
    ...runtime,
    useMDXComponents
  })

  assert.equal(
    renderToString(
      <MDXProvider
        components={{
          inlineCode: (props) => <code id="inlineCode" {...props} />,
          h1: (props) => <h1 style={{color: 'tomato'}} {...props} />
        }}
      >
        <Content />
      </MDXProvider>
    ),
    '<h1 style="color:tomato">hi</h1>\n<p>test<code id="inlineCode">inlineCode</code></p>'
  )
})
```

### Expected behavior

test pass

### Actual behavior

![image](https://user-images.githubusercontent.com/9312044/158125021-a02c5936-cd5b-4841-89f6-aaa3d50aa448.png)

### Runtime

Node v14

### OS

macOS

### Build and bundle tools

webpack

**Comment by wooorm** [comment]
Please read the changelog/migration guide: https://mdxjs.com/migrating/v2/#update-mdx-content.

**Comment by maqi1520** [comment]
thanks
