### ISSUE TITLE
Update Embed Guide to Reflect MDX v2

### ISSUE THREAD

**Issue by slavakurilyak** [mdx-js/mdx#1982]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v2

### Steps to reproduce

None

### Expected behavior

It would be great to see the [embed](https://mdxjs.com/guides/embed/) guide be updated to reflect MDX v2.

### Actual behavior

None

**Comment by ChristianMurphy** [comment]
It appears to be up-to-date and reflect the current API.

If you have found a specific issue, please share the details.
If you have a question on the guide please use discussions https://github.com/mdx-js/mdx/discussions
