### ISSUE TITLE
Usage of the Indented code block after migration to the v2 are not parsed as code

### ISSUE THREAD

**Issue by mavr1k** [mdx-js/mdx#1984]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.1.0

### Link to runnable example

https://codesandbox.io/s/naughty-babbage-t6jdcn?file=/pages/index.mdx

### Steps to reproduce

In MD specification there are three variations of code blocks:

~~~
Inline `code`

Indented code (can be with tabs or with 4 spaces)

    // Some comments
    line 1 of code
    line 2 of code
    line 3 of code


Block code "fences"

```
Sample text here...
```

Syntax highlighting

``` js
var foo = function (bar) {
  return bar++;
};

console.log(foo(5));
```
~~~

Working with MDX before v2 every option worked great. But now Indented code doesn't parse as a code element. Do you have plans to support it in MDXv2?

### Expected behavior

Indented code block should be parsed as code.

### Actual behavior

Indented code block should be parsed as a paragraph.

### Runtime

Node v16

### Package manager

npm v8, yarn v3

### OS

macOS

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
This is intentional. Use fenced code instead. See:
- https://mdxjs.com/blog/v2/#improvements-to-the-mdx-format
- https://mdxjs.com/docs/what-is-mdx/#markdown
