### ISSUE TITLE
Access FrontMatter datas Component MDX

### ISSUE THREAD

**Issue by mattSam** [mdx-js/mdx#199]
Hi ! 
I add the plugin remark 'remark-frontmatter' to use frontmatter in yaml. When i show the component, the yaml is removed so it's ok, but i don't know how to get datas from it... If someone can help me :heart: 

My webpac config loader  :
```javascript
{
    loader: '@mdx-js/loader',
    options: {
        mdPlugins: [highlight, emoji, frontmatter],
        type: 'yaml',
        marker: '-',
        fence: '---',
    },
}
```

**Comment by silvenon** [comment]
Is exporting frontmatter an option for you?

```
export const meta = {
  date: '2018-03-01'
}

# Title

Body
```

That way you can easily access it while importing.

**Comment by mattSam** [comment]
Thanks for answer, 

I wanted this, but i have a plugin webpack which read each Markdown file to get Yaml with [gray-matter](https://github.com/jonschlinkert/gray-matter). I could to write Yaml and the `export const` but it's duplicate... 

I tried to use mdx to access `export const` dynamically in js code... but can not do it :sob:

**Comment by silvenon** [comment]
Hm, it's hard to help without seeing some more code to understand in what way your hands are tied. So you have both Markdown and MDX files? How are you using them exactly? Why do you need to extract frontmatter with gray-matter?

**Comment by silvenon** [comment]
Also, MDX should definitely make it more clear and obvious how to access data from plugins, no question about it, but I think currently that the feature is only partially implemented, so let's try to find a workaround.

**Comment by mattSam** [comment]
Yeah, I understand, 
I don't have Markdown pure file sorry, only Mdx. 
To explain my project, i have multiples Mdx files for document with Yaml frontmatter.
First, I have my homemade webpack plugin which export the Yaml frontmatter datas from all mdx to create my menu (The Yaml it's for title name and futurs others options).
Second, my react App load file with the mdx loader perfectly but the plugin remark-frontmatter don't allow me to acces frontmatter data... just `export const` as you said.

I have may be the workaround to use two rules webpack  for both cases.

**Comment by mattSam** [comment]
Yeap, 
I tried the 2 rules with OneOf [Links of example for interessested](https://gist.github.com/devonzuegel/36aa56cc7baa85f0db4cad5652a6a0f4) it's working ! :smile: 
I will go on this way, thanks you for you help ;)

**Comment by wangjianio** [comment]
> Yeah, based on what you said I think you'll either need to modify your homemade plugin to read from `export const meta` instead of YAML frontmatter, or you need to use two rules.

@silvenon Any idea of get `export const meta` in node script?

**Comment by johno** [comment]
From the consuming script you should be able to:

```js
import Document, { meta } from './some/file.mdx'
```

**Comment by wangjianio** [comment]
I want to get couple of .mdx files meta info to generate contents, but as in node environment, it do not support `import`, `export const`, `# title` or `<div></div>` directly.

As far as I thought, I can use a script to read .mdx file and use its meta info to generate.

How should I do?

**Comment by johno** [comment]
Most of what you'll need should be in [this guide](https://mdxjs.com/advanced/transform-content) and [this plugin](https://github.com/manovotny/remark-mdx-metadata). The plugin uses MDX's plugin API (via remark) to find export nodes and then parses them with babel to access the data.

**Comment by wangjianio** [comment]
[remark-mdx-metadata](https://github.com/manovotny/remark-mdx-metadata) plugin can add or update metadata, but what I need is extracting metadata😞

**Comment by JerryGreen** [comment]
There's great tool for extracting FrontMatter metadata, for NextJS: https://github.com/hashicorp/next-mdx-enhanced
