### ISSUE TITLE
In the Playground Editor of a document, the Editor Tab and Options Tab automatically lose focus after switching between them.

### ISSUE THREAD

**Issue by PlayGuitar-CoderQ** [mdx-js/mdx#1993]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.1.0

### Steps to reproduce

 Click on the Playground page, first enter the content in the Editor tab, then click on the options tab and then come back to the Editor tab to enter the content, then the focus will be lost automatically.

👉  https://mdxjs.com/playground/

I am still in process in learning English.  Sorry!😜

![image](https://user-images.githubusercontent.com/55419399/160995758-7de6a9aa-cf59-4cb9-a7af-2e7f2bdff08e.png)

### Expected behavior

The editor should type normally after switching tab selections

### Actual behavior

The editor is behaving unusually out of focus after switching the Tab

### OS

macOS

**Comment by wooorm** [comment]
Weird!

- I believe it is recent that this started happening
- We also recently updates `react-tabs`, coincidence?!
- Apparently, that did some things to focus? https://github.com/reactjs/react-tabs/releases

Are you perhaps interested in investigating the problem? Perhaps this is a problem with them? Or we need to change something in the tabs here?

**Comment by PlayGuitar-CoderQ** [comment]
I would be more than happy to look into it 🦾

**Comment by PlayGuitar-CoderQ** [comment]
@wooorm  https://github.com/reactjs/react-tabs/issues/451  
There are already corresponding issues, and it is indeed a problem with react-tabs

**Comment by danez** [comment]
Hello :)

So I just released version 4.2.0 of react-tabs, which includes a fix for the focus.

The problem here in this ticket is different though: The behavior for focus changed in v4 so that tabs are instantly focused on click to allow instant keyboard navigation. To disable this again I added a new prop `focusTabOnClick`, which disables this and does not mess with focus on click: https://github.com/reactjs/react-tabs#focustabonclick-boolean

This should make react-tabs not focus itself on click and leave the focus untouched. Can you check if this helps?

**Comment by wooorm** [comment]
Thanks Daniel!

@PlayGuitar-CoderQ Could you try that?

**Comment by PlayGuitar-CoderQ** [comment]
No problem, I'll check it out.

**Comment by PlayGuitar-CoderQ** [comment]
@wooorm  But I'm running mdx according to the contribution guide and there's an error reported that I haven't understood what's causing it. 🤔

<img width="823" alt="image" src="https://user-images.githubusercontent.com/55419399/161364886-1ab40196-c345-4590-a575-7a2709582dcc.png">

**Comment by wooorm** [comment]
Hmm I believe currently you need to be on Node 14 for this.
I'll check later and update the docs.

**Comment by PlayGuitar-CoderQ** [comment]
Thanks， It's true that my version of node is too high.

After I ran the run docs for the first time

I ran index.html under public on the local server and found that index.css was introducing errors and that the page was not styled

![image](https://user-images.githubusercontent.com/55419399/161371304-320ceec5-dc24-4617-8be5-8b1a1b2dd387.png)

**Comment by wooorm** [comment]
You can create a local server inside the `public/` folder, then the styles should work.

**Comment by PlayGuitar-CoderQ** [comment]
Thank you for your patience and answers 👍.

I have successfully run and tested react-tabs@4.2.0 to resolve this issue,  so just upgrade react-tabs.😁
gif picture：👇

![Large GIF (602x336)](https://user-images.githubusercontent.com/55419399/161445403-884091b6-c377-4337-907b-a1b22c502578.gif)

**Comment by PlayGuitar-CoderQ** [comment]
@danez  Thanks Daniel!   I have tested your fix with no problems.  
I was going to try to fix this, but you fixed it quickly. 👍👍

**Comment by wooorm** [comment]
Thanks @PlayGuitar-CoderQ for the pull request, and @danez for the upstream fix!
