### ISSUE TITLE
MDX + Vite + React 18 – Error in development mode (`module is not defined at jsx-runtime.js`)

### ISSUE THREAD

**Issue by oeb25** [mdx-js/mdx#1994]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/rollup@2.1.0 react@18.0.0

### Link to runnable example

https://stackblitz.com/edit/vitejs-vite-cbdltq?file=main.jsx

### Steps to reproduce

Loading an MDX-generated component produces the error `module.exports` during development runtime.

_I am not positive whether this is a Vite or an MDX issue, but since I have not been able to find a fix, I don't know where else to report this. I am also opening an issue on Vite to be sure!_

A reproduction case [can be found here](https://stackblitz.com/edit/vitejs-vite-cbdltq?file=main.jsx). After the build, check the browser console for the error. The error exists in all tested major browsers.

### Expected behavior

The component is loaded without error.

### Actual behavior

The JS file generated by MDX contains an import of `"/@id/react/jsx-runtime"`, which in turn imports `"/node_modules/react/jsx-runtime.js"`, which is a file containing the following contents:

```js
if ("development" === "production") {
  module.exports = require("./cjs/react-jsx-runtime.production.min.js");
} else {
  module.exports = require("./cjs/react-jsx-runtime.development.js");
}
```

It then fails when accessing `module.exports`, since it is not defined in this context:

```
Uncaught ReferenceError: module is not defined at jsx-runtime.js:6:3
```

### Runtime

Other (please specify in steps to reproduce)

### Package manager

npm v8

### OS

macOS

### Build and bundle tools

Vite

**Comment by vlad-zhukov** [comment]
It's a Vite issue, see https://github.com/vitejs/vite/issues/6215

As a fix you can add

```
optimizeDeps: {
  include: ['react/jsx-runtime'],
}
```

**Comment by wooorm** [comment]
Thanks for the workaround Vlad!
Closing this then, as it’s not something to change here, but rather in Vite.
Apparently the issue’s been open for a while, so I’m also open to a PR documenting @vlad-zhukov’s workaround in https://mdxjs.com/docs/getting-started/#vite!
