### ISSUE TITLE
Evaluate/compile MDX doesn't work for basic markdown

### ISSUE THREAD

**Issue by didaktio** [mdx-js/mdx#1995]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/mdx

### Steps to reproduce

```ts
import { evaluate } from '@mdx-js/mdx';
import * as runtime from 'react/jsx-runtime.js';

...
React.useEffect(() => {
  (async () => {
    ....
    const { default: c } = await evaluate(`# heading`, { ...runtime });
    ....
   })();
}, [])
...
```

### Expected behavior

Returns value without throwing. Adding plugins remark-rehype and/or remark-mdx-code-meta results in a successful evaluation. But combining these is proving difficult, and it's not clear exactly where the issue is.

The production use case is simply that remote mdx/md is fetched (as a string) and given to mdx-js to parse. Custom components are also used, but I'm not currently able to even get to that point. 

### Actual behavior

<img width="364" alt="image" src="https://user-images.githubusercontent.com/54242233/161097179-bc16c7c0-860b-4c56-990a-4edb3ef6688f.png">

### Runtime

Node v17

### Package manager

yarn v1

### OS

macOS

**Comment by ChristianMurphy** [comment]
@didaktio I'm not able to replicate the issue https://codesandbox.io/s/mdx-with-plain-markdown-uppz3z
Could you share a runnable example?
