### ISSUE TITLE
Whitespace text nodes cannot appear as a child of <tr>

### ISSUE THREAD

**Issue by Lokua** [mdx-js/mdx#2000]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdx@2.1.1

### Link to runnable example

[Code Sandbox](https://codesandbox.io/s/fervent-star-m9qufk?file=/src/App.js)

### Steps to reproduce

Seems we are unable to render jsx tables without white space warnings. This is not limited to `<tr>` as the title suggests, but pretty much any scenario where'd you want to write a table in jsx directly using typical code indentation will result in this error: `Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <tr>. Make sure you don't have any extra whitespace between tags on each line of your source code.`.

code sandbox repro: https://codesandbox.io/s/fervent-star-m9qufk?file=/src/App.js

Easy work around is to wrap the jsx in a component: https://codesandbox.io/s/wonderful-haibt-bldeqz?file=/src/App.js

So not really a huge problem, but something I thought was worth bringing up.

### Expected behavior

Semantic tables in jsx/html (non-markdown) don't result in console warnings.

### Actual behavior

jsx/html (non-markdown) tables result in validateDOMNesting warnings.

**Comment by jblarriviere** [comment]
I've experienced an issue that i think is related to this. It looks like some form of code indentation create unexpected linebreaks, whitespaces and/or `p` tags in the generated file.

If it can help, I've realised that this indentation leads to a line break and a space being added as children of the `Inline` between the buttons : 
```mdx
<Inline>
	<Button>A</Button>
    <Button>B</Button>
</Inline>
```

when this one creates no br or whitespace but wraps the content of the buttons in a `p` tag : 
```mdx
<Inline>
	<Button>
		A
	</Button>
    <Button>
		B
	</Button>
</Inline>
```

**Comment by wooorm** [comment]
@jblarriviere that is unrelated and expected behavior: https://mdxjs.com/docs/what-is-mdx/#interleaving

**Comment by paulkre** [comment]
Does anyone have a workaround?

**Comment by wooorm** [comment]
There’s a workaround mention in the PR:

```
Easy work around is to wrap the jsx in a component: [codesandbox.io/s/wonderful-haibt-bldeqz?file=/src/App.js](https://codesandbox.io/s/wonderful-haibt-bldeqz?file=/src/App.js)
```
