### ISSUE TITLE
Error compiling MDX due to bad formatting

### ISSUE THREAD

**Issue by hk86** [mdx-js/mdx#2002]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdx-js/mdx@2

### Steps to reproduce

1. Use https://mdxjs.com/playground/
2. Insert 
```
<div><p>TEST</p>
</div>
```

### Expected behavior

The HTML is valid, but has a bad formatting. Still I would expect to compile it correctly.

### Actual behavior

Compiling error:

15:1-15:17  error  Expected a closing tag for `</p>` (15:1-15:6) before the end of `paragraph`  end-tag-mismatch  mdast-util-mdx-jsx

### Runtime

Node v16

### Package manager

npm v8

### OS

Linux

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
- Make sure to stick with the rules of interleaving: https://mdxjs.com/docs/what-is-mdx/#interleaving.
- Don’t use `<p>`, in MDX we use markdown. Write a line and it becomes a paragraph.
- Don‘t use a random `div` that does not add anything
