### ISSUE TITLE
Describe current Site integration issues with CRA 5 in documentation

### ISSUE THREAD

**Issue by userzimmermann** [mdx-js/mdx#2004]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

https://mdxjs.com/docs/getting-started/#create-react-app-cra states that: "There is no need to configure it."

Unfortunately, that's currently not the case with CRA 5 anymore; and many people (including myself) have already spent a lot of time with figuring out reasons & finding workarounds …

### Solution

Please add a statement to https://mdxjs.com/docs/getting-started/#create-react-app-cra —briefly describing the situation & maybe directing people to possible workarounds like those discussed in https://github.com/mdx-js/mdx/discussions/1870 

### Alternatives

Just accepting the situation and waiting for https://github.com/facebook/create-react-app/issues/12166 to get fixed …

**Comment by userzimmermann** [comment]
Ok, @wooorm – If you direct me to the corresponding documentation sources, then I'll add it :)

**Comment by wooorm** [comment]
At the bottom of each page on the website is a link “Edit this page on GitHub”, that should point you there. More on how to contribute is explained in the contribution guide: https://mdxjs.com/community/contribute/.

**Comment by userzimmermann** [comment]
Good morning, @wooorm :) & first: Thanks for quickly merging https://github.com/mdx-js/mdx/pull/2007 —yet I still can't build the documentation locally:

```
$ npm run docs-generate

> docs-generate
> cross-env NODE_LOADER_CONFIG=website/loader-react-server.js node --unhandled-rejections=strict --no-warnings --experimental-loader @node-loader/core --conditions=react-server website/generate.server.js

file:///C:/Users/userz/Projects/mdx/docs/_component/layout.server.js:56
      <div>
      ^

SyntaxError: Unexpected token '<'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:139:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)
```

JSX syntax is not accepted in `.js` files; which sounds reasonable ;) —but somehow it must work for you (and your CI) … Am I missing some Node.js environment setting to enable this general JSX support? Is this Windows-related?

And—a maybe blasphemous question ;D —why not using `.jsx` file endings?

**Comment by wooorm** [comment]
Use Node 14

**Comment by userzimmermann** [comment]
> Use Node 14.

Which wonderfully works!—& as a side-effect I'm now familiar with NVM!—& https://github.com/mdx-js/mdx/pull/2009 tears down my final contribution barrier :)

**Comment by echarles** [comment]
I hit the same issue while generating the docs site with node 18 and indeed node 14 solves it.

1. Should an `engine` key be added to `package.json` to inform developers of that constraint?
2. Does that mean that the whole MDX library ecosystem do no work with node >14?

**Comment by wooorm** [comment]
Are you talking about CRA, per this issue, or about the docs of this project?

Re 1: No, this is about the docs site
Re 2: No, MDX can as far as I am aware even be used on Node 10, with some experimental esm flag

**Comment by echarles** [comment]
> Are you talking about CRA, per this issue, or about the docs of this project?

talking about the docs with `npm run docs` - Sorry I just realize that the issue is about CRA, so may not be the best place to discuss...

> Re 1: No, this is about the docs site

yep, so if the docs can only be built with Node 14, `engines` key could be added https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines

> Re 2: No, MDX can as far as I am aware even be used on Node 10, with some experimental esm flag

Is that documented somewhere?

**Comment by remcohaszing** [comment]
> yep, so if the docs can only be built with Node 14, `engines` key could be added https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines

Adding `engines` would cause `npm install` to fail for the mono repo for other Node.js versions.

> Is that documented somewhere?

Yes, it’s docmented for every package, e.g.: https://mdxjs.com/packages/mdx/#install

**Comment by wooorm** [comment]
For how to build the site, see the contribution docs: https://mdxjs.com/community/contribute/#site

> Is that documented somewhere?

The recommendation in the docs is to use a maintained version of Node. That is Node 14 currently. End of the month that will be Node 16: https://github.com/nodejs/Release.
[All docs](https://mdxjs.com/packages/mdx/#install) currently mention 12, because Node 10 needed a flag, and you should be at 14+ anyway.

**Comment by echarles** [comment]
Agree, `engines` is not the way to go as would break other modules. https://mdxjs.com/community/contribute/#site is informative, maybe a specific script to check the node/npm version would have helped as a developer.

<img width="990" alt="Screenshot 2023-04-01 at 11 55 21" src="https://user-images.githubusercontent.com/226720/229279358-21132bf6-47cb-4968-a71f-5817a7494c20.png">

Thx also for the infos about current and future support of node.
