### ISSUE TITLE
Include file content

### ISSUE THREAD

**Issue by mgohin** [mdx-js/mdx#2015]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I need to display some configuration files in my MDX files, and it would be better to reference a file (and lines if possible) to always have a fresh view of those files, instead of copy-past content in a code block.

For your information, I use MDX with Storybook.

### Solution

ASCIIDoc have this feature : https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#includes

### Alternatives

I copy past files content, but if I forget to do it when those files change, I'm f*****.

**Comment by wooorm** [comment]
Hey,

a) You can use JS inside MDX. So you can import `node:fs` and read files and display them.
b) You can import files, including other MDX files.
c) You can extend markdown/MDX, see https://mdxjs.com/docs/extending-mdx/ for more info

Closing as this is something that is solved outside of core.

**Comment by mgohin** [comment]
Thanks for the complete and quick answer
