### ISSUE TITLE
`position` is missing is `mdxJsxAttribute` node

### ISSUE THREAD

**Issue by JounQin** [mdx-js/mdx#2034]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-mdx

### Steps to reproduce

```js
<div abc="xxx"></div>
```

### Expected behavior

Add `position` in `mdxJsxAttribute` node

### Actual behavior

```json
{
  "type": "root",
  "children": [
    {
      "type": "mdxJsxFlowElement",
      "name": "div",
      "attributes": [
        {
          "type": "mdxJsxAttribute",
          "name": "abc",
          "value": "xxx"
        }
      ],
      "children": [],
      "position": {
        "start": {
          "line": 1,
          "column": 1,
          "offset": 0
        },
        "end": {
          "line": 1,
          "column": 22,
          "offset": 21
        }
      },
      "data": {
        "_mdxExplicitJsx": true
      }
    }
  ],
  "position": {
    "start": {
      "line": 1,
      "column": 1,
      "offset": 0
    },
    "end": {
      "line": 2,
      "column": 1,
      "offset": 22
    }
  }
}
```

### Runtime

Node v16

### Package manager

yarn v1

### OS

macOS

**Comment by wooorm** [comment]
Could you try and reduce the MDX of this error, and see if it still persists? Are all those spaces needed for the problem?

**Comment by JounQin** [comment]
> Could you try and reduce the MDX of this error, and see if it still persists? Are all those spaces needed for the problem?

Done, the white spaces are not required.

See https://github.com/syntax-tree/mdast-util-mdx-jsx/blob/main/lib/index.js#L190

Should move this issue to there instead.

**Comment by wooorm** [comment]
Ahh. This is not technically hard to fix.
But it is somewhat intentional.
In unist, nodes are in 'children'. These are somewhere else. So they're not really nodes. But maybe that doesn't matter practically.

Do you want to explore the solution in a pull request?

**Comment by JounQin** [comment]
> Do you want to explore the solution in a pull request?

Yeah, I'd like to do it when I'm free this week.

**Comment by JounQin** [comment]
@wooorm Can you move this issue to https://github.com/syntax-tree/mdast-util-mdx-jsx and assign it to me?
