### ISSUE TITLE
Support React `__source` prop

### ISSUE THREAD

**Issue by remcohaszing** [mdx-js/mdx#2035]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

React uses the `__source` prop display where components originate in the React devtools.

Babel supports this in [`@babel/babel-plugin-transform-react-jsx-source`](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx-source).

### Solution

Inject this prop in a similar way as [`@babel/babel-plugin-transform-react-jsx-source`](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx-source). This should only happen in development and only for React, but optionally supporting alternative runtimes.

Also I’m willing to implement this.

### Alternatives

It could be an external recma plugin, but I think it’s useful to include in core.

**Comment by wooorm** [comment]
- What about `__self`?
- I think this at least makes sense as a utility similar to [`estree-util-build-jsx`](https://github.com/syntax-tree/estree-util-build-jsx/blob/main/index.js#L243), which is then used here
- Preact has some support in their automatic JSX runtime: https://github.com/preactjs/preact/blob/6a4b346615105fe0b2d8591736ac75ceb7e75890/jsx-runtime/src/index.js#L26. I’m guessing that all automatic runtimes receive this as a separate prop, but I can’t find the “source” in Babel. If that’s the case, `estree-util-build-jsx` should move the prop to a separate argument, and this option can be turned on in `development`

**Comment by remcohaszing** [comment]
I found a bit more info in the [React RFC for the automatic runtime](https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#dev-only-transforms).

So basically in the classic runtime, we need to compile to:

```js
React.createElement(
  Component,
  {
    ...props,
    __source={{ filename, lineNumber, columnNumber }}
    __self={this}
  },
  ...children
)
```

And in the automatic runtime, we need to compile to the following, where `isStaticChildren` is a boolean indicating if a production runtime would use `jsxs` instead of `jsx`:

```js
import { jsxDEV as _jsxDEV } from 'react/jsx-runtime'

_jsxDEV(
  Component,
  props,
  key,
  isStaticChildren,
  { filename, lineNumber, columnNumber },
  this
)
```

I still need to figure out when the `__self` prop or last argument of `_jsxDEV` needs to be added. It could be added later as well, so I can focus on supporting `__source` first.

I also believe this shows this functionality belongs in core, especially for the automatic runtime.

**Comment by wooorm** [comment]
We generate JSX. Because otherwise each step needs to know which runtime the user wants, and sometimes they don‘t want to compile it away.
Much easier to use JSX as the lingua franca, and then at the end optionally transform JSX into function calls.

I think we need to do the same here: add that prop to JSX.

On the receiving end, we can see from Preact and React, that they optionally expect `__source`. So, if there’s an automatic runtime, we can define `__source` on JSX. Though `estree-util-build-jsx` has to move it from props to the 5th argument.

For the classic runtime, as you linked before, as `__source` is passed in props, and some `h` functions don’t handle `__source` meaning it ends up in HTML, we can’t *just* define and later pass it.

I don’t support `_jsxDEV` in `estree-util-build-jsx` yet. Is that required, because otherwise `__source` is not used in production? We can, if needed, add support for a `development` option to `estree-util-build-jsx`.

**Comment by wooorm** [comment]
> options.file

Maybe `filePath`? I don’t see the rest of `file` being used, likely. It also helps that `file.path` does not mean `file.history[0]` (the original file).

I don’t see a need for an extra `@mdx-js/mdx` option, to opt out. If we run into trouble, we can add it later.

I’m under the impression that TS is a bit messy with everything it supports for JSX, compared to the comments that we, Babel, and SWC support. I’d focus on modelling Babel!

---

Sounds like we have a plan?!

**Comment by remcohaszing** [comment]
I believe we need the file contents, because estree uses offsets which we need to map to lines and columns. Depending on that we need either a vfile or just the file path. I'll figure that out on the go. Apart from that, we have a plan! 👍

**Comment by remcohaszing** [comment]
[AST explorer](https://astexplorer.net) only attaches start and end offsets, but apparently the estree format produced by MDX attaches `loc` as well. So you’re right, we don’t need any additional information, at least not for MDX.
