### ISSUE TITLE
Specify outdir for @mdx-js/esbuild

### ISSUE THREAD

**Issue by whaaaley** [mdx-js/mdx#2046]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Some esbuild plugins allow you to specify an outdir for specific file types. CSS in esbuild itself has options to output all imported CSS into the out directory. I'd like an option to write the output from MDX files into my dist folder instead of including them in my bundle.

I will admit, reason I want this is primarily due to the lack of code splitting in esbuild. Or more accurately, well supported code splitting. It's still a WIP and currently doesn't work for my use case. However I'd still like to use MDX, but I have so many MDX files it's bloating my bundle size. I need to load them asynchronously and requesting them from my dist folder might be the best bet until code splitting is well supported.

### Solution

Maybe something like

```js
esbuild.build({
  plugins: [
    mdx({
      // development: !production,
      // jsxRuntime: 'classic',
      // pragma: 'jsx.jsx',
      // pragmaFrag: 'jsx.jsxFragment',
      // pragmaImportSource: '~/modules/superstatic/src/jsx-pragma.js',
      // rehypePlugins: [
      //   rehypePrism
      // ],
      outDir: './deploy/dist/' // <= this
    })
  ]
})
```

### Alternatives

Wait for esbuild code splitting.

**Comment by wooorm** [comment]
I’m not sure about this. As you say, it’s a hack around esbuild.
For CSS or other external files it makes much more sense. For MDX, which is compiled to JS, I don’t understand the need to put some files in a folder. How would they even be stitched together again?

>  I'd like an option to write the output from MDX files into my dist folder instead of including them in my bundle.

It sounds like you have a bunch of blog posts and they’re all bundled in one JS file for your site? This sounds rather weird. Perhaps it’s an XY problem, and you can explain more about what you’re doing and why and what you’re running into.

> I need to load them asynchronously and requesting them from my dist folder might be the best bet until code splitting is well supported.

You can do this by running esbuild several times. esbuild is fast.

**Comment by whaaaley** [comment]
Yeah you're right. For the stitching, I was just going to use a script loader. But I understand this could create a lot of problems if MDX is importing more stuff. My MDX files are pretty simple. 

As far as this plugin is concerned it's probably just better to wait for code splitting. For my use-case I might have to mess around with Rollup if I want code splitting with non-esm bundles for the time being. I'll close this issue!
