### ISSUE TITLE
Can't parse markdown comments

### ISSUE THREAD

**Issue by vitonsky** [mdx-js/mdx#2047]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

next-mdx-remote 4.0.3

### Steps to reproduce

Try to compile this text
```md
Some text
<!-- md comment -->
```

### Expected behavior

Text compiled successfully

### Actual behavior

Error
```
Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)
```

### Runtime

Node v14

### Package manager

npm v6

### OS

Linux

### Build and bundle tools

webpack

**Comment by ChristianMurphy** [comment]
This is explained in "what is mdx?"
https://mdxjs.com/docs/what-is-mdx/#mdx-syntax

> HTML syntax doesn’t work in MDX as it’s replaced by JSX (`<img>` to `<img />`). Instead of HTML comments, you can use JavaScript comments in braces: `{/* comment! */}`
