### ISSUE TITLE
Support bundler specific options inside plugin ecosystem

### ISSUE THREAD

**Issue by kbulatovic** [mdx-js/mdx#2094]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Hello -:)

The motivation behind this feature request is a need to have access to some bundler options inside plugin in scenarios where mdx is used with tools like webpack or rollup.
In my specific example i wanted to write a rehype plugin that does some `ImportDeclaration` custom module resolving, relative to the current transformed mdx file path. This is easy if we use core package as it exposes the entry point. But in bundlers, plugin doesn't have that option. 

So in order for me to make this happen is to fork a rollup/webpack mdx packages, and manually add plugins in compilation phase, and pass those options there.

### Solution

Add additional layer on top of `PluggableList`, something like `BundlerPlugin` that will give end plugin writers access to bundler options that make sense for the plugin to consume (which can vary, on specific use cases i guess??). That type should be only defined inside bundler packages. Best way to provide the api is through plugin first closure options argument, as the plugin should still stay agnostic to the environment, and consumers can opt in in to pass that option depending on their use case.

### Alternatives

I don't know any alternative way of doing this rather then modifying webpack/rollup packages (or do a custom implementation which is what i want to avoid).

**Comment by wooorm** [comment]
You can use webpack/rollup/esbuild etc plugin system already. You can make ugins for them. They work in combination with this.

We have our own plugin system.
They are passed path information already. That has nothing to do with rollup/wrbpack/esbuild.

Docs: https://github.com/unifiedjs/unified#function-transformertree-file-next

**Comment by kbulatovic** [comment]
Thank you for the fast response. 

Oh, okay i didn't actually check out the transformer signature, VFile is exactly what i need.

Thank you very much, sry for the bother -:)
