### ISSUE TITLE
(@mdx-js/react) Where is the exported Components type?

### ISSUE THREAD

**Issue by khinshankhan** [mdx-js/mdx#2104]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/react^2.1.2

### Link to runnable example

-

### Steps to reproduce

Install the package `@mdx-js/react` and try to import mdx components type.

### Expected behavior

Until recently I was on an old version of v1, which had `MDXProviderComponentsProp` as an available when using `@types/mdx-js__react` + https://mdxjs.com/packages/react/#types seemed to indicate it was exported? So, I expected there to be an export for `Components`. 

### Actual behavior

`Components` is not available 

![image](https://user-images.githubusercontent.com/22206867/184568416-1cd966fc-7a60-423f-b1e7-c4e806acae77.png)

Seeing https://github.com/mdx-js/mdx/blob/main/packages/react/index.js didn't export it, I figured out after going through the package to install `mdx/types` and am now using `MDXComponents` ie `import { MDXComponents } from "mdx/types";`. 

If this is the proper way to use the type, I think https://mdxjs.com/packages/react/#types might be a little misleading and could include the bit to install the package to use this type. Actually, it should probably link to https://mdxjs.com/docs/getting-started/#types?

### Runtime

Node v16

### Package manager

pnpm

### OS

Linux

### Build and bundle tools

Gatsby

**Comment by wooorm** [comment]
Types are in `@types/mdx` indeed, as documented in the [Types section of the Getting started docs](https://mdxjs.com/docs/getting-started/#types).
It is indeed correct that the docs for `@mdx-js/react` are out of date (and likely also for preact, vue). A PR improving them, including a link you mention, would be appreciated!

**Comment by wooorm** [comment]
@khinshankhan Interested in working on a PR?

**Comment by khinshankhan** [comment]
Sure. I only know + tested with react, so should I only update the react docs or just use generic terminology for all the frameworks?

**Comment by wooorm** [comment]
You can see that our packages for [react](https://mdxjs.com/packages/react/#types), [preact](https://mdxjs.com/packages/preact/#types), and [vue](https://mdxjs.com/packages/vue/#types), each have the exact same types section.
Depending on what wording you think of for react, I don’t think it needs to be specific to React either, I am thus assuming that the same wording can be reused for the others!
