### ISSUE TITLE
[TypeScript] @mdx-js/rollup doesn't match Vite 3's plugin types

### ISSUE THREAD

**Issue by guoyunhe** [mdx-js/mdx#2105]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/rollup 2.1.2

### Steps to reproduce

Create a vite.config.ts with:

```ts
import mdx from '@mdx-js/rollup';
import react from '@vitejs/plugin-react';
import { UserConfig } from 'vite';

const config: UserConfig = {
    plugins: [
      react({ jsxRuntime: 'classic' }),
      mdx({
        jsxRuntime: 'classic',
        providerImportSource: '@mdx-js/react',
      }) as any,
    ],
}

export default config;
```

### Expected behavior

TypeScript should not show errors

### Actual behavior

TypeScript shows errors:

```
error TS2322: Type 'Plugin' is not assignable to type 'PluginOption'.
  Type 'Plugin' is not assignable to type 'Plugin_2'.
    Types of property 'resolveId' are incompatible.
      Type 'ObjectHook<(this: PluginContext, source: string, importer: string | undefined, options: { custom?: CustomPluginOptions | undefined; isEntry: boolean; }) => ResolveIdResult | Promise<...>, {}> | undefined' is not assignable to type '((this: PluginContext, source: string, importer: string | undefined, options: { custom?: CustomPluginOptions | undefined; ssr?: boolean | undefined; isEntry: boolean; }) => ResolveIdResult | Promise<...>) | undefined'.
        Type '{ handler: (this: PluginContext, source: string, importer: string | undefined, options: { custom?: CustomPluginOptions | undefined; isEntry: boolean; }) => ResolveIdResult | Promise<...>; order?: "pre" | ... 2 more ... | undefined; }' is not assignable to type '(this: PluginContext, source: string, importer: string | undefined, options: { custom?: CustomPluginOptions | undefined; ssr?: boolean | undefined; isEntry: boolean; }) => ResolveIdResult | Promise<...>'.
          Type '{ handler: (this: PluginContext, source: string, importer: string | undefined, options: { custom?: CustomPluginOptions | undefined; isEntry: boolean; }) => ResolveIdResult | Promise<...>; order?: "pre" | ... 2 more ... | undefined; }' provides no match for the signature '(this: PluginContext, source: string, importer: string | undefined, options: { custom?: CustomPluginOptions | undefined; ssr?: boolean | undefined; isEntry: boolean; }): ResolveIdResult | Promise<...>'.

 38       mdx({
          ~~~~~
 39         jsxRuntime: 'classic',
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 42       }),
    ~~~~~~~~

    at createTSError (/Users/guoyunhe/Git/cratedx/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/guoyunhe/Git/cratedx/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/guoyunhe/Git/cratedx/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/guoyunhe/Git/cratedx/node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (/Users/guoyunhe/Git/cratedx/node_modules/ts-node/src/esm.ts:400:37)
    at /Users/guoyunhe/Git/cratedx/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/Users/guoyunhe/Git/cratedx/node_modules/ts-node/src/esm.ts:409:15)
    at async ESMLoader.load (node:internal/modules/esm/loader:359:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:47) {
  diagnosticCodes: [ 2322 ]
}
```

### Runtime

Node v16

### Package manager

npm v8

### OS

macOS

### Build and bundle tools

Vite

**Comment by wooorm** [comment]
Why would that be a bug here? This uses Rollup's plugin type. What would you suggest? Why not a bug in Vite? https://github.com/mdx-js/mdx/blob/69a15b76f15136a33f2f9fe947a605e97d28fc6c/packages/rollup/lib/index.js#L4

**Comment by wooorm** [comment]
Closing due to no response (and per my above comment: I think we’re doing the right thing)

**Comment by wooorm** [comment]
> p.s. Document [here](https://mdxjs.com/docs/getting-started/#vite) doesn't work, except for being the way above.

If it doesn’t work, that’s because Vite changed. It used to work.
As it doesn’t work anymore, are you interested in updating the docs?

**Comment by ryuujo1573** [comment]
> > p.s. Document [here](https://mdxjs.com/docs/getting-started/#vite) doesn't work, except for being the way above.
> 
> If it doesn’t work, that’s because Vite changed. It used to work. As it doesn’t work anymore, are you interested in updating the docs?

Sure, I'll try to do it when I wake up tomorrow. 🛏️

To-Do-rrow:
* Check breaking change by `vite`
* Write a doc about this
* Write an issue to `vite` if needed

**Comment by wooorm** [comment]
> No idea of what that means,

What that means is that you are using pnpm. Which does not install peer dependencies. It means you need to install it.

> I installed rollup by `pnpm i -D rollup` and it gave me a version of `>=3`

This is fine for us, but not fine for Vite. Vite wants a version higher than `2.79.1` but lower than `3.0.0`

> conflicts

Yes. Install a lower version. `pnpm i -D rollup@2`

> I just did something unconsciously that made this messy

Raise it with Vite folks or install v2 for them. Our package supports version 2 and 3.

**Comment by ryuujo1573** [comment]
Thank you. I've learned something new !! 🌵
