### ISSUE TITLE
Get Page Title

### ISSUE THREAD

**Issue by jacobp100** [mdx-js/mdx#2106]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

It would be nice if there was a way to get the first `h1` on the page. I.e.

### Solution

```
# Some <Title />

Some body
```

Would return the title as `<>Some <Title /></>`

### Alternatives

Manually exporting the title

**Comment by wooorm** [comment]
https://mdxjs.com/docs/extending-mdx/#list-of-plugins (`rehype-mdx-title`)
