### ISSUE TITLE
Add Astro to Site generators in Getting started

### ISSUE THREAD

**Issue by wooorm** [mdx-js/mdx#2110]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Astro supports MDX 2 well, but it’s not listed in the Getting started section.
AFAIK people don’t need to install our packages, but install a by Astro provided integration.

### Solution

Add a small section here: https://mdxjs.com/docs/getting-started/#site-generators.
Include some basics and defer to Astro docs

### Alternatives

Remove other tools that have their own integrations? The list is becoming long, but I think it’s a bad plan.

**Comment by bholmesdev** [comment]
@wooorm I'd be very interested in adding this! Should be a quick PR 👍

**Comment by wooorm** [comment]
Cool to hear! Yep. You don’t need to build the website for this I think. Just `lint` and `format` should be enough to make sure prose is clean:

https://github.com/mdx-js/mdx/blob/6690566c65647a98693aa5eaec5fb6995a16d4a2/package.json#L133-L134
