### ISSUE TITLE
Markdown link syntax is not supported

### ISSUE THREAD

**Issue by guoyunhe** [mdx-js/mdx#2113]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/rollup 2.1.2

### Steps to reproduce

1. go to https://mdxjs.com/playground/
2. type the following Markdown in the editor

```md
My blog is <https://guoyunhe.me/>
```

```md
My email is <i@guoyunhe.me>
```

### Expected behavior

Should be rendered as links.

It is very easy to differ Markdown links from JSX components: URL must have a `/` and email address must have a `@`. However, JSX tag must not contain `/` or `@`.

### Actual behavior

Compile error.

**Comment by wooorm** [comment]
This is intentional as there are cases where autolinks conflict with JSX tags. It is documented here: https://mdxjs.com/docs/what-is-mdx/#markdown.

**Comment by tats-u** [comment]
@wooor XML shouldn't accept `://` or `@ ` as a tag name right?

We don't have to consider other schemes without `//` because they are useless as auto links.

**Comment by wooorm** [comment]
Read the comment above your comment.
Use links: `[text](url)`, raw URLs are bad anyway. If you want raw URLs, use `remark-gfm`.

**Comment by tats-u** [comment]
@wooorm I've read. `:` itself is valid as XML tag names but `/` & `@` are not.

https://www.w3.org/TR/xml/

<html><body>
<h5><a name="d0e804" id="d0e804">Names and Tokens</a></h5>

[4] | NameStartChar | ::= | ":"  \| [A-Z] \| "_" \| [a-z] \| [#xC0-#xD6] \| [#xD8-#xF6] \| [#xF8-#x2FF] \|  [#x370-#x37D] \| [#x37F-#x1FFF] \| [#x200C-#x200D] \| [#x2070-#x218F] \|  [#x2C00-#x2FEF] \| [#x3001-#xD7FF] \| [#xF900-#xFDCF] \| [#xFDF0-#xFFFD] \|  [#x10000-#xEFFFF]
-- | -- | -- | --
[4a] | NameChar | ::= | NameStartChar \| "-" \| "." \| [0-9] \| #xB7 \| [#x0300-#x036F] \| [#x203F-#x2040]
[5] | Name | ::= | NameStartChar (NameChar)*


</body>
</html>

<html><body>
<h5><a name="d0e2259" id="d0e2259">Start-tag</a></h5>

[40] | STag | ::= | '<' Name (S 								Attribute)* S? '>' | [WFC: Unique Att Spec]
-- | -- | -- | -- | --



</body>
</html>

1. Try parsing as JSX
2. If fails, try parsing as autolinks

This should be perfect for URLs with `://` and emails without space.

> Use links: [text](url), raw URLs are bad anyway.

In technical documents, sometimes we want users to remember or copy-and-paste URLs sometimes.

This autolink feature is important in Japanese (and Chinese). 

```md
VS Codeのソースコードは、<https://github.com/microsoft/vscode>で入手できます。
```

We don't insert spaces around URLs and other native words (in not a few cases): https://github.com/prettier/prettier/issues/6385
Some people do but it's not so much common (especially Japanese).

**Comment by wooorm** [comment]
a) This project has nothing to do with XML. XML is not JSX. JSX relates to JS. MDX relates to JSX and markdown (CommonMark)
b) `/` is fine in JSX: it closes a tag.
c) > Try parsing as JSX; If fails, try parsing as autolinks
   
   No. Ambiguous grammars like that are slow, unsafe, and hard to explain to users.
d) The `mailto` and `xmpp` protocol are written without `//`, anyone can come up with any protocol; and in JSX, anyone can use any namespace. `<svg:rect/>` is an autolink according to markdown. `<whatever:whatever>` is an autolink according to markdown. And they are also valid JSX.

**Comment by tats-u** [comment]
@wooorm
> This project has nothing to do with XML. XML is not JSX. JSX relates to JS. 

SVG is XML. X of JSX is that of XML.

> / is fine in JSX: it closes a tag.

It's just single `/`. Not double ones.

> `<svg:rect/>`

`:` are not adjacent to `/`.

**Comment by wooorm** [comment]
JavaScript isn’t Java.

---

https://spec.commonmark.org/dingus/?text=a%20%3Csvg%3Arect%2F%3E%20b

^-- it links.

https://spec.commonmark.org/dingus/?text=a%20%3Cwhatever%3Awhatever%3E%20b

^-- it links.

**Comment by tats-u** [comment]
@wooorm 

>  SVG in HTML isn’t XML. 

lol
You haven't opened `.svg` images by a text editor, have you? It's just a XML.

Do you understand what I want to say?

```mermaid
flowchart TD
    left["&lt;"] --> ns["NameSpace or Tag"]
    ns --> colon[:]
    colon --> ns
    ns --> at["@"]
    at --> domain["E-mail domain"]
    domain --> em([E-mail])
    ns --> ems["E-mail specific symbols\ne.g. +"]
    ems --> emn["Email account"]
    emn --> at
    ns --> sp["␣ or /"]
    colon --> sl["//"]
    sl --> url([URL])
    sp --> jsx([JSX])

```

**Comment by wooorm** [comment]
> You haven't opened .svg images by a text editor, have you? It's just a XML.

That is not what you were saying. That is XML. Because that is not SVG *in* HTML. Please read the HTML spec on how foreign content works in HTML. Thanks for changing that.

> lol

Don’t be insulting. Thanks for changing that.

> Their syntax is very similar as XML.

That is different.

> Do you understand what I want to say?

No, you are saying different things all the time.

> This flowchart perfectly recognizes <svg:links/> as JSX.

You made a flow chart of something that doesn’t match the JSX grammar and that doesn’t match the markdown grammar.

Here’s the grammar for autolinks: https://github.com/wooorm/markdown-rs/blob/24d78c3420980f3e56fc420f8efc7e601b144ee7/src/construct/autolink.rs#L9-L20.
Here’s the grammar for a JSX tag: https://github.com/wooorm/markdown-rs/blob/24d78c3420980f3e56fc420f8efc7e601b144ee7/src/construct/partial_mdx_jsx.rs#L12-L59

They conflict.

Introducing some new grammar that doesn’t match JSX and doesn’t match markdown doesn’t sound like a great idea.

Your flowchart is missing a lot of detail.

**Comment by tats-u** [comment]
> Here’s the grammar for autolinks: https://github.com/wooorm/markdown-rs/blob/24d78c3420980f3e56fc420f8efc7e601b144ee7/src/construct/autolink.rs#L9-L20.
Here’s the grammar for a JSX tag: https://github.com/wooorm/markdown-rs/blob/24d78c3420980f3e56fc420f8efc7e601b144ee7/src/construct/partial_mdx_jsx.rs#L12-L59
>
> They conflict.

Have you thought of merge these grammers? I've just tried to.
Why not give priority to analysis as JSX, and if it is not accepted, why not just analyze it as an address?

>Your flowchart is missing a lot of detail.

Don't complain about the brief outline I wrote in a short time.

**Comment by wooorm** [comment]
> Have you thought of merge these grammers? I've just tried to a little.

This is the problem. This is open source. I think it doesn’t work. You come up and say that it does. That’s on your to explain that something works.

> Why not give priority to analysis as JSX, and if it is not accepted

JS(X) has syntax errors. It doesn’t say “didn’t match”, let’s try other things. It says “crash!”.

> And is this JS MDX parser uses that Rust code as wasm?

Maybe look through how the projects work? I.e., see https://mdxjs.com/packages/mdx/#architecture for docs, or read the code. There are rust and javascript versions.

> Don't complain about the brief outline I wrote in a short time.

Spend time on your proposals. It’s on you to convince people.

> Suggest me some "corner cases".

No, you can come up with something that works.

> I don't say this is an introduction. Just a (partial) revival of the feature you've thrown away.

It is: you propose a new grammar. Something that isn’t JSX and something that isn’t markdown autolinks.

**Comment by tats-u** [comment]
It looks quite difficult to implement realistically from what you've said. OK.

> It says “crash!”.

This is critical. So we have to create a JS(X)-based original parser, but... It's never what we want to maintain. Thanks.

**Comment by wooorm** [comment]
Micromark parses ESM/expressions/JSX itself.

**Comment by tats-u** [comment]
> Always disable automatic links

https://github.com/micromark/micromark-extension-mdx-md

> Disable automatic links that have even the slightest chance of being JSX

Copy and modify https://github.com/micromark/micromark/blob/main/packages/micromark-core-commonmark/dev/lib/autolink.js or add an option to it

>Micromark parses ESM/expressions/JSX itself.

You're right according to https://github.com/micromark/micromark-extension-mdxjs

**Comment by wooorm** [comment]
> You're right according to

Yes, I wrote all this code 😅

> Need to look more closely at the code to determine if it is possible but looks difficult

Difficult is one thing.

It’s unclear what you propose.

That’s the problem.

You can also make a flow chart, or BNF grammar with what I provided above.

To show your vague ideas of improving things, actually work. And how it would work.

**Comment by tats-u** [comment]
```
mustNeverBeJsx ::= "<" maybeUrlOrEmail ">"
maybeUrlOrEmail ::= httpOrHttps | email
httpOrHttps ::= "http" /s?/ "://" urlContent
urlContent ::= (at least conforms to the CommonMark autolink's specification)
email ::= commonAccount "@" domain
commonAccount ::= /[!#$%&'*+\-/=?^_`|}~a-zA-Z0-9.]{1,64}/
domain ::= (at least conforms to the CommonMark autolink's specification / max length is 255)
```

>  Scheme names consist of a sequence of characters. The lower case
   letters "a"--"z", digits, and the characters plus ("+"), period
   ("."), and hyphen ("-") are allowed.

> RFC 5322 allows quoted string addresses (not accepeted by JSX) like "foo \"@\\ bar"@example.com but it's not common.

https://www.rfc-editor.org/rfc/rfc1738#section-2.1

I don't know if `{` in emails is interoperable with JSX. `{...` is not valid email account name because consecutive periods without quoted is invalid in emails.

This have only to cover most cases and doesn't have to cover corner cases (especially emails)

> It’s unclear what you propose.
> That’s the problem.

The GFM autolink feature is sometimes incompatible with Japanese.
I don't like inserting space between Japanese and URLs. I would keep it as a last resort.

> 私のポートフォリオは、https://日本語domain.example/で公開しています。
