### ISSUE TITLE
Add Solid to JSX in Getting started

### ISSUE THREAD

**Issue by wooorm** [mdx-js/mdx#2116]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Solid supports MDX 2 with https://github.com/high1/solid-jsx but it’s not listed in the Getting started section.

### Solution

Add a small section here: https://mdxjs.com/docs/getting-started/#jsx.
Include some basics and defer to Solid/solid-jsx’ docs

### Alternatives

n/a

---

@high1 something you might be interested in working on?

**Comment by Djunnni** [comment]
can i try this?

**Comment by wooorm** [comment]
Yes please!

**Comment by wooorm** [comment]
Solved in GH-2159.
