### ISSUE TITLE
Problem when a string is appended without spaces after bold parentheses

### ISSUE THREAD

**Issue by pyrasis** [mdx-js/mdx#2119]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.1.3

### Steps to reproduce

https://mdxjs.com/playground/

```
**hello**world

**(hello)**world

**(hello)** world
```

![image](https://user-images.githubusercontent.com/210015/187802935-57aa03c0-02e1-4243-8b27-3dce17b8438b.png)

### Expected behavior

```
<b>hello</b>world

<b>(hello)</b>world

<b>(hello)</b> world
```

### Actual behavior

```
<b>hello</b>world

**(hello)**world

<b>(hello)</b> world
```

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Other (please specify in steps to reproduce)

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by ChristianMurphy** [comment]
This isn't a bug, it is how markdown works.
You can see the same behavior by posting your example

```markdown
**hello**world

**(hello)**world

**(hello)** world
```

into GitHub itself

---

**hello**world

**(hello)**world

**(hello)** world

---

For a full description see https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis
