### ISSUE TITLE
Invalid webpack configuration object error on build

### ISSUE THREAD

**Issue by harrysolovay** [mdx-js/mdx#212]
I'm following [the create-react-app example](https://github.com/mdx-js/mdx/tree/master/examples/create-react-app). My code can be found [here](https://github.com/harrysolovay/NextJS-TypeScript-MDX) (incase you'd like to reference it directly). When I run the start script, everything works as expected. When I run my build script, however, I get the following:

```sh
$ react-app-rewired build
Creating an optimized production build...
Failed to compile.

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[1].oneOf[0].use should be one of these:
   non-empty string | function | object { loader?, options?, query? } | function | [non-empty string | function | object { loader?, options?, query? }]
   Details:
    * configuration.module.rules[1].oneOf[0].use should be a string.
    * configuration.module.rules[1].oneOf[0].use should be an instance of function.
    * configuration.module.rules[1].oneOf[0].use should be an object.
    * configuration.module.rules[1].oneOf[0].use should be one of these:
      non-empty string | function | object { loader?, options?, query? }
    * configuration.module.rules[1].oneOf[0].use should be an instance of function.
    * configuration.module.rules[1].oneOf[0].use[0] should be a string.
    * configuration.module.rules[1].oneOf[0].use[0] should be an instance of function.
    * configuration.module.rules[1].oneOf[0].use[0] has an unknown property 'include'. These properties are valid:
      object { loader?, options?, query? }
    * configuration.module.rules[1].oneOf[0].use[0] should be one of these:
      non-empty string | function | object { loader?, options?, query? }


error Command failed with exit code 1.
```

Any suggestions on how to fix the build process? Thank you!!! Please let me know if you have any questions.

Kind regards,

Harry

**Comment by harrysolovay** [comment]
Please don't leave me hangin' haha. I really want to implement this library! 🙏

**Comment by silvenon** [comment]
Hey @harrysolovay, we definitely won't leave you hanging! Your code is currently unavailable so I can't take a look. This error strongly suggests an incorrect webpack configuration, probably not an issue with MDX. What would really help is if you gradually make small changes from our CRA example towards your own and see when it breaks. Which changes have you made?

**Comment by harrysolovay** [comment]
Thank you so much for getting back to me.

I actually fixed the bug :/ and I don't have the state of the project when I encountered the bug–– I'm sorry! I've been completely unhelpful to anyone else experiencing this issue. Please don't hate me haha.

Kind regards,

Harry

**Comment by silvenon** [comment]
No hate, only love ❤️ Glad you got it fixed!

**Comment by silvenon** [comment]
Our example doesn't have invalid webpack configuration. It fails on build though (whoops) because of @rebass/markdown, but that's a different story.

I don't think MDX is really a problem in your case, it's just one of the variables in your configuration. You need to retrace your steps, carefully study how to properly override CRA and learn to read webpack's configuration errors because they are very helpful. Remove piece by piece until you pinpoint the location of the error, and if you're still stuck find out if there's a CRA support channel where you can ask for help.

I've never really used CRA, so it would probably take me a long time to find out what the solution to your problem is.

**Comment by harrysolovay** [comment]
You're completely right! I was improperly configuring the use of a `.babelrc`. Thank you!
