### ISSUE TITLE
Objects are ignored in remarkPlugins

### ISSUE THREAD

**Issue by gaearon** [mdx-js/mdx#2136]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/mdx@2.1.3

### Steps to reproduce

This neither crashes nor works.

```js
const code = await compile(source, {
  remarkPlugins: [
    await import('some-remark-plugin')
  ]
});
```

### Expected behavior

The issue is that `import` returns an object like `{ default: ... }`. I forgot about that. I didn't check it because I expected that MDX would crash when given an invalid plugin. My request is to crash if the plugin isn't a function instead of ignoring it.

### Actual behavior

MDX happily skipped my invalid plugin without attempting to run it. So I didn't know there is a problem. (I spent 30 minutes on this.) 

### Runtime

Node v17

### Package manager

npm v8

### OS

macOS

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
> My request is to crash if the plugin isn't a function instead of ignoring it.

Thing is: we supports presets (which are objects): collections of plugins and/or settings. In this case, it’s seen as a preset without settings, without plugins, and with an unknown field.

https://github.com/unifiedjs/unified/blob/144eec01b0e1faa23655359d61c3749ad2af99e7/index.d.ts#L551-L558

So we can’t throw on objects.

> I spent 30 minutes on this.

Yeah, makes sense, I’m assuming other folks will also run into this.

We could throw on objects that have neither `plugins` nor `settings` fields though.
I opened https://github.com/unifiedjs/unified/issues/200. There are some downsides but I think it’s good to have. I think it should go in a major, and I don’t think it’s worth it to cut a major just for this. So I expect it to land, but not soon!
