### ISSUE TITLE
css classes removed when hashed link is used in anchor tag

### ISSUE THREAD

**Issue by anuj-scanova** [mdx-js/mdx#2151]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.6.22

### Link to runnable example

@storybook/storybook

### Steps to reproduce

Using `MDX` with `@srotybook`.

Wanted to add anchor tag `<a>` with a hash link like
```html
<a href="#item" className="btn btn-primary mx-2">Button</a>
```

But on rendering, the classes are removed from the anchor tag, the output is
```html
<a href="#item" target="_self">Button</a>
```

If the anchor tag is used without `href` or any other value, e.g.,
```html
<a href="https://example.com" className="btn btn-parimary mx-2">Button 2 </a>
```

Then it works fine and renders as
```html
<a href="https://example.com" class="btn btn-primary mx-2">Button 2</a>
```

### Expected behavior

CSS classes should be rendered too with the hash link.

### Actual behavior

CSS classes are removed with the has link. Works fine for HTTP links or without `href` attribute.

### Runtime

Node v16

### Package manager

npm v8

### OS

macOS

**Comment by wooorm** [comment]
This project does not remove classes. If that’s the case, it’s Storybook.
But, you probably have your own custom component for `a`, and your custom component does not pass those classes through.
