### ISSUE TITLE
react/jsx-runtime.js is no longer available

### ISSUE THREAD

**Issue by hahnbeelee** [mdx-js/mdx#2156]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

https://mdxjs.com/guides/mdx-on-demand/

### Link to runnable example

https://github.com/mintlify/mint/blob/a4c4c326901c29adda9788b569df44502cf94d1d/client/src/pages/_sites/%5Bsite%5D/%5B%5B...slug%5D%5D.tsx

### Steps to reproduce

1. `cd client`
2. `yarn dev`

### Expected behavior

I expect run & compile to work.

### Actual behavior

There are a couple places in the docs that use:
```js
import * as runtime from 'react/jsx-runtime.js'
```

However, when I try to replicate the code, I get the following error:
```
Error: Package subpath './jsx-runtime.js' is not defined by "exports" in /path/node_modules/react/package.json
```
I'm using React v^18.2.0 and I can't downgrade my React version. Is there something else I can provide as the second argument of `run` to get it to work? I see the [run API documentation](https://mdxjs.com/packages/mdx/#runfunctionbody-options) says I can provide "jsx, jsxs, and Fragment from an automatic JSX runtime as options", but I have no idea what that means. Do I provide a string(e.g. 'jsx')? Do I import something? I upload this as an issue because I think the docs need improvement and if anyone can show me the light, I'd be more than willing to make a PR fixing it as well :)

### Runtime

Node v17

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
Hey!

Remove the `.js` in newer React and it should work!

Feel free to create a PR that removes it. Or adds a note!

**Comment by hahnbeelee** [comment]
@wooorm Thank you! Can you shine light on the [run API documentation](https://mdxjs.com/packages/mdx/#options-1) that says:
> You can pass jsx, jsxs, and Fragment from an automatic JSX runtime as options.

**Comment by hahnbeelee** [comment]
It seems to be updated in [the code](https://github.com/mdx-js/mdx/blob/main/docs/guides/mdx-on-demand.server.mdx)! It just hasn't been updated at mdxjs.com/
