### ISSUE TITLE
remark-mdx esm nodes not being detected

### ISSUE THREAD

**Issue by hahnbeelee** [mdx-js/mdx#2161]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

```js
import { remark } from "remark";
import remarkMdx from "remark-mdx";
import type { Root } from "mdast";
import { remove } from "unist-util-remove";

const removeImports = () => {
  return (tree: Root) => {
    remove(tree, (node) => {
      return (
        node.type === "mdxjsEsm" &&
        node?.value &&
        node?.value.startsWith("import")
      );
    });
    return tree;
  };
};

export const preParseMdx = async (content: string): Promise<string> => {
  const file = await remark()
    .use(remarkMdx)
    .use(removeImports)
    .process(content);
  return String(file);
};

  const content = `
  import test1 from 'test1'
  import test2 from 'test2'


  import test3 from 'test3'


  TEXT POST IMPORTS!!!!!!!!
  `;
await preParseMdx(content);
```

### Expected behavior

Due to the custom plugin imports should be removed after running the above code. This made me suspect that the esm nodes are not being detected properly, but inside the remark-mdx package readme it says that it is.

### Actual behavior

The import statements aren't being detected and are labeled as `type: "text"` and not `type: "mdxjsEsm"`

### Runtime

Node v17

### Package manager

npm v8

### OS

macOS

**Comment by ChristianMurphy** [comment]
Sorry you ran into a spot of trouble @hahnbeelee.
Trying out your example in a sandbox, it appears to work as-is https://codesandbox.io/s/remove-imports-cide41

I suspect it may be related to incompatible versions of dependencies installed on your machine, try out the versions from the sandbox:
* `remark` 14.0.2
* `remark-mdx` 2.1.5
* `unist-util-remove` 3.1.0

I'm going to close this, as there doesn't appear to be a bug in MDX.
Happy to continue the conversation here or in https://github.com/mdx-js/mdx/discussions if you have follow up questions or concerns.

**Comment by hahnbeelee** [comment]
Thanks for the prompt reply. It's weird it isn't working for me although I have the same versions.

**Comment by ChristianMurphy** [comment]
Strange indeed.
https://mdxjs.com/community/support/ offers some ideas.
In particular creating a sandbox with a runnable example of the issue you are seeing may help folks offer more concrete suggestions.

**Comment by wooorm** [comment]
You're using a template string. With indentation. That indentation is part of the markdown.
Import/export must start at the start of a line.
Put content in an actual file and it'll be more clear.
I think that's it.

**Comment by hahnbeelee** [comment]
@wooorm Thanks for the insight Titus. This was 100% what was going on.

**Comment by hahnbeelee** [comment]
@ChristianMurphy I'll make sure to make a code sandbox when and if I have another issue.
