### ISSUE TITLE
nested lists break the parser

### ISSUE THREAD

**Issue by veesahni** [mdx-js/mdx#2172]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/mdx 2.1.5

### Steps to reproduce

Paste the following into the MDX Playground

```html
<ul>
  <li>Test</li>
  <li>Sub list here:
    <ul>
      <li>line1</li>
      <li>line2</li>
    </ul>
  </li>
</ul>
```

### Expected behavior

Should render instead of error.

### Actual behavior

Causes the following error:

`Expected a closing tag for <li>(3:3-3:7) before the end of paragraph end-tag-mismatch  mdast-util-mdx-jsx`

### Discussion

As a workaround, the following renders fine:

```html
<ul>
  <li>Test</li>
  <li>Sub list here:</li>
  <ul>
    <li>line1</li>
    <li>line2</li>
  </ul>
</ul>
```

... however, my understanding is that this the output this generates is not actually valid HTML.  [See discussion here](https://stackoverflow.com/questions/5899337/proper-way-to-make-html-nested-list): `<ul>` should contain only zero or more `<li>`

### Runtime

Node v18

### Package manager

npm v8

### OS

Linux

### Build and bundle tools

Rollup

**Comment by ChristianMurphy** [comment]
Please see the guide on MDX syntax https://mdxjs.com/docs/what-is-mdx/#jsx
A JSX block can either be inline or block, in your example line 3 is inline, but you want it to be a block.
To do so use:

```jsx
<ul>
  <li>Test</li>
  <li>
    Sub list here:
    <ul>
      <li>line1</li>
      <li>line2</li>
    </ul>
  </li>
</ul>
```
