### ISSUE TITLE
Automatic development mode in Webpack loader

### ISSUE THREAD

**Issue by remcohaszing** [mdx-js/mdx#2198]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Webpack supports a [`mode`](https://webpack.js.org/configuration/mode/) setting, which can be set to `production`, `development`, or `none`. MDX supports a boolean `development`, but does not use webpack’s `mode`.

It would make sense to set the MDX `development` option based on Webpack’s `mode`.

### Solution

Default the MDX `development` option to Webpack’s `mode === 'development'`. If `development` is specified explicitly in the loader options, that should take precedence.

### Alternatives

We could also use `mode !== 'production'`, which would change the behaviour of the `'none'` mode, but I think it’s best if `'none'` would use the default value provided by `@mdx-js/mdx`.

**Comment by wooorm** [comment]
yep, sounds good
