### ISSUE TITLE
mdx-js/loader v1 contains critical security vulnerability from loader-utils@2.0.0 dependency

### ISSUE THREAD

**Issue by Hotell** [mdx-js/mdx#2200]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/loader 1.6.22

### Steps to reproduce

https://github.com/microsoft/fluentui/issues/26095

### Expected behavior

release hotfix of mdx-js/loader@1 which uses `~` or `^` for loader-utils, so users on v1 are able to mitigate any security risks

```diff
 "dependencies": {
    "@mdx-js/mdx": "1.6.22",
    "@mdx-js/react": "1.6.22",
-    "loader-utils": "2.0.0"
+    "loader-utils": "~2.0.3"
  },
```

### Actual behavior

loader v1 uses strict versioning for `loader-utils` package that contains critical security vulnerability

### Runtime

Node v14

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

webpack

**Comment by wooorm** [comment]
Duplicate, see https://github.com/mdx-js/mdx/pull/2169#issuecomment-1321283767
