### ISSUE TITLE
When Text Nodes are used on the same line as a closing tag, it crashes MDX

### ISSUE THREAD

**Issue by Ayc0** [mdx-js/mdx#2212]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/mdx 2.2.1

### Steps to reproduce

Go to https://mdxjs.com/playground/, and write this:

```mdx
<div>
asd
</div>.
```

### Expected behavior

As all of:
- ```mdx
  <div>
  asd
  </div>
  .
  ```
- ```mdx
  <div>asd</div>.
  ```
- ```mdx
  <div>asd
  </div>.
  ```

work, and as they should create the same AST, I'd expect that the input code would work too.

### Actual behavior

```mdx
<div>
asd
</div>.
```

This code throws:

```
example.mdx
  3:1-3:7  error  Expected the closing tag `</div>` either after the end of `paragraph` (3:8) or another opening tag after the start of `paragraph` (2:1)  end-tag-mismatch  mdast-util-mdx-jsx

✖ 1 error
```

Note: the following crashes too:

```mdx
<div>
asd
</div>.
```

### Runtime

Node v16, but also just Chrome as the bug is visible in the live playground.

### Package manager

As it's visible in the live playground, I don't think it's relevant.

### OS

macOS

### Build and bundle tools

As it's visible in the live playground, I don't think it's relevant.

**Comment by wooorm** [comment]
Yes. This is expected. It is ambiguous what you want to happen. The error message tells you what to do. You need to be explicit. If you want the text inside the `div` to be a paragraph:

```
<div>
  asd.
</div>
```

If you don’t:

```
<div>asd</div>.
```

**Comment by Ayc0** [comment]
Sometimes (and specially due to prettier), we don't really have the choice though 😕 
Like if we want to do:

```mdx
<div><p>This is some fake text, it's too long on purpose <a href="/really/really/really/really/really/really/really/long/link">here</a> and here is the end of the text.</p></div>
```

This compiles properly:

<img width="994" alt="image" src="https://user-images.githubusercontent.com/22725671/210642778-72afb0ea-1825-4bbc-a806-273dbff2b83a.png">


But when we run this through prettier, it generates:

```mdx
<div>
  <p>
    This is some fake text, it's too long on purpose{" "}
    <a href="/really/really/really/really/really/really/really/long/link">
      here
    </a>{" "}
    and here is the end of the text.
  </p>
</div>
```

[See playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D5UAOuAKgBaYDOABJVRRALZxUBmAhgNbPwAeMANDRgByajAgQqAG2gBzKtCoEArgCcCECs1RsqpVXBYBeADogA9AbZSpAT0txrdh0-tWbbxx5ff3zmVCy5lKYUBxmuKRwBqjmbLhUbFDoetHMtDBRVAgpECxUmdxwfAB0sUSxWHgg-CAQBDCY0BTIoGyqqhAA7gAK7QgtKNZdbLYttQBGqmxgXDAAymxMADKhcMjsUlqT07NwCwQzobLIMKrKcLVwDBNw6Oh3y0myymyycABiEKoMbDCNgWQIDYynENRApBgDCkAHVyPAKIcwHB5gNMI1sOjbECwBRxiBQlpVDAetNZL8NtZtiAAFYUHjzY5SOAARWUEHglK2lxAh1URKBDHQPHBBFUoRgMMw6EyyAAHAAGWpizRwGHTAhAsVwInYda1ACO7PgpPqg2BFAAtFA4Hc7uCDEbMAZSW8KUhNtStAxMKdzjyKEzWcb1h6qTyYGwJlKZaRkAAmWpnNiYEKBADCjHdIB1AFZwcotMQo4NPTzsBcAJLJBALMDihoAQWS8xgtmZXK0AF8u0A)

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/22725671/210642595-0e754688-d68d-4e7a-8298-9b8caeaa5a36.png">


But this newly formatted text doesn't work anymore in MDX:
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/22725671/210642883-5366e6c2-fd8a-48f0-b91c-4a5321476896.png">

**Comment by ChristianMurphy** [comment]
Prettier is still catching up with MDX 2, see https://github.com/prettier/prettier/issues/12209 for the ongoing discussion and progress

**Comment by Ayc0** [comment]
> Prettier is still catching up with MDX 2, see [prettier/prettier#12209](https://github.com/prettier/prettier/issues/12209) for the ongoing discussion and progress

I cross posted the issue in this other thread 🙇
