### ISSUE TITLE
Mapping for lowercased tags doesn't work

### ISSUE THREAD

**Issue by amodes** [mdx-js/mdx#2215]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

^2.0.0

### Steps to reproduce

I want to apply custom styles for anchor tags.
In my `.mdx` files I use the anchors like this:

```js
<a href={props.EXTERNAL_LINK} target="_blank" rel="noreferrer">{props.EXTERNAL_LINK}</a>
```
My mapping looks like this:
```js
import { MDXProvider } from '@mdx-js/react'
import ReactDOMServer from 'react-dom/server'

const bodyHtml = ReactDOMServer.renderToStaticMarkup(
  <MDXProvider components={{
    a: (props) => <a style={{ fontSize: 21, color: '#9F2B68', fontFamily: 'arial, helvetica, sans-serif' }} {...props} />,
  }}>
    <TemplateComponent  />
  </MDXProvider>)
```  

My `webpack.config.js`

```js
{
   loader: '@mdx-js/loader',
   options: {
      providerImportSource: '@mdx-js/react',
      remarkPlugins: [remarkGfm],
     },
},
```

`package.json`

```
"@mdx-js/loader": "^2.0.0",
"@mdx-js/mdx": "^2.0.0",
"@mdx-js/react": "^2.0.0",
```

### Expected behavior

Checking the docs example of
https://mdxjs.com/table-of-components/

the styles defined in the mapping should get applied to the anchor tag.

### Actual behavior

The styles defined in the mapping are just completely ignored and the output doesn't contain the styles of the mapping. 
Same when I try to map other html tags like `h1` or `p`.

If I change the mapping to uppercased components like this

```js
<A href={props.EXTERNAL_LINK} target="_blank" rel="noreferrer">{props.EXTERNAL_LINK}</A>
```
```js
import { MDXProvider } from '@mdx-js/react'
import ReactDOMServer from 'react-dom/server'

const bodyHtml = ReactDOMServer.renderToStaticMarkup(
  <MDXProvider components={{
    A: (props) => <a style={{ fontSize: 21, color: '#9F2B68', fontFamily: 'arial, helvetica, sans-serif' }} {...props} />,
  }}>
    <TemplateComponent  />
  </MDXProvider>)
```  

everything works as expected. (It again doesn't if I use lowercased non-html native tags)

I thinks this is no expected behaviour and seems like a bug. But if it is expected it would be cool to write it down somewhere in the docs.

### Runtime

Node v16

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

webpack

**Comment by wooorm** [comment]
a) you probably don’t need a provider, that makes your code slower and includes code you likely don’t need. See https://mdxjs.com/docs/using-mdx/#using-mdx.
b) this behavior is expected. You can pass “lowercase” components to replace things you write in markdown (in this case, `[whatever](https://the.url.com)`, uses the `a` component you pass). If you use JSX syntax, the same rules as JSX in react or so apply: `x` is a literal tag name, `X` is a component. That is to say, in JSX, you have to adhere to how JSX works in other places:

```mdx
[xxx](yyy)

<Link target="_blank" rel="noreferrer">zzz</Link>
```

```js
const Link = (props) => <a style={{ fontSize: 21, color: '#9F2B68', fontFamily: 'arial, helvetica, sans-serif' }}

<TemplateComponent
  components={{
    a: Link, // This gets used for markdown things
    Link // This is a component you can use
  }}
/>
```

**Comment by amodes** [comment]
Thanks @wooorm, took me a while to understand that.
So in the mdx instead of
```js
<a href={props.EXTERNAL_LINK} target="_blank" rel="noreferrer">{props.EXTERNAL_LINK}</a>
```
I have to use
```js
[{props.TOKEN_LINK}]({props.TOKEN_LINK})
```

**Comment by wooorm** [comment]
Not really, that doesn’t work. The first part (`[{props.TOKEN_LINK}]`) is fine. As we support expressions in markdown in all the places where you could also make things emphasis for example. But we don’t support the second part. It’s not a templating language. Emphasis doesn’t work there either, so we don’t allow expressions there.

Your specific case can be solved with JSX, and an actual component:

```mdx
<Link href={props.EXTERNAL_LINK} target="_blank" rel="noreferrer">{props.EXTERNAL_LINK}</Link>
```
