### ISSUE TITLE
remark-mdx plugin does not support import alias - throw Errors.

### ISSUE THREAD

**Issue by SagaGG** [mdx-js/mdx#2216]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-mdx ^2.2.1

### Steps to reproduce

I got the error below when I use the import alias.

My example code:
```
import { remark } from "remark";
import remarkMdx from "remark-mdx";

const outputStream = remark().use(remarkMdx) processSync(`
    import { Test as AliasTest } from "my-package"
`)
```

remove alias "as" it works fine.

### Expected behavior

I should get the return stream without any error

### Actual behavior

Error throw out
```
node:internal/process/promises:289
│             triggerUncaughtException(err, true /* fromPromise */);
│             ^
│ [7:26: Could not parse expression with acorn: Unexpected content after expression] {
│   reason: 'Could not parse expression with acorn: Unexpected content after expression',
│   line: 7,
│   column: 26,
│   position: {
│     start: { line: 7, column: 26, offset: 211 },
│     end: { line: null, column: null }
│   },
│   source: 'micromark-extension-mdx-expression',
│   ruleId: 'acorn'
│ }
│ Node.js v19.0.1
```

### Runtime

Other (please specify in steps to reproduce)

### Package manager

npm v8

### OS

macOS

### Build and bundle tools

esbuild, Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
Exports/imports must start on the first column. You use an indented string. Don’t:

```js
const outputStream = remark().use(remarkMdx) processSync(`
import { Test as AliasTest } from "my-package"
`)
```

**Comment by SagaGG** [comment]
@wooorm  thanks, it's working now.
