### ISSUE TITLE
inline image tags not rendered

### ISSUE THREAD

**Issue by geddski** [mdx-js/mdx#222]
images inside of markdown text is rendered as text instead of as an image. 

```md
The terrain <img src="/img/terrains/grass.jpg" width="24" style={{margin: "0 !important", display: "inline-block !important"}} alt="css grid item" /> items we'll use are stacked to the left of the shuttle to show their order in the DOM.
```

should be rendered as:
![image](https://user-images.githubusercontent.com/515722/44061545-0da3a8ac-9f16-11e8-95a5-3d2c4e65e144.png)

but instead is just text:
![image](https://user-images.githubusercontent.com/515722/44061540-0726e6ba-9f16-11e8-97e3-262ab202c8e8.png)

**Comment by geddski** [comment]
As a workaround for anyone else who needs this: just use a `span` instead of an `img` and then style that span with a background image.

Closing this issue since there's a workaround.

**Comment by timneutkens** [comment]
Seems like something that should work 🤔

**Comment by silvenon** [comment]
Yeah, inline JSX doesn't seem to work. The original example doesn't work because `style={{ }}` is not valid HTML (it's JSX), so remark interprets the whole element as a string. Using a string instead of an object for `style` will work.

**Comment by jamesknelson** [comment]
This is also not being parsed properly. There's a workaround where you can import the image at the top of the file and add that, but it's not ideal.

```md
<a href={require('./async-cheatsheet.png')}>
<img alt="Asynchronous JavaScript Cheatsheet" src={require('./async-cheatsheet.png')} />
</a>
```

Any idea how I'd go about fixing this? I'm moving all my markdown from MDXC to MDX, and this is the one thing that seems not to work.

**Comment by silvenon** [comment]
I'm not sure what causes this, but a workaround that might work is creating a custom component that simply renders 'a':

```js
// Link.js
export default 'a'
```
```
import Link from './Link'

<Link href={require('./async-cheatsheet.png')}>
<img alt="Asynchronous JavaScript Cheatsheet" src={require('./async-cheatsheet.png')} />
</Link>
```

The parser treats `<a>` elements differently (for example `<div>` works) probably because links are special in Markdown.

**Comment by jamesknelson** [comment]
Neat, that works. Thanks!

**Comment by johno** [comment]
The image tag isn't working because of the curly braces. This will be fixed when `remark-mdx` is finalized and then used in core. You can follow along with #196 to track progress. Thanks for opening up an issue!
