### ISSUE TITLE
npx init?

### ISSUE THREAD

**Issue by isthisnagee** [mdx-js/mdx#223]
Hi there!

The readme says to run `npx init mdx`. I'm not sure if I'm missing some prereqs or not, but that didn't work for me (got `npx: command not found: init`). `npm init mdx` did work though.

Here's the line:

https://github.com/mdx-js/mdx/blob/cafd5766b8263fcfa6c6c9d497b1c5014f1ba8fd/readme.md#L63

I'll submit a PR if it's a typo, and if it isn't and there's some prereqs involved, I don't mind submitting a pull request explaining what's needed.

Edit: Oh I guess it should be `npx create-mdx` or `yarn create mdx`?

**Comment by johno** [comment]
Whoops, that's a typo, nice catch. It should read `npm init mdx`. Will gladly accept a PR if you'd like to make one. Thanks!

**Comment by isthisnagee** [comment]
sure :)

**Comment by baurine** [comment]
really? for me, the `npm init mdx` command just create an initial package.json.

```
> npm init mdx
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (try-mdx)
version: (1.0.0)
description:
git repository:
keywords:
author:
license: (ISC)
About to write to /Users/sparkhuang/Codes/Personal/try-mdx/package.json:

{
  "name": "try-mdx",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}


Is this ok? (yes)

> ls
package.json

> cat package.json
{
  "name": "try-mdx",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}
```

did I miss something?

my node is 8.11 and npm is 5.6

**Comment by johno** [comment]
`npm init` requires npm v6+. We'll be updating the docs over the holidays to make the `npm init` flow less front and center since it can be a source of confusion.

**Comment by baurine** [comment]
got it now, thank you @johno !
