### ISSUE TITLE
Support async components

### ISSUE THREAD

**Issue by remcohaszing** [mdx-js/mdx#2242]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

React server components can be asynchronous. It would be nice if MDX content supports this too.

```mdx
# Hello visitor

This page has been visited {await Promise.resolve(42)} times
```

### Solution

If an `await` expression is detected, mark `_createMdxContent` as async.

### Alternatives

We could not support it :shrug:

**Comment by wooorm** [comment]
- As I understand it, that’s not RSC. That’s specifically the server part of RSC (in Next.js?)
- As I understand it, they’re not stable yet: https://github.com/reactjs/rfcs/pull/229
- I’m quite wary about changing return types like this, magically, based on content. Should probably be an experimental flag for people to opt in and try this if they want. Similar to `useDynamicImport`, `allowDangerousRemoteMdx`

**Comment by wooorm** [comment]
@remcohaszing I think there are too many ifs currently, this isn’t actionable until React (and others!) solve their promise story. We can discuss again in the future. Can I close this?

**Comment by remcohaszing** [comment]
Maybe I mixed up some terminology and supporting async components isn't the same as supporting RSC. But from the perspective of MDX this is about supporting async components.

Next.js supports already async components in `app/page.tsx`, so why support not `await` in `app/page.mdx`?

Also the related TypeScript issue has been resolved.

I'd say we can wait for user feedback to see if users actually want to use this. Based on the fact there are already some 👍 reactions, I think they do.

**Comment by wooorm** [comment]
We don’t just support Next, or React, but any arbitrary runtime.
Supporting await is one thing, we can detect that syntacticly (although we’d need to first parse as if that could happen). But components returning promises is something that can only be done at runtime?

**Comment by remcohaszing** [comment]
> We don’t just support Next, or React, but any arbitrary runtime.

I think this proves my point. We support any arbritrary runtime. This runtime may support async function components. Why should MDX not support that?

Also to clarify, my proposal is to **only** make the component async if the body contains `await` expressions. It’s about supporting `await`, not making everything `async`. This is statically analyzable and doesn’t require any detection at runtime.

**Comment by wooorm** [comment]
But nobody supports it yet? It doesn’t seem like a great idea to design things that can’t be tested.

> It’s about supporting await, not making everything async.

How are they not related? We already parse `await`. It would make `_createMdxContent` and `MDXContent` async and it would mean users need to await it?

**Comment by remcohaszing** [comment]
> But nobody supports it yet?

Next.js does. For example see https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#fetching-data-on-the-server-with-fetch

It would make `_createdMdxContent` async if and only if an `await` expression is used.

`MDXContent` would return a promise if `_createdMdxContent` is async and no `MDXLayout` is used.

[`MDXContent`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mdx/types.d.ts#L96) is currently typed as a function that returns a JSX element. That would no longer hold true. It would need to be changed to a `FunctionComponent`.

```diff
- export type MDXContent = (props: MDXProps) => JSX.Element;
+ export type MDXContent = FunctionComponent<MDXProps>;
```

**Comment by wooorm** [comment]
> Next.js does

I don’t classify that as the “yet” part. They support RSC. The RFC isn’t merged, see first comment here: https://github.com/mdx-js/mdx/issues/2242#issuecomment-1412144276.

> and no MDXLayout is used.

And what if a layout is used?

> It would need to be changed to a FunctionComponent.

And what if someone is using Preact or Vue or anything other than Next? The types wouldn’t match reality. They could get `Promise<JSX.Element>` as a return type even though their types say they can’t.

**Comment by remcohaszing** [comment]
> And what if a layout is used?

Then `_createMdxContent` is passed as a JSX component, and `MDXContent` returns synchronously.

> And what if someone is using Preact or Vue or anything other than Next? The types wouldn’t match reality. They could get `Promise<JSX.Element>` as a return type even though their types say they can’t.

The return type of MDX’s `FunctionComponent` is adjusted to the framework via the global `JSX` namespace. If someone uses Preact, they get the Preact types. If someone uses Vue, they get the Vue types.

**Comment by wooorm** [comment]
```patch
+++ b/packages/mdx/lib/plugin/recma-document.js
@@ -602,9 +602,23 @@ export function recmaDocument(options) {
       argument = argument.children[0]
     }
 
+    let awaitExpression = false
+
+    walk(argument, {
+      enter(node) {
+        if (
+          node.type === 'AwaitExpression' ||
+          (node.type === 'ForOfStatement' && node.await)
+        ) {
+          awaitExpression = true
+        }
+      }
+    })
+
     return [
       {
         type: 'FunctionDeclaration',
+        async: awaitExpression,
         id: {type: 'Identifier', name: '_createMdxContent'},
         params: [{type: 'Identifier', name: 'props'}],
         body: {
```

`example.js`

```js
import fs from 'node:fs/promises'
import {compile} from '@mdx-js/mdx'
import {createElement} from 'react'
import {renderToString} from 'react-dom/server'

const document = `{await Promise.resolve(42)}`

const result = String(await compile(document))

await fs.writeFile('output.js', result)

console.log('code:', result)

const id = './output.js#' + Date.now()
/** @type {import('mdx/types.js').MDXModule} */
const mod = await import(id)
const Content = mod.default

console.log('Content:', Content)

const output = renderToString(createElement(Content))

console.log('output:', output)
```

Yields:

```
$ node example.js 
code: /*@jsxRuntime automatic @jsxImportSource react*/
import {Fragment as _Fragment, jsx as _jsx} from "react/jsx-runtime";
async function _createMdxContent(props) {
  return _jsx(_Fragment, {
    children: await Promise.resolve(42)
  });
}
function MDXContent(props = {}) {
  const {wrapper: MDXLayout} = props.components || ({});
  return MDXLayout ? _jsx(MDXLayout, {
    ...props,
    children: _jsx(_createMdxContent, {
      ...props
    })
  }) : _createMdxContent(props);
}
export default MDXContent;

Content: [Function: MDXContent]
/Users/tilde/Projects/oss/mdx/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6183
    throw new Error("Objects are not valid as a React child (found: " + (childString === '[object Object]' ? 'object with keys {' + Object.keys(node).join(', ') + '}' : childString) + "). " + 'If you meant to render a collection of children, use an array ' + 'instead.');
          ^

Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.
    at renderNodeDestructiveImpl (/Users/tilde/Projects/oss/mdx/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6183:11)
    at renderNodeDestructive (/Users/tilde/Projects/oss/mdx/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderIndeterminateComponent (/Users/tilde/Projects/oss/mdx/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5789:7)
    at renderElement (/Users/tilde/Projects/oss/mdx/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5950:7)
    at renderNodeDestructiveImpl (/Users/tilde/Projects/oss/mdx/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/Users/tilde/Projects/oss/mdx/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at retryTask (/Users/tilde/Projects/oss/mdx/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6532:5)
    at performWork (/Users/tilde/Projects/oss/mdx/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6580:7)
    at /Users/tilde/Projects/oss/mdx/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6904:12
    at scheduleWork (/Users/tilde/Projects/oss/mdx/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:78:3)

Node.js v20.8.1
```

Interesting. All tests pass too. But eh. Useless? And no type errors?

**Comment by remcohaszing** [comment]
Yes, we’d need to check for `AwaitExpression`s within the body of `_createMdxContent`.

```js
function _createMdxContent() {
  await 1 // ← top-level

  if (await 1) { // if-statement
    await 1
  }

  while (await 1) { // loop
    await 1
  }

  const foo = {
    bar: await 1 // nested property
  }

  foo(await 1) // as argument

  async function foo() {
    await 1 // Inside an embedded function doesn’t count.
  }
}
```

This is doable, but it does look a bit more involved than I initially anticipated.

**Comment by wooorm** [comment]
Why? I posted working code above!

**Comment by remcohaszing** [comment]
> Why? I posted working code above!

While I was fiddling.

I think your code works, but needs to stop traversion on a function expression, function declaration, or arrow function.

**Comment by wooorm** [comment]
Ah, it should also check async functions!

**Comment by wooorm** [comment]
wait no, it should indeed skip, and not *use* `async` on functions as if an await was found. Lol

**Comment by remcohaszing** [comment]
I thought maybe async components only work with streams, since you can’t go from an async function to a synchronous `renderToString`. But that doesn’t seem to work either.

```js
import fs from 'node:fs/promises'
import {compile} from '@mdx-js/mdx'
import {createElement} from 'react'
import server from 'react-dom/server'

const document = `{await Promise.resolve(42)}`

const result = String(await compile(document))

await fs.writeFile('output.js', result)

console.log('code:', result)

const id = './output.js#' + Date.now()
/** @type {import('mdx/types.js').MDXModule} */
const mod = await import(id)
const Content = mod.default

console.log('Content:', Content)

console.dir(server)

server.renderToPipeableStream(createElement(Content)).pipe(process.stdout)
```

**Comment by remcohaszing** [comment]
Note that the change turns what would now emit a syntax error to support for a new feature without breaking changes. This could be done later in a semver minor.

**Comment by wooorm** [comment]
Not sure about the types in `mdx/types.js` btw!

**Comment by remcohaszing** [comment]
We could either leave it as-is, or make the changes I proposed in https://github.com/mdx-js/mdx/issues/2242#issuecomment-1770926859.

For now I think it's best to keep the types as-is for compatibility with TypeScript 5.0 and lower.

**Comment by wooorm** [comment]
fine!

**Comment by albertkimjunior** [comment]
Hey @remcohaszing and @wooorm, I noticed that await is now supported in MDX on the updates page, and when digging around a bit came across this Github thread. I was just a bit confused on how this might work with making POST requests in a .js script in order to dynamically update a markdown component with new information.

It may also be entirely unrelated to MDX support specifically and how we're compiling it with Mintlify, just as an additional context to mention.

The .js file is located in our snippets folder in the same directory as mint.json and contains this code:
`import React, { useEffect, useState } from 'react';

const GithubStars = () => {
  const [stars, setStars] = useState(null);

  useEffect(() => {
    async function fetchStars() {
      const response = await fetch('https://api.github.com/repos/AgentOps-AI/agentops');
      const data = await response.json();
      const stars = Math.ceil(data.stargazers_count / 1000) * 1000;
      setStars(stars.toLocaleString());
    }
    fetchStars();
  }, []);

  return <p>{stars ? `${stars}th` : '2,000th'}</p>;
}

export default GithubStars
`

Which we then try to reference in the MDX file like so:
`import GithubStars from '/snippets/github-stars'

<Check>Check out our Github – you might be our <Github Stars /> star!</Check>`

Is there a different way that is expected to support await statements to accomplish what we're looking to do?

**Comment by wooorm** [comment]
Your problem has, I believe, nothing to do with MDX, which is mostly a language.
This pr was about doing what was expected for the "async" keyword, from a lang perspective.
But actually supporting that, and all other async stuff, has more to do with your framework!
