### ISSUE TITLE
`@mdx-js/loader`: Consider accepting strings for package names in addition to loaded modules

### ISSUE THREAD

**Issue by wbinnssmith** [mdx-js/mdx#2246]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

One of the current limitations with Turbopack’s webpack loader support [0] is that we can only accept serializable JS primitives, arrays, and objects as options. Because of this, it's not currently possible to pass any loaded remark or rehype plugins to the `@mdx-js/loader`.

### Solution

Instead, `@mdx-js/loader` could also accept specifier strings in place of loaded modules for things like remark and rehype plugins. e.g. for

```
const rehypeKatex = require('rehype-katex');

// ... webpack configuration
{
  loader: '@mdx-js/loader',
  options: {
    rehypePlugins: [rehypeKatex],
  }
}
```

..it could also accept:
```
// ... webpack configuration
{
  loader: '@mdx-js/loader',
  options: {
    rehypePlugins: ['rehype-kate'],
  }
}
```

The loader itself could then load those modules and pass them along to the compiler.

[0] https://github.com/vercel/turbo/blob/6cbb83526da9aa5c10982ecec87b32c77fcd620b/docs/pages/pack/docs/migrating-from-webpack.mdx#webpack-loaders-for-nextjs

### Alternatives

Alternatively, the compiler could also accept specifiers and load the modules itself.

**Comment by wooorm** [comment]
Hi!

a) will that limitation in turbopack be lifted?
b) where should things be loaded from? An author can do things relative to the file (they have access to `import.meta.url`, and `import` will resolve from the file), a loader can’t (it’s somewhere in node modules, which could be anywhere, it only has access to `process.cwd`, which in my experience with these things is going to result in unexpected results)
c) why is there such a limitation in turbopack, if this is a JavaScript file? Why not use a JSON file instead?

**Comment by wbinnssmith** [comment]
Yes, we'd like to get rid of this limitation at some point. I definitely understand your concerns. We can close this out for now and revisit if necessary when things are further along with our implementation. Thanks!

**Comment by wooorm** [comment]
Sounds like a plan! I am not totally opposed to this, but I think it’ll be rather complex. So if this can be solved later on your end while the project matures, that sounds good to me!
