### ISSUE TITLE
remark-mdx crashes on "<"

### ISSUE THREAD

**Issue by creativiii** [mdx-js/mdx#2264]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-mdx@2.3.0

### Link to runnable example

https://codesandbox.io/s/remark-mdx-issue-196smb?file=/src/index.js

### Steps to reproduce

I'm trying to parse MDX from an editor, but I've encountered an issue whenever I try to type the character "<". The MDX parser thinks it's the start of a component and crashes the entire thing.

- Try to parse a string that ends in "<"
- Parsing fails with:
```
Unexpected end of file before name, expected a character that can start a name, such as a letter, `$`, or `_`
```

### Expected behavior

I think the "<" should ideally be escaped like what happens when it's not placed at the end of the file:
```
1 < 2 -> 1 /< 2
```

### Actual behavior

The parser throws an error and crashes.

### Runtime

Node v16

### Package manager

yarn v3

### OS

macOS

### Build and bundle tools

webpack

**Comment by wooorm** [comment]
This is very much intentional.
Have you tried typing a < somewhere in a javascript file? It crashes. Why should mdx behave differently?

**Comment by wooorm** [comment]
The advise is explained in the article on [“What is MDX?”](https://mdxjs.com/docs/what-is-mdx/#mdx-syntax) and [Troubleshooting](https://mdxjs.com/docs/troubleshooting-mdx/#problems-writing-mdx). Write MDX, which means in this case: handle `<`. By escaping it: `\<`.
