### ISSUE TITLE
Packages names in MDX file with versions converted to mailto link (i.e. @mdx-js/mdx@1.6.21)

### ISSUE THREAD

**Issue by dnim** [mdx-js/mdx#2283]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.6.21

### Steps to reproduce

* go to https://www.mdxjs.cn/playground/
* enter `@mdx-js/mdx@1.6.21` 
* the `mdx@1.6.21` will be converted to `emailto` link

<img width="855" alt="Screenshot 2023-04-05 at 09 47 17" src="https://user-images.githubusercontent.com/1839962/230016379-51434aa0-1a8b-4017-b169-6b5a75904970.png">

### Expected behavior

* no conversion is happened (as in the new 2nd MDX version)

### Actual behavior

* pattern as `mdx@1.6.21` has no emailto conversion

### Runtime

Node v18, Node v16

### Package manager

npm v8, npm v6

### OS

macOS

### Build and bundle tools

webpack

**Comment by wooorm** [comment]
Hi! MDX 0 and 1 have bugs and are unmaintained. Use MDX 2

**Comment by dnim** [comment]
> Hi! MDX 0 and 1 have bugs and are unmaintained. Use MDX 2. Or use `` `code` ``

Hi! Thanks for the super fast reply. Thanks for good advise. Unfortunately we using Docusaurus that using MDX v1 so though maybe it will be possible to provide some fix :)

**Comment by ChristianMurphy** [comment]
Docusaurus can leverage MDX 2.
As of today you can use https://github.com/pomber/docusaurus-mdx-2
Or you can help with https://github.com/facebook/docusaurus/issues/4029
