### ISSUE TITLE
Invalid option in element 0 of "warnings": "id"

### ISSUE THREAD

**Issue by cangSDARM** [mdx-js/mdx#2289]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/esbuild@2.3.0

### Steps to reproduce

This is a transferred issue. the original author of the library suspects that this is a bug in @mdx-js/esbuild, and I'm not really sure.
The problem is that it's preventing my mdx file from building, but I don't know what's happening and I can't deal with the bug.
The title of the issue is what my console prints, and I don't understand what that means.

For more details see the [original issue](https://github.com/contentlayerdev/contentlayer/issues/395) and the [reproduced code](https://codesandbox.io/p/sandbox/elastic-diffie-nth2d5)

### Expected behavior

I don't know exactly what happened, maybe there should be a clearer hint?

### Actual behavior

I dont understand what is "Invalid option in element 0 of 'warnings': 'id'"

### Runtime

Node v18, Node v16, Node v14

### Package manager

npm v9, npm v8

### OS

Windows

### Build and bundle tools

esbuild

**Comment by ChristianMurphy** [comment]
@cangSDARM sorry you ran into a spot of trouble.
Could you create a minimal reproducible example with `@mdx-js/esbuild` showing the issue?
Similar to @schickling's suggestion in the original issue, https://github.com/contentlayerdev/contentlayer/issues/395#issuecomment-1520156274.
The reproduction code you provide does not directly use `@mdx-js/mdx` or `mdx-js/esbuild`.

I'd recommend starting with a sandbox with plain `esbuild` and `@mdx-js/esbuild` then adding on.
For example: https://stackblitz.com/edit/node-qlczlq?file=index.js,package.json (running `npm install` and `npm run build` in the sandbox)
📓 that this sandbox does use your file, and does not have an error. Which indicates this is more likely a configuration error upstream at `contentlayer`.

**Comment by cangSDARM** [comment]
I went back and tried to reproduce it, but now it works fine!
It should be an update from you guys or contentlayerd that fixed the problem.

So I will close this issue
