### ISSUE TITLE
React components inside code

### ISSUE THREAD

**Issue by montogeek** [mdx-js/mdx#230]
Why it isn't possible to do this?
```md

```js

<Component />

```

```

It works if you put it outside of the code:
```md
<Component />
```js
var t = false;
```
```

Where is exactly the limitation, inside remark AST?

**Comment by silvenon** [comment]
It seems like parts of your question is spilling into the code blocks. Fixing the formatting of your question would really help me understand the issue, thanks!

**Comment by ChristopherBiscardi** [comment]
@montogeek you could use [carbon](https://carbon.now.sh/) to generate an image instead of trying to escape the markdown inside of github

**Comment by silvenon** [comment]
It's important to be clear what you mean by "works" and "doesn't work". You still didn't describe your goal. Here's an example:

> I would like to render a Markdown code block which contains raw code for a JavaScript code block containing the code `<Component />` without it being interpreted as JSX.

**Comment by montogeek** [comment]
Sorry for the noise, let me try once again:
I would like to render a React component inside Markdown backticks (code) "```", right now it is not possible, it get interpreted as simple strings instead of JSX.

**Comment by silvenon** [comment]
To me that's expected behavior, everything inside backticks should be escaped, otherwise you wouldn't be able to write code blocks properly. Why would you want this behavior?

**Comment by montogeek** [comment]
A use case, I would like to replace custom code inside backticks with React components.
I need to think in a different approach.

Thanks for answering!

**Comment by timneutkens** [comment]
Sure it's called `code` inlinecode is `inlineCode`

**Comment by gaurav-nelson** [comment]
> 
> 
> It's possible to do this by providing a custom `code` component to MDXProvider.

Thanks for sharing. Is there an example available for such a component?

**Comment by JanCizmar** [comment]
> > It's possible to do this by providing a custom `code` component to MDXProvider.
> 
> @nicknovitski Thanks for sharing. Is there an example available for such a component?

Hi, I needed to provide some value (apiKey) into code snippets generated with MDX, so I did something like this: 
```
 <MDXProvider
                  components={{
                    //providing custom code component
                    code: function Code(props) {
                      return (
                        <Box>
                          <pre>
                            {props.children?.replace(
                              '{{{apiKey}}}', // I am replacing all matching strings in the provided code with the value
                              selectedApiKey || ''
                            )}
                          </pre>
                        </Box>
                      );
                    },
                  }}
                >
                  {React.createElement(myImportedMdxContent)} //here I am rendering my MDX component
</MDXProvider>
```
Hope it helps.
