### ISSUE TITLE
Use spread syntax to create shallow clones

### ISSUE THREAD

**Issue by remcohaszing** [mdx-js/mdx#2310]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

MDX generates JavaScript code that uses shallow copies. The ones I am aware of are defining `_components` and compiling JSX props. E.g.:

```js
const _components = Object.assign(
  {
    p: 'p',
    pre: 'pre',
    code: 'code'
  },
  props.components
)
```

IMO it’s cleaner to use spread syntax for shallow clones. E.g.:

```js
const _components = {
  p: 'p',
  pre: 'pre',
  code: 'code',
  ...props.components
}
```

I have some nitpicky arguments, but mostly I just personally like it better.

1. Spread syntax exists for shallow clones
2. `Object.assign` exists for shallow copying objects from one object to another. It’s still an elegant way to polyfill spread syntax for environments that don’t support it.
3. MDX generates code with uses default a default argument. Support for this is roughly the same as for spread syntax.
4. Spread syntax produces a slightly flatter AST.
5. Terser can minify it better by flattening / inlining / deduping objects.

### Solution

Replace `Object.assign()` with spread syntax.

### Alternatives

Keep using `Object.assign()`.

**Comment by wooorm** [comment]
sure, PR welcome, the idea was to use code that works in most places.
Note that the assign is also used because there are *multiple* possible sources, it’s pretty complex.

**Comment by wooorm** [comment]
Solved in GH-2328.

**Comment by galenditty161** [comment]
@wooorm https://react-navigation-v6.github.io/UCEG4AqsqYLzvdmcGl5BwDWknnjmJ1mQ3CLUsGlMnURxyShH8g/
