### ISSUE TITLE
Website has incorrect statistic: 250% smaller

### ISSUE THREAD

**Issue by erikschul** [mdx-js/mdx#2312]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

https://mdxjs.com/blog/v2/

🚄 Bundle size of @mdx-js/mdx is more than three times as small (250% smaller)

### Expected behavior

example: 100 kb => 25 kB 
that would be a 75% reduction
the size would be 25% of what it used to be

### Actual behavior

incorrect statistic

**Comment by erikschul** [comment]
It sounds as though you think lying is okay, as long as it has utility (marketing).

I disagree. And, I argue that statistics is a science, and misusing that science intentionally is unscrupulous.

Have a nice day.

**Comment by wooorm** [comment]
Yeah, no....
