### ISSUE TITLE
FlowType support

### ISSUE THREAD

**Issue by yury** [mdx-js/mdx#232]
Please add flowtype support.

Statically typed static pages would be awesome

**Comment by timneutkens** [comment]
I'm not entirely sure what the benefit would be, the only thing mdx adds is import/export and usage of components, you're not writing new code, you're writing markdown.

**Comment by timneutkens** [comment]
But isn't it the other way around. Flow would have to support mdx right 🤔

**Comment by yury** [comment]
I think it would work out of the box if mdx will be in right chain of babel :)

**Comment by johno** [comment]
Going to close this in favor of the upstream issue in flow. Thanks for opening!
