### ISSUE TITLE
Can't escape a single quote with \

### ISSUE THREAD

**Issue by NickHeiner** [mdx-js/mdx#2332]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdx-loader@3.0.2, mdx.macro@0.2.9

### Steps to reproduce

https://codesandbox.io/s/mdx-forked-kmcqc5

### Expected behavior

I would have expected that this would have worked to escape a single quote:

```jsx
<FullConversation contents='Today\'s Issue:' />
```

I checked https://mdxjs.com/docs/troubleshooting-mdx/ but didn't find anything about this.

I also tried this, and it also didn't work:

```jsx
<FullConversation contents='Today''s Issue:' />
```

### Actual behavior

I get this error:

```
SyntaxError
unknown: Unterminated string constant (7:43)

   5 |       {...props}
   6 |       components={components}>
>  7 | <FullConversation contents='Today\'s Issue:' />
     |                                            ^
   8 |     </MDXLayout>
   9 |   )
  10 | };
```

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Other (please specify in steps to reproduce)

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by ChristianMurphy** [comment]
Welcome @NickHeiner! 👋 
MDX is JSX in Markdown.
Your example isn't valid JSX

Trying out the same code in Babel as JSX fails: https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=DwMQrgNhDCD2B2A3ApgJwM4EMAuBLBABAMYLbLzboC8A5ACqwAmmAngDo3oECS66YyAFw0CAegB8QA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.22.9&externalPlugins=&assumptions=%7B%7D

Some options which are valid:

```jsx
<FullConversation contents="Today's Issue:" />
```

or

```jsx
<FullConversation contents={'Today\'s Issue:'} />
```

**Comment by NickHeiner** [comment]
Whoops! Thanks.
