### ISSUE TITLE
`hast-util-to-estree` should be bumped to v3 in `@mdx-js/mdx`

### ISSUE THREAD

**Issue by B2o5T** [mdx-js/mdx#2336]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/mdx

### Steps to reproduce

https://github.com/mdx-js/mdx/blob/8a563128a346a637dfe6bc83df55f069947d2337/packages/mdx/package.json#L57
should be bumped to v3

let's set style as string in plugin and provide it in `rehypePlugins`
```js
node.properties.style = 'background-color:#000002; --shiki-dark-bg:#000002; color:#000002; -webkit-transform: rotate(0.01turn); -ms-transform: rotate(0.01turn); --fg: #0366d6; color: var(--fg)'
```

### Expected behavior

with v3
```js
return <_components.h1 style={{
  backgroundColor: "#000002",
  "--shiki-dark-bg": "#000002",
  color: "var(--fg)",
  WebkitTransform: "rotate(0.01turn)",
  msTransform: "rotate(0.01turn)",
  "--fg": "#0366d6"
}}>{"foo"}</_components.h1>;
```

### Actual behavior

with v2
```js
  11 |   return <_components.h1 style={{
  12 |     backgroundColor: "#000002",
  13 |     -ShikiDarkBg: "#000002",
     :     ^
  14 |     color: "var(--fg)",
  15 |     WebkitTransform: "rotate(0.01turn)",
  16 |     msTransform: "rotate(0.01turn)",
     `----
 
   x Expected '}', got ':'
```

**Comment by wooorm** [comment]
That was fixed in https://github.com/syntax-tree/hast-util-to-estree/releases/tag/2.3.2?
I don’t think anything related landed in 3.
Reinstall your dependencies to get bugfixes.

**Comment by B2o5T** [comment]
Why not to pin `^2.3.2` instead of `^2.0.0`?

**Comment by wooorm** [comment]
Because the open source javascript ecosystem is a stack of projects that depend on each other. Semver makes sure that we don‘t need to update this project for you to get fixes: you can get fixes yourself.
