### ISSUE TITLE
Support text folding in playground for ast output editors

### ISSUE THREAD

**Issue by B2o5T** [mdx-js/mdx#2338]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Text folding currently enabled only for raw editor 
<img width="296" alt="image" src="https://github.com/mdx-js/mdx/assets/7361780/50dfbfc2-f2c4-4d5c-beb2-8da7586a3805">

### Solution

enable it for ast output editors too 
<img width="745" alt="image" src="https://github.com/mdx-js/mdx/assets/7361780/37178c70-e08d-465c-bfe0-bfdb9078e84e">

### Alternatives

no alternatives should be enabled by default to improve dev experience

**Comment by B2o5T** [comment]
as an alternative you can migrate to `monaco-editor` that uses web workers and in the latest updates supports `mdx` as language https://github.com/microsoft/monaco-editor/pull/3096

**Comment by wooorm** [comment]
Hmm, maybe. @remcohaszing does monaco + mdx have enough features, e.g., our plugin options and such?

I do think a whole editor is going to get heavy, and a plain textarea like https://wooorm.com/markdown-tm-language/ would be a lot lighter

**Comment by remcohaszing** [comment]
Yes, the `@mdx-js/monaco` supports all of this. I would love for the MDX website to support this (as soon as the Volar integration is ready). It’s not mobile friendly though. A nice solution would be to use Monaco on desktop, and a light weight editor on mobile.

**Comment by remcohaszing** [comment]
Note that MDX syntax highlighting in Monaco editor is not remotely as good as the tm language. To support that language would mean to pull in another heavy dependency on top of Monaco editor.

**Comment by remcohaszing** [comment]
We would need https://github.com/bolinfest/monaco-tm.

Also it is possible to cherry-pick some Monaco editor features to make it smaller, but its core is already big (I don’t have exact numbers right now).

**Comment by wooorm** [comment]
There’s now a much simpler, faster, playground, with proper syntax highlighting.
I prefer that over adding all the features an editor can have.
I suggest using your own editor to and copy/paste into the playground.
Or use `compile` from `@mdx-js/mdx` locally to see what things turn into!

**Comment by B2o5T** [comment]
@wooorm I saw the new playground, thanks for working on it, looks very nice!
