### ISSUE TITLE
The guide at https://mdxjs.com/guides/math/ does not work

### ISSUE THREAD

**Issue by B1RO** [mdx-js/mdx#2341]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

.

### Steps to reproduce

Follow the guide in a mdx environment

### Expected behavior

Math should be properly rendered

### Actual behavior

The css file does not get loaded and math does not work. This is because the css file linked in the guide is obsolete/out of date. It'd be better if the part of the guide that explains the css part was modified.
 I think you should remove the link to the css file, and link to katex page, so that user gets an up-to-date link. Every time I create a mdx project I forget this quirk with the docs and spend 20 minutes debugging the issues.

**Comment by wooorm** [comment]
it’s open source! you can make a pr to help other folks!
