### ISSUE TITLE
mdx-js does not work with Docusaurus 2.4

### ISSUE THREAD

**Issue by mrousavy** [mdx-js/mdx#2344]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.3.0

### Steps to reproduce

I use TypeDoc + Docususaurus to generate my docs. Here's the PR where I tried to upgrade (everything is in the `docs/` folder) https://github.com/mrousavy/react-native-vision-camera/pull/1783

### Expected behavior

It should build

### Actual behavior

It does not build:

```
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/api/.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/api/classes/Camera.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/api/classes/CameraCaptureError.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/api/classes/CameraRuntimeError.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/api/interfaces/CameraDevice.
```

I'll try to rebuild with the verbose parameter to get the full error in a second, am on the airport rn

### Runtime

Node v16

### Package manager

yarn v3

### OS

macOS

### Build and bundle tools

Docusaurus

**Comment by ChristianMurphy** [comment]
For help upgrading Docusaurus to MDX 2 reach out at https://github.com/facebook/docusaurus/discussions/9053
As Sébastien mentions at https://github.com/mrousavy/react-native-vision-camera/pull/1783#discussion_r1318662098 you need to be on Docusaurus 3.
