### ISSUE TITLE
`create-react-app` build

### ISSUE THREAD

**Issue by IcanDivideBy0** [mdx-js/mdx#236]
Not sure the issue comes from this repository, but the build process is broken on the `create-react-app` example.

How to reproduce:
```sh
cd examples/create-react-app
yarn
yarn build
```
output:
```
yarn run v1.9.4
$ react-app-rewired build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/@rebass/markdown/index.js:8 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

On my project (I'm using `mdx-deck`), the warning comes form `./node_modules/@compositor/webfont/index.js:5`.

**Comment by johno** [comment]
This should now be fixed in the latest example that switches to cra + mdx.macro.
