### ISSUE TITLE
Links to docs pages inside docs pages fail to resolve

### ISSUE THREAD

**Issue by victor23k** [mdx-js/mdx#2365]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

1. Go to a doc page such as [What is MDX?](https://mdxjs.com/docs/what-is-mdx/).
2. Use a link in the page to other page in the docs section such as the [§ Getting started](https://mdxjs.com/docs/what-is-mdx/getting-started/) link in the introduction to the page.

### Expected behavior

Be redirected to [https://mdxjs.com/docs/getting-started/](https://mdxjs.com/docs/getting-started/) in the example showed above.

### Actual behavior

The redirections gets you to [https://mdxjs.com/docs/what-is-mdx/getting-started/](https://mdxjs.com/docs/what-is-mdx/getting-started/) in the example showed above, which gives a 404: Not found.

### Runtime

Node v19

### Package manager

npm v9

### OS

macOS

**Comment by victor23k** [comment]
I have tried adding redirections in `docs/_config.js` and also modifying the links in the mdx pages for the docs, but nothing that I tried works. I don't have a full grasp on how the website is built so I would need some direction in order to fix this, but I would like to do it.

**Comment by wooorm** [comment]
Thanks!
