### ISSUE TITLE
mdx 2.3.0 + remark-gfm 4.0.0 breaks tables

### ISSUE THREAD

**Issue by ky1ejs** [mdx-js/mdx#2379]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.3.0

### Steps to reproduce

1. Check out https://github.com/ky1ejs/kylejs-site/pull/86
2. Run `npm run build`
3. See error relating to GFM table

### Expected behavior

Build should complete successfully

### Actual behavior

TypeError: Cannot read properties of undefined (reading 'inTable')

![268693986-e320c477-446a-4a47-9b16-d01825fccfac](https://github.com/mdx-js/mdx/assets/3501212/e950fcff-7c38-434d-9fd8-984385a3666d)

### Runtime

Node v18

### Package manager

npm v9

### OS

macOS

### Build and bundle tools

Next.js

**Comment by ky1ejs** [comment]
I wanted to report this since I didn't see an issue tracking this problem on this repo yet.

According to [this `remark-gfm` issue](https://github.com/remarkjs/remark-gfm/issues/57), many packages in the Markdown JS/TS ecosystem are still updating to latest models/packages since a major release recently (circa August 2023).

In the issue linked above, the maintainer mentions that MDX should be making its way to be up to date with the latest changes.

I'd be happy to help out with this, be would be helpful to get an intro to the work with an existing contributor (and, for that matter, a status check of whether y'all are already aware/working on this :) ).

**Comment by wooorm** [comment]
All the packages are done except for MDX (and remark-lint). Wait a day or two for MDX. One feature rest docs. Use the previous remark-gfm for now.

**Comment by wooorm** [comment]
v3 is out!

**Comment by muditjuneja** [comment]
I am using these 2 - 
`"@mdx-js/mdx": "^3.0.0",
    "@mdx-js/react": "^3.0.0"`
    
  along with "remark-gfm": "^4.0.0" and this still gives me this error. 
  I am using gatsby with `"gatsby-plugin-mdx": "^5.13.1",`

**Comment by ChristianMurphy** [comment]
@muditjuneja this is a bug in `gatsby-plugin-mdx`, Gatsby does not support MDX 3 yet.
See https://github.com/gatsbyjs/gatsby/discussions/36406 and https://github.com/gatsbyjs/gatsby/issues/38789

**Comment by muditjuneja** [comment]
Thank you @ChristianMurphy ++++ for these links. I will read more into this.
