### ISSUE TITLE
Vue Support

### ISSUE THREAD

**Issue by brennj** [mdx-js/mdx#238]
Hey guys, I'm in love with this library. Its super cool and easy to use. I use Vue in my day job, and I would really love to be able to write some component docs with this, because as far as I know - there is nothing in the Vue world for this, even though we have JSX.

I think its because of the differences that Vue needs, in comparison to being able to define a functional React component that makes it slightly non-trivial? I'm rusty with my parsers, so not sure how another layer of abstraction ontop of parsing with deciding to use a JSX outputter is.

i.e.
```
export default {
  render() {
    return <div>Hello World</div>;
  }
};
```

in comparison to:
```
const MyComponent = () => <div>Hello World</div>
```

I miss React. :) Would love to understand whether it was possible or not.

Thanks guys!

**Comment by silvenon** [comment]
I have zero experience with Vue, but MDX has a `compilers` option which is an array of processors that operate on JSX. Maybe you could add a custom one there which modifies the final JSX output into something Vue-friendly?

What would really help is if you could take a look at JSX that MDX outputs and outline which changes in that JSX would be necessary for it to work in Vue.

**Comment by brennj** [comment]
I'm having a look into it @silvenon! As far as I understand theres a few tasks:

1. Make compatible `MDXTag` and `MDXProvider` Vue components (I've worked on this today over at  https://github.com/brennj/mdx/tree/vue-plugin ! I've written some tests to match the React side and looks good so far, maybe)
2. Like you say, pass a custom compiler that will change the following code:

```
export default ({components, ...props}) => <MDXTag name="wrapper"  components={components}><MDXTag name="p" components={components}>{`Hello World!`}</MDXTag></MDXTag>
```

into Vue friendly code. I'm still trying to figure this bit out as theres some specific React parts in the loader and stuff but I think it should be fairly fine. I might see how far I can get and offer up a PR if I'm happy with it :)

**Comment by johno** [comment]
I have a PR open (https://github.com/mdx-js/mdx/pull/455) that gets us a lot of the way there thanks to the fine work of @brennj.

I'm currently stuck on the way Vue handles element creation (I've never really used it before 🙃). I've created the custom pragma function for Vue to receive the type and props which is happening as expected. But, for whatever reason I can't seem to get it to render.

If anyone wants to tinker around in that branch there's a directory (`examples/vue`) you can get running and then edit `packages/vue/create-element.js`. Would love any insights as to what I'm doing wrong.

**Comment by ChristopherBiscardi** [comment]
A working createElement (and related code) is merged into #455

**Comment by callumflack** [comment]
A vanilla install from the [MDX Vue example](https://github.com/mdx-js/mdx/tree/master/examples/vue) fails with:

![image](https://user-images.githubusercontent.com/749885/56780340-40644280-6822-11e9-8fda-02f987da9084.png)

**Comment by johno** [comment]
A new Vue beta is now shipped in the latest version of MDX thanks to @codebender828! 🎉

**Comment by calaoa** [comment]
Hi everybody, Would anyone have a pointer at a working example on how to embed a Vue component into a Markdown file? As far as I understand, [`@mdx-js/vue`](https://github.com/mdx-js/mdx/tree/master/packages/vue) allows to expose a Markdown file as a Vue component, but how to achieve the other way round (it seems the [`vue-plugin-mdx`](https://github.com/mdx-js/mdx/pull/239/files?file-filters%5B%5D=.js&file-filters%5B%5D=.md#diff-9735f24f8a5e76b5353075662126d5a5) by @brennj does not exist as such anymore), that is for instance, as mentioned above:

```
import Test from './Test.vue';

# Hello World!

<Test />
```

**Comment by codebender828** [comment]
Hey @calaoa ! Yes it's possible to consume Vue components in your MDX files. You'd need to consume it as JSX in your MDX file.

Here's an example of how consume [Vue components in MDX files](https://github.com/codebender828/mdx-vue-demo/blob/master/src/views/home.mdx).

(This is an old demo but works. I made this when I was working on adding support for Vue.js. All functionality is already added to the MDX package.)
Demo: https://mdx-vue.now.sh/

**Comment by calaoa** [comment]
Thanks a lot @codebender828! Meantime I just noticed that [`@mdx-js/examples/vue`](https://github.com/mdx-js/mdx/tree/master/examples/vue) is showcasing an example along this line as well. Quite powerful... Now wondering how to load mdx files dynamically into a Vue app without the need to hardcode any mdx file import into the source code, a bit like what [`@nuxt/content`](https://github.com/nuxt/content) offers (see the [first demo video](https://content.nuxtjs.org/#videos) illustrating a Markdown file calling a Vue component as far as I understand)...

**Comment by callumflack** [comment]
@calaoa I'm excited about `@nuxt/content` — what was your experience like? Interested to know your thoughts comparing it to MDX + Vue.

**Comment by calaoa** [comment]
Hey @callumflack, `@nuxt/content` looks very appealing indeed, however there's two things I'm not fond of so far with it (a plugin could come into play for the first one I guess, I need to experiment further):
- Search: I favor [`MiniSearch`](https://github.com/lucaong/minisearch) over [`Loki`](https://github.com/LokiJS-Forge/LokiDB)
- TypeScript: as far as I can see, `@nuxt/content` is not using TypeScript (yet)

(Hopefully not hijacking the thread too much… MDX + Vue opens so many paths… E.g. something like [`Jupyter`](https://jupyter.org/) with an MDX-Vue-Node-Git stack… A route I'm humbly exploring with [`Babouk`](https://babouk.net)…)

**Comment by calaoa** [comment]
For what it's worth, I actually achieved the usage of Vue components 'within' (sort of) Markdown by using [`v-runtime-template`](https://github.com/alexjoverm/v-runtime-template)👏 coupled with [`remark-rehype`](https://github.com/remarkjs/remark-rehype) (and other `remark`'s👏): Markdown gets transformed to HTML, then the embedded Vue tags are made executable by `v-runtime-template` (provided the Vue displaying the result imports the components declared in the Markdown, which can be made dynamic as well via [Vue async components](https://vuejs.org/v2/guide/components-dynamic-async.html#Async-Components)👏). Eventually nothing involving MDX here yet (possible follow up though), sorry for the noise.

**Comment by callumflack** [comment]
Thanks @calaoa — I see your digital garden fascination! I've got similar interests. Markdown + components can mean rich, interactive "gardening" w/o being tied to a platform. I hope people like you can make new information systems with these tools. As such, it's a good thing to converse about them here.
