### ISSUE TITLE
mdx 3 converts component elements to p tag

### ISSUE THREAD

**Issue by Heet-Bhalodiya** [mdx-js/mdx#2408]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v3.0.0

### Steps to reproduce

**I am using node v20.9.0**

```
<Typography>
  Please refer to MUI&#39;s official docs for more details on component&#39;s{' '}
  <Link href='https://mui.com/material-ui/react-alert/' target='_blank' rel='noopener noreferrer' className='no-underline'>
    usage guide
  </Link>{' '}
  and{' '}
  <Link href='https://mui.com/material-ui/react-alert/#api' target='_blank' rel='noopener noreferrer' className='no-underline'>
    API documentation
  </Link>
  .
</Typography>
```

using above code in mdx file I am getting following errors which was not there in the mdx version 2.

![image](https://github.com/mdx-js/mdx/assets/100203834/c7d6f6fa-59bb-4f35-a7d8-b7473ba15241)

### Expected behavior

![Screenshot 2023-11-27 at 5 11 53 PM](https://github.com/mdx-js/mdx/assets/100203834/15dfd0b2-e1a0-4201-aaa7-9c2945765416)

![Screenshot 2023-11-27 at 5 10 19 PM](https://github.com/mdx-js/mdx/assets/100203834/1339635e-f3f7-43db-8218-f9e28363b489)

### Actual behavior

mdx 3 converts component elements to p tag which lead to `<p> cannot appear as a descendant of <p>` error

![image](https://github.com/mdx-js/mdx/assets/100203834/313df6e1-6055-4cc7-ae8a-1ff70f2b3869)

![image](https://github.com/mdx-js/mdx/assets/100203834/6d4497c9-e177-4bb4-8eb7-46ed73a14d8e)

### Runtime

Other (please specify in steps to reproduce)

### Package manager

pnpm

### OS

macOS

### Build and bundle tools

Docusaurus

**Comment by wooorm** [comment]
You can search through closed issues or read the docs.
Such as: https://mdxjs.com/docs/what-is-mdx/#interleaving.

**Comment by remcohaszing** [comment]
You can use an expression to use plain JSX instead of MDX.

```mdx
{
<Typography>
  Please refer to MUI&#39;s official docs for more details on component&#39;s{' '}
  <Link href='https://mui.com/material-ui/react-alert/' target='_blank' rel='noopener noreferrer' className='no-underline'>
    usage guide
  </Link>{' '}
  and{' '}
  <Link href='https://mui.com/material-ui/react-alert/#api' target='_blank' rel='noopener noreferrer' className='no-underline'>
    API documentation
  </Link>
  .
</Typography>
}
```

**Comment by wooorm** [comment]
> So I can't write all these code in one line. 

It doesn’t have to be on one line. That’s not what the text says.
For example:

```mdx
<Typography>Please refer to MUI&#39;s official docs for more
details on component’s <Link href='https://mui.com/material-ui/react-alert/'
target='_blank' rel='noopener noreferrer' className='no-underline'>usage guide
</Link> and <Link href='https://mui.com/material-ui/react-alert/#api'
target='_blank' rel='noopener noreferrer' className='no-underline'> API
documentation</Link>.</Typography>
```
