### ISSUE TITLE
Github link missing in mdxjs.com

### ISSUE THREAD

**Issue by augbog** [mdx-js/mdx#242]
I couldn't find a link to the Github repository from the https://mdxjs.com website. Even in the contributing section, it simply tells you how to start but not where to clone the project.

**Comment by macklinu** [comment]
This would be a great docs site addition. Maybe adding a GitHub logo link to the header or a footer would make sense? Any design thoughts on where this could go across all pages?

![image](https://user-images.githubusercontent.com/2344137/44937142-b3b5c300-ad2c-11e8-8caa-31b85552b9ab.png)

![image](https://user-images.githubusercontent.com/2344137/44937182-e5c72500-ad2c-11e8-9e55-867c147672d8.png)
