### ISSUE TITLE
created a new recma plugin `recma-mdx-change-props`

### ISSUE THREAD

**Issue by talatkuyuk** [mdx-js/mdx#2437]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

We are not able to use "props" key in the mdx files like:
```markdown
# Hi {props.foo}

<Test name={props.baz} />
```

### Solution

Solution is to change `props` into `_props` in the `_createMdxContent` function:
```javascript
function _createMdxContent(_props) {
  const _components = {
    // ...
    ..._props.components
  }, // ...
  // ...
}
```

That is why I created the recma plugin [`recma-mdx-change-props`](https://www.npmjs.com/package/recma-mdx-change-props).

The `recma-mdx-change-props` changes the `props` parameter into `_props` in the function `_createMdxContent`; and makes appropriate changes in order to provide us to be able to use for example {props.foo} in the mdx files.

I am going to open a PR to add this into the docs. Thanks.

### Alternatives

Another alternative would be to make appropriate changes in the `@mdx-js/mdx` package in maybe `recma-document.js`. But, **I prefer to use the `recma-mdx-change-props`** in order to make the mdx community accustomed to use recma plugins for who especially needs to use `{props.foo}` in the mdx files.

**Comment by wooorm** [comment]
Weird? The code here generates `props`?

https://github.com/mdx-js/mdx/blob/b9b37b687d13a951188a2dc164e7a123050d5e6d/packages/mdx/lib/plugin/recma-document.js#L622-L623

It’s also documented: https://mdxjs.com/docs/using-mdx/#props

**Comment by talatkuyuk** [comment]
In the example that you reference:
```jsx
import Example from './example.mdx' // Assumes an integration is used to compile MDX -> JS.

// Use a `createElement` call:
React.createElement(Example, {name: 'Venus', year: 2021})

// ...
```
You are not able to pass `props` key, but this recma plugin makes it available.
```jsx
import Example from './example.mdx' // Assumes an integration is used to compile MDX -> JS.

// Use a `createElement` call:
React.createElement(Example, { title: "Xx", props: {name: 'Venus', year: 2021} })

// ...
```
This issue is related maybe with `nextjs` users who are using `next-mdx-remote` like me.

**Comment by wooorm** [comment]
It seems to be `next-mdx-remote`, with its `scope`.
The tools maintained here put it all in `props`.

**Comment by talatkuyuk** [comment]
The plugin is added into the docs. Thanks.
