### ISSUE TITLE
Useless/bad error message when forgetting to close an element

### ISSUE THREAD

**Issue by theRealProHacker** [mdx-js/mdx#2451]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Link to runnable example

https://mdxjs.com/playground/

### Steps to reproduce

Linked issue in astro: https://github.com/withastro/astro/issues/10318

This code
```mdx
<A>
<B></B>
```
results in this error message: 

```
1:1: Expected a closing tag for `</B>` (1:1-1:4)
```

### Expected behavior

I would have expected an error that asks me to close the `<A>` tag/element.

### Actual behavior

The error asks me to close the `</B>` tag, which is itself a closing tag

**Comment by ChristianMurphy** [comment]
Welcome @theRealProHacker! 👋 
Sorry you ran into some confusion.

The error is not raised in this repo, it comes from https://github.com/syntax-tree/mdast-util-mdx-jsx/blob/bf60d93bdffde6e4d3359324170d438e5ee62a63/lib/index.js#L424-L471
Contributions to improve error reporting are welcome!

Feel free to reach out with questions on how to contribute.

**Comment by theRealProHacker** [comment]
Hi, the issue got fixed in https://github.com/syntax-tree/mdast-util-mdx-jsx/issues/12 and put in a new release (https://github.com/syntax-tree/mdast-util-mdx-jsx/releases/tag/3.1.1). I don't know where exactly, but maybe the dependency should be bumped up in the playground etc.
