### ISSUE TITLE
MDXProvider is invalid after processSync processing when {jsxImportSource: 'vue', providerImportSource: '@mdx-js/vue'} is configured.

### ISSUE THREAD

**Issue by luobingxun** [mdx-js/mdx#2453]
### Initial checklist

- [x] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.0.1

### Steps to reproduce

1. Write vite plug-in and use createProcessor provided by mdx. createProcessor({jsxImportSource: 'vue',providerImportSource: '@mdx-js/vue'})
2. Use MDXProvider in jsx translated by @vitejs/plugin-vue-jsx plug-in to find that the components cannot be customized

### Expected behavior

The MDXProvider can customize the components in the mdx file

### Actual behavior

Cannot be customized, the components provided by the MDXProvider are invalid, and a warning is reported in the browser console
 inject() can only be used inside setup() or functional components.

**Comment by miss-money** [comment]
demo warehouse address: https://github.com/miss-money/vite-plugin-mdx-demo-test/tree/master/demo/vue

**Comment by wooorm** [comment]
This sounds like a bug in @vitejs/plugin-vue-jsx, why report it here not there?
MDX compiles the jsx away already. That plugin doesn't see jsx?
