### ISSUE TITLE
Dynamic linked heading does not interpolate link properly

### ISSUE THREAD

**Issue by sumanthratna** [mdx-js/mdx#2493]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.0.1

### Steps to reproduce

This is my MDX file: 
```mdx
export const metadata = {
  path: "/blog/new-post",
  title: "This is a Fake Title",
};


# <>[{metadata.title}]({metadata.path})</>

hey again
```

### Expected behavior

The above MDX should render the following HTML after interpolating `metadata.path`: 
```html
<h1><a href="/blog/new-post">This is a Fake Title</a></h1>
<p>hey again</p>
```

### Actual behavior

The above MDX renders the following HTML: 
```html
<h1><a href="%7Bmetadata.path%7D">This is a Fake Title</a></h1>
<p>hey again</p>
```
Note that the link text is interpolated properly, but not the link href. 

### Runtime

Node v21

### Package manager

yarn v4

### OS

macOS

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
Hey!

That is indeed not something that works. It is intentional. MDX is not a template language.

```mdx
# <a href={metadata.path}>{metadata.title}</a>
```

**Comment by sumanthratna** [comment]
Thanks for clarifying @wooorm! I am still a little confused about the mechanics of interpolation. 

The following does not interpolate the title: 
```mdx
# `{metadata.title}`
```

The following does: 
```mdx
# ~**_{metadata.title}_**~
```

Is there a rule to understand which Markdown features result in interpolation?

**Comment by ChristianMurphy** [comment]
Code will never interpolate.
Inlines (strong, emphasis, strike) usually will.

**Comment by talatkuyuk** [comment]
I would like to announce that the new `recma` plugin [**`recma-mdx-interpolate`**](https://github.com/ipikuka/recma-mdx-interpolate) makes the interpolation possible in `alt`, `src`, `href`, and `title` attributes of markdown **link** and **image** syntax in MDX, even in markdown (`md`) format.

You can use interpolations in MDX/markdown via **`recma-mdx-interpolate`** like below:
```markdown
### markdown links
[{props.email}](mailto:{props.email} "{props.title}")

### markdown images
![{{alt}}]({src} "{title}")

### in markdown header
# The title [{text}]({path})

### nested image in the link
[![{{alt}}]({src})](https://example.com)

### even in html syntax in markdown
<a href={link.href} title={link.title}>{link.text}</a>
<img src={image.src} alt={image.alt} title={image.title}>
```
You can visit the plugin for more details. Cheers !

**Comment by talatkuyuk** [comment]
The `recma` plugin [**`recma-mdx-interpolate`**](https://github.com/ipikuka/recma-mdx-interpolate) supports **interpolation in code fences** as well.

By using **`recma-mdx-interpolate`**, you can write markdown/MDX content:
````mdx
export const package_manager = "npm";

```bash
{{ package_manager }} install my-package
```
````

Another example; the following interpolates the title even having an inline code:
```md
# `{metadata.title}`
```

For more information you can see that discussion comment: https://github.com/orgs/mdx-js/discussions/2288#discussioncomment-16144517
