### ISSUE TITLE
Vite + Vue + MDX Components (Warn)

### ISSUE THREAD

**Issue by henrikruscon** [mdx-js/mdx#2512]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

https://mdxjs.com/packages/vue/#usemdxcomponentscomponents

### Steps to reproduce

MarkdownComponent.vue
```vue
<template>
    <MDXProvider :components="components">
        <component :is="markdown" />
    </MDXProvider>
</template>

<script>
import LinkComponent from '../components/LinkComponent.vue'
import { h } from 'vue'
import { MDXProvider } from '@mdx-js/vue'

export default {
    components: {
        MDXProvider
    },

    props: {
        markdown: {
            type: Function,
            required: true
        }
    },

    setup() {
        const components = {
            h2: h('h2', {
                class: ['text-3xl font-semibold font-read tracking-tight mt-14 mb-2']
            }),
            p: h('p', {
                class: ['text-lg font-read tracking-[-0.0125em] py-4']
            }),
            a: LinkComponent
        }

        return { components }
    }
}
</script>

```

LinkComponent.vue
```vue
<template>
    <a class="group flex items-center outline-none" :href="href">
        <slot />
    </a>
</template>

<script>
export default {
    props: {
        href: {
            type: String,
            default: ''
        }
    }
}
</script>
```

vite.config.js
```js
mdx({
	remarkPlugins: [remarkGfm, remarkFrontmatter, remarkMdxFrontmatter],
	jsxImportSource: 'vue',
	providerImportSource: '@mdx-js/vue'
}),
```

### Expected behavior

No warnings.

### Actual behavior

Returns warning for all links in the imported MDX.

`[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance. `

Is there any documentation on how to properly replace MDX components with this setup?

### OS

macOS

### Build and bundle tools

Vite

**Comment by wooorm** [comment]
* can you please share the needed package.json and other files to make your code runnable? I can‘t dive into your code if I don’t know all of it
* can you please make your reproduction smaller? E.g., is tailwind really needed to reproduce this? Please remove everything that is not relevant
* please read the readme of what you linked: particularly they “Note: you don’t have to use MDXProvider and can pass components directly: […]” part — you probably don’t need to use the provider
* this is a vue warning about performance; it’s not an error; it’s not from MDX. It’s from vue

**Comment by henrikruscon** [comment]
Here is a much simplified version in form of a [CodeSandbox](https://codesandbox.io/p/devbox/wild-water-ys544f?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyfrrdlu00073b6lu3uy4auj%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyfrrdlt00023b6lfustkuvw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyfrrdlt00043b6lj6axp1eb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyfrrdlt00063b6l77qqqo5n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyfrrdlt00023b6lfustkuvw%2522%253A%257B%2522id%2522%253A%2522clyfrrdlt00023b6lfustkuvw%2522%252C%2522activeTabId%2522%253A%2522clyfrt7q000853b6lcflqdhw7%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyfrrdlt00013b6l3ycqpnkz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fnode_modules%252F.pnpm%252F%2522%252C%2522id%2522%253A%2522clyfrt7q000853b6lcflqdhw7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clyfrrdlt00063b6l77qqqo5n%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyfrrdlt00053b6lbcvjshsr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyfrrdlt00063b6l77qqqo5n%2522%252C%2522activeTabId%2522%253A%2522clyfrrdlt00053b6lbcvjshsr%2522%257D%252C%2522clyfrrdlt00043b6lj6axp1eb%2522%253A%257B%2522id%2522%253A%2522clyfrrdlt00043b6lj6axp1eb%2522%252C%2522activeTabId%2522%253A%2522clyfrvqtd00vq3b6lultnvy5u%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clyfrvqtd00vq3b6lultnvy5u%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) of what was shared prev. Check the console output and you'll see the same warnings.

Which part of my implementation is causing the Vue warnings and how to avoid them? I fail to find any documentation on how to properly override components with MDXProvider using my current stack on MDX.

Thank you for taking your time.

**Comment by wooorm** [comment]
There are so many files there, it does not feel simplified. There are more components than before. They all contain more code. Can you please remove anything that is not relevant? Please help me help you

**Comment by wooorm** [comment]
Why are you asking these things here btw? You are doing dynamic `import()`s which are different from our docs and getting a Vue warning. Why not ask Vue people about Vue warnings?

**Comment by wooorm** [comment]
Anyway, you say `Link.vue` is not relevant. But when I change that, the warning goes away / appears. Sounds like `Link.vue`, unrelated to MDX itself, is what you need to change.

**Comment by henrikruscon** [comment]
There are no issues with the dynamic import, nor is it causing any warnings.

Is there a better approach to dynamically load a specific MDX file based on a slug? There are no examples for this.

When you say you change the Link, what exactly do you mean? The link component is as basic as they get, it has a single prop and a default slot, what exactly is there to change besides not importing it at all? Care to share an example that works with a custom component using MDXProvider? The docs for `@mdx-js/vue` only show how to replace a tag with another tag, not replacing a tag with a component. This is what I'm trying to do and this is what's causing the warning. How is this related to Vue and not MDX in relation to Vue?

Thanks for taking your time with this.

**Comment by henrikruscon** [comment]
Here is a forked version without the dynamic import entirely just to prove that it has nothing to do with the warnings: [CodeSandbox](https://codesandbox.io/p/devbox/wild-water-forked-pxgpct?file=%2Fsrc%2Fcomponents%2FMarkdown.vue%3A16%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyfrrdlu00073b6lu3uy4auj%2522%252C%2522sizes%2522%253A%255B71.81268882175226%252C28.18731117824774%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyfrrdlt00023b6lfustkuvw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyfrrdlt00043b6lj6axp1eb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyfrrdlt00063b6l77qqqo5n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyfrrdlt00023b6lfustkuvw%2522%253A%257B%2522id%2522%253A%2522clyfrrdlt00023b6lfustkuvw%2522%252C%2522activeTabId%2522%253A%2522clyfxh7q800023b6l27dv8k7n%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyfrrdlt00013b6l3ycqpnkz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fnode_modules%252F.pnpm%252F%2522%252C%2522id%2522%253A%2522clyfrt7q000853b6lcflqdhw7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clyfxh7q800023b6l27dv8k7n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FMarkdown.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clyfrrdlt00063b6l77qqqo5n%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyfrrdlt00053b6lbcvjshsr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyfrrdlt00063b6l77qqqo5n%2522%252C%2522activeTabId%2522%253A%2522clyfrrdlt00053b6lbcvjshsr%2522%257D%252C%2522clyfrrdlt00043b6lj6axp1eb%2522%253A%257B%2522id%2522%253A%2522clyfrrdlt00043b6lj6axp1eb%2522%252C%2522activeTabId%2522%253A%2522clyfrvqtd00vq3b6lultnvy5u%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clyfrvqtd00vq3b6lultnvy5u%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by wooorm** [comment]
> Is there a better approach to dynamically load a specific MDX file based on a slug? There are no examples for this.

Well, a) what you do doesn’t normally work, so there’s already something in play here, and b) see https://mdxjs.com/guides/mdx-on-demand/.

> The link component is as basic as they get, it has a single prop and a default slot, what exactly is there to change besides not importing it at all?

Well, read the warning: that warning is about `Link`. And it is about default slots. Removing that default slot makes the warning disappear. Adding it again, makes it appear.

> The docs for `@mdx-js/vue` only show how to replace a tag with another tag

You don’t need `@mdx-js/vue`

> How is this related to Vue and not MDX in relation to Vue?

Vue is choosing to warn. MDX works with any JSX runtime. Vue is one of them. It still works.

>  This is what I'm trying to do and this is what's causing the warning. 

I don‘t know. Apparently Vue warns for certain cases where all other frameworks don’t warn.

**Comment by henrikruscon** [comment]
Did you see the version I [just shared](https://codesandbox.io/p/devbox/wild-water-forked-pxgpct?file=%2Fsrc%2Fcomponents%2FMarkdown.vue%3A16%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyfrrdlu00073b6lu3uy4auj%2522%252C%2522sizes%2522%253A%255B71.81268882175226%252C28.18731117824774%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyfrrdlt00023b6lfustkuvw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyfrrdlt00043b6lj6axp1eb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyfrrdlt00063b6l77qqqo5n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyfrrdlt00023b6lfustkuvw%2522%253A%257B%2522id%2522%253A%2522clyfrrdlt00023b6lfustkuvw%2522%252C%2522activeTabId%2522%253A%2522clyfxh7q800023b6l27dv8k7n%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyfrrdlt00013b6l3ycqpnkz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fnode_modules%252F.pnpm%252F%2522%252C%2522id%2522%253A%2522clyfrt7q000853b6lcflqdhw7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clyfxh7q800023b6l27dv8k7n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FMarkdown.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clyfrrdlt00063b6l77qqqo5n%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyfrrdlt00053b6lbcvjshsr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyfrrdlt00063b6l77qqqo5n%2522%252C%2522activeTabId%2522%253A%2522clyfrrdlt00053b6lbcvjshsr%2522%257D%252C%2522clyfrrdlt00043b6lj6axp1eb%2522%253A%257B%2522id%2522%253A%2522clyfrrdlt00043b6lj6axp1eb%2522%252C%2522activeTabId%2522%253A%2522clyfrvqtd00vq3b6lultnvy5u%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clyfrvqtd00vq3b6lultnvy5u%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) that imports the file with `@mdx-js/rollup` instead? That rules out the dynamic import being related to the issue.

Removing the default slot makes no difference at all for the warning, [here's a new fork](https://codesandbox.io/p/devbox/wild-water-forked-6g3xz5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyfrrdlu00073b6lu3uy4auj%2522%252C%2522sizes%2522%253A%255B71.81268882175226%252C28.18731117824774%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyfrrdlt00023b6lfustkuvw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyfrrdlt00043b6lj6axp1eb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyfrrdlt00063b6l77qqqo5n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyfrrdlt00023b6lfustkuvw%2522%253A%257B%2522id%2522%253A%2522clyfrrdlt00023b6lfustkuvw%2522%252C%2522activeTabId%2522%253A%2522clyfxh7q800023b6l27dv8k7n%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyfrrdlt00013b6l3ycqpnkz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fnode_modules%252F.pnpm%252F%2522%252C%2522id%2522%253A%2522clyfrt7q000853b6lcflqdhw7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clyfxh7q800023b6l27dv8k7n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FMarkdown.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clyfrrdlt00063b6l77qqqo5n%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyfrrdlt00053b6lbcvjshsr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyfrrdlt00063b6l77qqqo5n%2522%252C%2522activeTabId%2522%253A%2522clyfrrdlt00053b6lbcvjshsr%2522%257D%252C%2522clyfrrdlt00043b6lj6axp1eb%2522%253A%257B%2522id%2522%253A%2522clyfrrdlt00043b6lj6axp1eb%2522%252C%2522activeTabId%2522%253A%2522clyfrvqtd00vq3b6lultnvy5u%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clyfrvqtd00vq3b6lultnvy5u%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) that removes both slot and prop entirely, basically just leaving the HTML syntax and it's still throwing the warning.

This is as barebone as it gets, it's still throwing issues. Seems specifically related to `MDXProvider` component to me. Any ideas?

**Comment by wooorm** [comment]
>  That rules out the dynamic import being related to the issue.

Sorry for the confusion, that is not what I was implying when I talked about dynamic imports. I wanted to point at that you were doing things not documented by us. Doing lots of different things.

> This is as barebone as it gets, it's still throwing issues. Seems specifically related to MDXProvider component to me. Any ideas?

Thanks for making this smaller.
Note, I still make files smaller.
For example, `contributing.mdx` can be replaced with `[x](https://y.com).`.
The provider in `Markdown.vue` can be removed, as `<Changelog :components="components" />` is enough.
It seems the “hot reloading vue tools” don’t work well. The warning disappeared before but now it doesn’t.

***

As I tried to get at before: I think this has nothing to do with MDX. It works with many runtimes, and they work. Vue is choosing to **warn**. Duckduckgo’ing your warning seems to indicate that Vue dislikes certain `h` calls (https://stackoverflow.com/questions/69875273/non-function-value-encountered-for-default-slot-in-vue-3-composition-api-comp). But we use the automatic runtime. Vue chooses to support it. It should not warn.

Please raise this issue, as minimal as you can (by removing every file that does nothing) to the Vue people. **They should not warn**.

**Comment by iceprosurface** [comment]
Here is My Solution, create a special jsx function and do not use `vue/jsx-runtime`:

```tsx
import { Props } from 'hast-util-to-jsx-runtime';
import { Fragment, withCtx } from 'vue';
import { h, withCtx } from 'vue';

function jsx(type: any, props: Props, key?: string | undefined) {
  const { children } = props;
  delete props.children;
  if (arguments.length > 2) {
    props.key = key;
  }
  if (type === Fragment) {
    // fragment need special handle, because it doesn't support default slot
    return h(type, props, children as any) as any as JSX.Element;
  }
  // other tags should use default slot to prevent "Non-function value encountered for default slot"
  return h(type, props, {
    default: withCtx(() => children),
    // add $stable mark if needed
  }) as any as JSX.Element;
}
```
