### ISSUE TITLE
Add demo for code syntax highlighting

### ISSUE THREAD

**Issue by silvenon** [mdx-js/mdx#253]
In #221 there was a great suggestion to add a demo for how to implement syntax highlighting, most probably it will be using [@mapbox/rehype-prism](https://github.com/mapbox/rehype-prism). I will add this demo, but first I need to solve the problem outlined in https://github.com/mdx-js/mdx/issues/221#issuecomment-419183553.

**Comment by phil-lgr** [comment]
yea, good one, something like

## Syntax Highlighting

### Prismjs

```
npm i --save prismjs
npm i --save-dev @mapbox/rehype-prism
```

```
const rehypePrism = require('@mapbox/rehype-prism');

module.exports = {
    test: /(\.mdx?)$/,
    use: [
        {
            loader: 'babel-loader',
            options: {
                plugins: ['@babel/plugin-transform-runtime', '@babel/plugin-proposal-object-rest-spread'],
                presets: ['@babel/preset-react']
            }
        },
        {
            loader: '@mdx-js/loader',
            options: {
                hastPlugins: [rehypePrism]
            }
        }
    ]
};
```

**Comment by silvenon** [comment]
@phil-lgr why do we need `prismjs`?

**Comment by phil-lgr** [comment]
oh for the default css:

_in a webpack project_
```
// default prismjs theme
import 'prismjs/themes/prism.css';
```

**Comment by silvenon** [comment]
Ah, got it! Maybe also [prism-themes](https://www.npmjs.com/package/prism-themes) instead, so they can can try on different ones.

**Comment by timneutkens** [comment]
Just leaving this here for future reference, implementing the plugin using next-mdx:

```js
const rehypePrism = require('@mapbox/rehype-prism');
const withMDX = require('@zeit/next-mdx')({
  extension: /\.(md|mdx)?$/,
  options: {
    hastPlugins: [
      rehypePrism
    ]
  }
})
```

**Comment by elitan** [comment]
I'm using @timneutkens's example with NextJS and MDX, and my question is:

How do I add PrismJS plugin [dif highlight](https://prismjs.com/plugins/diff-highlight/) (or any other plugin) to this setup?
