### ISSUE TITLE
Multiline expression with template literal indentation issue

### ISSUE THREAD

**Issue by vrepsys** [mdx-js/mdx#2533]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-mdx 3.0.1, remark-stringify/remark-parse 11.0.0

### Link to runnable example

https://codesandbox.io/p/live/8c858a72-e7de-4db3-ad55-7f630eb6d197

### Steps to reproduce
```js
const toAst = (md) => {
  const ast = unified().use(remarkParse).use(remarkMdx).parse(md);
  console.log(JSON.stringify(ast.children[0].children[0].value, null, 2));
  return ast;
};

const toMdx = (ast) => {
  return unified().use(remarkMdx).use(remarkStringify).stringify(ast);
};

let text = `<CodeBlock>
{\`link:
title: front page\`}
</CodeBlock>`;
console.log(text);
text = toMdx(toAst(text));
console.log(text);
text = toMdx(toAst(text));
console.log(text);
text = toMdx(toAst(text));
console.log(text);
text = toMdx(toAst(text));
console.log(text);
```

### Expected behavior

I expected the string literal value to remain the same across conversions, as you can see in CodeSandox the actual behaviour is that already in the first iteration multiline code literal is indented which changes its actual value just by converting back and forth.

I'd expect the output to be:
```
<CodeBlock>
{`link:
title: front page`}
</CodeBlock>

"`link:\ntitle: front page`"
<CodeBlock>
{`link:
title: front page`}
</CodeBlock>

"`link:\ntitle: front page`"
<CodeBlock>
{`link:
title: front page`}
</CodeBlock>

"`link:\ntitle: front page`"
<CodeBlock>
{`link:
title: front page`}
</CodeBlock>
"`link:\ntitle: front page`"
```

### Actual behavior

The tempalte literal value in expression attains more and more spaces
```
"`link:\ntitle: front page`"
"`link:\n  title: front page`"
"`link:\n    title: front page`"
"`link:\n      title: front page`"
```

That's because of indentation, here's a complete output of reproducing code:
```
<CodeBlock className="language-yaml" title="test">
{`link:
title: front page`}
</CodeBlock>
"`link:\ntitle: front page`"
<CodeBlock>
  {`link:
  title: front page`}
</CodeBlock>

"`link:\n  title: front page`"
<CodeBlock>
  {`link:
    title: front page`}
</CodeBlock>

"`link:\n    title: front page`"
<CodeBlock>
  {`link:
      title: front page`}
</CodeBlock>

"`link:\n      title: front page`"
<CodeBlock>
  {`link:
        title: front page`}
</CodeBlock>
```

Also tested this with one of the 2.x versions, and the behaviour is different -- the template literal value changes the first time (which is still an issue), but then stops changing with iterations once i

I really appreciate all the open-source work on MDX!

**Comment by wooorm** [comment]
Thanks for the report. `npm update` should do the trick!

**Comment by Airkro** [comment]
Still happen in 3.1.0:

```js
import { remark } from 'remark';
import remarkMdx from 'remark-mdx';

function transform(input) {
  return remark()
    .use(remarkMdx)
    .process(input)
    .then((file) => file.toString().trim());
}

/* prettier-ignore */
const input =
`<div>{\`
  abc
\`}</div>`;
/* prettier-ignore */

console.log(input);

const output1 = await transform(input);

console.log(output1);

const output2 = await transform(output1);

console.log(output2);

const output3 = await transform(output2);

console.log(output3)
```

```log
<div>{`
  abc
`}</div>
<div>
  {`
    abc
    `}
</div>
<div>
  {`
      abc
      `}
</div>
<div>
  {`
        abc
        `}
</div>
```

**Comment by wooorm** [comment]
remove your package lock, clear your cache, and reinstall
