### ISSUE TITLE
Compile into a valid page even on invalid syntax

### ISSUE THREAD

**Issue by Iceburgino** [mdx-js/mdx#2539]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

MDX is an ideal format for writing documents. It's versatile and simple. And yet it can't be used that way because of parsing errors of JSX. The user that is just writing a document (like docx), and not a webpage, is not accustomed an error just discarding the entire page. 

### Solution

Something akin to what [tree-sitter](https://github.com/tree-sitter/tree-sitter) does - localizing erroneous part and parsing it as text.

### Alternatives

Nothing comes to mind that's better than proposed. Maybe rendering the older version of the page.

**Comment by ChristianMurphy** [comment]
Hey @Iceburgino! 👋 
There will not be a loose mode in core MDX.
That isn't how JSX/XML work, the document needs to be fully valid.

If you want an authoring experience that previews faster, take a look at https://github.com/mdx-js/mdx-analyzer/issues/267

And if you need a more forgiving parser.
Use markdown, there is no such thing as an invalid document in plain markdown.

**Comment by Iceburgino** [comment]
@ChristianMurphy Unfortunately, using markdown is not viable for us, as it's too simple to satisfy customer needs. The authoring experience needs to be something like in [obsidian](https://obsidian.md/), where you can type in the part, and it will not crash the app but just won't render properly. I presume the link you provided tackles the problem of syntax highlighting, but not previewing partial results?

**Comment by remcohaszing** [comment]
I recommend that you keep around the last version that could render. Then if the user introduces a syntax error, you render the previous version instead.

Additionally I recommend to integrate Volar with MDX language service in your text editor, so you can display errors in the editor.
