### ISSUE TITLE
do not add empty object `= {}` as default `props`

### ISSUE THREAD

**Issue by dimaMachina** [mdx-js/mdx#2548]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I saw in the generated code an empty object as default props `props = {}`, this is unneeded as `props` are always object

```js
export default function MDXContent(props = {}) {
```

<img width="1636" alt="image" src="https://github.com/user-attachments/assets/a1ac9b5a-8e98-417b-8281-c8e3aaa5c523">

### Solution

```js
export default function MDXContent(props) {
```

### Alternatives

no alternative

**Comment by wooorm** [comment]
> this is unneeded as props are always object

Who defines that?

I think it’s not needed when used as `<MDXContent />`. But some people don’t do that. Some people do `MDXContent()`

**Comment by dimaMachina** [comment]
> But some people don’t do that. Some people do

if they do it, they can do `MDXContent({})` 😅

**Comment by remcohaszing** [comment]
Also React always passes an object as props. Other JSX frameworks might not.

**Comment by wooorm** [comment]
People can indeed do `MDXContent({})`. And that’s probably good.
But. Now people don’t have to. And indeed: what about other frameworks.
I personally don’t think it’s worth a breaking change. For what benefit?
And I worry about those frameworks.

**Comment by dimaMachina** [comment]
> And indeed: what about other frameworks.

preact definitely should follow React convention, I guess behaviour there is similar, about other framework, idk

> For what benefit?

why do specify something that is technically is never will be used, to save some bytes too 😂

**Comment by remcohaszing** [comment]
I would agree with this if it was just a React component, but MDX can be used in various ways.

Feel free to create your own recma plugin if you really want to remove the default argument
