### ISSUE TITLE
MDX 3.1.0 introduce breaking change - no longer replace mdx components in React components declared in mdx files

### ISSUE THREAD

**Issue by dimaMachina** [mdx-js/mdx#2549]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/mdx

### Steps to reproduce

See diff of snapshot 
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/df50d5d8-5c9f-4197-9fd7-350e9fb979a4">

### Expected behavior

as before or you should cut a new major release

https://github.com/user-attachments/assets/1228865a-2c36-40ba-9e53-40b7a087095c

### Actual behavior

https://github.com/user-attachments/assets/43742758-ac9a-48c3-961a-f5e726f25af2

### Affected runtime and version

node 20

**Comment by wooorm** [comment]
Hi!

I think you mean this patch https://github.com/mdx-js/mdx/commit/c747990530d67dc2eca2dce05bda5ce60c80409e.
The old behavior was not intentional. The new behavior is intentional. It is assumed that few people depended on it. It broke other people. So, it is considered a patch.

See https://github.com/facebook/docusaurus/issues/9905#issuecomment-1976712289 for some more background info.

**Comment by dimaMachina** [comment]
@wooorm Even it was not intentional I am pretty sure there are a lot of folks who relied on it, instead of doing breaking change in `minor` 3.1 release you could do a release of MDX 4 with this change and drop off old Node.js 16 and require Node.js 18 for example

@remcohaszing what do you think?

**Comment by wooorm** [comment]
I am pretty sure basically nobody uses this. Why do you think many people use this?

What you link to in nextra is not changed.

What is no longer possible is that you can define a custom component (`Test` above), write regular JSX in it (`span` above), and then pass components to change them.

**Comment by dimaMachina** [comment]
> I am pretty sure basically nobody uses this. Why do you think many people use this?

Because it was an easy way to have reusable component with the same styles applied from `providerImportSource`

 > What you link to in nextra is not changed. It is not related

What do you mean? Below `MyComponent` is now unstyled

```mdx
export function MyComponent() {
  return (
    <>
      <table>
        <thead>
          <tr>
            <th>Month</th>
            <th>Savings</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>January</td>
            <td>$100</td>
          </tr>
          <tr>
            <td>February</td>
            <td>$80</td>
          </tr>
        </tbody>
        <tfoot>
          <tr>
            <td>Sum</td>
            <td>$180</td>
          </tr>
        </tfoot>
      </table>
      <h1>h1</h1>
      <h2>h2</h2>
      <h3>h3</h3>
      <h4>h4</h4>
      <h5>h5</h5>
      <h6>h6</h6>
    </>
  )
}

<MyComponent />
```

**Comment by wooorm** [comment]
I do not know what you mean. What does “unstyled” mean? You can use CSS if you want to style things?
Your issue above is not about style.
The Nextra issue is not about style?
Can you please provide some more info?

**Comment by dimaMachina** [comment]
> What does “unstyled” mean?

mdx components from `providerImportSource` no longer injected for html elements in `MyComponent` component

> You can use CSS if you want to style things?

Sure, the issue is that you did significant breaking change in `minor` release

**Comment by wooorm** [comment]
Your Nextra PR is wrong.

```
export function Table({ columns, data }) {
  return <table>{/* ... */}</table>
}

<Table columns={3} data={4} />
```

Has worked and still works. https://mdxjs.com/playground/

---

I understand that you don’t understand English well. You are mixing different things. That change in your Nextra PR is wrong. It has nothing to do with this. Components are still supported.

**Comment by dimaMachina** [comment]
> Your Nextra PR is wrong.
> 
> ```
> export function Table({ columns, data }) {
>   return <table>{/* ... */}</table>
> }
> 
> <Table columns={3} data={4} />
> ```
> 
> Has worked and still works. [mdxjs.com/playground](https://mdxjs.com/playground/)

You are taking this example out of the context of [written section](https://nextra-v2-rlux92mvs-shud.vercel.app/docs/guide/advanced/table#ways-to-fix-it). This section explained how to have a styled `<table>` and not how to use React Components in MDX.

> I understand that you don’t understand English well. You are mixing different things. That change in your Nextra PR is wrong. It has nothing to do with this. Components are still supported.

Thank you for pointing out my English 😂, my PR is not wrong, I removed the no longer worked way of styling `<table>`.

**Comment by wooorm** [comment]
Jeez. I do not understand why Nextra has this weird guide up.

If you want to pass components, pass components: `Span`, `Table`, `TableCell`. 

In JSX, `Span` is a reference to something. `span` is not a reference to something. `span` is `span`.

This was documented: https://mdxjs.com/docs/using-mdx/#components.

**Comment by dimaMachina** [comment]
There is no mention in Nextra’s docs of passing `<Table>` component somewhere, he was just locally declared in mdx file

**Comment by wooorm** [comment]
That’s the problem. If they passed `Table`, `Td`, whatever components they wanted, there are no hacks or workarounds needed, no guide needed.

**Comment by JounQin** [comment]
This is really a breaking change for document authors/tools. 😢 

When we migrate `md` `<table>` into `mdx`, we need to change all things now.

I hope we can have an option to get back old behavior, so that migrating from `md` to `mdx` would be much easier.

Or maybe a remark plugin is required for those tools to simulate previous behavior for html elements.

**Comment by JounQin** [comment]
https://github.com/mdx-js/mdx/tree/2.3.0/packages/react#propscomponents

I'm still on `@mdx-js/react@2.3.0`, does this change affect old versions? Maybe I'm meeting a different issue.

**Comment by wooorm** [comment]
Unrelated to this issue.

Please open a discussion with more info and what you want to do
