### ISSUE TITLE
Linting for mdx?

### ISSUE THREAD

**Issue by transitive-bullshit** [mdx-js/mdx#255]
MDX is definitely awesome 😄 

For a React design system project, I'm currently using a split of `.md` and `.js` files for functionality across many components that MDX would clearly simplify. My biggest hesitation to convert them, however, is is that it's really useful to have default `eslint` linting of the normal `js` / `jsx` files, both within my team's local editors and within CI.

*So my question is what is the status of linting mdx files?*

There seems to be some work going on within remark [here](https://github.com/remarkjs/remark/pull/345), but it seems pretty far from fulfilling any aspect of linting `mdx` files in general.

*On a related note, how are other people who're using mdx solving this issue?*

Thanks!

**Comment by silvenon** [comment]
I'm trying to understand what that PR you linked is about, could you help me break it down?

The problem is that, unlike JSX, MDX isn't being parsed by Babel, so I'm not sure how to approach this problem, we've mentioned this in #232 as well.

I really want this too, but I think we'll have to be very creative to solve it.

> On a related note, how are other people who're using mdx solving this issue?

We aren't. 😕

**Comment by timneutkens** [comment]
On a related note though, `prettier` supports `mdx` 😌

**Comment by functionalStoic** [comment]
Do either of these projects seem like a viable starting place?

https://github.com/DavidAnson/markdownlint
https://github.com/DavidAnson/vscode-markdownlint

**Comment by azz** [comment]
I just started working on **[`eslint-plugin-mdx`](https://github.com/azz/eslint-plugin-mdx)** which lets you lint the JSX and imports from MDX files with ESLint.

**Comment by transitive-bullshit** [comment]
This seems to be exactly that I (and presumably others) have been looking for -- thanks a ton @azz! I love how it should seamlessly integrate with existing JS linting workflows.

A few follow-up questions:

1. If I'm understanding correctly, `eslint-plugin-mdx` will lint only the js/jsx/import/export portions of `mdx` files concatenated together as though they were normal `js` files only with the `react/react-in-jsx-scope` rule disabled. Is that understanding accurate?
2. Is there any follow-up work to be done here? Can we effectively resolve this issue as closed?

Thanks again!

**Comment by azz** [comment]
1. 💯 Correct
2. Not sure, I think it's vest to use separate tools to lint the markdown part vs js parts, so ESLint + markdownlint. I'm not sure how well markdownlint supports mdx?

**Comment by transitive-bullshit** [comment]
> Not sure, I think it's best to use separate tools to lint the markdown part vs js parts, so ESLint + markdownlint. I'm not sure how well markdownlint supports mdx?

Wouldn't we just recommend `remark` over `markdownlint` since `mdx` is already using `remark` under the hood? tbh, I'm not sure what, if any substantive differences exist between the two markdown linters, though I'm much more familiar with the `unified` / `remark` ecosystem.

Eslint linting for the JS portions of mdx files is exactly what i was looking for and imho the 95% linting use case, so I'll close this issue. For future internet wanderers, feel free to open another issue that discusses general linting of `mdx` files that would also operate on the markdown portions.

Thanks!

**Comment by silvenon** [comment]
@azz awesome for creating eslint-plugin-mdx! 🎉 Feel free to submit a PR to this repo to add eslint-plugin-mdx to the docs.

**Comment by silvenon** [comment]
My bad, I see that you did! ⭐️

**Comment by jackkrone** [comment]
> > Not sure, I think it's best to use separate tools to lint the markdown part vs js parts, so ESLint + markdownlint. I'm not sure how well markdownlint supports mdx?
> 
> Wouldn't we just recommend `remark` over `markdownlint` since `mdx` is already using `remark` under the hood? tbh, I'm not sure what, if any substantive differences exist between the two markdown linters, though I'm much more familiar with the `unified` / `remark` ecosystem.
> 
> Eslint linting for the JS portions of mdx files is exactly what i was looking for and imho the 95% linting use case, so I'll close this issue. For future internet wanderers, feel free to open another issue that discusses general linting of `mdx` files that would also operate on the markdown portions.
> 
> Thanks!

Markdownlint views JSX as inline html. You can enable markdownlint to allow inline html (see rule [MD033](https://www.npmjs.com/package/markdownlint)) and therefore to ignore the jsx in an mdx file. I think this would be the ideal way to use it in combination with `eslint-plugin-mdx`. I'm not sure how it will handle import and export statements though.
