### ISSUE TITLE
render incorrectly when there is punctuation before *

### ISSUE THREAD

**Issue by angular-moon** [mdx-js/mdx#2552]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.1.0

### Steps to reproduce

https://stackblitz.com/edit/github-qz545m?file=index.js

### Expected behavior

**hello:** world (there should be no space between hello and world)

### Actual behavior

**hello:**world

### Affected runtime and version

node@20.13.1

**Comment by wooorm** [comment]
That’s markdown. Try it here. Or on [CommonMark](https://spec.commonmark.org/dingus/?text=incorrectly%3A%20**hello%3A**world)

```
incorrectly: **hello:**world
```

incorrectly: **hello:**world
