### ISSUE TITLE
Using MDX inline to the build or as a component?

### ISSUE THREAD

**Issue by romellogoodman** [mdx-js/mdx#278]
Hey! Is there a way to dynamically use MDX without the use of a markdown file. For example in places where I just want to pass in markdown to a component and have it render.

Something like this is what im thinking:

`
// Import the component
import MDX from 'mdx'

// Have some markdown
const markdown = '.....the markdown'

// Pass the markdown in and render it
ReactDOM.render(<MDX markdown={markdown}/>, document.getElementById('root'));
`

Thanks!

**Comment by timneutkens** [comment]
https://github.com/mdx-js/mdx/tree/master/packages/runtime

**Comment by romellogoodman** [comment]
That works perfectly! I'll close the issue
