### ISSUE TITLE
<p>tag does not not behave as <div> for fragments

### ISSUE THREAD

**Issue by danmarshall** [mdx-js/mdx#280]
Hello, I would like to do is substitute a value in a line of text.
This is somewhat related to #15.

Given these examples:
```html
The #1 value of x is <span>{props.scope.x}</span>.

The #2 value of x is 
<span>{props.scope.x}</span>.

<div>The #3 value of x is {props.scope.x}.</div>

<p>The #4 value of x is {props.scope.x}.</p>
```
Result:
![image](https://user-images.githubusercontent.com/11507384/46228220-3aeb5c00-c316-11e8-986c-578b09e6d6c2.png)

Ideally it would be nice if there was a way to inline a component as in 1 but I'm ok with the workaround as in 3 and 4. The bug is that while it works for the `<div>` tag, it does not work for the `<p>` tag.

**Comment by danmarshall** [comment]
Update-  This works:
```html
<p>
    The value of x is {props.scope.x}.
</p>
```
But this still does not:
```html
<p>The value of x is {props.scope.x}.</p>
```

**Comment by silvenon** [comment]
I think it's related to https://github.com/mdx-js/mdx/issues/246#issuecomment-422076927. This is my priority because it's a really unexpected bug and makes MDX way less awesome.

**Comment by danmarshall** [comment]
Ok I will close this, since it appears that you are already tracking it in #246, thanks!
