### ISSUE TITLE
add remark plugins support in runtime

### ISSUE THREAD

**Issue by naivefun** [mdx-js/mdx#282]
Now I do not see options available for plugins?
Scope for custom react components
Components for html tag renderer

Am I right?

**Comment by silvenon** [comment]
Indeed, support for `mdPlugins` and `hastPlugins` seems to be missing from runtime.

**Comment by buz-zard** [comment]
Is this actually deployed? I'm having issues with `0.16.6` version.

By looking at the actual build output https://unpkg.com/@mdx-js/runtime@0.16.6/dist/index.js
`var jsx = _mdx2.default.sync(children, { skipExport: true }).trim();` plugins don't get passed to mdx sync method 🤔

I copied the source of runtime and it works perfectly, maybe this is a build issue?
