### ISSUE TITLE
use mdx in create-react-app with eject

### ISSUE THREAD

**Issue by liuzhiyang0113** [mdx-js/mdx#292]
Check it out for me，i use mdx in create-react-app with eject.
webpack.config.dev.js
<code>
{
   test:'/\.mdx?$/',
   use:[
      {
         loader:require.resolve('babel-loader'),
          options:{
             babelrc: false, 
             presets: require.resolve('babel-preset-react-app'), 
              cacheDirectory: true
           }
       },
       "@mdx-js/loader"
   ]
}
</code>

but it put an error .
> Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/hello.2e5bf04c.mdx') is not a valid name.

**Comment by piotrf** [comment]
Hey, @liuzhiyang0113, what was your issue about?

**Comment by davidyeiser** [comment]
I had this same error but had forgotten to "rewire" the npm scripts in `package.json`

```
"scripts": {
    "start": "react-scripts start"
  }
```

to:

```
"scripts": {
    "start": "react-app-rewired start"
  }
```
