### ISSUE TITLE
intellij/webstorm syntax highlighting support

### ISSUE THREAD

**Issue by ryee-dev** [mdx-js/mdx#293]
_Originally posted by @ryee-dev in https://github.com/mdx-js/mdx/issues/119#issuecomment-428648272_

**Comment by silvenon** [comment]
Unfortunately there doesn't seem to be any updates on this. I added VS Code support because I'm using VS Code. Maybe you could take a stab at intellij/webstorm? 😉 

I'm closing this because #119 is where we track editor support.
