### ISSUE TITLE
Enforce a style guide for our Markdown files

### ISSUE THREAD

**Issue by silvenon** [mdx-js/mdx#311]
Continuing from #300, we should enforce rules for our Markdown files by using remark-cli and remark-preset-wooorm to match unified. This should be added to lint-staged under `*.md` key and as part of the test script as well, that way errors can be detected as early as pre-commit.

@wooorm I'm assigning you for now, but if you don't have time I can do it instead.

**Comment by wooorm** [comment]
Alright I’ll try to get something we can discuss out tomorrow! P.S. could someone give me write access to make it easier to collaborate?

**Comment by silvenon** [comment]
I think @johno can do that.

**Comment by johno** [comment]
Done.

**Comment by wooorm** [comment]
OK I’ll send the docs PR tomorrow. Found a bunch of broken things, and raised some issues where docs were different from code already!
