### ISSUE TITLE
0.16.2 mdx-loader throw error

### ISSUE THREAD

**Issue by janryWang** [mdx-js/mdx#322]
### Subject of the issue

![image](https://user-images.githubusercontent.com/4060976/48819211-c8cd4b80-ed89-11e8-8568-b3bd480a3107.png)

![image](https://user-images.githubusercontent.com/4060976/48819317-514bec00-ed8a-11e8-9b3f-c3040e163db7.png)

### Your environment

*   Name and version of operating system
*   Names and version of required packages
*   Version of node, npm, yarn, or names and versions of browser

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behaviour

What should happen?

### Actual behaviour

What happens instead?

**Comment by janryWang** [comment]
@silvenon

**Comment by johno** [comment]
Thanks for reporting @janryWang, we should have a new release published shortly with a fix.
