### ISSUE TITLE
0.16.3 mdx-loader throw error: props is not defined

### ISSUE THREAD

**Issue by wangyiliangnet** [mdx-js/mdx#324]
### Subject of the issue

![image](https://user-images.githubusercontent.com/5622029/48879984-4906b600-ee49-11e8-8d49-b1538ca57f82.png)

It seems 'props' is missed in mdx-hast-to-jsx.js。
![image](https://user-images.githubusercontent.com/5622029/48880056-971bb980-ee49-11e8-9ad5-28e84386f269.png)

The problem solved when i added definition of 'props'，but i am not sure if it's the right way:
![image](https://user-images.githubusercontent.com/5622029/48880078-ba466900-ee49-11e8-9002-2e5aff581b0e.png)

**Comment by silvenon** [comment]
We'll see if it's useful for users to also receive `components` in layout, or if we should leave it out using rest/spread like you shown.

You can expect a patch release today or tomorrow.

**Comment by silvenon** [comment]
I believe this is fixed now in v0.16.4.
