### ISSUE TITLE
@mdx-js/loader need support custom markdown html element's classname or class prefix.

### ISSUE THREAD

**Issue by janryWang** [mdx-js/mdx#325]
### Subject of the issue

support custom markdown html element's classname or class prefix. I need the ability to control the theme style.

### Your environment

not a bug

### Steps to reproduce

not a bug

### Expected behaviour

not a bug

### Actual behaviour
not a bug

**Comment by silvenon** [comment]
Could you elaborate using input and output example code?

**Comment by janryWang** [comment]
like this

```
module.exports = {
  module: {
    rules: [
      {
        test: /.mdx?$/,
        use: ['babel-loader',{loader:'@mdx-js/loader',options:{className:"mdx"}}]
      }
    ]
  }
}

```

output

```
<MDXTag name="h1" className="mdx" />

```

**Comment by ChristopherBiscardi** [comment]
can't you do this by using an MDXProvider and mapping over the components to add a className to every element that gets rendered?

**Comment by silvenon** [comment]
@janryWang assuming that you want resulting DOM elements to contain a class, MDX core isn't a place for that. [rehype-add-class](https://github.com/martypdx/rehype-add-classes) might meet your needs, otherwise you could create your own plugin.

**Comment by timneutkens** [comment]
The way @ChristopherBiscardi is outlining also saves a ton in bundle size.
