### ISSUE TITLE
export feature does not work unless surrounded by newlines

### ISSUE THREAD

**Issue by jescalan** [mdx-js/mdx#340]
This is a strange issue, but finally found the source after digging for a bit. Basically, if you run an [export, like this](https://mdxjs.com/syntax#export-default), but do not include newlines around the export, it is not detected at all, and will drop the export verbatim as a string into the resulting mdx file. As far as I know, es6 modules do not have any rules around adding extra newlines, so the behavior was pretty confusing to me.

I would be more than happy to submit a patch to fix this, just want to make sure that the maintainer(s) of the library give me the green light first!

To reproduce - this works:

```
import Layout from './Layout'

export default ({ children }) => <Layout some='metadata' >{children}</Layout>

# Hello, world!
```

However, this does not:

```
import Layout from './Layout'
export default ({ children }) => <Layout some='metadata' >{children}</Layout>

# Hello, world!
```

**Comment by johno** [comment]
Yeah, this is a bug in the way we're parsing import/export nodes. I'm hoping we can avoid needing to bring in a full-fledged js parser. Maybe a solid initial fix is to check if the following line begins with `export` and splitting it up?

We'd gladly accept a patch if you'd like to work on it. ❤️

**Comment by jescalan** [comment]
Ah sorry just saw this comment after leaving a comment on the other one about how it might be better to bring in an actual parser. I will definitely submit some initial regex fixes, but it does feel super fragile to rely on regex long term. Any further reasoning beyond wanting to avoid bringing in a real parser (other than perf)?

**Comment by johno** [comment]
Haha, looks like we're dancing between both your issue : )

You can find my [initial reasoning here](https://github.com/mdx-js/mdx/issues/341#issuecomment-443026648).

**Comment by johno** [comment]
The other thing is introducing a substantially larger bundle size, but that might be inevitable to ensure our parsing is solid. It's definitely something I'm open to, but might make sense as its own issue to weigh the pros and cons to kick off such an initiative.

**Comment by johno** [comment]
I'm going to preemptively close this because it will be supported in 0.18 that should go out next week. Thanks for opening up the issue!
