### ISSUE TITLE
Automate canary releases to npm

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#344]
As @ChristopherBiscardi [mentioned](https://github.com/mdx-js/mdx/issues/343#issuecomment-443976324) we should begin automating canary releases to npm. We can follow the flow similarly to `next` and `gatsby-mdx` via Travis CI.

**Comment by ChristopherBiscardi** [comment]
Seems like a good first issue for someone. Main task is to add the script mentioned in the comment above, and have it execute only if the travis build is master branch and everything else has passed.

**Comment by leimonio** [comment]
This PR https://github.com/mdx-js/mdx/pull/376 has also failed because of npm authentication on Travis CI.

**Comment by johno** [comment]
I set an `NPM_AUTH_TOKEN` as an env var. I was under the impression that would be picked up for npm authentication but I guess I'm mistaken?

**Comment by leimonio** [comment]
It doesn't seem to properly getting deployed, just checked latest build and fail for same reason. According to [documentation](https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#set-the-token-as-an-environment-variable-on-the-cicd-server) `NPM_TOKEN` env variable should be used.

**Comment by johno** [comment]
I've updated the token env var to be `NPM_TOKEN`. Hopefully that does the trick.

**Comment by johno** [comment]
Looks like this is almost working! Looks like the way the ci versions are being generated makes is [causing issues](https://travis-ci.org/mdx-js/mdx/jobs/491742432).

**Comment by leimonio** [comment]
I've added another script to explicitly fetch tags before publishing https://github.com/mdx-js/mdx/pull/400 We're almost there! 🤞

**Comment by johno** [comment]
Looks like we're now g2g, thanks @leimonio!

**Comment by leimonio** [comment]
@johno That's great, glad I helped! Let me know if I can help to migrate current CI/CD configuration to circleci.

**Comment by johno** [comment]
If you wanted to take that on, feel free to write up an issue and assign yourself. That would be greatly appreciated!
