### ISSUE TITLE
Instructions on running tests

### ISSUE THREAD

**Issue by jonsherrard** [mdx-js/mdx#351]
### Subject of the issue

I've got an _idea_, for a contribution I'd like to make. My first port of call was to try and run the tests "out of the box".

A fresh `yarn install && yarn test` outputs:

```
yarn run v1.5.1
$ remark . -qf && eslint . && lerna run test

/Users/jonsherrard/playground/mdx/packages/runtime/src/index.js
  4:22  error  Unable to resolve path to module '@mdx-js/tag'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)

error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c remark . -qf && eslint . && lerna run test
Directory: /Users/jonsherrard/playground/mdx
Output:
".
```

I've tried a few combinitions of `lernna link` in various packages, to no avail.

### Your environment

*   Name and version of operating system
MacOS 10.14 (Mojave)
*   Names and version of required packages
Fresh `git clone` only
*   Version of node, npm, yarn, or names and versions of browser
Node v10.13.0, NPM v6.4.1, Yarn 1.5.1

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

`git clone git@github.com:mdx-js/mdx.git && cd mdx && yarn install && yarn test`

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behaviour

Tests should run and pass

### Actual behaviour

```
yarn run v1.5.1
$ remark . -qf && eslint . && lerna run test

/Users/jonsherrard/playground/mdx/packages/runtime/src/index.js
  4:22  error  Unable to resolve path to module '@mdx-js/tag'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)

error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c remark . -qf && eslint . && lerna run test
Directory: /Users/jonsherrard/playground/mdx
Output:
".
```

**Comment by timneutkens** [comment]
https://github.com/mdx-js/mdx/blob/master/package.json#L27

Sound like we should add a `prepublish` there that runs `npm run bootstrap` so that `npm install` / `yarn` would just work out of the box.

**Comment by jonsherrard** [comment]
Hi @timneutkens I did try running `npm run bootstrap` but it doesn't work.

Also you need to run `npm install` first, so that the lerna package is available, could that be an issue?

So far the only way I've got it working is running `yarn add @mdx-js/tag` inside `packages/runtime`

**Comment by wooorm** [comment]
What I do is run `yarn install`, and then I follow [Travis](https://github.com/mdx-js/mdx/blob/fc40de3ea63f58e8453458a54575734f40bcfd90/.travis.yml#L7) (`yarn lerna exec yarn install` and `yarn lerna link --force-local`). That works for me 🤷‍♂️

**Comment by jonsherrard** [comment]
Thanks @wooorm, I'll give that a go and that submit a PR for `contributing.md` and `yarn run bootstrap`

**Comment by jonsherrard** [comment]
@wooorm's solution works. (thanks!)
