### ISSUE TITLE
Document alternative installation/setup options

### ISSUE THREAD

**Issue by regrettably** [mdx-js/mdx#355]
The getting started guide suggests that you can only use `mdx` through use of npm's `init`.  
Users who wish to integrate `mdx` into an existing project should have a documented path to follow, including installation of `mdx` and `mdx-loader`

**Comment by johno** [comment]
Thanks for opening up this issue! We've pushed a large docs reorganization and revamp that should hopefully address this. Please let us know if it isn't sufficient or what can be more clear.

https://mdxjs.com/getting-started/webpack
