### ISSUE TITLE
contents of multi line strings get parsed as markdown

### ISSUE THREAD

**Issue by giladv** [mdx-js/mdx#357]
osx 10.13
mdx loader 0.16.6
node 9.10

the following will throw an unexpected token error 
```mdx
<MyCodeBlockComp>{`
   some display code

   more display code
`}</MyCodeBlockComp>
```
__this will also happen if the multi line string would be passed as a prop and not as children__

internally i can see it tried to wrap the 'more display code' line inside a MDX paragraph although its inside JS string.

if this is by design - how am i suppose to pass multi line strings to  components? 
let's say a code block component which accepts lines to highlight so i cant use the built in ``` syntax.

**Comment by ChristopherBiscardi** [comment]
> let's say a code block component which accepts lines to highlight so i cant use the built in ``` syntax.

Without addressing the original multiline-string issue, you *can* accomplish this with the built-in codeblock syntax. If you write it like:

![markdown meta block](https://user-images.githubusercontent.com/551247/50551010-43ae3f80-0c2f-11e9-94e5-a79928c308ea.png)

If you look at the above example, you will end up with a prop named `highlight` that includes the string `1,4-5,19` as its value. You can then process and highlight as desired with your preferred method (such as [prism-react-renderer](https://github.com/FormidableLabs/prism-react-renderer), etc)

**Comment by johno** [comment]
Going to close this since we can track the progress of this parsing bug in #195. Thanks for opening up the issue!

**Comment by Stvad** [comment]
it seems that the linked issue is resolved in v2 which I don't think I can use (using mdx via gatsby plugin). Is there any workarounds for this?

**Comment by ChristianMurphy** [comment]
@Stvad https://github.com/mdx-js/mdx/discussions is a good place to ask questions
