### ISSUE TITLE
Execute function returning mardown?

### ISSUE THREAD

**Issue by danm** [mdx-js/mdx#361]
Loving MDX,
I want to abstract some markdown to a seperate file where you can pass params to a function and it will generate and return a Markdown table which can be rendered by MDX.
Are there docs on how I would accomplish this?
thanks

**Comment by timneutkens** [comment]
Why not use a React component at that point 🤔 It'd potentially lead to less code too.

**Comment by johno** [comment]
Glad you're loving MDX @danm! The preferred approach in MDX for dynamic data is to use the same components that are being rendered via `MDXProvider`, so you can do something like:

```jsx
import { Table, TableRow } from './ui'

# Here's my table

<Table>
  {props.someData.map(row => (
    <TableRow key={id}>
      <TableCell>{row.foo}</TableCell>
      <TableCell>{row.bar}</TableCell>
    </TableRow>
  ))}
</Table>

Other Markdown content.
```

If you have any other questions feel free to reach out!

**Comment by polarathene** [comment]
@johno I've got a similar scenario to this issue. 

I needed to conditionally return different inline code in a MDX paragraph, I used a react component(technically another MDX doc with a react component) but as I'm returning a string wrapped in backticks, it's either escaped and rendered as plain text, or if I use a blank line above the string(within the react component), it'll be rendered as markdown but wrapped with a `<p>` tag breaking the sentence onto a new line.

```JSX
A string with <DynamicInlineCode /> inlined.
```
Further detailed in #241 .
