### ISSUE TITLE
Checking whether a component is MDX

### ISSUE THREAD

**Issue by hugmanrique** [mdx-js/mdx#368]
### Subject of the issue

I'm using Next to serve both `.js` and `.mdx` pages and I couldn't find any (_clean_) way to detect whether the page component in `getInitialProps` or the app `render()` method itself is a MDX component. I also created the page element on the `render` method to check if the component had a `displayName` or any special prop, but I couldn't find any. I also tried to check if that element was `instanceof MDXTag` but it returned false (as the page component doesn't extend MDXTag, it just returns it from the `render` method 😓)

One dirty way I found to check if the component is MDX was `element.toString()` but I would prefer to avoid such a hack.

I need this method to conditionally render a layout and would prefer to not have to declare a boolean export on each `.mdx` file.

The API of a `isMDXElement` method could be similar to [`React.isValidElement()`](https://reactjs.org/docs/react-api.html#isvalidelement). Maybe components produced by `@mdx-js/loader` could have a `static` class property or a named export?

I'm opening this before creating a PR because I believe the approach should be discussed before the implementation.

**Comment by johno** [comment]
I don't see any reason why we couldn't add a static boolean/method to `@mdx-js/tag`. Should be nice and lightweight:

```js
class MDXTag extends Component {
  static isMDXElement = () => true

  render() {
    // ...
  }
}
```

cc/ @timneutkens

**Comment by hugmanrique** [comment]
How do you propose users could use this API?

I was talking more about the output produced by `mdx-loader`. An `MDXTag` is returned from the `render` method, but we cannot access it until React has rendered it (and even then, it's pretty difficult to get). I was thinking more about a static prop on the output of `mdx-loader`.

**Comment by Rufus31415** [comment]
I think I've encountered the same problem, which is to detect an MDX component with @next/mdx. For example, to check whether a page is an .md or .mdx, it would be nice to have a isMDXComponent property :

**_app.js :**
``` js
function MyApp({ Component, pageProps }) {
  if (Component.isMDXComponent) {
    // it's a .mdx page
  }
}
```
---

To add this IsMDXComponent property to MDXContent, I created a recma plugin (it's a bit cumbersome, but I couldn't find a simpler way)

**next.config.js :**
```js
const withMDX = require('@next/mdx')({
  extension: /\.(md|mdx)$/,
  options: {
    recmaPlugins: [() => function transformer(ast) {
      // add property isMDXComponent to MDXContent
      ast.body.unshift({
        type: 'ExpressionStatement',
        expression: {
          type: 'AssignmentExpression',
          operator: '=',
          left: {
            type: 'MemberExpression',
            object: { type: 'Identifier', name: 'MDXContent' },
            property: { type: 'Identifier', name: 'isMDXComponent' },
            computed: false,
            optional: false
          },
          right: { type: 'Literal', value: true }
        }
      })
    }]
  }
})
```

**Comment by remcohaszing** [comment]
That plugin exists as [`recma-mdx-is-mdx-component`](https://github.com/remcohaszing/recma-mdx-is-mdx-component).
