### ISSUE TITLE
Missing mdPlugins/hastPlugins support in 0.16.6

### ISSUE THREAD

**Issue by buz-zard** [mdx-js/mdx#372]
### Subject of the issue

The `0.16.6` build output https://unpkg.com/@mdx-js/runtime@0.16.6/dist/index.js don't pass plugins to mdx sync method.
```js
var jsx = _mdx2.default.sync(children, { skipExport: true }).trim();
```

Although `0.15.7` works fine - https://unpkg.com/@mdx-js/runtime@0.15.7/dist/index.js

```js
  var jsx = _mdx2.default.sync(children, {
    mdPlugins: mdPlugins,
    hastPlugins: hastPlugins,
    skipExport: true
  }).trim();
```

### Your environment

`"@mdx-js/runtime": "^0.16.6",`

### Steps to reproduce

Try to pass remark plugins via prop `mdPlugins`. They don't get used.

### Expected behaviour

They should be used.

### Actual behaviour

They don't get used.

**Comment by johno** [comment]
Thanks for creating this issue @buz-zard! It looks like the runtime package build script was broken for a while so an old version was being published 🤦‍♂️. It should be fixed for all 0.17.x versions.
