### ISSUE TITLE
 Functions are not valid as a React child

### ISSUE THREAD

**Issue by mvolkmann** [mdx-js/mdx#374]
### Subject of the issue

With the simplest use case I can think of, I get this message in the devtools console:

"Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it."

### Your environment

*   Name and version of operating system: macOS
*   Names and version of required packages: @mdx-js/runtime 0.16.6
*   Version of node, npm, yarn, or names and versions of browser: Chrome latest

### Steps to reproduce

1. Create a new React app with create-react-app.
2. Edit src/App.js.
3. Add this at top: import MDX from '@mdx-js/runtime';
4. Add this anywhere in rendered output: <MDX># Test</MDX>
5. npm start

### Expected behaviour

What should happen? It should render a Markdown title.

### Actual behaviour

What happens instead? It doesn't output anything in the browser window and outputs the warning message above in the devtools console.

I realize that I don't need to use this approach for static markdown, but I need to use it with markdown text that will change a runtime.

**Comment by numso** [comment]
I'm running into this same issue. FWIW, if I copy the contents of https://github.com/mdx-js/mdx/blob/master/packages/runtime/src/index.js into my project and use that instead, my mdx renders fine. It's not ideal but this workaround has gotten me unblocked for now.

https://codesandbox.io/s/p76qkpzkk7

**Comment by johno** [comment]
This _should_ be fixed in the latest minor version (0.17.X). Please reopen if there's still an issue.
