### ISSUE TITLE
Fresh repository clone won't test without extra build step

### ISSUE THREAD

**Issue by AlmeroSteyn** [mdx-js/mdx#377]
### Subject of the issue

When doing a fresh clone of the `mdx` repository the `test` and `format` instructions fail due to `/packages/tag` not being built.

I do not know if this is specifically related to a `Windows` development environment. I discussed this with @silvenon and initially we suspected this was related to it being on Windows but the fact that it is related to `tag` not being built makes me question that.

### Your environment

*   Windows 10
*   MDX latest code
*   Node 8.11.2, Yarn 1.12.0

### Steps to reproduce

Clone a completely clean instance of the repository. Run `yarn` followed by `yarn bootstrap` followed by `yarn test`.

### Expected behaviour

The tests should run.

### Actual behaviour

The tests fail with message that `@mdx-js/tag` cannot be found.

### Hotfix

Go to `/packages/tag` directory and run `yarn build`. After that the tests run and passes.

**Comment by mxstbr** [comment]
This also happens on MacOS.

**Comment by jonsherrard** [comment]
There's a fix for this here: https://github.com/mdx-js/mdx/issues/351

There was a note added to the docs, but maybe it's still not clear enough :/

**Comment by johno** [comment]
Perhaps we can have the build run as a `postinstall` script for `tag`?

**Comment by wooorm** [comment]
@johno maybe I’m missing something, or it’s a typo, but could you elaborate on `tag`?

**Comment by johno** [comment]
@wooorm Sure! `tag` refers to the `@mdx-js/tag` library that lives in `packages/tag` which is causing the fresh install errors when running tests because it requires a babel compilation build step.

**Comment by AlmeroSteyn** [comment]
Thanks for actioning this.
