### ISSUE TITLE
Pass exports to layout component

### ISSUE THREAD

**Issue by mxstbr** [mdx-js/mdx#378]
It would be neat if MDX automatically passed all named exports to the default exported layout component. For example, right now I have to do the following:

```JS
import BlogPost from '../../components/BlogPost';

export const meta = {
  published: true,
  title: 'Tech Choices I Regret at Spectrum',
  // ...more meta data...
}

export default ({ children }) => <BlogPost meta={meta}>{children}</BlogPost>
```

It would be neat if I could do this instead and `BlogPost` would get `meta` passed as a prop automatically (on top of `children` of course):

```JS
import BlogPost from '../../components/BlogPost';

export const meta = {
  published: true,
  title: 'Tech Choices I Regret at Spectrum',
  // ...more meta data...
}

export default BlogPost;
```

That way, my `BlogPost` could have a `getInitialProps` method to fetch data with Next.js. Right now, I have to asynchronously fetch data in the `componentDidMount` lifecycle, which is not the best user experience.

**Comment by loganpowell** [comment]
It took me forever to find this... Thank you @mxstbr

**Comment by deadcoder0904** [comment]
This doesn't work with using a loader, right? Example → https://github.com/tailwindlabs/blog.tailwindcss.com/blob/master/next.config.js#L89
