### ISSUE TITLE
Next.js getInitialProps compatibility

### ISSUE THREAD

**Issue by mxstbr** [mdx-js/mdx#382]
### Subject of the issue

I thought that after #379, this would be possible in Next.js:

```JS
const BlogPost = () => {};

BlogPost.getInitialProps = async () => {
  const data = await fetch();
  return data;
};
```

```JS
import BlogPost from '../../components/BlogPost';

export default BlogPost;
```

Unfortunately, the `getInitialProps` method is never called, as the BlogPost is not the most top-level component that is exported:

```JS
export default ({components, ...props}) => <MDXTag name="wrapper" Layout={({ children }) => <BlogPost meta={meta}>{children}</BlogPost>} layoutProps={props} components={components}>
```

Is there any way to make it possible to run a `getInitialProps` function from my `BlogPost`? I'm not sure what the right approach here is, as obviously the `MDXTag` component needs to be wrapped around the BlogPost children... Maybe a patch in Next.js could make this possible? Not sure.

/cc @timneutkens

**Comment by sergiodxa** [comment]
I think the only way is to create a page and import the MDX there, then assign the getIntialProps and export it again.

**Comment by mxstbr** [comment]
I think MDX could do something like

```JS
if (Layout.getInitialProps) {
  MDXTag.getInitialProps = Layout.getInitialProps;
}
```

Right?

**Comment by sergiodxa** [comment]
That would be great! ping @timneutkens

**Comment by johno** [comment]
In the perfect world MDX wouldn't need to know about Next.js implementation details.

The tricky part is that I don't think we can really transpile MDX without wrapping it in a component (since we have to export a component) which would break all statics since they're not hoisted. Something interesting that we could consider though is some type of `static` syntax because I can definitely see the usecase for being able to define statics in an MDX doc.

```js
import fetchBlog from '../lib/fetch-blog'

static getInitialProps = fetchBlog(123)

# Hello, world!
```

Which would transpile to:

```js
import fetchBlog from '../lib/fetch-blog'

const MDXContent = props => (
  // ...
)

MDXContent.isMDXComponent = true
MDXContent.getInitialProps = fetchBlog(123)

export default MDXContent
```

I'll need to think about this a bit more as this is just off the top of my head. Do you have any thoughts @timneutkens or @ChristopherBiscardi?

**Comment by johno** [comment]
Also, `getInitialProps` handling (as @mxstbr [proposed](https://github.com/mdx-js/mdx/issues/382#issuecomment-467752698)) could be done at the loader level AFAICT in Next.js since it can be appended to the file.

**Comment by mxstbr** [comment]
Might be worth just copying all statics with https://github.com/mridgway/hoist-non-react-statics, that way no Next.js implementation details are exposed?

**Comment by johno** [comment]
Yeah, that might be the best route 👍. Then we don't have to introduce new `static` syntax which is nice.

**Comment by timneutkens** [comment]
I wouldn't use hoist-non-react-statics, it brings in react-is 😅

**Comment by johno** [comment]
What will your future approach be in Next.js @timneutkens?

**Comment by timneutkens** [comment]
@johno just copying getInitialProps

**Comment by adamwathan** [comment]
Anyone know if there's any way to do this nowadays? 🤔

**Comment by johno** [comment]
This isn't currently possible when MDX is used for the page entrypoint. You'd have to use a JS entrypoint and pass along the data to the MDX file:

```js
import React from 'react'

import Doc from '../path/to/file.mdx'

const Component = props => <Doc {...props} />

Component.getInitialProps = async () => {
  // ...
}

export default Component
```

That said, I _believe_ first-class support of `getInitialProps` for MDX pages will be coming in an upcoming minor version of Next.js (release date TBD).

**Comment by leerob** [comment]
This is also something I'd be interested in. I'm trying to load information about a blog post from Firebase on page load inside an MDX file. Something like this:

```js
Post.getInitialProps = async function({pathname}) {
    const db = await loadDb();
    const item = await db.child(pathname).once('value');

    return {value: item.val()};
};
```

However, because I'm using `.mdx` files as page entry points in my application (versus React components), this doesn't work as mentioned above.

**Comment by jescalan** [comment]
I have implemented a fix for this, but it definitely is not ideal when it comes to user-friendliness. It is fairly simple though, a couple lines in a custom `_app.js` file.

```js
import App, { Container } from 'next/app'

class NextApp extends App {
  static async getInitialProps({ Component, ctx }) {
    let pageProps = {}

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx)
    } else if (Component.isMDXComponent) {
      pageProps = await Component({}).props.originalType.getInitialProps(ctx)
    }

    return { pageProps }
  }

  render() {
    const { Component, pageProps } = this.props

    return (
      <Container>
        <Component {...pageProps} />
      </Container>
    )
  }
}

export default NextApp
```

This will ensure that `getInitialProps` on your mdx layout is run and passed through the containing elements.

**Comment by viztor** [comment]
Maybe we should have a conventional export other than default to hook custom methods, maybe something like export methods = {}. then expand all of these on the parent layout which would leave us agnostic of next.js implementation detail.

**Comment by johno** [comment]
I'm going to go ahead and close this since @jescalan has implemented a work around. In a future version of Next.js this will be handled more natively.

Btw, is there a related Next.js issue that folks would be able to subscribe to @timneutkens?

**Comment by jescalan** [comment]
My workaround is really woefully inadequate as a user experience to be honest - it's still roughly on my list to look into [`wrapExport`](https://github.com/mdx-js/mdx/blob/e48dfd8d9783f2c46ee32fe4c00b0000828c1472/packages/mdx/mdx-hast-to-jsx.js#L173) here but not quite pressing enough. I do think perhaps this would be more appropriate filed in nextjs though

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/issues/8535

**Comment by daveybrown** [comment]
I'm following this issue. The answer should fix the compatibility issue when using next-mdx-enhanced with next-i18next.

```You have not declared a namespacesRequired array on your page-level component: MDXContent.```
