### ISSUE TITLE
No documentation for async methods

### ISSUE THREAD

**Issue by balupton** [mdx-js/mdx#387]
Seems the only API that is documented for using MDX directly is the sync API at https://mdxjs.com/advanced/sync-api

However it refers to an async API, however there is no documentation for any async API.

It would be nice for the documentation for direct use to be more elaborate.

**Comment by balupton** [comment]
At the end of the day, all I am after is something that returns all the exports of the mdx file.

**Comment by johno** [comment]
Thanks for opening up this issue! I've added more detailed docs to the v1 branch (since the output of the JSX will be changing) that can be found at: https://v1-alpha.mdxjs.com/advanced/

If you think something is missing or it could be improved please let us know!
