### ISSUE TITLE
Convert Compiled MDXContent Class back to Function

### ISSUE THREAD

**Issue by ChristopherBiscardi** [mdx-js/mdx#389]
in v0.16 we change the compiled MDX to be a class to solve some rendering issues and stabilize the reference to layouts defined inline.

In order to support hooks, etc in MDX content, we should convert it back to a function while maintaining the stable layout reference.

**Comment by timneutkens** [comment]
Why would we support hooks in mdx content, it sounds very strange to me to allow that, people can use hooks inside components rendered in MDX even without changing the class to a function.

I'm +1 on changing it back to a function but not for the reason to allow hooks in MDX, you can't write JS in MDX anyway, only `import` `export`.

The right reason to change this is for example to allow Vue to render MDX output.

**Comment by johno** [comment]
This has landed in the v1 alpha.
