### ISSUE TITLE
Migrate withMDXComponent to useContext 

### ISSUE THREAD

**Issue by alexandernanberg** [mdx-js/mdx#416]
### Subject of the issue

Migrate the `withMDXComponent` to `React.useContext`. That would remove the `Consumer` component in the tree which would clean up the ReactDevtools view. This would need react >= 16.8 so it's a breaking change. 

I'd be happy to create a PR for this if it's something you want to add.

**Comment by johno** [comment]
We'd happily accept a PR into the v1 branch! That's currently where all our breaking changes will live as we complete the rest of the tasks for the v1 release.

**Comment by johno** [comment]
Now in the v1 branch, thanks @alexandernanberg!
