### ISSUE TITLE
feature request: Add "props" property on jsx node types

### ISSUE THREAD

**Issue by alexandernanberg** [mdx-js/mdx#419]
### Subject of the issue

AFAIK there is no way to pass props to the component from a plugin without inlining it in the value e.g. `<Image foo="bar" />`. What I'd like to see is the ability to add props with a `node.props` field as well. That would be helpful if you need to pass props that are an object for example.

Plugins would then be able to do this:

```js
node.type = 'jsx'
node.value = `<MyComponent />`
node.props = {
  foo: { bar: 'baz' },
}
```

**Comment by johno** [comment]
Interesting 🤔. Would you then expect the JSX output to be?:

```js
<MyComponent foo={{ bar: 'baz' }} />
```

Also, could you elaborate on your use case a bit?

**Comment by alexandernanberg** [comment]
Yeah exactly! 

I guess the use case would be whenever you need to pass a prop that is an object. In my specific use case I'm trying to emulate [gatsby-remark-images](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-images) but with a custom React component instead of a regular `<img />` element. [My current solution](https://github.com/strt/www/blob/8d2494659c4638c01bf518e81d78766788d5610b/plugins/gatsby-remark-image-component/index.js#L86).

There might be a better solution to my problem that I'm unaware of 😄

**Comment by alexandernanberg** [comment]
Just noticed that children of the component aren't presented as children in the AST. This makes it a bit difficult to work with imo.

So 

```mdx
<Column width="50%">
  
  ![](../path-to-image.jpg)

</Column>
```

is parsed as 

```js
{ type: 'jsx',
  value: '<Column width="50%">',
  position: [Position] },
{ type: 'text', value: '\n' },
{ type: 'element',
  tagName: 'img',
  properties: [Object],
  children: [],
  position: [Object] },
{ type: 'text', value: '\n' },
{ type: 'jsx', value: '</Column>', position: [Position] },
```

I might be unaware of any underlying issues but I think it would be a lot easier if it instead parsed to

```js
{ type: 'jsx',
  value: 'Column',
  props: {width: '50%' },
  position: [Position],
 children: [
   { type: 'text', value: '\n' },
  { type: 'element',
    tagName: 'img',
    properties: [Object],
    children: [],
    position: [Object] },
  { type: 'text', value: '\n' },
 ]
},
```

**Comment by johno** [comment]
Based on [this comment](https://github.com/mdx-js/mdx/issues/419#issuecomment-468590564) this is something we can address in #241 for 1.1.0.
