### ISSUE TITLE
Support for passing MDAST instead of raw markdown text

### ISSUE THREAD

**Issue by kimmobrunfeldt** [mdx-js/mdx#420]
Our documentation is combined from multiple smaller MDX content pieces. To have for example unique slugs, we have a centralized pre-processing for the content which parses the smaller pieces into their own MDASTs and makes sure that the slugger state is shared between these smaller pieces.

This means we would need the ability to pass the MDAST directly to the runtime, instead of passing the raw markdown text as `children`. **Would you be open to merge this feature if I send a PR for it?**

## The new suggested API of runtime

This would be a backwards compatible change.

With mdast:
```jsx
<MDX scope={scope} components={components} mdast={myMdast} />
```

With raw markdown text:
```jsx
<MDX scope={scope} components={components}>{myMdText}</MDX>
```

#### 1. Expose [createCompiler()](https://github.com/mdx-js/mdx/blob/5938d62f831141a98eff52ddafca7d302ce9b78a/packages/mdx/index.js#L99-L103)  from `@mdx-js/mdx`

This is needed to get direct access to unified API in runtime. We also want to use the DEFAULT_OPTIONS when creating the new compiler, so the function might need refactoring for that part. 

The other option would be to expose the DEFAULT_OPTIONS so that runtime gains the knowledge of them, but it sounds a bit more complicated approach to me.

#### 2. Support `mdast` prop in `@mdx-js/runtime`

[These lines](https://github.com/mdx-js/mdx/blob/5938d62f831141a98eff52ddafca7d302ce9b78a/packages/runtime/src/index.js#L21-L29) would need to be changed to:

```js
// This is the newly exposed function
const compiler = mdx.createCompiler({
  mdPlugins,
  hastPlugins,
  skipExport: true
})

let jsx
// mdast is a new prop
if (mdast) {
  const tree = compiler().runSync(mdast)
  jsx = compiler.stringify(tree)
} else {
  jsx = compiler.processSync({ contents: children }).contents
}

const { code } = transform(jsx.trim())
```

**Comment by kimmobrunfeldt** [comment]
We need this internally, so I started to work on the changes already. You can see the diff here: https://github.com/mdx-js/mdx/compare/master...AitoDotAI:master. 

I hit a wall with exports and imports though. Normal markdown parser isn't enough, as some JSX may be interpreted as html blocks etc. What I'm now thinking is that the parameter should actually be MDXAST instead of MDAST. Any pointers would be appreciated!

**Comment by johno** [comment]
Thank you very much for the detailed writeup and spiking!

The one thing I'm wondering is if your use case can be handled as a remark plugin that's passed to MDX? If you're operating on the MDAST it sounds like you're using some type of plugin to transform it based on your central slug processing.

I ask because it _sounds_ like we could handle that without modifying core at all (potentially). Let me know what you think!

---

- https://mdxjs.com/plugins
- https://github.com/remarkjs/remark/blob/master/doc/plugins.md

**Comment by johno** [comment]
Due to lack of activity I'm going to close this for now. Please feel free to open a new issue if your needs can't be addressed with a remark plugin.
