### ISSUE TITLE
Backslash doesn't insert a br

### ISSUE THREAD

**Issue by alexandernanberg** [mdx-js/mdx#421]
### Subject of the issue

I've been using `\` for new lines in my markdown files and it worked great with rehype etc. Migrated to MDX and noticed it didn't work the same way. Not 100% sure if this is a standard way of inserting new lines or not.

### Your environment

*   MacOS 10.14.1
*   `@mdx-js/mdx` @ `0.18.1`
*   Node @ `v10.15.0`

### Steps to reproduce

```js
(async () => {
  const result = await mdx(`
# Hello, MDX

**Hello**\
I <3 Markdown and JSX
`)
  console.log(result)
})()
```

### Expected behaviour

Backslash (`\`) should be converted to a `<br/>` element

### Actual behaviour

It's just omitted

**Comment by wooorm** [comment]
Did you try passing `commonmark: true`? That should be needed with just remark as well.

It seems it’s [passed down to remark-parse](https://github.com/mdx-js/mdx/blob/8469707ef5f0dcf3c0d56cf2793710916ef92c0c/packages/mdx/index.js#L59) btw

**Comment by alexandernanberg** [comment]
I suppose you mean like this?

```js
const result = await mdx(
  `
# Hello, MDX

**Hello**  
I <3 Markdown and JSX
`,
  {
    commonmark: true,
  },
)
```

Same output when trying that

**Comment by alexandernanberg** [comment]
Did some digging and I think [this](https://github.com/mdx-js/mdx/blob/23b1e94555e96183ff201bb9db909cfa7a031b89/packages/mdx/mdx-hast-to-jsx.js#L167-L179) is the cause. Not sure how to solve it though

**Comment by wooorm** [comment]
That could be it!

Or maybe because you use a slash in a template literal:

```js
console.log(`a\
b`)
//=> 'ab'
```

**Comment by alexandernanberg** [comment]
Oh my bad, had no idea that backslash didn't work in template strings. Adding `commonmark: true` in my `gatsby-mdx` options solved it for me!
