### ISSUE TITLE
A function inside backticks inside a codeblock is passed as a function not a string & it will throw in MDXContent.render

### ISSUE THREAD

**Issue by ahmedelgabri** [mdx-js/mdx#433]
### Subject of the issue

having something like this inside a codeblock will throw an error `Uncaught ReferenceError: foo is not defined` might be related to #430

```
`${foo.toLowerCase()}`
```

### Your environment

*   Name and version of operating system: macOS 10.14.3
*   Names and version of required packages: 
```
    "@mdx-js/mdx": "0.20.1",
    "@mdx-js/tag": "0.18.0",
    "gatsby-mdx": "0.4.0",
    "mdx-utils": "0.0.2",
```
*   Version of node, npm, yarn, or names and versions of browser: 

node: 11.10.1
yarn: 1.13.0

### Steps to reproduce

add this as a code block 

~~~
```
`${foo.toLowerCase()}`
```
~~~

### Expected behaviour

Doesn't break or call the function

### Actual behaviour

Throws an error `Uncaught ReferenceError: foo is not defined`

**Comment by johno** [comment]
Thanks for reporting. This should now be fixed in `0.20.2`.
