### ISSUE TITLE
MDXContent cannot be invoked without 'new'

### ISSUE THREAD

**Issue by koenbok** [mdx-js/mdx#443]
### Subject of the issue

Since exactly version `0.16.0` I'm getting the following errors in my SSR that uses Babel:

- `Class constructor MDXContent cannot be invoked without 'new'`
- `Cannot call a class as a function`

This depends if I enable the Babel runtime.

It's very likely this exact commit:
https://github.com/mdx-js/mdx/pull/427

### Your environment

*   `Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64`
*   `node v11.9.0`

Exact Webpack / Babel setup: https://github.com/framer/monobase/blob/mdx-bug/src/compiler.ts#L77

### Steps to reproduce

- Clone: https://github.com/framer/monobase
- `git checkout mdx-bug`
- `make`

**Comment by johno** [comment]
Thanks for the detailed bug report! In the 1.0 alpha we have removed the need for the wrapping class component which fixes this issue. I'd suggest upgrading. The current alpha shouldn't see a new breaking change (only known bug is HTML-style comments are being missed in MDX).

```sh
yarn add @mdx-js/loader@next
```

I took the alpha for a spin in your repo and that fixed it for me.

![image](https://user-images.githubusercontent.com/1424573/53920434-60e5fc80-402a-11e9-8e0a-27d94981781b.png)

Please let us know if you encounter any other issues!
