### ISSUE TITLE
Move to CircleCI

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#449]

**Comment by johno** [comment]
Would you be interested in taking this on still @leimonio?

**Comment by leimonio** [comment]
Yeap @johno thanks for mentioning. 👌

**Comment by johno** [comment]
Hm, going to reopen for now. Looks like the ci release isn't working as expected: https://circleci.com/gh/mdx-js/mdx/6

**Comment by leimonio** [comment]
@johno can you try once more? https://github.com/mdx-js/mdx/pull/538

**Comment by johno** [comment]
Looks like it's almost there now (tests are being run on PRs again thank you!). Looks like the npmrc addition is resulting in an uncommitted change so the publish won't work.

I think we could prolly remove the `.npmrc` and gitignore it since it isn't being used anyway. I'll give that a shot shortly.

**Comment by johno** [comment]
Seems to have worked. Thanks again @leimonio! 💟

**Comment by leimonio** [comment]
Great stuff!! Let me know if I can help anything else, happy to further contribute! :)
