### ISSUE TITLE
Performance & Output Testing

### ISSUE THREAD

**Issue by jescalan** [mdx-js/mdx#457]
Working through a larger implementation of mdx and I have run into some issues with the outputs - getting very large outputs just for a single simple file due to most of core-js being included. I also am unable to tree-shake apart the front matter from the content when using a layout with a custom loader - this can be seen on the `layout` branch of the provided sample repo:

https://github.com/jescalan/mdx-output-testing

Sorry for the brief description here, I can add more detail if you want, I just have to run shortly!

**Comment by johno** [comment]
Thanks for opening up this issue and investigating @jescalan!

**For those following along or that stumble upon this**
We've found that vanilla webpack does properly tree shake with the v1 alpha/rc. In Next.js the create-element pragma isn't being properly tree shaken if only frontmatter is imported, but it is code split so I _think_ we can call this resolved for now.

After v1 is released and stabilized we'll spend more time on performance tuning in MDX and popular frameworks like Next and Gatsby. When that occurs we can reopen this.

If you think there is anything more we should address before v1 in terms of this issue please let us know @jescalan.
