### ISSUE TITLE
Untangling the wrapper component and export default

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#459]
Having the `wrapper` element and `export default` both being able to wrap the rendered MDX is a bit confusing because they operate subtly differently. Consider the following input/output:

#### Input

```md
import TomatoBox from 'tomato-box'

export author = "Fred Flintstone"
export default = props => <main {...props} />

# Hello, world!

Here is a paragraph

<TomatoBox />
```

#### Output

```jsx
import TomatoBox from 'tomato-box'

export const author = "Fred Flintstone"

const MDXLayout = props => <main {...props} />

const layoutProps = {
  author:
}

export default function MDXContent(props) {
  return (
    <div name="wrapper">
      <MDXLayout {...layoutProps} {...props}>
        <h1>{`Hello, world!`}</h1>
        <p>{`Here is a paragraph`}</p>
        <TomatoBox />
      </MDXLayout>
    </div>
  )
}

MDXContent.isMDXComponent = true
```

Both `wrapper` and `export default` are achieving the same thing in subtly different ways. They also, as shown in the output above, result in two components when there could hypothetically be only one. This would result in a simpler API. But why keep both?

### Page level wrapping

In order to ensure MDX is as flexible as possible, `export default` is a desirable feature. Consider scenarios where you're using a framework that has MDX files as entrypoints and no app layout mechanism that operated on directories. When you have a single file that needs a different

If you have `pages/special-page-with-tomato-border.mdx` you're essentially unable to override layout from the MDX file. The key feature of `export default` is being able to emit _outward_.

### Wrapper

For most purposes, `wrapper` is the preferred way to achieve MDX layout since it's based on pure composition using context. However, as described above it's a bit limiting when an MDX file needs to export its layout.

## How do we combine them>

I propose that we make the wrapper the default wrapping component, but when an `export default` is defined, it overrides the wrapper from context. The output might look like:

```jsx
import TomatoBox from 'tomato-box'

export const author = "Fred Flintstone"

const MDXLayout = props => <main {...props} />

const layoutProps = {
  author:
}

export default function MDXContent(props) {
  return (
    <div name="wrapper" MDXLayout={MDXLayout} MDXLayoutProps={layoutProps}>
      <h1>{`Hello, world!`}</h1>
      <p>{`Here is a paragraph`}</p>
      <TomatoBox />
    </div>
  )
}

MDXContent.isMDXComponent = true
```

---

Thanks to @jxnblk and @ChristopherBiscardi for discussions that led to this proposal.

**Comment by alexandernanberg** [comment]
So if you’d set a custom wrapper component with the `MDXProvider` the default export would still overwrite it right?

**Comment by johno** [comment]
It would, yeah. It'd serve as the "escape hatch".

**Comment by jxnblk** [comment]
I'd love to see this as I think it can really simplify the API and potentially help with the initial confusion I had about the `wrapper` component. I can't think of anything specific that this sort of change would prohibit in comparison to the current API, but there might be some use-cases for the current implementation that I haven't thought of. In a related note: I'm toying with the combined layout/wrapper here in mdx-deck v2, which helps simplify the slide "layout" components: https://github.com/jxnblk/mdx-deck/blob/84d7ad1ec7dae7474c6701e3c4d1dd25131ab813/packages/mdx-plugin/index.js#L32-L39

**Comment by johno** [comment]
This is now supported in the v1 rc so going to close this.
