### ISSUE TITLE
Rename `mdPlugins` and `hastPlugins` to `remarkPlugins` and `rehypePlugins`

### ISSUE THREAD

**Issue by wooorm** [mdx-js/mdx#465]
### Subject of the issue

I don’t remember where it came up, I believe either Kent or Max raised it, but it’s not clear for users of MDX where they should place plugins, as users are often not well versed in the internals of unified.

I hope we can bring this in before 1.0.0 as it’s a major change. We could also support both and just document the new names, but then it’ll have to be supported for a while.

### Expected behaviour

Name of options should match values. `require(remark-something)` makes sense in `remarkPlugins` and `require(rehype-something)` in `rehypePlugins` 

### Actual behaviour

Name of options matches implementation details.

**Comment by johno** [comment]
Yeah, this is a great idea. Totally makes sense.

I wonder since it'd be relatively easy to support both that we warn when `mdPlugins` and `hastPlugins` are used and say support will be dropped in v2?

**Comment by wooorm** [comment]
I though about “deprecating” but still supporting it to ease migration. That’s :+1: for me!

**Comment by timneutkens** [comment]
Yeah I'd definitely do a warning and not break it 👍

**Comment by wooorm** [comment]
Another alternative: just throw a helpful error saying what to use. It's just as useful as a depreciation message, maybe slightly more so, in getting people to switch. And I feel like it's more normal to break usage on a v1 than in any other future mayor version, where backcompat becomes more and more important as time moves on. Anyway, up to y'all, I don't care too much!
