### ISSUE TITLE
Add example for Zero

### ISSUE THREAD

**Issue by asadm** [mdx-js/mdx#476]
[Zero](https://github.com/remoteinterview/zero) is a framework to write apps in a mix of JSX/MDX/JS. Would this project be open to adding example zero app under `./examples` and Getting Started section?

**Comment by johno** [comment]
Sure @asadm that'd be great!

**Comment by johno** [comment]
I'm going to close this for now but for anyone that wants to submit a PR for a Zero example and getting started guide we'll gladly merge!

**Comment by asadm** [comment]
Sorry for delaying this. I got busy with work!

**Comment by johno** [comment]
Not a worry, thanks for the PR!

**Comment by asadm** [comment]
Cheers. Congrats on V1!
