### ISSUE TITLE
Inconsistent JSX parsing between runtime and loader (multiline string prop)

### ISSUE THREAD

**Issue by buz-zard** [mdx-js/mdx#501]
### Subject of the issue

`@mdx-js/runtime` doesn't handle multiline string props:

```mdx
# Hello

<div children="O
K" />
```

![image](https://user-images.githubusercontent.com/3521740/55615875-35753f80-5799-11e9-8aca-a3b9a2e56896.png)

 Thought `@mdx-js/loader` works as expected:

![image](https://user-images.githubusercontent.com/3521740/55615997-7ec58f00-5799-11e9-96b6-65f9656d1150.png)

### Your environment

*   macOS
*   `"@mdx-js/runtime": "^1.0.0-rc.0",`, `"@mdx-js/loader": "^1.0.0-rc.0",` (note 0.20.3 versions have the same issue)
*   `npm - 6.9.0`

### Steps to reproduce

([repo](https://github.com/buz-zard/issue-mdx-runtime-1))

`App.js`:

```js
import React from 'react';
import MDX from '@mdx-js/runtime';

import Test from './Test.mdx';

const mdx = `
# Hello

<div children="OK" />
`;

export default function App() {
  return (
    <div>
      <Test />
      <MDX>{mdx}</MDX>
    </div>
  );
}
```

`Test.mdx`:

```mdx
# Hello

<div children="O
K" />
```

### Expected behaviour

The runtime should work identically to the loader and handle multiline string prop.

### Actual behaviour

An error get's thrown:

![image](https://user-images.githubusercontent.com/3521740/55615875-35753f80-5799-11e9-8aca-a3b9a2e56896.png)

**Comment by johno** [comment]
It looks like this boils down to `buble` being used in the runtime rather than babel. So there will always be subtle differences in syntax support.

Not sure if there's really a way we can solve this unless we explore making `@mdx-js/babel-runtime`. Buble was chosen for the existing runtime because it's much lighter than lugging all of babel.

**Comment by johno** [comment]
This will be addressed in https://github.com/mdx-js/mdx/pull/734
