### ISSUE TITLE
Intellisense / Typescript

### ISSUE THREAD

**Issue by natew** [mdx-js/mdx#510]
### Subject of the issue

Didn't see this mentioned anywhere, but lack of intellisense is the biggest limiting factor for MDX for me for now. Instead I'm importing from a second .tsx file and writing all my examples there, but if I had type checking + autocomplete, I'd reduce my file count by double!

**Comment by johno** [comment]
Thanks for opening up this issue! Unfortunately right now we don't have the bandwidth to help address this (I don't even use TS myself).

If anyone comes across this, we'd absolutely love PRs to help improve TypeScript support (in docs or types) from the community. 🙏 ❤️ 🙏 ❤️
