### ISSUE TITLE
Shortcodes breaks if same component if used more than once

### ISSUE THREAD

**Issue by alexandernanberg** [mdx-js/mdx#518]
### Subject of the issue

Shortcodes breaks if same component if used more than once. We probably want to add a check if the `makeShortcode` is already added or not.

### Your environment

`@mdx-js/mdx`@1.0.2
`@mdx-js/react`@1.0.2

### Steps to reproduce

```md

<Foo bg='red'>
  <Bar>hi</Bar>
  {hello}
  {/* another commment */}
</Foo>

<Foo bg='red'>
  <Bar>hi</Bar>
</Foo>

```

### Expected behaviour

Should work without errors

### Actual behaviour

```
SyntaxError: unknown: Identifier 'Foo' has already been declared (17:6)

      15 | const Foo = makeShortcode("Foo");
      16 | const Bar = makeShortcode("Bar");
    > 17 | const Foo = makeShortcode("Foo");
         |       ^
      18 | const Bar = makeShortcode("Bar");
      19 | const layoutProps = {
      20 |   foo
```

**Comment by johno** [comment]
Nice catch. We should be making sure that the element names are unique before mapping with the shortcode calls.

**Comment by ChristopherBiscardi** [comment]
Should be able to `new Set(jsxNames)` here: https://github.com/mdx-js/mdx/blob/452e8ebbf58e6d9c9f0ce0a2041cf1a7c8a87160/packages/mdx/mdx-hast-to-jsx.js#L177 to fix this

**Comment by chasemccoy** [comment]
Yep I am running into this as well.

**Comment by chasemccoy** [comment]
@ChristopherBiscardi I opened a PR here to make that change: https://github.com/mdx-js/mdx/pull/522
