### ISSUE TITLE
Is it possible to include html tags with data- attributes?

### ISSUE THREAD

**Issue by kuworking** [mdx-js/mdx#520]
I'm experiencing that if I place in a `mdx` document (rendered by `Gatsby-plugin`) something like this

    <div>
      <div>hey</div>
    </div>

it works, but this doesn't

    <div>
      <div data-myattr="hey">hey</div>
    </div>

as it gets rendered like

    <div>
      <pre>
       <code>
        <div data-myattr="hey">hey</div>
       </code>
      </pre>
    </div>

but if I add a second child, like this

    <div>
      <div>hey</div>
      <div data-myattr="hey">hey</div>
    </div>

then it works as a normal `<div>` tag

Is this an expected behavior? Or am I saying some nonsense?

**Comment by johno** [comment]
Is it possible you might've had empty lines before your data attribute div?

```html
<div>
  <div data-myattr="hey">I'll be rendered as expected</div>
</div>

<div>
 
    <div data-myattr="hey">I'll be rendered as a code block</div>

</div>
```

The latter part is a commonmark feature where opening/closing tags that are separated by empty lines have their inner content parsed as markdown. Hopefully this helps!

---

![image](https://user-images.githubusercontent.com/1424573/56301354-e44c4080-60f4-11e9-8634-36009cedbbcd.png)
