### ISSUE TITLE
Docs: @babel/proposal-object-rest-spread no longer needs to be specified explicitly

### ISSUE THREAD

**Issue by kaykayehnn** [mdx-js/mdx#521]
### Subject of the issue

The docs mention that when setting up Webpack/Parcel, Babel is required to support the language features that MDX uses. The recommended Babel config includes @babel/proposal-object-rest-spread, which is now at [stage 4](https://github.com/tc39/proposal-object-rest-spread#status-of-this-proposal) in the proposal pipeline and is supported [out of the box](https://github.com/babel/babel/blob/165ef2941694184d83307b41d311751bd3dabae0/packages/babel-preset-env/src/available-plugins.js#L40) in @babel/preset-env.

So the recommended Babel config can be simplified by removing the references to @babel/proposal-object-rest-spread

```diff
{
  "presets": [
    "@babel/env",
    "@babel/react"
-  ],
-  "plugins": [
-    "@babel/proposal-object-rest-spread"
-  ]
+  ]
}
```

and

```diff
- npm install --save-dev @babel/preset-env @babel/preset-react @babel/plugin-proposal-object-rest-spread
+ npm install --save-dev @babel/preset-env @babel/preset-react
```

**Comment by johno** [comment]
Thanks for opening up this issue! It's now addressed in #539.
