### ISSUE TITLE
`name` property renamed to `originalType`

### ISSUE THREAD

**Issue by chasemccoy** [mdx-js/mdx#524]
Noticed a breaking change when updating to MDX 1.0.0 that was not documented anywhere, and wanted to make folks aware of it. 

Previously, components props had a `name` attribute that was the name of the HTML element. This was used in a lot of places to do check for conditional rendering of components. Now, it appears that the `name` property is called `originalType` instead. 

@ChristopherBiscardi `mdx-utils` used the `name` property and so it is broken with MDX 1.0.0. 

This change is fine (though inconvenient), but it should probably be documented somewhere for folks migrating to version 1.0

**Comment by johno** [comment]
Thanks for bringing this up! This is definitely something we need to document and add to the migration guide.

**Comment by ChristopherBiscardi** [comment]
published `mdx-utils@0.1.0` to account for this.

**Comment by johno** [comment]
I'm going to go ahead and close this for now since `mdx-utils` has been updated to handle this. AFAIK this is the only usage operating at that level right now.

Thanks for opening up the issue @chasemccoy and your quick update @ChristopherBiscardi!
