### ISSUE TITLE
Upgrading to v1 seems to cause an issue when exporting arbitrary props

### ISSUE THREAD

**Issue by brandonweiss** [mdx-js/mdx#530]
### Subject of the issue

Upgrading to v1 throws warnings on MDX documents that export arbitrary props, possibly because of the change from wrapping the document in a `div` to using a React Fragment?

### Steps to reproduce

I have an MDX document like this:

```mdx
export const author = "Foo"

# Heading
```

When I transform it I seem to get this warning:

```
Warning: Invalid prop `author` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
    in Fragment
    in MDXCreateElement
    in MDXContent
```

As far as I can tell, this is because all the props exported from the document are automatically passed to the “wrapper” component, which used to be a `<div>` and is now a `<React.Fragment>`.

The switch is fine and I think it makes sense, I’m just unclear if what is now happening is expected?

It seems like the default wrapper should be something like `({ children }) => <React.Fragment>{children}</React.Fragment>`?

**Comment by LucidityDesign** [comment]
I get the same error but without exporting anything:
```
Warning: Invalid prop `entries` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
```
(I'm using docz)

**Comment by johno** [comment]
I believe this has to do with using `React.Fragment` as the default wrapper element and forwarding all props. We'll need to change it from `wrapper: React.Fragment` to `wrapper: ({ children }) => <React.Fragment>{children}</React.Fragment>` in `create-element.js`.
