### ISSUE TITLE
runtime issue - _convertSourceMap(...).default.removeComments is not a function

### ISSUE THREAD

**Issue by buz-zard** [mdx-js/mdx#536]
### Subject of the issue

I'm trying to use latest version of runtime using example code and the runtime seems completely broken in V1 (`1.0.0-rc.0` seemed to work with warnings but still).

```
import React from 'react';
import MDX from '@mdx-js/runtime';

// Provide custom components for markdown elements
const components = {
  // eslint-disable-next-line jsx-a11y/heading-has-content
  h1: props => <h1 style={{ color: 'tomato' }} {...props} />,
};

// Provide custom components that will be referenced as JSX
// in the markdown string
const scope = {
  Demo: () => <h1>This is a demo component</h1>,
};

const mdx = `
# Hello, world!

<Demo />
`;

export default () => (
  <MDX components={components} scope={scope}>
    {mdx}
  </MDX>
);
```

`Uncaught TypeError: _convertSourceMap(...).default.removeComments is not a function` error get's thrown.

![image](https://user-images.githubusercontent.com/3521740/56244231-16ce4d00-60a5-11e9-9123-1fc9f60aca4b.png)

### Your environment

*   macOS
*   `"@mdx-js/runtime": "^1.0.9",`, `"@mdx-js/mdx": "^1.0.9",`

### Steps to reproduce

Just try to use the runtime ([repo](https://github.com/buz-zard/issue-mdx-runtime-2/tree/broken))

---

Also v1 seemed to introduce an error warning:
![image](https://user-images.githubusercontent.com/3521740/56244541-c60b2400-60a5-11e9-845c-d7d34e2beb70.png)
([repo](https://github.com/buz-zard/issue-mdx-runtime-2))

this prevents runtime from being used in gatsby-netlify-cms - https://github.com/gatsbyjs/gatsby/issues/10326

P.S. would you accept a MR with tests for runtime? As I'm developing a [netlify-cms-widget-mdx](https://github.com/buz-zard/gatsby-mdx/tree/master/packages/netlify-cms-widget-mdx), I very much depend on the stability and consistency of the runtime, so I would gladly chip in.

**Comment by johno** [comment]
Hmmm, yeah looks like babel introduced some runtime breakage. I think we need to stub the `fs` module in the runtime.

We'd happily accept a PR with tests for runtime. Apologies it's been so unstable/flaky! 😬

**Comment by lottamus** [comment]
This can be fixed by adding a mock via your webpack config:

```
node: {
  fs: 'empty'
}
```

Check out https://webpack.js.org/configuration/node/#other-node-core-libraries

**Comment by buz-zard** [comment]
Tried `"@mdx-js/runtime": "^1.0.15",` and by adding

```
  node: {
    fs: 'empty',
  },
```

removes both warnings, and runtime actually starts working. Thought in environments where you can't modify the webpack (e.g. [netlify cms](https://github.com/gatsbyjs/gatsby/issues/10326)), it breaks as described in the issue 😕

**Comment by johno** [comment]
I've added docs for those that can modify the webpack config to work in the browser. For a full fix we'll need to investigate using Babel standalone.

**Comment by karlsander** [comment]
Not to be a +1 person, but I would really love to see this fixed. A stable @mdx-js/runtime could enable a lot of neat tooling around mdx, like dedicated editors, and support prototyping more out-of-the-box ideas (like rendering in Framer X and react native).

I took a try at hacking together some kind of dirty fix, shimming fs in the rollup bundling, because I REALLY wanted to try it in Framer X, but I couldn't figure anything out.

What would moving to babel standalone involve? Or do you have any pointers for a hacky fix?

**Comment by johno** [comment]
👋 @karlsander 

I've [opened up a new issue](https://github.com/mdx-js/mdx/issues/704) which can be centered around figuring out how to best get a more runtime-friendly implementation. It's something that it's definitely worth doing, though I'm not sure if that means moving to `@babel/standalone` or offering our own standalone package.

Maybe we could figure out a solution in the near future!
