### ISSUE TITLE
Implement parcel bundler plugin

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#54]

**Comment by devongovett** [comment]
Awesome project. Happy to help with this! 😄

**Comment by johno** [comment]
❤️

Happy to accept a PR for a WIP, standalone package in `packages`, or a gist with code. If there's anything you need, let us know.

If you wanted to provide direction in our implementation that'd be great too (I know I wouldn't be able to attack it this next week, but maybe someone else could take it on).

**Comment by ifyoumakeit** [comment]
I'd definitely be into adding this into the monorepo if there's interest.  I recently created https://github.com/ifyoumakeit/parcel-plugin-mdxc before realizing that `mdx` existed. I'd fork @hamlim's, make a PR repo and add some more tests.

**Comment by johno** [comment]
This is great stuff @hamlim. If you wanted (or if you wanted to pass that on to someone else), we'd love to accept a PR for `parcel-plugin-mdx` into the MDX monorepo.

Before merging I'd def like to get a test in there, though. Maybe @ifyoumakeit would like to take that part on?

**Comment by ifyoumakeit** [comment]
I've messed with merging the plugin into the monorepo with [my fork](https://github.com/mdx-js/mdx/compare/master...ifyoumakeit:move-into-mdx?expand=1), but definitely defer to @hamlim.

I can always cherry-pick out the [test](https://github.com/ifyoumakeit/mdx/blob/8842e6fc3553c3ee583fd3e29b1e887efcb5d537/packages/parcel-plugin-mdx/test/index.test.js) when he opens a PR. Just happy to see it working in Parcel!

**Comment by johno** [comment]
Oh nice @ifyoumakeit! I just wanted to make sure @hamlim got his commits attributed which it looks like you've done with your port. So if you want to PR that in, happy to merge. Thanks! 💟
