### ISSUE TITLE
Documentation: (nextjs example) 404 on codesandbox link

### ISSUE THREAD

**Issue by aretecode** [mdx-js/mdx#548]
### Subject of the issue

https://github.com/mdx-js/mdx/tree/master/examples/next has a link to a 404 codesandbox

### Your environment

Codesandbox / github wiki

### Steps to reproduce

Open the link above and see the codesandbox in the link

### Expected behaviour

The site should load

### Actual behaviour

404

**Comment by johno** [comment]
Thanks for opening! The link has been updated.
