### ISSUE TITLE
MDX Vue example fails to compile

### ISSUE THREAD

**Issue by callumflack** [mdx-js/mdx#557]
### Subject

A vanilla install from [the MDX Vue example](https://github.com/mdx-js/mdx/tree/master/examples/vue) fails with the error `./create-element was not found`.

### Environment

*   latest Mac OS, latest Chrome, Yarn 1.15.2
*   Names and version of required packages: exact install from the example

### Steps to reproduce

Install from the example zip.

### What should happen?

The project should successfully compiles and hot-reload for development with `yarn run serve`.

### What happens instead?

![image](https://user-images.githubusercontent.com/749885/56843889-7bca4400-68ea-11e9-81ac-ef19654ce419.png)

**Comment by ChristopherBiscardi** [comment]
Looks like the vue-loader in the example is `"@mdx-js/vue-loader": "^1.0.0-alpha.4",` while the version currently released is `1.0.15`.

**Comment by callumflack** [comment]
Thanks. When I do that, I get:

![image](https://user-images.githubusercontent.com/749885/57049768-d97cd880-6cbc-11e9-8b6d-4198e281d81d.png)

And when I add `npm install --save @mdx-js/vue`, I get the same error message. 

This is probably a very simple fix but I'm afraid I don't know how MDX works. I just want to run it and use it…

**Comment by johno** [comment]
If you re-scaffold out the example with `npm init mdx vue` it should now work properly. The example had the wrong pinned dependency that cause issues with deps/compilation.

Thanks for opening the issue!
