### ISSUE TITLE
Headers tags wraps with paragraph

### ISSUE THREAD

**Issue by jeetiss** [mdx-js/mdx#593]
### Subject of the issue

h1 and H1 tags wraps with unnecessary paragraph tag 

### Steps to reproduce

you can reproduce this bug in [playground](https://mdxjs.com/playground)

<img width="986" alt="Снимок экрана 2019-06-04 в 10 35 07" src="https://user-images.githubusercontent.com/6726016/58860292-75cb3e00-86b4-11e9-8058-79eb139b705c.png">

### Expected behaviour

h1 and H1 tags renders without wrapping p

### Actual behaviour

every h1 and H1 tag wraps with paragraph tag

**Comment by nkuehn** [comment]
Can confirm this in my project,  GatsbyJS / React validates and warns with `validateDOMNesting(...): <h2> cannot appear as a descendant of <p>. `

It's actually not just unnecessary but not valid HTML. 

Also mentioned here on spectrum: https://spectrum.chat/mdx/general/should-literal-h1-be-contained-in-a-p~d6bd0b1d-0a94-4641-b23d-b815e61914e7?authed=true

**Comment by chasemccoy** [comment]
Also seeing this on my site! In my case it caused some weird visual issues because of the invalid DOM nesting 🙈

**Comment by chasemccoy** [comment]
I am curious what version this broke in? I am currently on `1.0.20`

**Comment by johno** [comment]
Looks like it was a 1.0 regression @chasemccoy. I've opened up #604 with a fix. Thanks for reporting @jeetiss!

**Comment by chasemccoy** [comment]
@johno thanks man!

**Comment by zero1five** [comment]
I can also reproduce this. Is there any new progress please?

**Comment by endiliey** [comment]
Anything blocking #604 ? :) Would love to help in some way

**Comment by johno** [comment]
> Anything blocking #604 ? :) Would love to help in some way

Mostly just time : )

Happy to coach someone through picking that PR up, adding some tests and fixing the regex.

**Comment by johno** [comment]
Going to pick this back up today and see if I can get a fix in. Will keep you folks posted. 🤞

**Comment by endiliey** [comment]
Thank you @johno

Its unfortunate that im on the newbie side for markdown and ast parsing so cant help much. But will keep an eye on the repo and somehow help along if possible

**Comment by johno** [comment]
This should now be fixed in `@mdx-js/mdx@1.0.25`. Please give it a try and let me know if you encounter any issues.

cc/ @endiliey (a thorough test would be greatly appreciated 💟)

**Comment by endiliey** [comment]
Seems to be working great.

Before
<img width="953" alt="before" src="https://user-images.githubusercontent.com/17883920/61144361-e3ae2500-a4fe-11e9-81da-e56d5433cca1.PNG">

After
<img width="957" alt="after" src="https://user-images.githubusercontent.com/17883920/61144364-e4df5200-a4fe-11e9-9372-2bfd6aa5153c.PNG">

Great work :party
