### ISSUE TITLE
Backslash sometimes inserted when using $ in text

### ISSUE THREAD

**Issue by lourd** [mdx-js/mdx#606]
I noticed that on some parts of my portfolio site (made with gatsby and gatsby-mdx), there are extra backslashes being inserted in some places where dollar signs are used. For example:

- Go to https://descioli.design/grove and Find for `\$` — there are 6 occurrences on the page. There are 12 usages of `$`, though — not every $ is preceded by a backslash.
- The MDX source for that page is [here](https://github.com/lourd/descioli-design/blob/master/content/stories/grove/grove.mdx). Note: no backslashes.
- The rendering of the page is [here](https://github.com/lourd/descioli-design/blob/master/src/components/Story.tsx#L161-L191). Pretty standard AFAIK.

It only started happening when I switched from Remark to MDX. I didn't notice it when I did the initial switch.

### Environment

*   macOS and ubuntu, latest version
*   @mdx-js/mdx@1.0.20, gatsby-mdx@0.6.3
*   node@10.1.0, yarn@1.13.0

### Steps to reproduce

Clone my portfolio repo, https://github.com/lourd/descioli-design, and run it. No additional configuration needed.

### Expected behaviour

No extra backslashes.

### Actual behaviour

Extra backslashes

**Comment by lourd** [comment]
This ended up being due to prettier. I'd set it up to run on pre-commit and missed the fact that it was also formatting .mdx files 🤦‍♂  Sorry to waste your time.

**Comment by johno** [comment]
I'm going to reopen since MDX output is in fact different than remark's. It's a bug in the template literal escaping that we'll need to address.

**Comment by lourd** [comment]
Just to be clear, it was Prettier that did the extra escape, not Remark. I
switched to MDX and accidentally had Prettier format my .mdx file in the
same commit, and incorrectly attributed the inserted backslash to the
Remark-MDX switch.

**Comment by millette** [comment]
Should mdx handle \$ and remove the \ when output, since $ must be escaped due to math support - see <https://github.com/prettier/prettier/issues/6213>.

**Comment by johno** [comment]
Yeah, ultimately we should detect the presence of `\$` and not escape it [twice](https://github.com/mdx-js/mdx/blob/master/packages/util/index.js#L30-L33).

In the ideal world Prettier wouldn't add the `$` escaping when there isn't inline math being used (or it at least wasn't the default), but it seems like we've reached the point where we need to solve it on our end.

**Comment by millette** [comment]
I even tried something like `cost: 5{"$"}` but that was output litteraly.

**Comment by adamwathan** [comment]
Sorry to comment on a closed issue but I'm still seeing MDX render `\$` in the HTML if the dollar sign is escaped in the MDX. It's a Next.js project, and here are my dependencies:

```js
{
  "name": "tailwind-jobs",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@mdx-js/loader": "^1.6.1",
    "@next/mdx": "^9.4.0",
    "@tailwindcss/ui": "^0.3.0",
    "autoprefixer": "^9.7.6",
    "next": "9.4.0",
    "postcss-nesting": "^7.0.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "tailwindcss": "^1.4.6"
  }
}
```

Is there a dependency I need to explicitly add that I'm missing, to make sure I'm actually grabbing a recent enough version to get this fix?

**Comment by flikteoh** [comment]
Hey @johno 

Is this still being worked on?

**Comment by NathanHealea** [comment]
@flikteoh and @johno,

I'am also seeing the same issue.`\$10` when using Gatsby + MDX.

**Comment by emanuelturis** [comment]
Wrapping the text inside a p tag has prevented Prettier from adding a the `\` before the `$`.

Example:
`
<p>
  The price is $30/month.
</p>
`

Hope that's helpful to someone.

**Comment by emanuelturis** [comment]
Wrapping the text inside a p tag has prevented Prettier from adding a the `\` before the `$`.

Example:
`
`
<p>
  The price is $30/month.
</p>
`
`

Hope that's helpful to someone.

**Comment by emanuelturis** [comment]
Wrapping the text inside a p tag has prevented Prettier from adding a the `\` before the `$`.

`
<p>The price is $30/month.</p>
`

Hope that's helpful to someone.

**Comment by emanuelturis** [comment]
Putting the text inside a p tag has prevented Prettier from adding a the `\` before the `$`.

```
<p>
  The price is $30/month.
</p>
```

Hope that's helpful to someone.

**Comment by emanuelturis** [comment]
Putting the text inside a p tag has prevented Prettier from adding a the `\` before the `$` when formatting.

```
<p>
  The price is $30/month.
</p>
```

**Comment by samajammin** [comment]
Hey @lourd - I'm having the same issue (pre-commit hook w/ Prettier). How did you prevent Prettier from doing this?

Thanks in advance!

**Comment by flores8** [comment]
If anyone else runs into this problem like I did today, here's how I fixed it. I needed prettier to stop adding in the backslash. I first started looking in the prettier settings to see if I could turn off the math portion but that ended up being a dead end. I realized that I needed to tell prettier to simply ignore it. 

I first tried to my prettier ignore file: https://media.lauraleeflores.com/llu5D48j that works however it will ignore the page completely and that was not ideal for me. 

The solution that worked was to simply ignore a portion of the file. You can learn more about that here: https://prettier.io/docs/en/ignore.html

Mine is an mdx file so this is how I ignored it: https://media.lauraleeflores.com/YEuR1dYj

I hope that helps someone who runs into the same problem.

**Comment by sebastienbarre** [comment]
Is there any plan on fixing this for `*` as well?

Note that as far as MDX is concerned, this will break Javascript expressions too from what I can see. For example:

```
MDX also supports JavaScript expressions inside curly braces, i.e.: {Math.PI * 2}
```
is changed by Prettier to:
```
MDX also supports JavaScript expressions inside curly braces, i.e.: {Math.PI \* 2}
```
Which breaks MDX parsers -- this is no longer a valid Javascript/JSX expression.

Thanks

**Comment by ChristianMurphy** [comment]
The `*` escaping is due to prettier currently supporting only MDX 1 rather than MDX 2, meaning it currently doesn't recognize the inline JSX expression and adds an escape.
MDX 2 support in prettier is being discussed at https://github.com/prettier/prettier/issues/12209

**Comment by wooorm** [comment]
To add: The JS in braces are a new MDX 2 thing. So, *we* just added support for them. Now *other* tools have to support them too!
