### ISSUE TITLE
The 'change-case' package is bloating bundle size

### ISSUE THREAD

**Issue by wilsonpage** [mdx-js/mdx#623]
The [`change-case`](https://www.npmjs.com/package/change-case) dependency is `>20kb` which is pushing us over our bundle size budget. Can it be replaced/inlined?

**Comment by johno** [comment]
Thanks for bringing this up!

That's something we'd gladly accept a PR for. Definitely don't need to bring along the entire package for a single function.

**Comment by wilsonpage** [comment]
@johno https://github.com/mdx-js/mdx/pull/624

**Comment by timneutkens** [comment]
> which is pushing us over our bundle size budget

Does this mean you're bundling mdx into your production bundles?

**Comment by wilsonpage** [comment]
> Does this mean you're bundling mdx into your production bundles?

@timneutkens I'm using [`next-mdx`](https://github.com/zeit/next-plugins/tree/master/packages/next-mdx) and noticed the `no-case` dependency when using the bundle-analyzer and traced it back to this repo. Is it weird that I'm seeing it in my production bundles?

**Comment by timneutkens** [comment]
Yes that's definitely strange as MDX works at build time
