### ISSUE TITLE
Tilde (~) in code-fences causes unexpected output

### ISSUE THREAD

**Issue by maximilianschmitt** [mdx-js/mdx#630]
Using a tilde `~` in code fences causes unexpected output.

### Example:

    # Hello, world!
    
    ```js filename=~/.bashrc
    echo Hello
    ```

### Expected output:

```html
<h1>Hello, world!</h1>
<pre><code class="language-js" metastring="filename=~/.bashrc" filename="~/.bashrc">echo Hello
</code></pre>
```

### Actual output:

```html
<h1>Hello, world!</h1>
<p>`<code></code>js filename=~/.bashrc echo Hello</p>
<pre><code></code></pre>
```

### Steps to reproduce

Minimal working example on Codesandbox: https://codesandbox.io/s/pedantic-swirles-7zrnh

---

Thoughts:

I've tried escaping the `~` with one or more backslashes (`\`) assuming that the markdown parser was interpreting it as a token, but it made no difference.

**Comment by johno** [comment]
Thanks for reporting! Turns out this is an upstream issue in remark so I've created an issue there: remarkjs/remark#421

**Comment by maximilianschmitt** [comment]
Nice, thanks for checking it out! I'll be following the upstream issue. :)

**Comment by johno** [comment]
This is now fixed in the latest remark (and thus MDX) thanks to @wooorm!
