### ISSUE TITLE
Wrong escaping for < and >

### ISSUE THREAD

**Issue by goodmind** [mdx-js/mdx#665]
### Subject of the issue

Wrong escaping in links

### Your environment

*   **OS**:  macOS
*   **Packages**:  @mdx-js/mdx 1.1.0
*   **Env**:  node v12.6.0

### Steps to reproduce

```md
Store\<Payload\>
```

### Expected behaviour

Should render like: Store\<Payload\>

### Actual behaviour

Renders as: Store\\<Payload\>

**Comment by johno** [comment]
For now I'd recommend using the [HTML entity](https://developer.mozilla.org/en-US/docs/Glossary/Entity) equivalent for these characters:

```Store&lt;Payload&gt;```

**Comment by wooorm** [comment]
JSX doesn’t support escapes. It does support character references. I think @johno’s comment above should be the solution.
