### ISSUE TITLE
"Edit this page" link missing pathname in docs

### ISSUE THREAD

**Issue by dzello** [mdx-js/mdx#681]
### Subject of the issue

The "Edit this page on GitHub" link is broken when you load a page in the browser directly. It works if you've navigated from another page.

### Steps to reproduce

- Visit [https://mdxjs.com/projects/](https://mdxjs.com/projects/)
- Click on "Edit this page on GitHub"

### Expected behaviour

The link should go to the correct page on GitHub: `https://github.com/mdx-js/mdx/edit/master/docs/projects.md`.

### Actual behaviour

The link points to `https://github.com/mdx-js/mdx/edit/master/docs/.md` which results in a 404 on GitHub.

### Triage

The `edit-link.js` component constructs the GitHub link URL like so:

```jsx
export default () => (
  <Location>
    {({location}) => (
      <a
        href={base + location.pathname + '.md'}
        css={css({
          display: 'inline-block',
          color: 'inherit',
          fontSize: 1,
          my: 4
        })}
      >
        Edit this page on GitHub
      </a>
    )}
  </Location>
)
```

When loading the page directly, the `location.pathname` is blank.

Unfortunately, I can't reproduce this locally. The link URL is correct when I load the page directly. So I'm wondering if it's something with the deployed environment that could be causing the missing path name.

If you can point me in the right direction, I'm happy to do a fix and submit a PR.

**Comment by johno** [comment]
Oh this is a weird one, thanks for reporting!

I think it does have to do with the deployment environment because when you initially load the page it ends up as `mdxjs.com/getting-started/` and all subsequent navigations are `mdxjs.com/getting-started`.

Though not sure if it's best for us to address at the Gatsby level or the deployment to ZEIT now 🤷‍♂

**Comment by swarup4741** [comment]
Is this issue still open ? then i can try to fix it

**Comment by wooorm** [comment]
Fixed!
