### ISSUE TITLE
Base64 images in styles are not rendered

### ISSUE THREAD

**Issue by PedroLamas** [mdx-js/mdx#682]
### Subject of the issue

Base64 images used inside a style are not rendered.

### Steps to reproduce

Inside any MDX file, just drop the following code:

```
<span style="display: block; width: 32px; height: 32px; background-image: url('data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/4QBkRXhpZgAATU0AKgAAAAgABAEaAAUAAAABAAAAPgEbAAUAAAABAAAARgEoAAMAAAABAAIAAAExAAIAAAAOAAAATgAAAAAAAABIAAAAAQAAAEgAAAABcGFpbnQubmV0IDQuMgD/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAgACADAREAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD0e7uY7S1kuJjhI1yaAPK9c8a6jMhljYxxv9yNCcAe/qadiL3K/h3xprC3q7w80Q6rk4PtQPY9dtbiO7tYrmE5jlQOp9iM0iiHVLFNS0+W0kYoJBww7EHIP5igDyDULCO2u5LRJYpTHwxXnHHUfjmmiGirptzmR441VQnGc4x9aYj2Hw7fjUdHhn2BGBKOFGBuBwSPY9aktO5Lrd2bHR7q5CklE7ds8Z/DOaBniF1Mx1Nrm3JyvysGHGKZFzpPBmh6Zq+oSPLM6SJhgiupDj25zkfT8aGCR6na20Fnbpb20YjiQfKopFjNSCHTboSRNKhibMajJYYPA96APOvB+gyXVzPHqmlSImA++ePhs9VGetBCO+0/RdN01i9lY28DkYLJGAfzoKsaFAz/2Q==')"></span>
```

### Expected behaviour

This should render a 32x32 span with an image inside.

### Actual behaviour

Span gets rendered but no image is shown; the whole "background-image" property has been dropped.

**Comment by PedroLamas** [comment]
This issue was first noticed [here](https://github.com/gatsbyjs/gatsby/issues/15058), it is related to [this issue](https://github.com/radubrehar/toStyle/issues/2) on the "to-style" package.

The `to-style` package doesn't correctly handle ":" and ";" on the CSS property values, so it drops those properties.

Ideally, I'd like to fix this by adding a dependency to `postcss` in `to-style` to parse the CSS string and convert to object, but seems that that project has been abandoned, so the only other option is to fix directly here.

So, is taking a dependency to `postcss` and pushing a fix here acceptable?

**Comment by PedroLamas** [comment]
I might have jumped the gun here... seems that this issue is actually not visible directly on Mdx but only on GatsbyJs, although the problem with the `to-style` is still present (doesn't handle "." or ";" in style values).

I'm closing this for now as to not false flag it and will re-open if I find a way to show the error here.

**Comment by johno** [comment]
Thanks for the amazing digging @PedroLamas! I'm going to go ahead and re-open since it's something that could cause issues in MDX core as well. Since we attempt to do style string transforming to style objects it's still a bug here, too.

We just haven't seen it yet because the Gatsby ecosystem's usage of `gatsby-remark-*` plugins that inject HTML typically flush out these weird edge cases.

**Comment by PedroLamas** [comment]
Great! In that case, I have a working fix that I will push in the next 10 minutes!

**Comment by PedroLamas** [comment]
And here's the PR: https://github.com/mdx-js/mdx/pull/683
