### ISSUE TITLE
Explore moving to babel standalone or offering a more browser friendly build

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#704]
Since `@babel/core` attempts to bring along the `fs` module we're often forced to [do annoying webpack config](https://mdxjs.com/getting-started/webpack#running-mdx-in-the-browser) and other hacks.

For environments where that control might not exist we should look into using `@babel/standalone` or even offering an `@mdx-js/standalone` that things like `@mdx-js/runtime` could use.

**Comment by JulioC** [comment]
Is this available in @mdx-js/mdx@2.0.0-next.1? If not, is there any estimate for its release? 

I'm curious to know how much improvement this will make in my bundle size
