### ISSUE TITLE
Add guide on using katex with MDX

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#712]
Katex is currently a popular search term on the docs website and we don't have a guide or docs on the best way to achieve this.

I don't use katex myself so I was hoping a community member might want to take this on? It can follow a [similar format as the syntax highlighting guide](https://mdxjs.com/guides/syntax-highlighting).

**Comment by wooorm** [comment]
@Rokt33r You made remark-math to do this. If you you ever worked with MDX, do you have thoughts on this?

**Comment by Rokt33r** [comment]
@wooorm I'll try it in this week. Btw, I think I should do transfer ownership of remark-math to remark. I'll make a new issue in remark-math.

**Comment by wooorm** [comment]
Oh I guess, similar to syntax highlighting, you can also go two ways: remark/rehype plugin, or a react component!

**Comment by Rokt33r** [comment]
Sorry for being late. I've just started working on this now.
