### ISSUE TITLE
If there are no shortcodes, don't add makeShortcode function to output JSX

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#721]
Right now we always embed the `makeShortcode` function, though if it's not needed (no shortcodes are used) we can skip adding it.

**Comment by mohrash92** [comment]
Hey i'm currently doing some work to treat the warning that makeShortcode produces in my app as an error so that I can exit my build produced by webpack. Not sure on how you're planning on skipping adding this function and how far have you got with this?

**Comment by wooorm** [comment]
@mohrash92 I don’t believe there has been any work on this yet! Contributions welcome!
