### ISSUE TITLE
📽 MDX introduction video

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#727]
It'd be helpful to walk through some basic features of MDX in a short video format to serve as an introduction to the library. This would be in addition to the new example graphic I'm working on.

We could record it and then host it on YouTube for embedding on the website.

**Potential outline**
- Write a bit of Markdown add in some inline JSX to make the background color tomato
- Use the MDXProvider to adjust styling of Markdown elements
- Import a chart and render it to the page
- Add shortcodes (Note and YouTube) with the MDXProvider and use them in the document

**Comment by tomWritesCode** [comment]
Hi John, 

Is there any progress on this? If not I would love to contribute.
