### ISSUE TITLE
Need to fetch markdown from remote source via getInitialProps NextJs

### ISSUE THREAD

**Issue by Kinbaum** [mdx-js/mdx#789]
I'm trying to retrieve a markdown file from a remote source using `getInitialProps`. I am able to do this, however I am unable to use the [async API](https://github.com/mdx-js/mdx/blob/master/docs/advanced/api.mdx#async-api) to transpile it to JSX. I am just receiving issues about the `fs` module.

Any guidance on this would be greatly appreciated.

**Comment by millette** [comment]
I just figured it out :-) See https://github.com/millette/t3

Note that I (temporalely) forked `mdx-runtime` to use buble-jsx-only instead of buble but it works with either.

**Comment by Dangeranger** [comment]
@Kinbaum Fetching remote Markdown is something that an application I am working on needed to do as well. Using `@mdx/runtime` as the example posted by @millette is the same approach we ended up using and it has been effective for returning compiled JSX to react for render to the page.
