### ISSUE TITLE
Headings should generate ids for deep-linking

### ISSUE THREAD

**Issue by keithjgrant** [mdx-js/mdx#810]
### Subject of the feature

Add ids to headings for deep linking.

### Problem

Most markdown implementations automatically add a slugified id to all headings (h1–h6) for deep-linking support. I would expect MDX to do the same.

### Expected behavior

Markdown such as `## More information` should render as `<h2 id="more-information">More information</h2>`. This way, links with this hash deep link to the heading (e.g. https://example.com/foo#more-information).

### Alternatives

Similar behavior can be accomplished by creating custom components that add the id, but this requires additional configuration.

**Comment by wooorm** [comment]
There's a rehype plugin for that! rehype-slug. Read more about plugins here: https://mdxjs.com/advanced/plugins

**Comment by johno** [comment]
Yeah, I think we shouldn't do this by default in MDX since it's pretty opinionated, but we should definitely document this in the guides.

**Comment by slorber** [comment]
Hey

I'm exploring how to bring i18n support to https://github.com/facebook/docusaurus where MDX files will be translated.

Auto-generated ids might be a problem in practice, because changing the text does change the id, which may break linking from other pages. This means that a translating changing some heading would have to go through all the other docs of the site and update all the anchor links everywhere.

Having a way to choose the id would be useful.

Related discussions about ReactJS translation system and anchor links:
https://github.com/reactjs/reactjs.org/issues/1605#issuecomment-458816106
https://github.com/reactjs/reactjs.org/issues/1605#issuecomment-458819231

**Comment by hhimanshu** [comment]
> @keithjgrant This can be accomplished by using remark/plugins.
> 
> I accomplished it, with the following webpack setup:
> 
> ```js
> const remarkSlugs = require('remark-slug');
> const rehypeHtml = require('rehype-stringify');
> 
> ...
>   rules: [
>     ...
>       {
>         test: /\.mdx?$/,
>         use: [
>           {
>             loader: '@mdx-js/loader',
>             options: {
>               remarkPlugins: [remarkSlugs],
>               rehypePlugins: [rehypeHtml],
>             },
>           },
>         ]
>       }
>   ]
> ```

Do you have an example repo that demonstrate the use of the deep-linking? A codesandbox example? I am interesting in knowing how to do this. Thank you

**Comment by wooorm** [comment]
Hi all! I’m going to close this as it can be accomplished with a plugin.

The internationalization context @slorber brought up is interesting, but IMO could also be in a plugin.

**Comment by slorber** [comment]
@Danon we now use this exact syntax in Docusaurus:

https://docusaurus.io/docs/markdown-features/toc#heading-ids

Implementation is here: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-mdx-loader/src/remark/headings/index.ts

**Comment by SimonSomlai** [comment]
I used this inside the `components` prop: 

```tsx
...(["h1", "h2", "h3", "h4", "h5", "h6"].reduce(
    (acc, heading) => ({
      ...acc,
      [heading]: (props: any) => {
        const { children } = props;
        const id = kebabCase(children);
        return React.createElement(heading, {
          ...props,
          id,
        });
      },
    }),
    {}
) as any)
```

**Comment by karlhorky** [comment]
@wooorm with the continued interest in this feature (eg. #1279 #2042 #2485) would support for the inline comment version be re-considered as a first-class MDX feature? (maybe with whitespace stripping from start + end too)

The plugins are nice, but I'm thinking especially in terms of integration with other tooling - eg. [the MDX Analyzer `mdx.validate.validateFragmentLinks` feature](https://github.com/mdx-js/mdx-analyzer/blob/main/packages/language-server/README.md#configuration:~:text=mdx.validate.validateFragmentLinks), which would benefit from a 1st-class MDX feature.

**Comment by remcohaszing** [comment]
The “blessed” syntax is to generate IDs based on the same formula GitHub uses, which is matched by [`rehype-slug`](https://github.com/rehypejs/rehype-slug), [`rehype-autolink-headings`](https://github.com/rehypejs/rehype-autolink-headings), and markdown language service / MDX language server.

**Comment by slorber** [comment]
@remcohaszing generating IDs feel like a bad idea as soon as you try to start localizing content (cf my previous comment here: https://github.com/mdx-js/mdx/issues/810#issuecomment-677731097

For example if I translate `## My Heading` to french `## Mon Titre`, you have many references to fix coming from other pages (that may not even me localized yet). For Docusaurus, this means that a translator translating a heading will get many broken link errors just after doing so. Having to change anchors everywhere while translaing is painful, and even worse when using SaaS translation tools like Crowdin. 

Also when switching language with a language dropdown, the original/localized anchors won't match and you won't keep the scroll position.

I still believe having hardcoded anchor IDs is important. That's why Docusaurus created a CLI to automatically generate those hardcoded ids based on github-slugger: https://docusaurus.io/docs/next/markdown-features/toc#heading-ids

**Comment by ChristianMurphy** [comment]
From a language design perspective.
MDX is JSX in CommonMark.

```md
### Hello World {#my-explicit-id}
```
is not valid CommonMark, JSX, or a mix of the two.
It is inconsistent with what the language is.

---

> I still believe having hardcoded anchor IDs is important

Perfectly reasonable, and already supported through JSX:
```jsx
<h2 id="my-heading">Mon Titre</h2>
```

---

You are of course welcome to create extensions to support other syntax features, not everything needs to be in MDX core.

**Comment by karlhorky** [comment]
> From a language design perspective. MDX is JSX in CommonMark.
> 
> ```
> ### Hello World {#my-explicit-id}
> ```
> 
> is not valid CommonMark, JSX, or a mix of the two. It is inconsistent with what the language is.

@ChristianMurphy thanks for the language points here!

What are the MDX team thoughts about [the `# What are you building? {/*what-are-you-building*/}` syntax](https://github.com/mdx-js/mdx/issues/810#issuecomment-2275868756)?

> Perfectly reasonable, and already supported through JSX:
> 
> ```js
> <h2 id="my-heading">Mon Titre</h2>
> ```

I guess why people are looking for another syntax in MDX is that JSX syntax gets a bit verbose.

(also especially once there are anchor tags being generated in the headings too, but I'm guessing the chances of that becoming a part of MDX core is lower)

**Comment by wooorm** [comment]
> I still believe having hardcoded anchor IDs is important. That's why Docusaurus created a CLI to automatically generate and add those hardcoded ids to the MDX docs (based on github-slugger): [docusaurus.io/docs/next/markdown-features/toc](https://docusaurus.io/docs/next/markdown-features/toc#heading-ids)

a) If you‘re going to translate things, why not translate the URL? Why should a French speaking user not see “`#mon-titre`” when they hover over a URL? Why should English IDs be used?
b) What guarantees that translated documents are *completely* translated and that they have the exact same headings, in the same order?
c) great to automate this, why save this in files? Seems smarter to save this as metadata next to files?

---

> What are the MDX team thoughts about https://github.com/mdx-js/mdx/issues/810#issuecomment-2275868756?

IIRC I came up with it.

> I guess why people are looking for another syntax in MDX is that JSX syntax gets a bit verbose.

You are also commenting on old issues: JSX support in MDX wasn’t as good before 2 years ago.

This is fine:

```
<a name="my-heading" />

# Mon Titre
```

**Comment by remcohaszing** [comment]
> generating IDs feel like a bad idea as soon as you try to start localizing content

Without going to deep into the topic, I imagine there are multiple ways to tackle this. Maybe the IDs should match the original title. Maybe the IDs should match the translated title. Maybe they should be custom. I think it’s good that this is up to the user to solve, possibly via plugins.

> What are the MDX team thoughts about [the `# What are you building? {/*what-are-you-building*/}` syntax](https://github.com/mdx-js/mdx/issues/810#issuecomment-2275868756)?

I like it personally. That would be a great community plugin to have.

> This is fine:
>
> ```mdx
> <a name="my-heading" />
> ```

[This is deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#name)

**Comment by wooorm** [comment]
> This is deprecated

A bit off topic, but it’s in “16.1 Obsolete **but conforming** features” (emphasis mine) 😅😅

I was sharing this more as another way to go about it.
Such markup (`a[name]`) works here on GH, as in, places that generate IDs for heading automatically. For when you want multiple IDs around a place. Or different IDs.
Ref: https://github.com/d3/d3-geo-polygon/blob/8414fe5e9481c69ca765785d443ca70b3baacebc/README.md?plain=1#L45
