### ISSUE TITLE
\$ Pattern Breaks MDX Parser and Creates a ReferenceError

### ISSUE THREAD

**Issue by dan-auth0** [mdx-js/mdx#827]
### Subject of the issue

Thank you for creating this great tool. This bug report addresses a bug similar to the one reported in #433 

Having the pattern `\$` within any fenced code snippet or backticks will break MDX and creates a `ReferenceError`.

Based on the code example in #433, if you add a `\` before the `$`, it breaks:

```
`\${foo.toLowerCase()}`
```

`\${test}` also breaks MDX.

### Your environment

This is happening within a Gatsby project using `.mdx` files.

*   **OS**: macOS 10.14.6
*   **Packages**:

```
    "gatsby": "^2.16.1",
    "@mdx-js/mdx": "^1.5.1",
    "@mdx-js/react": "^1.5.1",
    "gatsby-plugin-mdx": "^1.0.53",
```

*   **Env**: 

Node: `v10.16.3`
Yarn: `1.17.3`
Chrome: `Version 77.0.3865.120`
Firefox: `69.0.3 (64-bit)`

### Steps to reproduce

Add the following to any MDX file:

```
`\${foo.toLowerCase()}`
```

and 

`\${test}`

I am experiencing this error for any blog post involving Kotlin and Spring Boot as the following is common syntax:

```kotlin
// .src/main/kotlin/com/auth0/kotlingraphql/SecurityConfig.kt

import org.springframework.beans.factory.annotation.Value

@Configuration
@EnableResourceServer
class SecurityConfig : ResourceServerConfigurerAdapter() {

    @Value("\${security.oauth2.resource.id}")
    private lateinit var resourceId: String

    @Throws(Exception::class)
    override fun configure(http: HttpSecurity) {
        http.authorizeRequests()
            .mvcMatchers("/graphql").authenticated()
            .anyRequest().permitAll()
    }

    @Throws(Exception::class)
    override fun configure(resources: ResourceServerSecurityConfigurer) {
        resources.resourceId(resourceId)
    }
}
```

I found this problem by narrowing down the files that were throwing errors and ultimately was able to pinpoint it to the following line:

`@Value("\${security.oauth2.resource.id}")`

if I remove either the `\` or the `$`, the blog post works fine.

✅ `@Value("\{security.oauth2.resource.id}")`
✅ `@Value("${security.oauth2.resource.id}")`
❌ `@Value("\${security.oauth2.resource.id}")`

The following error is thrown:

```
ReferenceError: security is not defined
```

It looks as if the `$` is escaped and MDX is treating the `${security.oauth2.resource.id}` as a JavaScript string template variable 🤔

### Expected behaviour

The following should render fine with all of its characters:

```
@Value("\${security.oauth2.resource.id}")
```

### Actual behaviour

`ReferenceError: security is not defined` is thrown in the browser.

Thank you for your time and assistance on this issue 🙏 It's the only thing preventing me from being able to present my MVP 😅

**Comment by johno** [comment]
This is now fixed by #991
