### ISSUE TITLE
[discussion] use `prettier` for `.md/.mdx` also

### ISSUE THREAD

**Issue by JounQin** [mdx-js/mdx#844]
### Subject of the feature

As title, I'm not quite sure why we are not using `prettier` for `mdx`.

### Problem

With [remark-preset-prettier](https://github.com/JounQin/remark-preset-prettier) we can disable all rules conflict with `prettier`.

### Expected behavior

Enable `prettier` everywhere.

**Comment by JounQin** [comment]
@mdx-js/maintainers Any opinions?

**Comment by ChristianMurphy** [comment]
I'd be fine with this.
Was this handled as part of #857?

**Comment by JounQin** [comment]
@ChristianMurphy Nope, they are ignored by `prettier` now: https://github.com/mdx-js/mdx/blob/master/.prettierignore#L4-L5
