### ISSUE TITLE
Vue documentation

### ISSUE THREAD

**Issue by wooorm** [mdx-js/mdx#851]
A bit related to GH-696 I guess, the readme for mdx-js/vue on npm and GH is missing!

**Comment by codebender828** [comment]
Hey, @wooorm ! I'd like to take this on. I'd be happy to talk to someone to advise me on how to go about this. Any advice?

**Comment by wooorm** [comment]
@codebender828 Heya, sorry for the wait, how can I help?

I’d suggest something like the [React readme](https://github.com/mdx-js/mdx/tree/master/packages/react) but showing a Vue example instead!

**Comment by codebender828** [comment]
Hey @wooorm Sorry for my late response as well. Didn't know you had responded to this comment! I was just talking with @johno about this.

So I guess I can create a README in the mdx-js/vue package with some examples to begin with.

**Comment by codebender828** [comment]
Hey @wooorm ! Greetings. Spun up some docs for the vue-loader package in the README file. I also added a Vue CLI example. Does this spark joy?

**Comment by wooorm** [comment]
It does! 👍
