### ISSUE TITLE
vue-loader returns a warning complaining about "wrapper" being an unknown element

### ISSUE THREAD

**Issue by syte** [mdx-js/mdx#854]
### Subject of the issue

After setting up the vue-loader as described in the setup documentation, I'm getting the following:

```
Unknown custom element: <wrapper> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

Also, it seems that the @mdx-js/vue package isn't exporting its mdx-provider. Shouldn't it be :)? Otherwise how do I use it without duplicating it in my own repo. I know it's relatively new, so thinking this may just be an issue.
### Your environment

*   **OS**: OSX Mojave
*   **Env**: yarn, chrome 78.0.3904.108 

### Steps to reproduce
Run `npm init mdx vue` to setup a new vue project and then proceed to run it with 'yarn serve'. Once running, view the console and you'll see the warning I posted above.

### Expected behaviour
I shouldn't be seeing warnings, and the mdx-provider should be exported so it can be used.

### Actual behaviour
I'm seeing warnings in the console as described above. The mdx-provider isn't be exported like it should be. I may try to debug this tomorrow by forking the @mdx-js/vue to see if I can further diagnose the issue and possibly do a PR to fix it. Assuming it's actually an issue.

Thanks for the hard work you've put into this project. It's fantastic.

**Comment by johno** [comment]
This should be fixed in the latest version!

**Comment by syte** [comment]
Thanks @johno!
