### ISSUE TITLE
Relax dependency versions

### ISSUE THREAD

**Issue by NMinhNguyen** [mdx-js/mdx#865]
### Subject of the feature

Relax dependency versions.

### Problem

See https://github.com/mdx-js/mdx/pull/858#issuecomment-563336666. Essentially, when installing an MDX package such as `@mdx-js/mdx`, I would rather not have a pinned version of any `@babel/*` dependencies installed - this causes duplicate versions and can plausibly lead to subtle bugs. If you look at https://unpkg.com/@mdx-js/mdx@1.5.1/package.json, you'll see `@babel/core` `7.6.2` gets installed, as well as fixed versions for `@babel/plugin-syntax-jsx` and `@babel/plugin-syntax-object-rest-spread`.

### Expected behavior

Dependencies should use carets (e.g. `^7.6.2`).

### Alternatives

Yarn users are able to use things like Yarn [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) but it's not ideal to have to resort to resolutions.

/cc @JounQin @johno

**Comment by timneutkens** [comment]
Based on our experience at @zeithq not using pinned deps will lead to the package randomly breaking a *lot*.

**Comment by NMinhNguyen** [comment]
@timneutkens I think that pinning versions can give a false sense of security - e.g. all Babel deps use carets for their own deps, so you get non-deterministic installs with every new install without a lockfile anyway.

**Comment by timneutkens** [comment]
@NMinhNguyen it greatly reduces the vector of breakage though.

**Comment by NMinhNguyen** [comment]
@timneutkens Perhaps you could consider relaxing some common build tooling dependencies that aren’t really meant to be duplicated (like Babel)?

**Comment by JounQin** [comment]
I'm not a fan of pining versions or depeendencies neither personally.

https://github.com/1stG/configs/blob/master/packages/renovate-config/package.json#L21

**Comment by NMinhNguyen** [comment]
@JounQin with the currently published packages, an older version of `@babel/core` gets installed because my other dependencies have a dependency on a later version of `@babel/core` (using a caret), so it’s unavoidable even with deduplication.

**Comment by JounQin** [comment]
> @JounQin with the currently published packages, an older version of `@babel/core` gets installed because my other dependencies have a dependency on a later version of `@babel/core` (using a caret), so it’s unavoidable even with deduplication.

You can try [resolutions](https://yarnpkg.com/en/docs/package-json#toc-resolutions) like https://github.com/mdx-js/eslint-mdx/blob/master/package.json#L46-L51 temporarily.

**Comment by NMinhNguyen** [comment]
@JounQin yup, I actually reference Yarn resolutions in the issue description :)

**Comment by JounQin** [comment]
@mdx-js/maintainers What do you think then?

**Comment by JounQin** [comment]
@johno @wooorm Would you like to join this thread?

**Comment by wooorm** [comment]
I don’t have an opinion on this. In my own projects, I prefer loose ranges, but I can see why this project would do it differently, and understand Tim’s view.

**Comment by JounQin** [comment]
@wooorm Can you explain in details? IMO we should move all `devDependencies` inside `workspaces` into root `package.json` to reduce conflicts with `yarn-deduplicate`. And then we can run `yarn workspace gatsby-example start` for development.

**Comment by wooorm** [comment]
I understand what you mean, but I don’t have an opinion on this (I personally dislike yarn, lerna, monorepo versioning).
As I don’t have an opinion on this, I trust [Tim](https://github.com/mdx-js/mdx/issues/865#issuecomment-564929177)’s and [John](https://github.com/mdx-js/mdx/pull/858#issuecomment-563336666)’s opinions.

**Comment by JounQin** [comment]
> none of these dependencies make it to the client since it's build tooling

As the issue's content, this is not correct.
