### ISSUE TITLE
[Discussion] Remove Travis CI and Circle CI in favor of GitHub Actions

### ISSUE THREAD

**Issue by JounQin** [mdx-js/mdx#868]
@mdx-js/maintainers 

Moved from https://spectrum.chat/mdx/general/discussion-remove-travis-ci-and-circle-ci-in-favor-of-github-actions~15924049-6f7f-4c03-8a50-984788848671 due to https://spectrum.chat/mdx/general/discussion-remove-travis-ci-and-circle-ci-in-favor-of-github-actions~15924049-6f7f-4c03-8a50-984788848671?m=MTU3NTIzODUzOTc1NQ==.

**Comment by johno** [comment]
I'm game for giving it a try! A PR would be welcome!

**Comment by JounQin** [comment]
@johno Let's give #920 a try and disable Circle CI.
