### ISSUE TITLE
[Discussion] Clarify which node versions are supported and add `engines` filed into `package.json`

### ISSUE THREAD

**Issue by JounQin** [mdx-js/mdx#878]
@mdx-js/maintainers 

See https://github.com/mdx-js/mdx/pull/877/files#diff-2c021ef745b66bae059c12ee2e1663caR21

**Comment by ChristianMurphy** [comment]
Related, recently unified had a similar discussion about adding `engines` https://github.com/unifiedjs/unified/issues/70
Unified decided not to, due to the scale of packages that would need to be updated, and some issues with state versions not lining up with real support.
MDX having a different project structure and user base may come to a different decision.

**Comment by JounQin** [comment]
@ChristianMurphy Then I think `node: *` is also fine to clarify these packages are for node only?

**Comment by wooorm** [comment]
What is the difference between `node: *` and no engines field at all?
Many packages *can* be used in other engines than Node?

**Comment by JounQin** [comment]
@wooorm That clarifies that `these packages are for node only`. `@pkgr/rollup` will read it to determine whether to treat `dependencies` as `external` just like `peerDependendcies` for non node packages.

**Comment by wooorm** [comment]
Why would you want to do that? 🤔 Some packages here work outside of Node.

**Comment by JounQin** [comment]
@wooorm So we should clarify which packages work outside of node and which work only on node. I didn't mean to add it at root `package.json`.

**Comment by wooorm** [comment]
Can you elaborate? In which cases would that help you?
Most code here *can* be included in a rollup bundle. It’s not often smart, but there are some cases where it makes sense.
What is the benefit in prohibiting it?

**Comment by JounQin** [comment]
> Most code here can be included in a rollup bundle.

@wooorm Yep, that's the point. `@pkgr/rollup` is a `rollup` wrapper, it will try best to determine which packages should be considered as externals, `dependencies` will be true on targeting node pkg but will not on targeting browser. Then `engines` field declares whether the pkg a node pkg instead of browser.

**Comment by wooorm** [comment]
Most packages here can be used in the browser, they probably shouldn’t, but it *should* be possible to bundle them. Why would we block that?

The way I understand it, the `browser` field can be used to create browser-specific versions.

**Comment by JounQin** [comment]
@wooorm 

> Most packages here can be used in the browser

Then we can do not add `engines` for them, my point is that we can add it for those packages which are really node only.

**Comment by wooorm** [comment]
Which projects are you proposing to change? create-mdx, parcel-plugin-mdx, webpack loaders?

**Comment by JounQin** [comment]
@wooorm The idea came from `@mdx-js/runtime`, but yeah we can change more packages like you mentioned.

**Comment by ChristianMurphy** [comment]
`@mdx-js/runtime` is one of the packages that can be used in browser.

**Comment by JounQin** [comment]
@ChristianMurphy It requires `buble-jsx-only`, is that really could be used in browser? Or whether its dependencies are all umd available?

**Comment by JounQin** [comment]
@ChristianMurphy OK, I saw it at https://unpkg.com/buble-jsx-only@0.19.8/dist/buble-browser-deps.umd.js , and then I'll fix the bundle issue first.

But this issue should be discussed regardless of it, right?

**Comment by ChristianMurphy** [comment]
right

**Comment by wooorm** [comment]
It feels to me like user-agent sniffing, whereas you should check features instead!

I can’t find it anymore, but there recently was a thread on twitter about someone upgrading to a new version of Node/npm (or an alpha version maybe?), and packages not installing because their `engines` field didn’t match the new release.
I’d like to prevent stuff like that.

**Comment by timneutkens** [comment]
Just to let you know, we use a minimum version on Next.js: https://github.com/zeit/next.js/blob/canary/packages/next/package.json#L195-L197

Newer versions of node are unlikely to break.

**Comment by wooorm** [comment]
How does that work if someone were on `8.11.0-alpha...`. I believe that thread I mentioned was about something like that (with [this tool](https://semver.npmjs.com) I checked that npm’s beta releases aren’t included in such a semver-min range?)

**Comment by JounQin** [comment]
Personally I think we should not care about `alpha/beta/canary/rc` releases, people using these testing/unreleased versions always can `ignore engines`.

And we can take case of all *active* lts versions of Node.js.

https://nodejs.org/en/about/releases/

They are `v10` and `v12` for now.

Or even maintainable versions including `v8`.
