### ISSUE TITLE
Dynamic import babel error

### ISSUE THREAD

**Issue by jorenbroekema** [mdx-js/mdx#894]
# Dynamic Imports babel error

I am using MDX format for demoing my components in Storybook. The problem I am facing is that I use dynamic imports in my demos, some of my components rely on this heavily and I want to demonstrate it.

When I try to use dynamic imports inside .mdx files (I use latest Google Chrome stable), babel complains that I should add a babel plugin for this feature. 

I first opened an issue [here](https://github.com/open-wc/open-wc/issues/1168) and they helped to track it down to the ToJSX function which has babel plugins hardcoded https://github.com/mdx-js/mdx/blob/master/packages/mdx/mdx-hast-to-jsx.js#L119 . I **think** this is why I am getting the error: 
```
SyntaxError: unknown: Support for the experimental syntax 'dynamicImport' isn't currently enabled (120:14):
  
    118 |   {html`
    119 |     <lion-icon
  > 120 |       .svg=${import('./icons/bugs/bug05.svg.js')}
        |              ^
    121 |       aria-label="Skinny dung beatle"
    122 |     ></lion-icon>
    123 |   `}
  
  Add @babel/plugin-syntax-dynamic-import (https://git.io/vb4Sv) to the 'plugins' section of your Babel config to enable parsing.
      at Object.raise (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:6983:17)
      at Object.expectPlugin (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:8381:18)
      at Object.parseExprAtom (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:9473:14)
      at Object.parseExprAtom (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:4097:20)
      at Object.parseExprSubscripts (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:9213:23)
      at Object.parseMaybeUnary (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:9193:21)
      at Object.parseExprOps (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:9059:23)
      at Object.parseMaybeConditional (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:9032:23)
      at Object.parseMaybeAssign (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:8978:21)
      at Object.parseExpression (/home/joren/code/lion/node_modules/@babel/parser/lib/index.js:8928:23)
```

Does it make sense for you guys to add the babel plugin for dynamic imports, so it works in MDX?

### Your environment

*   **OS**: MacOS Mojave 10.14.6
*   **Packages**: `@open-wc/demoing-storybook`  or use `npm init @open-wc` to scaffold the necessary files for Storybook.
*   **Env**:  latest Google Chrome stable, node v13.3.0, npm 6.13.2, yarn 1.21.1

### Steps to reproduce

1. `npm init @open-wc`
2. Scaffold a new project
3. Web Component
4. Toggle "Demoing"
5. Toggle "Demoing" again for example files
6. Install with yarn or npm
7. Files are now scaffolded under the folder name of your choice
8. Go into /stories/index.stories.mdx
9. Replace the following code in the first Story:
  ```js
  {html`
    <my-wc-demo></my-wc-demo>
  `}
  ```
  with 
  ```js
  {() => {
    import('../something.js');
    return html`
      <my-wc-demo></my-wc-demo>
    `;
  }}
  ```
  So now it has a dynamic import statement.
10. Run `npm run storybook` or `yarn storybook`
11. Witness the error that I am reporting ;)

### Expected behaviour

It should give an error that it cannot find the file `../something.js` because this does not exist (in my reproduction example).
With a real example, it should dynamically import the existing file without errors.

### Actual behaviour

A SyntaxError occurs on the dynamic import statement, "Support for the experimental syntax 'dynamicImport' isn't currently enabled. Add @babel/plugin-syntax-dynamic-import (https://git.io/vb4Sv) to the 'plugins' section of your Babel config to enable parsing."

Hopefully I have given you guys enough information about the problem. I don't know what solution makes most sense for you guys, let me know if you need more information from my side! Happy to send a PR if you guys agree that the solution is to add the plugin.

**Comment by johno** [comment]
Hmmm, it likely doesn't make sense for MDX to add syntactic support for experimental syntax in babel. The most straightforward workaround is to move that logic into a component that calls the dynamic import. When v2 ships we can also consider an API that will allow for babel configuration to be passed to MDX, but we're also hoping to drop babel entirely so maybe this will simply resolve itself. Thanks for opening an issue!
