### ISSUE TITLE
vue mdx links without href

### ISSUE THREAD

**Issue by gsmeira** [mdx-js/mdx#901]
### Subject of the issue

I just tried to create a mdx project for vue and the links are being shown without `href` attribute.

### Your environment

*   **OS**: `Ubuntu 19.10`
*   **Env**: `yarn 1.21.1` `node 12.13.0`

### Steps to reproduce

1. Run `npm init mdx vue`
2. Add a link like `<https://mdxjs.com>` or `[MDX](https://mdxjs.com)` in the `test.mdx` file
3. Build the project or run `yarn serve`
4. Open in the browser to see the results

### Expected behaviour

A link with the `href` attribute.

### Actual behaviour

A link with just a `parentname` attribute, like this: `<a parentname="p">stuff</a>`

**Comment by johno** [comment]
I can confirm this is indeed an issue. Not sure why, but the `href` isn't being passed in `attrs` which causes it to be dropped:

![image](https://user-images.githubusercontent.com/1424573/73305236-ee988080-41d6-11ea-98f0-37cf00274c1a.png)

**Comment by johno** [comment]
This should be fixed in the latest minor release!
