### ISSUE TITLE
Can't resolve 'fs' in '@mdx-js/runtime'

### ISSUE THREAD

**Issue by deligent-ant** [mdx-js/mdx#913]
Can't resolve 'fs' in '@mdx-js/runtime'

**Comment by JounQin** [comment]
Please provide a minimal and runnable reproduction.

**Comment by wooorm** [comment]
It is expected that you use something to bundle the runtime. The bundling here goes wrong.
As you’re using webpack, see https://webpack.js.org/configuration/node/ for help on how to configure it.

**Comment by h12345jack** [comment]
> webpack



> It is expected that you use something to bundle the runtime. The bundling here goes wrong.
> As you’re using webpack, see https://webpack.js.org/configuration/node/ for help on how to configure it.

I fixed it by apply ```fs = 'empty'```. [solutions](https://github.com/webpack-contrib/css-loader/issues/447)
