### ISSUE TITLE
Infinite render loop with Gatsby

### ISSUE THREAD

**Issue by DominicTobias** [mdx-js/mdx#928]
### Subject of the issue

Hey,

I've posted this https://github.com/gatsbyjs/gatsby/issues/20942 too but the issue is likely caused here as it doesn't happen with normal gatsby components.

Changing anything in the index.mdx in your example here once it's running in the browser causes an infinite render loop in `MDXProvider`: https://github.com/mdx-js/mdx/tree/master/examples/syntax-highlighting

Here's a repro but it's essentially the same as your example with a couple of unnecessary things like unify-ui removed, same issue happens in either: https://github.com/DominicTobias/mdx-infinite-render-loop

### Your environment

*   **OS**: MacOS Catalina
*   **Packages**: Latest Gatsby and your packages as per repo provided
*   **Env**: Latest yarn, latest Node LTS (v12)

### Steps to reproduce

Repro: https://github.com/DominicTobias/mdx-infinite-render-loop

1. `yarn start`
2. Open up browser and observe this page:
![Screenshot 2020-01-30 at 18 41 53](https://user-images.githubusercontent.com/760314/73442666-33b3e280-4390-11ea-9fac-96d51ecbf49b.png)
3. Go to `index.mdx` and change anything for example `padding: "20px",` -> `padding: "21px",`
4. Observe infinite render loop in browser:
![Screenshot 2020-01-30 at 18 42 50](https://user-images.githubusercontent.com/760314/73442742-5514ce80-4390-11ea-87bb-4aed1bf1ccdf.png)

Issue does not happen if `<LivePreview />` isn't rendered

### Expected behaviour

Should update the browser with changes without going into an infinite render loop causing CPU overload

### Actual behaviour

Infinitely renders MDXProvider until the browser is refreshed

**Comment by ChristianMurphy** [comment]
@DominicTobias here is the example you provided running in codesandbox.
https://codesandbox.io/s/github/DominicTobias/mdx-infinite-render-loop
Testing in Chrome browser I'm not seeing an infinite recursion.

Some follow up questions:
* Does it issue only happen in a specific browser?
* Does the package manager being used affect the result `npm` vs `yarn`?

**Comment by DominicTobias** [comment]
Thanks for setting that up, here the codesandbox in action, I made no modifications to it 😅

![loop](https://user-images.githubusercontent.com/760314/73842565-caccde80-4857-11ea-883a-385d19dca8a0.gif)

**Comment by ChristianMurphy** [comment]
@DominicTobias what browser are you using? The following is from a test on Firefox 72.0.2.

![example](https://user-images.githubusercontent.com/3107513/73874892-8ae30880-4811-11ea-85f9-6f1e5dde8cd4.gif)


Also does the issue happen if you update the live preview, or only with hot reload?

**Comment by DominicTobias** [comment]
Hm how strange! Am using Chrome 80, only if I hot reload. I'll chalk it down to strangeness only reproducible by me. Actually even though I can still repro it there, once I started to make my site more complex it mysteriously went away. Thanks for checking ;)

**Comment by farism** [comment]
fwiw, this isn't strangeness only reproducible by you @DominicTobias. Myself and a colleague are working on converting our doc site to gatsby and we are both encountering the same issue. I also see it on the codesandbox in chrome. Maybe we should reopen this?

<img width="1472" alt="Screen Shot 2020-04-07 at 11 27 00 PM" src="https://user-images.githubusercontent.com/3803714/78752118-5a5e3e80-7928-11ea-8c9d-f0e0a9c5c602.png">

**Comment by DominicTobias** [comment]
@farism did you figure it out? Haven't used Gatsby for a while and set up a new doc site using `
gatsby-theme-apollo-docs`. Was working fine for a while now it does it only on .mdx pages on changes and I have to browse to a .md page every time to stop it from infinitely reloading the page. Tried `gatsby clean` and fresh node_modules install etc
