### ISSUE TITLE
When using children components and `renderToStaticMarkup` the output is an empty div

### ISSUE THREAD

**Issue by helmutgranda** [mdx-js/mdx#954]
### When using children components and `renderToStaticMarkup` the output is an empty div

I am creating a simple visuals for a Design System, one of the features is to display components in action as well as the code used to generate the component but more along the lines of the inside of the components. For that I am using `renderToStaticMarkup` from React. When used you would expect the HTML Markup to be displayed but in fact it is only an empty div that is displayed. I am using MDX to create the documents and MDXProvider to feed the components into the application as such:

```
<ShowHtml>
  <Test />
</ShowHtml>
```

I have put together a codesandbox to show this error:

https://codesandbox.io/s/gatsby-starter-mdx-basic-21mif

This is *not* a place to ask questions.  For that, go to [Spectrum](https://spectrum.chat/mdx)

### Your environment

*   **OS**: codesandbox.io 
*   **Packages**: 
    "@mdx-js/mdx": "^1.1.5",
    "@mdx-js/react": "^1.1.5",
    "gatsby": "^2.13.50",
    "gatsby-image": "^2.2.8",
    "gatsby-plugin-manifest": "^2.2.4",
    "gatsby-plugin-mdx": "^1.0.0",
    "gatsby-plugin-offline": "^2.2.4",
    "gatsby-plugin-react-helmet": "^3.1.3",
    "gatsby-plugin-sharp": "^2.2.9",
    "gatsby-source-filesystem": "^2.1.8",
    "gatsby-transformer-sharp": "^2.2.5",
    "prism-react-renderer": "1.0.2",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.1"
*   **Env**: unknown - online version

### Steps to reproduce

You can view all the code in action here:

https://codesandbox.io/s/gatsby-starter-mdx-basic-21mif

### Expected behaviour

It should render the HTML from any component feed into the parent component.

### Actual behaviour

an empty `div` is rendered

**Comment by wooorm** [comment]
I don’t see any `renderToStaticMarkup` in your codebox, where were you doing that?
Anyway, you may have more luck asking Gatsby folks, as I’m guessing this is Gatsby related

**Comment by wooorm** [comment]
I think this is an issue with Gatsby
