### ISSUE TITLE
React Native/Primitives support (makeShortcode override and docs)

### ISSUE THREAD

**Issue by macintoshhelper** [mdx-js/mdx#972]
### Template middleware for React Native/primitives support

**please see https://github.com/mdx-js/mdx/issues/972#issuecomment-613661375 for a clearer explanation**

---

Middleware (say in the options) that allows for adding imports and a custom component for the `<div>` component. Or could be a config override.

### Problem

`<div {...props}/>` in the React template breaks React primitives support (React Native, `react-sketchapp`, etc).

**Updated**

Am referring to the `makeShortcode` function in https://github.com/mdx-js/mdx/blob/5ce610db134f5a97f11e63910cad6034fba2d2d1/packages/mdx/mdx-hast-to-jsx.js#L146-L150 , which is a fallback for shortcodes that are not defined in the `<MDXProvider>`

### Expected behavior

There should either be a way to use middleware to inject imports and a custom component (to replace the `<div {...props/>`, or a import resolver component to use, which resolves to `<div>` on React web, or `<View>` on native platforms, but this will need a resolver for each platform (`pdf`, `react-native`, `react-windows`, etc).

This could be in the form of an options config such as:

```js
const options = {
  shortcodeOverride: {
    import: 'import { View } from 'react-primitives',
    component: 'View',
  }
};
```

### Alternatives

I'm currently using a custom Webpack loader to use the library with `react-sketchapp`:

```js
// ...
  const code = `/* @jsx mdx */
  import React from 'react'
  import { mdx } from '@mdx-js/react'
  import { View } from 'react-primitives'
  ${result
    .replace('return <div {...props}/>', 'return <View {...props}/>')
  `;
// ...
```

**Comment by wooorm** [comment]
Hi!

- To rephrase, you’re saying that MDX currently outputs a `div` around everything, and you’d like to be able to set it to a different component, such as `View`?
- Are you saying that MDX + Primitives doesn’t work, or that MDX doesn’t work with React Native and the like?
- Could you clarify what you mean by *middleware*? This seems like a different issue: you don’t want to place your imports in the MDX file, but instead pass them in as a string somewhere else?

**Comment by macintoshhelper** [comment]
Hi! The problem with native platforms is the `makeShortcode` function: https://github.com/mdx-js/mdx/blob/5ce610db134f5a97f11e63910cad6034fba2d2d1/packages/mdx/mdx-hast-to-jsx.js#L146-L150

What I'm doing for now, is using a custom Webpack loader that does a string replace of the `<div {...props}` to `<View {...props}`, but this feels a bit hacky, incase the `mdx-hast-to-jsx.js` code changes. Example code: https://github.com/elemental-design/style-guide/blob/5ea0046c896450d55fc0517fba88d316c2653014/examples/sketch/webpack-loaders/mdx.js#L31-L38

What I mean by middleware, would be a preprocess/postprocess callback option optionally passed into `mdx-hast-to-jsx.js`, or an additional imports option, and shortcode function override, and this could be passed through Webpack loader options from the `webpack.config.js`. Also, adding features like `gray-matter` requires a custom Webpack loader currently, but maybe this could be done with a  callback passed to the MDX Webpack loader options? Hope this makes sense. Maybe the best solution would be to just have an ecosystem of custom Webpack loaders on `npm`, that could be added to the docs? `webpack.config.js` overrides might be an anti-pattern.

Other than this, MDX works pretty well with primitives (React Native, React Sketch.app, etc), so long as all components are handled with the `<MDXProvider components={...}>` to replace `react-dom` fallback.

Here's some example code of how I'm getting MDX to work with `react-sketchapp`: https://github.com/elemental-design/style-guide/blob/master/examples/sketch/src/i18n/components.js#L63 Maybe this would be worth adding to the documentation? Special handling is required for list support on native platforms. I created a Rollup plugin for MDX too, which could be useful for people using this project for React Native, etc. I'd be happy to open a PR documenting this.

**Comment by pke** [comment]
Would like to see support for React Native so I could integrate MDX in my FAQ components.

**Comment by macintoshhelper** [comment]
> Would like to see support for React Native so I could integrate MDX in my FAQ components.

I believe you can use `@mdx-js/runtime` to use MDX in React Native. This issue is more about cross-platform Webpack support, which is more of a niche use case. If you want to compile MDX files to components in advance, you should be able to use `rollup-plugin-mdx` as a build step.

**Comment by pke** [comment]
I wonder what the `substantial bundle size overhead` (mentioned in the [README.md](https://github.com/mdx-js/mdx/blob/master/packages/runtime/readme.md)) is in the end? Our app is already hitting the 20 MB mark (thanks to Google Maps insane payload of 15MB!)

**Comment by macintoshhelper** [comment]
I'd recommend trying `rollup-plugin-mdx` (I'm the maintainer, so will add React Native support and documentation soon), and creating a build step file, e.g. `scripts/build-mdx.js`, and add it to your `package.json` scripts.

I don't have any open-source examples myself, but this seems like a good example: https://github.com/zahnster/mdx-react-pack

**Comment by pke** [comment]
I could add it as a `prestart` build step in development but then it would not live update when I change the mdx files, would it?

**Comment by macintoshhelper** [comment]
You can use Rollup watch, e.g.

```json
{
  "dev:mdx": "rollup -w",
  "dev": "npm run dev:mdx && npm start" // I think this should work? Not sure
}
```

@wooorm Any thoughts on adding React Native/Primitives instructions to the docs, and covering building the MDX JSX in advance with `rollup-plugin-mdx`? Would be great to cover an alternative to `@mdx-js/runtime` for native apps, React ink, etc.

**Comment by wooorm** [comment]
@macintoshhelper Hi, thanks for your patience. Sorry, I missed your mention.

I’m all for docs on how to do it. But, this issue is specifically about customizing `div` to something else I believe. How does that relate to rollup-plugin-mdx or mdx-js/runtime?
