### ISSUE TITLE
Add an open graph image based on the logo

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#976]

**Comment by AyushSaini00** [comment]
Hey, I think this is already added. I've checked the og image using twitter card validator. Here's an screenshot:
![og mdx.js](https://user-images.githubusercontent.com/62163030/125626106-f77a6cbe-d628-4f26-86ac-c81c2554419b.png)

**Comment by wooorm** [comment]
There is an OG image yes, and there are now some OG images generated automatically for each page as well. The core for generated the images, for anyone who in the future would want to work on them, is here: https://github.com/mdx-js/mdx/blob/2ba3e441d9a5f26022df924ea9be1d0ab1798b0b/website/post.js#L139!
