### ISSUE TITLE
Make MDX a general purpose templating language

### ISSUE THREAD

**Issue by behrangsa** [mdx-js/mdx#992]
### Make MDX a general purpose templating language

Allow MDX generate content other than Markdown, such as AsciiDoc, or more broadly work as a templating language similar to Velocity, Jinja, etc.

### Problem

The component-based, JSX-based approach of MDX is very elegant and can be used to generate content other than Markdown too, for example, AsciiDoc documents.

If expanded, it can also be used as a source code generator to produce Java, JavaScript, Ruby, Python, C, C++, etc. source code.

### Expected behavior

* When passed a file with `.java.mdx` extension, it should work as a source code generator for Java.
* When passed a file with `.adoc.mdx` extension, it should work as an AsciiDoctor generator.

For example, given this JSON document:

```json
{
    "title" : "Foo",
    "firstName" : "Behrang",
    "lastName" : "Saeedzadeh"
}
```

and properly defined components one could build an AsciiDoc document like this:

```adoc
<Title props={{...}} />

My name is _<Text props={{...}} />_ `<Text props={{...}} />`
```

which together would output:

```adoc
= Foo

My name is _Behrang_ `Saeedzadeh`.
```

### Alternatives

Writing a custom React renderer.

**Comment by wooorm** [comment]
The MD in MDX stands for Markdown, so I’m not sure dropping that for this project makes sense. However, the idea of merging JSX with other markup languages makes sense.

Have you looked at [unified](https://unifiedjs.com)? It could help with things like this.

**Comment by wooorm** [comment]
I think what you’re looking for is a JSX parsing, which is not something I’m interested in, but you’re free to implement it. See https://facebook.github.io/jsx/ for the format.

I’m working on a fix to support this the other way around: decouple JS from mdxjs, and thus make MDX a language that can work outside of JavaScript. Keep an eye out for that if you’re interested in how to parse JSX with a state machine!
