### ISSUE TITLE
Disable indented code blocks

### ISSUE THREAD

**Issue by mcntsh** [mdx-js/mdx#993]
### Subject of the feature

Provide a way to disable indented code blocks.

### Problem

If JSX within a MDX file is is indented past 4 spaces, it will get parsed as a code block instead of JSX.

### Expected behavior

It will only render JSX

### Alternatives

None

**Comment by wooorm** [comment]
You can use [remark plugins](https://mdxjs.com/advanced/plugins) with MDX. With those plugins, you can turn off [markdown tokenizers](https://github.com/remarkjs/remark/tree/master/packages/remark-parse#turning-off-a-tokenizer).

**Comment by mcntsh** [comment]
@wooorm Gotcha, thank you!

**Comment by PoetaKodu** [comment]
@wooorm given that I'm not fluent with remark plugins, how can I turn that off? It's **incredibly** annoying. Could you give some more hints? Which thing should I turn off?

**Comment by wooorm** [comment]
with mdx@1 this plugin: https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-disable-tokenizers

**Comment by PoetaKodu** [comment]
@wooorm thank you, you're the best! It worked :D

**Comment by 71** [comment]
Why does this need any configuration? ["What is MDX?"](https://mdxjs.com/docs/what-is-mdx/#markdown) links to [micromark/mdx-state-machine](https://github.com/micromark/mdx-state-machine#722-indented-code), which states

> Indentation to create code blocks is not supported. Instead, use fenced code blocks.
>
> The reason for this change is so that elements can be indented.
